* female
** + Agatha

US >1000.
Latinized form of the Greek name (Agathe), derived from Greek (agathos) meaning "good". Saint Agatha was a 3rd-century martyr from Sicily who was tortured and killed after spurning the advances of a Roman official.

** Agnes

US >1000. Denmark 17.
Latinized form of the Greek name (Hagne), derived from Greek (hagnos) meaning "chaste". Saint Agnes was a virgin martyred during the persecutions of the Roman emperor Diocletian.

** Alianna

Variation of Aliana.
> Variant of Alyona or Eliana or possibly a combination of ALI (2) and ANA

** Alice

From Adelaide. "Noble form" or similar. US 172, Italy 10, Sweden 2, others.

** Anastasia

Greek. "Resurrection". Female form of Anastasius. Name of 4th Century Dalmation saint, martyred by Diocletian. US 365. Chile 80.

** + Bernadette

French feminine form of Bernard. "Brave as a bear". US 896.

** Bridget

Irish. "Exalted one." US 448.

** Darlene

American. Modification of 'darling'. "Dear, loved one." US 997.

** + Dorothy

English form of Dorothea, itself a form of the Greek (). "Gift of God". US 652.

** Elora

Of uncertain origin and meaning, this name is most likely a contraction of Elnora.
Otherwise, Elora is a community in Ontario, Canada named for a ship belonging to the founder's brother. The ship's name had been inspired by the Ellora Caves near Aurangabad, Maharashtra, India.
Elora Danan is one of the protagonists in the 1988 movie Willow.

** Flannery

From an Irish surname which was derived from Ó Flannghaile meaning "descendant of Flannghal". The given name Flannghal means "red valour". A famous bearer was American author Flannery O'Connor (1925-1964).

** + Hero
** Joan

Hebrew, or Medieval form of Johanne. "God is gracious." US 893. Catalonia 19.

** Lauren

English. Feminine form of Laurence. "Laurel". US 58. Canada 53.

** Margaret

English. "Pearl". US 182.

** - Rosalind

English. "Beautiful Rose". US 918.  

** Ruth

Hebrew. "Friendship". US 348. Ireland 100.  

** - Sophia

Greek. "Wisdom". US 2. Canada 2.

** - Sophie

French form of above. "Wisdom". US 59. Ireland, Netherlands, Scotland 1. Etc.

** - Suzanne

French. "Lily". US 950.

** Veronica
** Other...

Clio
Cornelia
Isolde
Mari
Octavia
Petra
Sidren
Toril

* additional female
Adelaide
Nickname: Addie
Meaning: "noble kind"
Saint Adelaide was the wife of the Holy Roman Emperor Otto the Great.

Agatha
Nickname: Aggy
Meaning: "good"
Saint Agatha was a 3rd-century martyr from Sicily who was tortured and killed after spurning the advances of a Roman official. 
The mystery writer Agatha Christie (1890-1976) was a famous modern bearer of this name.

Alice
Nickname: Allie
Meaning: ?

Alma
Nickname: ?
Meaning: "nourishing" or "young woman"

Andromeda
Nickname: Annie
Meaning: "to be mindful of a man"
In Greek mythology Andromeda was an Ethiopian princess rescued from sacrifice by the hero Perseus.

Arabella
Nickname: Bell
Meaning: "lovable" or possibly "invokable"
Derives ultimately from "Amabilis". Saint Amabilis was a 5th-century priest in Riom, central France.

Beatrix
Nickname: Bea, Trixie
Meaning: probably "voyager, traveler"
Viatrix or Beatrix was a 4th-century saint who was strangled to death during the persecutions of Diocletian.
Famous bearers include the British author and illustrator Beatrix Potter (1866-1943), the creator of Peter Rabbit.

Bridget
Nickname: ?
Meaning: "exalted one"
In Irish mythology this was the name of the goddess of fire, poetry and wisdom, the daughter of the god Dagda. In the 5th century it was borne by Saint Brigid, the founder of a monastery at Kildare and a patron saint of Ireland.

Darlene
Nickname: ?
Meaning: "darling"

Deirdre
Nickname: Dee?
Meaning: uncertain, possibly "woman"
This was the name of a tragic character in Irish legend who died of a broken heart after Conchobhar, the king of Ulster, forced her to be his bride and killed her lover Naoise.

Dorothy
Nickname: Dot
Meaning: "gift of God"
Associated with The Wizard of Oz.

Elora
Nickname: El
Meaning: uncertain (derives from Eleanor)

Irene
Nickname: ?
Meaning: "peace"
It was also borne by several early Christian saints. The name was common in the Byzantine Empire, notably being borne by an 8th-century empress, who was the first woman to lead the empire. She originally served as regent for her son, but later had him killed and ruled alone.

Isolde
Nickname: Izzy
Meaning: uncertain, possibly something to do with "ice" or "iron" and "battle"
In medieval Arthurian legend Isolde was an Irish princess betrothed to King Mark of Cornwall. After accidentally drinking a love potion, she became the lover of his knight Tristan, which led to their tragic deaths.

Joan
Nickname: Joe?
Meaning: derives ultimately from Iohannes (John), meaning "YAHWEH is gracious"
Joan of Arc.

Lauren
Nickname: Laury?
Meaning: derives from Laurence, probably meaning "laurel"

Maxine
Nickname: Max
Meaning: derives ultimately from either Maximus ("greatest") or Magnus ("great")

Petra
Nickname: ?
Meaning: derives from Peter, meaning "stone"

Phoebe
Nickname: ?
Meaning: "bright, pure"
In Greek mythology Phoibe was a Titan associated with the moon.
The name appears in Paul's epistle to the Romans in the New Testament, where it belongs to a female minister in the church at Cenchreae.
Came into common use after the Protestant Reformation.

Selena / Selene
Nickname: ?
Meaning: "moon"

Tabitha
Nickname: ?
Meaning: "gazelle"
Tabitha in the New Testament was a woman restored to life by Saint Peter. Her name is translated into Greek as Dorcas.
Came into common use after the Protestant Reformation.

Theodora
Nickname: ?
Meaning: derives from Theodore, "gift of God"

Ursula
Nickname: Ursa
Meaning: Little bear

Valerie
Nickname: Val
Meaning: ultimately derives from Valerius, "to be strong"
This was the name of several early saints.

Veronica
Nickname: ?
Meaning: derives from Berenice, "bringing victory"
A sister of King Herod Agrippa II.
Came into common use after the Protestant Reformation.
* male
** Abraham

Hebrew. "Father of nations". US 194.    

** Alistair

Anglicized form of Alasdair, which is Scottish form of Alexander. "Defender of the people." Alexander is US 6, Canada 8, etc. Alistair has no data.

** Basil

English. "King". US 998. 

** - Charles

German. "Free man". US 63. England/Wales 62.

** Edmund

English. "Rich protector". US 924.

** Edgar

English. "Rich spear". US 216. Catalonia 79.

** - George

Greek. "Farmer". US 164. England/Wales 9. Australia 73. Scotland 100.

** - Gilbert

English. "Bright pledge". US 830.

** - Gregory

Greek. "Vigilant". US 268. France 223.

** Guy

Norman French form of Wido. "Wood". US 995.

** Herbert

English. "Army bright". US 975.

** Isaac

Hebrew. "He will laugh". US 39. Canada 31.

** Joseph

Hebrew. "God will increase". US 20. England/Wales 15.

** Leon

Various Germanic. "Lion". 417. England/Wales 60. Austria 16. Croatia 12.

** Malcolm

Scottish. "Disciple of Saint Columba". US 527   

** + Maximilian

Latin. "Greatest". US 433. Austria 3. Sweden 74.

** Oliver

English. "Olive tree" or "Elf army". US 88. England/Wales 1. Australia 3. Denmark 9. Norway 6. Etc.

** Robert

   English. "Bright fame". US 54. Ireland 43. Hungary 47.

