* buying a car
** https://www.reddit.com/r/LifeProTips/comments/780k88/lpt_car_dealers_say_they_have_the_best_deals_and/doq2171/
No dealer will ever put the best offer in writing. They may put a good offer in writing, but never the best.

When you find the car you want for a good price (you should've done research beforehand to know what a good price is), say to the salesman, "I will buy the car right now for x" (with x being $1,000 or more less than their best offer). They will get their sales manager, who might bitch and moan about how good the deal is, but now you've turned the tables on them. You can also throw in that you'll finance through them if they can match your bank's best rate. This is how you get the best price.

If they know you're serious about buying, talking with other dealerships, and willing to finance through them, unless your offer is truly ridiculous no good sales manager will let you walk out the door over $500 or $1,000.

I did this buying a car for my wife recently, since she won't negotiate and will just pay sticker. Negotiatated with two dealerships at the end of the month. They both came in at $4,000 under sticker. I liked one dealership better, so I had the sales manager put a proposal together. When he showed me the monthly payments I said, "Gee wiz, I'd love to be able to buy this car today but I need my monthly payment about $30 a month lower to fit my budget" (which was BS, but was basically $1,000 off). "If you can get me $30 bucks a month cheaper, for the same term and same rate I'll buy it right now". The sales manager immediately put his hand out and said "deal". Boom, saved $1,000.

Edit: I'm getting a lot of comments that you should never negotiate off monthly payment, which is correct. The only time I brought up monthly payment was at the very end, and it was just to pull a little bit more money out of them without negotiating on the sales price or the trade-in. I wasn't really negotiating on the monthly payment per se, rather I knew how much lowering the monthly payment (while keeping loan terms the same) would take off the sales price. I was just playing stupid and playing the game that they're used to playing.
