* compensation for being delayed by airports
https://www.choice.com.au/travel/on-holidays/airlines/articles/flight-delays-and-cancellations-compensation#USA
* counteracting Ripoff Reports
It could be risky, and baiting an extorter, but: write articles by your company about the $5000 extortion by Ripoff report, then use any way you can to rank it. Write several verions, like "updates" to the story all with unique text and try to rank 4-5 of these articles. Use your biz name and ripoff report all through the story to overtake their keywords. Hire SEO to guarantee rank.

* DLAB
"Yeah I do i took it back in 2011, scored 128 (high enough for the cat 4 languages eg Chinese, Korean, Arabic etc.) All I can say is that the best way to study is to know your grammatical terms. Know what a subject is, know what an object is, a verb, a preposition, basic idea of cases and conjugation. Beyond that there is no real way to study for the test, it is truly an aptitude test. All the information is there you just have to make the logical jumps, even if it makes no sense, kinda like languages. Best of luck, you will feel like shit at the end."

"There's an overpriced book by Delta Gear on the DLAB. To my surprise it was very accurate and had me brush up on just the parts of English grammar that mattered."
* insurance replacing stuff after e.g. a fire
https://www.reddit.com/r/personalfinance/comments/43iyip/our_family_of_5_lost_everything_in_a_fire/cziljy3/

* military
"Unless things have changed in the last decade the standard enlistment length is 4 years. If you really want all of the benefits without going over seas, choose a non-deployable MOS. With that said I don't regret my 4 years active with 2 combat deployments to Iraq. Everyone is different though.

Edit: I was in the Marines so for everyone enlightening me about enlistment lengths other branches offer, thank you. I was a dumb Grunt so all of these numbers like "3" and "6" are throwing me off but I think I'm getting the gist that other options are available.

To everyone saying "No such thing as non-deployable MOS". Sure, you're technically correct. With that said any recruiter worth his weight in awesome pamhlets and motivational DVD's can hook you up with a job he or she knows probably won't go to a combat zone. And even if it did you'd be chillin' at Camp Victory eating Taco Bell or at some giant base hitting up mid-rats and bitching that you ran out of minutes on your phone card.

Like I said I was Infantry so if you ain't 03, you ain't shit!

Edit 2: Jesus fuck. I leave to fix my washing machine and I come back to an inbox that's destroyed worse than barracks rat's pussy.

Thanks /u/daragaaz for the gold. Not sure why you thought it was smart to give a Marine something shiny. Usually we try to stick our dicks in anything new and exotic but I'll do my best to refrain."
* note to leave on badly parked cars:
"Sorry I damaged your vehicle. I wasn't expecting it to be unaligned with the marked parking spots. People are watching so I'm making it look like I'm writing down my contact information. I'm not. Quit parking like an asshole."
* salary negotiations in job interviews
https://www.reddit.com/r/personalfinance/comments/82z8yk/quick_reminder_to_not_give_away_your_salary/dvdxz1u/
https://www.reddit.com/r/personalfinance/comments/82z8yk/quick_reminder_to_not_give_away_your_salary/dve6yho/
* skills to probably never learn
[[https://www.reddit.com/r/oddlysatisfying/comments/7tszmu/waterbend_by_joe_fieldpausch/dtf7giy/][pharoah shuffle / waterbend]]
[[https://www.reddit.com/r/LearnUselessTalents/comments/5ot796/instantly_make_a_tiny_cloud_in_your_mouth/][smoke from mouth]]
** Whistling
> Bottom lip over bottom teeth.
> Tongue towards upper teeth. Keep it closely behind them but don't touch them.
> Now blow with gusto. It's more of a whistling blow than a simple exhale.
> You should feel the air pass between your tongue and upper teeth.
> Practice A LOT.
* taking advantage of credit card reward programs
https://www.reddit.com/r/churning/
* transcription work
https://www.reddit.com/r/mturk/comments/193w09/are_audio_transcription_hits_worth_it/c8klhs7/

"Transcriber here, I started out on MTurk and now have quit my job and have done transcriptions full-time for over a year now.

Here are some rules of the game and tips of the trade, to the best of my knowledge.

If you can't type above 60-80 WPM, don't bother. I know some Turkers don't care much about rate per hour, but it is NOT worth your time, transcribing if you don't have the typing speed to come with it. Depending on the quality of audio, you should aim to have an hour finished within two and a half to three hours.

Use your own transcription software (I started out with ExpressScribe (free), and now use a custom hotkey setup for VLC. Don't use the in-browser Ctrl+Spacebar or whatever it is. It's messy and slow and cumbersome.

I've never enjoyed CastingWords, only SpeechInk. There are a lot of haters of SpeechInk on Reddit, but I am not one of them. They have consistently always done me right. I was even once paid when I did an entire transcript in the COMPLETELY wrong format. If you keep in contact with them, they will look out for you. Robin is insanely helpful, and many of their long-term clients will keep in communication with you if you do a good job.

Some people say stop and fix spelling errors or spend longer periods of time on parts you can't hear. I say if the typo is minor, move on and do a spellcheck at the end (also, do it in a Word or Libre doc, don't do it in the browser window!). Mark inaudible sections if you can't hear it in the first or second playback, and spend time at the end going over those hard to hear sections.

It's REALLY easy to move on in transcription off of MTurk if you find it suits you. I'm serious, I've actually quit my full-time job and now work 100% from home. It's a small living, but if you're in need of a job (if you can get past the feast or famine bit), there's always transcription work. If you like it, if you're good at it, check out ODesk, Elance, and Guru.com. I've done projects with PBS and HBO - massive resume boosters and great experience, and have set myself up with five or six long-term clients, so I'm always in business.

TL;DR, try it out. Do SpeechInk, not CastingWords. Fuck CastingWords. Be fast, don't stress, and if you like it, move onto other websites than MTurk - if you're good, you can and will make bank."
