** 4 steps re: OCD

"25 years of compulsive urges and obsessive thoughts made my brain an unbearable place. Suicide was the obvious solution. "Brain Lock", by Jeffrey M. Schwartz, MD saved my life. On my arm is written the Four Step Self Treatment Method. Cognitive behavioral therapy can rid us of our nightmare!"

"Relabel: you call the intrusive thought or urge to do a troublesome compulsive behavior exactly what it is: an obsessive thought or a compulsive urge. The question arises, "why is this bothering me?"

Reattribute: you say, "It keeps bothering me because I have a medical condition called OCD. I am having the symptoms of a medical problem."

Refocus: refocus your attention on another behavior by doing something useful and positive.

Revalue: you will learn to devalue unwanted obsessive thoughts and compulsive urges as soon as they intrude. You will come to see intrusive OCD symptoms as the useless garbage they really are."

** mental scratch

http://hsperson.com
https://psychology-tools.com/autism-spectrum-quotient/
https://aspietests.org/userdetails.php?target=/raads/questions.php
https://www.reddit.com/r/hsp/top/
https://smile.amazon.com/dp/B076L7V7H2/ref=cm_sw_r_cp_apap_uoXtq3UBJqHsa?sa-no-redirect=1#customerReviews
https://en.wikipedia.org/wiki/Sensory_processing_disorder#Standardized_tests

