* resume
Nathaniel Rhein
8588 Deans Hill Rd, Berrien Center, MI 49102    •    (313) 908-0706    •    nathaniel@aaplog.org

WORK EXPERIENCE
AAPLOG, Eau Claire, MI
IT support (independent contractor), 2017–Current
    • Digital security, research into legal issues, transcription, scheduling, and clerical work
    • Coordinating and providing transportation for special events

Samlind of Indiana, South Bend, IN
CNA, 2011–2015
    • Home health care for two clients
    • Bathing, hygiene, turning, medication administration, blood sugar checks, vital signs, activities, transportation, grocery shopping, assistance with bills and utilities, cleaning, behavioral support, and general assistance

Brookdale Sterling House of South Bend, South Bend, IN
CNA, 2011
    • Direct care for a group of ~35 residents
    • Bathing, hygiene, feeding, cleaning, laundry, activities, and assistance with ADLs

VOLUNTEER EXPERIENCE
Emmaus Lutheran Church, South Bend, IN
2nd level children's teacher, 2017–2018
    • Weekly class for children ages 5–10.

Springs of Life Lutheran Church and Grade School, Nairobi City, Kenya
5th grade teacher, 2010
    • Daily class for 5th grade students
    • English, Math, Bible Study, and Physical Education

Friendship Camp for Developmentally Disabled Adults, Angola, IN
Caretaker, 2007 & 2008
    • Behavioral support, activities, and general assistance

EDUCATION
    • Bethel College, Mishawaka, IN
B.A., Interdisciplinary Studies (in progress)

COMPUTER SKILLS
    • Proficient with Microsoft Word and Excel
    • Typing: 100 WPM
    • Hardware & software maintenance, upgrades, and troubleshooting
    • Transcription
    • File organization

* work experience
** AAPLOG

# employment
05/17-current

# position
IT support (independent contractor)

# adress & contact info
PO Box 395, Eau Claire, MI 49111-0395
(202) 230-0997
communications@aaplog.org

# supervisor
Dr. Donna Harrison
President

# duties
IT support including digital security, research into legal issues, transcription, scheduling, and clerical work. Coordinating and providing transportation for special events.

# pay
$15.00 per hour

# reason for leaving
Still employed.

** Samlind of Indiana

# employment
04/11-03/15

# position
CNA (home care)

# adress & phone
50776 IN-933, South Bend, IN 46637
(574) 855-1810

# supervisor
Jason Douglas
Program Director

# duties
Home health care for two clients. Bathing, hygiene, turning, medication administration, blood sugar checks, vital signs, activities, transportation, grocery shopping, assistance with bills and utilities, cleaning, behavioral support, and general assistance.

# pay
$10.50 per hour

# reason for leaving
Relocation.

** Brookdale Sterling House of South Bend

# employment
02/11-05/11

# position
CNA (facility care)

# adress & phone
17441 State Road 23, South Bend, IN 46635
(574) 273-2233

# supervisor
Mildred Bowen
Health & Wellness Director

# duties
Direct care for a group of ~35 residents. Included bathing/hygiene, feeding, cleaning, laundry, activities, taking phone calls, and general assistance.

# pay
$9.00 per hour

# reason for leaving 
Better fit at Samlind.

** Panera Bread

# employment
08/08 to 03/09

# position
Dining Room Associate

# adress & phone
1290 E Ireland Rd., South Bend, IN 46614
(574) 231-4932

# supervisor
Sara Meyer

# duties
Busing tables, washing dishes, cleaning, refilling stock, and miscellaneous errands.

# pay
$7.50.

# reason for leaving
Let go due to overstaffing.

** Kroger

# employment
04/06 to 02/07

# position
Bagger

# adress & phone
1217 E Ireland Rd.
(574) 291-0666

# supervisor
Barb Arnet

# duties
Bagging groceries, gathering carts, helping customers, cleaning, and miscellaneous errands.

# pay
$5.50 per hour

# reason for leaving
Had to make time for college.
* volunteer work

** Emmaus Lutheran Church
South Bend, IN

2nd level children's teacher

2018

** Springs of Life Lutheran Church and Grade School
Nairobi City, Kenya

5th grade teacher

2010

** Emmaus Lutheran Church
South Bend, IN

Nursery supervisor

2009 to 2011

** Friendship Camp for Developmentally Disabled Adults
Angola, IN

Caretaker

2007 & 2008

* references

** Jackie Ottbridge
(574) 323-5947

** Rick Tribble
IT Manager
Koontz-Wagner Services, LLC - South Bend, IN
(574) 532-0443
rtribble@gmail.com

** Dave Smith
Owner
Logical Solutions - South Bend, IN
(574) 258-0639
LogicSolut@comcast.net

** Rick Stuckwisch
Pastor
Emmaus Lutheran Church - South Bend, IN
(574) 233-0574
pastor@emmaus24.org

** Charles Horner
Principal Engineer
Robert Bosch, LLC - South Bend, IN
(574) 234-5969
Charley.Horner@us.bosch.com

** Mark Harrison, MD
Hospitalist / Infection Control
Lakeland Regional Health System - St. Joseph, MI
(269) 487-8023
mharrison@lakelandregional.org
* misc. skills, experiences
Spent several months as a volunteer 5th grade teacher in Nairobi City, Kenya.
Have assisted in farm work and home repair and modification, including felling and chopping trees, renovating a barn, installing a metal roof, installing a fence, constructing gates, installing a wood stove, installing a chimney, building bridges in a swamp, and taking down small buildings with hand tools.
* addresses

# current
8588 Deans Hill Rd
Berrien Center, MI 49102

# previous 1
1416 Miami St.
South Bend, IN 46613

# previous 2
546 Altgeld St.
South Bend, IN 46614
* 2018 application process

** 2018-01-15 Mon
Went to Michigan Works, but it was closed.

Went to Lyons, was directed to submit online application. Offered to let me use the on-site computer, which I did. However, after filling out the application, the website would not work. I decided to try again from home.
** 2018-01-16 Tue
Went to Michigan Works. Talked with worker there, got a long list of local jobs, and an offer to apply for them using an on-site computer. I decided to do it from home. Worker also helped troubleshoot my resume. Gave me a lead: IT3 Computer Solutions, LLC, in Dowagiac. Other leads: Shopko Hometown and A-1 Expert Tree Service.

Went to Aldi and submitted my application.
** 2018-01-17 Wed
** 2018-01-18 Thu

Re-did resume, incorporating advice from worker at Michigan Works
Updated LinkedIn profile

# ONLINE APPLICATIONS
Shelton Farms - Office Assistant
Rural King - Sales Associate
GreenEcho, Saint Joseph - IT Help Desk Analyst
Beacon Specialized Living Services - Direct Care Worker
Michiana Health Information Network - IT Support Analyst
1st Source Bank - IT Support Technician - South Bend, IN
enviro-clean - ? - St. Joseph
Chemical Bank - Teller - Benton Harbor
<further applications recorded in spreadsheet>

** 2018-01-19 Fri
More applications.
* special interests, skills, qualifications, etc.
** Shelton Frams: office
I have experience building and maintaining PCs for myself and my acquaintances. I am well-acquainted for automation techniques to optimize office work and file organization.
** Lyons: interests
Books, movies, games, and some programming / web development. Nothing big, although I did manage to find a problem with your online application process: the application fails to submit (504 Gateway Time-Out) if any field contains more than 255 characters.
** Chemical Bank - dealing professionally with people

I have a good deal of experience dealing professionally with people of different positions and expectations, in part due to my time teaching at a grade school in Nairobi, as well as my time assisting with a medical/ethics conference, during which I had to maintain contact with and arrange/provide transportation for approximately 80 people, mainly doctors, from around the world.
** Shopko: Skills [for AAPLOG]
Organization, time management, typing, computer proficiency, information digitization, computer troubleshooting, hardware assembly and maintenance, problem solving.
** Shopko: Skills [for Samlind]
Diligence, patience, cleaning, self-determination, problem solving, creativity, and some conflict resolution.
** Shopko: Skills [for Brookdale]
Prompt response, time management, patience, cleaning, presenting myself and the facility to residents, their families, and potential new residents.
* scratch

Bethel Master of Arts
Interdisciplary Studies
-roughly 8-15-2007
to 4-15-2018
