* The Dragonslayer of Merebarton
K J Parker



I WAS MENDING my chamber pot when they came to tell me about the dragon.

Mending a pot is one of those jobs you think is easy, because tinkers do it, and tinkers are no good or theyfd be doing something else. Actually, itfs not easy at all. You have to drill a series of very small holes in the broken pieces, then thread short lengths of wire through the holes, then twist the ends of the wires together really tight, so as to draw the bits together firmly enough to make the pot watertight. In order to do the job you need a very hard, sharp, thin drill bit, a good eye, loads of patience and at least three pairs of rock-steady hands. The tinker had quoted me a turner and a quarter; get lost, I told him, Ifll do it myself. It was beginning to dawn on me that some sorts of work are properly reserved for specialists.

Ah, the irony.

Stupid of me to break it in the first place. Ifm not usually that clumsy. Stumbling about in the dark, was how I explained it. You shouldfve lit a lamp, then, shouldnft you, she said. I pointed out that you donft need a lamp in the long summer evenings. She smirked at me. I donft think she quite understands how finely balanced our financial position is. Wefre not hard up, nothing like that. Therefs absolutely no question of having to sell off any of the land, or take out mortgages. Itfs just that, if we carry on wasting money unnecessarily on lamp-oil and tinkers and like frivolities, therefll come a time when the current slight reduction in our income will start to be a mild nuisance. Only temporary, of course. The hard times will pass, and soon wefll all be just fine.

Like I said, the irony.

gEbbafs here to see you,h she said.

She could see I was busy. gHefll have to come back,h I snapped. I had three little bits of wire gripped between my lips, which considerably reduced my snapping power.

gHe said itfs urgent.h

gFine.h I put down the pot\call it that, no way it was a pot any more. It was disjointed memories of the shape of a pot, loosely tied together with metal string, like the scale armour the other side wore in Outremer. gSend him up.h

gHefs not coming up here in those boots,h she said, and at once I realised that no, he wasnft, not when she was using that tone of voice. gAnd why donft you just give up on that? Youfre wasting your time.h

Women have no patience. gThe tinker\h

gThat bit doesnft go there.h

I dropped the articulated mess on the floor and walked past her, down the stairs, into the great hall. Great, in this context, is strictly a comparative term.

Ebba and I understand each other. For a start, hefs practically the same age as me\Ifm a week younger; so what? We both grew up silently ashamed of our fathers (his father Ossun was the laziest man on the estate; mine\well) and wefre both quietly disappointed with our children. He took over his farm shortly before I came home from Outremer, so we both sort of started off being responsible for our own destinies around the same time. I have no illusions about him, and I canft begin to imagine he has any about me. Hefs medium height, bald and thin, stronger than he looks and smarter than he sounds. He used to set up the targets and pick up the arrows for me when I was a boy; never used to say anything, just stood there looking bored.

He had that look on his face. He told me I wasnft going to believe what he was about to tell me.

The thing about Ebba is, he has absolutely no imagination. Not even when roaring drunk\whimpering drunk in his case; very rare occurrence, in case youfve got the impression hefs what she calls basically-no-good. About twice a year, specific anniversaries. I have no idea what theyfre the anniversaries of, and of course I donft ask. Twice a year, then, he sits in the hayloft with a big stone jar and only comes out when itfs empty. Not, is the point Ifm trying to make, prone to seeing things not strictly speaking there.

gTherefs a dragon,h he said.

Now Ossun, his father, saw all manner of weird and wonderful things. gDonft be bloody stupid,h I said. He just looked at me. Ebba never argues or contradicts; doesnft need to.

gAll right,h I said, and the words just sort of squeezed out, like a fat man in a narrow doorway. gWhere?h

gDown Merebarton.h



A BRIEF DIGRESSION concerning dragons.

Therefs no such thing. However, therefs the White Drake (its larger cousin, the Blue Drake, is now almost certainly extinct). According to Hrabanusf Imperfect Bestiary, the White Drake is a native of the large and entirely unexpected belt of marshes you stumble into after youfve crossed the desert, going from Crac Boamond to the sea. Hrabanus thinks itfs a very large bat, but conscientiously cites Priscian, who holds that itfs a featherless bird, and Saloninus, who maintains that itfs a winged lizard. The White Drake can get to be five feet long\thatfs nose to tip-of-tail; three feet of that is tail, but it can still give you a nasty nip. They launch themselves out of trees, which can be horribly alarming (I speak from personal experience). White Drakes live almost exclusively on carrion and rotting fruit, rarely attack unless provoked and absolutely definitely donft breathe fire.

White Drakes arenft found outside Outremer. Except, some idiot of a nobleman brought back five breeding pairs about a century ago, to decorate the grounds of his castle. Why people do these things, I donft know. My father tried to keep peacocks once. As soon as we opened the cage they were off like arrows from the bowstring; next heard of six miles away, and could we please come and do something about them, because they were pecking the thatch out in handfuls. My father rode over that way, happening to take his bow with him. No more was ever said about peacocks.

Dragons, by contrast, are nine to ten feet long excluding the tail; they attack on sight, and breathe fire. At any rate, this one did.



THREE HOUSES AND four barns in Merebarton, two houses and a hayrick in Stile. Nobody hurt yet, but only a matter of time. A dozen sheep carcasses, stripped to the bone. One shepherd reported being followed by the horrible thing: he saw it, it saw him, he turned and ran; it just sort of drifted along after him, hardly a wingbeat, as if mildly curious. When he couldnft run any further, he tried crawling down a badger hole. Got stuck, head down the hole, legs sticking up in the air. He reckoned he felt the thump as the thing pitched down next to him, heard the snuffling\like a bull, he reckoned; felt its warm breath on his ankles. Time sort of stopped for a while, and then it went away again. The man said it was the first time hefd pissed himself and felt the piss running down his chest and dripping off his chin. Well, there you go.

The Brother at Merebarton appears to have taken charge, the way they do. He herded everyone into the grain store\stone walls, yes, but a thatched roof; youfd imagine even a Brother wouldfve watched them making charcoal some time\and sent a terrified young kid off on a pony to, guess what. Youfve got it. Fetch the knight.



AT THIS POINT, the story recognises (isnft that what they say in Grand Council?) Dodinas le Cure Hardy, age fifty-six, knight, of the honours of Westmoor, Merebarton, East Rew, Middle Side and Big Room; veteran of Outremer (four years, so help me), in his day a modest success on the circuit\three second places in ranking tournaments, two thirds, usually in the top twenty out of an average field of forty or so. Through with all that a long time ago, though. I always knew I was never going to be one of those gaunt, terrifying old men who carry on knocking fem down and getting knocked down into their sixties. I had an uncle like that, Petipas of Lyen. I saw him in a tournament when he was sixty-seven, and some young giant bashed him off his horse. Uncle landed badly, and I watched him drag himself up off the ground, so desperately tired. I was only, what, twelve; even I could see, every last scrap of flesh and bone was yelling, donft want to do this any more. But he stood up, shamed the young idiot into giving him a go on foot, and proceeded to use his head as an anvil for ten minutes before graciously accepting his surrender. There was so much anger in that performance\not at the kid, for showing him up, Uncle wasnft like that. He was furious with himself for getting old, and he took it out on the only target available. I thought the whole thing was disturbing and sad. I wonft ever be like that, I told myself.

(The question was, is: why? I can understand fighting. I fought\really fought\in Outremer. I did it because I was afraid the other man was going to kill me. So happens my defence has always been weak, so I compensate with extreme aggression. Never could keep it going for very long, but on the battlefield thatfs not usually an issue. So I attacked anything that moved with white-hot ferocity fuelled entirely and exclusively by ice-cold fear. Tournaments, though, jousting, behourd, the grand melee\what was the point? I have absolutely no idea, except that I did feel very happy indeed on those rare occasions when I got a little tin trophy to take home. Was that enough to account for the pain of being laid up six weeks with two busted ribs? Of course it wasnft. We do it because itfs what we do; one of my fatherfs more profound statements. Conversely, I remember my aunt: silly woman, too soft for her own good. She kept these stupid big white chickens, and when they got past laying she couldnft bear to have their necks pulled. Instead, they were taken out into the woods and set free, meaning in real terms fed to the hawks and foxes. One time, my turn, I lugged down a cage with four hens and two cocks squashed in there, too petrified to move. Now, what draws in the fox is the clucking; so I turned them out in different places, wide apart, so they had nobody to talk to. Released the last hen, walking back down the track; already the two cock birds had found each other, no idea how, and were ripping each other into tissue scraps with their spurs. They do it because itfs what they do. Someone once said, the man whofs tired of killing is tired of life. Not sure I know what that means.)



A PICTURE IS emerging, I hope, of Dodinas le Cure Hardy; while he was active in chivalry he tried to do what was expected of him, but his heart was never in it. Glad, in a way, to be past it and no longer obliged to take part. Instead, prefers to devote himself to the estate, trying to keep the ancestral mess from collapsing in on itself. A man aware of his obligations, and at least some of his many shortcomings.

Go and fetch the knight, says the fool of a Brother. Tell him\



ON REFLECTION, IF I hadnft seen those wretched White Drakes in Outremer, therefs a reasonable chance Ifd have refused to believe in a dragon trashing Merebarton, and then, who knows, it mightfve flown away and bothered someone else. Well, you donft know, thatfs the whole point. Itfs that very ignorance that makes life possible. But when Ebba told me what the boy told him hefd seen, immediately I thought: White Drake. Clearly it wasnft one, but it was close enough to something Ifd seen to allow belief to seep into my mind, and then I was done for. No hope.

Even so, I think I said, gAre you sure?h about six or seven times, until eventually it dawned on me I was making a fool of myself. At which point, a horrible sort of mist of despair settled over me, as I realised that this extraordinary, impossible, grossly and viciously unfair thing had landed on me, and that I was going to have to deal with it.

But you do your best. You struggle, just as a man crushed under a giant stone still draws in the last one or two desperate whistling breaths; pointless, but you canft just give up. So I looked him steadily in the eye, and I said, gSo, what do they expect me to do about it?h

He didnft say a word. Looked at me.

gThe hell with that,h I remember shouting. gIfm fifty-six years old, I donft even hunt boar any more. Ifve got a stiff knee. I wouldnft last two minutes.h

He looked at me. When youfve known someone all your life, arguing with them is more or less arguing with yourself. Never had much joy with lying to myself. Or anyone else, come to that. Of course, my mother used to say: the only thing I want you not to be the best in the world at is lying. She said a lot of that sort of thing; much better written down on paper rather than said out loud in casual conversation, but of course she couldnft read or write. She also tended to say: do your duty. I donft think she ever liked me very much. Loved, of course, but not liked.

He was looking at me. I felt like that poor devil under the stone (at the siege of Crac des Bests; man I knew slightly). Comes a point when you just canft breathe any more.



WE DO HAVE a library: forty-seven books. The Imperfect Bestiary is an abridged edition, local copy, drawings are pretty laughable, they make everything look like either a pig or a cow, because thatfs all the poor fool who drew it had ever seen. So there I was, looking at a picture of a big white cow with wings, thinking: how in Godfs name am I supposed to kill something like that?

White Drakes donft breathe fire, but therefs this stupid little lizard in Permia somewhere that does. About eighteen inches long, otherwise completely unremarkable; not to put too fine a point on it, it farts through its mouth and somehow contrives to set fire to it. You see little flashes and puffs of smoke among the reed beds. So itfs possible. Wonderful.

(Why would anything want to do that? Hrabanus, who has an answer for every damn thing, points out that the reed beds would clog up the delta, divert the flowing water and turn the whole of South Permia into a fetid swamp if it wasnft for the frequent, regular fires, which clear off the reed and lay down a thick bed of fertile ash, just perfect for everything else to grow sweet and fat and provide a living for the hundreds of species of animals and birds who live there. The fires are started by the lizards, who appear to serve no other function. Hrabanus points to this as proof of the Divine Clockmaker theory. I think they do it because itfs what they do, though Ifm guessing the lizards who actually do the fire-starting are resentful younger sons. Tell you about my brother in a minute.)



SHE FOUND ME in the library. Clearly shefd been talking to Ebba. gWell?h she said.

I told her what Ifd decided to do. She can pull this face of concentrated scorn and fury. Itfs so intensely eloquent, therefs really no need for her to add words. But she does. Oh, she does.

gIfve got no choice,h I protested. gIfm the knight.h

gYoufre fifty-six and you get out of breath climbing the stairs. And youfre proposing to fight dragons.h

Itfs a black lie about the stairs. Just that one time; and that was the clock-tower. Seventy-seven steps to the top. gI donft want to do it,h I pointed out. gLast bloody thing I want\h

gLast bloody thing youfll ever do, if youfre stupid enough to do it.h She never swears, except when quoting me back at myself. gJust think for a minute, will you? If you get yourself killed, whatfll happen to this place?h

gI have no intention of getting myself\h

gFlorianfs too young to run the estate,h she went on, as though I hadnft spoken. gThat clown of a bailiff of yours canft be trusted to remember to breathe without someone standing over him. On top of which, therefs heriot and wardship, thatfs hundreds and hundreds of thalers we simply havenft got, which means having to sell land, and once you start doing that you might as well load up a handcart and take to the roads, because\h

gAbsolutely no intention of getting killed,h I said.

gAnd for crying out loud donft shout,h she shouted. gItfs bad enough youfre worrying me to death without yelling at me as well. I donft know why you do this to me. Do you hate me, or something?h

We were four and a quarter seconds away from tears, and I really canft be doing with that. gAll right,h I said. gSo tell me. What do I do?h

gI donft know, do I? I donft get myself into these ridiculous messes.h I wish I could do that; I should be able to. After all, itfs the knightfs move, isnft it? A step at right angles, then jump clean over the other manfs head. gWhat about that useless brother of yours? Send him.h

The dreadful thing is, the same thought had crossed my mind. Itfd be\well, not acceptable, but within the rules, meaning therefs precedents. Of course, Ifd have to be practically bedridden with some foul but honourable disease. Titurel is ten years younger than me and still competing regularly on the circuit, though at the time he was three miles away, at the lodge, with some female hefd found somewhere. And if I really was ill\

I was grateful to her. If she hadnft suggested it, I might just have considered it. As it was; gDonft be ridiculous,h I said. gJust think, if I was to chicken out and Titurel actually managed to kill this bloody thing. Wefve got to live here. Hefd be insufferable.h

She breathed through her nose; like, dare I say it, one of the D things. gAll right,h she said. gThough how precisely itfs better for you to get killed and your appalling brother moves in and takes over running the estate\h

gI am not going to get killed,h I said.

gBut there, you never listen to me, so I might as well save my breath.h She paused and scowled at me. gWell?h

Hard, sometimes, to remember that when I married her, she was the Fair Maid of Lannandale. gWell what?h

gWhat are you going to do?h



gOH,h HE SAID, sort of half-turning and wiping his forehead on his forearm. gItfs you.h

Another close contemporary of mine. Hefs maybe six months older than me, took over the forge just before my father died. Hefs never liked me. Still, we understand each other. Hefs not nearly as good a tradesman as he thinks he is, but hefs good enough.

gCome to pay me for those harrows?h he said.

gNot entirely,h I replied. gI need something made.h

gOf course you do.h He turned his back on me, dragged something orange-hot out from under the coals, and bashed it, very hard, very quickly, for about twenty seconds. Then he shoved it back under the coals and hauled on the bellows handle a dozen times. Then he had leisure to talk to me. gIfll need a deposit.h

gDonft be silly,h I said. There was a small heap of tools piled up on the spare anvil. I moved them carefully aside and spread out my scraps of parchment. gNow, youfll need to pay attention.h



THE PARCHMENT IfD drawn my pathetic attempts at sketches on was the fly-leaf out of Monomachus of Teanafs Principles of Mercantile Law. Ifd had just enough left over to use for a very brief note, which Ifd folded four times, sealed, and sent the stable boy off to deliver. It came back, folded the other way; and under my message, written in big crude handwriting, smudged for lack of sand\

What the hell do you want it for?

I wasnft in the mood. I stamped back into the house (Ifd been out in the barn, rummaging about in the pile of old junk), got out the pen and ink and wrote sideways up the margin (only just enough room, writing very small)\

No time. Please. Now.

I underlined please twice. The stable boy had wandered off somewhere, so I sent the kitchenmaid. She whined about having to go out in her indoors shoes. I ask you.



MODDO THE BLACKSMITH is one of those men who gets caught up in the job in hand. He whinges and complains, then the problems of doing the job snag his imagination, and then your main difficulty is getting it away from him when itfs finished, because hefs just come up with some cunning little modification whichfll make it ever so slightly, irrelevantly better.

He does good work. I was so impressed I paid cash.

gYour design was useless, so I changed it,h hefd said. A bit of an overstatement. What hefd done was to substitute two thin springs for one fat one, and add on a sort of ratchet thing taken off a millersf winch, to make it easier to wind it up. It was still sticky with the oil hefd quenched it in. The sight of it made my flesh crawl.

Basically, it was just a very, very large gin trap, with an offset pressure plate. gItfs pretty simple,h I said. gThink about it. Think about birds. In order to get off the ground, theyfve got very light bones, right?h

Ebba shrugged: if you say so.

gWell,h I told him, gthey have. And you break a birdfs leg, it canft get off the ground. Ifm assuming itfs the same with this bastard. We put out a carcass, with this underneath. It stands on the carcass, braces it with one foot so it can tear it up with the other. Bang, got him. This thing ought to snap the buggerfs leg like a carrot, and then it wonft be going anywhere in a hurry, you can be sure of that.h

He frowned. I could tell the sight of the trap scared him, like it did me. The mainspring was three eighths of an inch thick. Just as well Moddo thought to add a cocking mechanism. gYoufll still have to kill it, though,h he said.

I grinned at him. gWhy?h I asked. gNo, the hell with that. Just keep everybody and their livestock well away for a week until it starves to death.h

He was thinking about it. I waited. gIf it can breathe fire,h he said slowly, gmaybe it can melt the trap off.h

gAnd burn through its own leg in the process. Also,h I added\Ifd considered this very point\geven without the trap itfs still crippled, it wonft be able to hunt and feed. Just like a bird thatfs got away from the cat.h

He pulled a small frown that means, well, maybe. gWefll need a carcass.h

gTherefs that sick goat,h I said.

Nod. His sick goat. Well, I canft help it if all my animals are healthy.



HE WENT OFF with the small cart to fetch the goat. A few minutes later, a big wagon crunched down to the yard gate and stopped just in time. Too wide to pass through; itfd have got stuck.

Praise be, Marhouse had sent me the scorpion. Rather less joy and happiness, hefd come along with it, but never mind.

The scorpion is genuine Mezentine, two hundred years old at least. Family tradition says Marhousefs great-great-and-so-forth-grandfather brought it back from the Grand Tour, as a souvenir. More likely, his grandfather took it in part exchange or to settle a bad debt; but to acknowledge that would be to admit that two generations back they were still in trade.

gWhat the hell,h Marhouse said, hopping down off the wagon box, gdo you want it for?h

Hefs all right, I suppose. We were in Outremer together\met there for the first time, which is crazy, since our houses are only four miles apart. But he was fostered as a boy, away up country somewhere. Ifve always assumed thatfs what made him turn out like he did.

I gave him a sort of hopeless grin. Our kitchenmaid was still sitting up on the box, hoping for someone to help her down. gThanks,h I said. gIfm hoping we wonft need it, but\h

A scorpion is a siege engine; a pretty small one, compared to the huge stone-throwing catapults and mangonels and trebuchets they pounded us with at Crac des Bests. Itfs essentially a big steel crossbow, with a frame, a heavy stand and a super-efficient winch. One man with a long steel bar can wind it up, and it shoots a steel arrow long as your arm and thick as your thumb three hundred yards. We had them at Metouches. Fortunately, the other lot didnft.

I told Marhouse about the dragon. He assumed I was trying to be funny. Then he caught sight of the trap, lying on the ground in front of the cider house, and he went very quiet.

gYoufre serious,h he said.

I nodded. gApparently itfs burned some houses out at Merebarton.h

gBurned.h Never seen him look like that before.

gSo they reckon. I donft think itfs just a drake.h

gThatfs\h He didnft get around to finishing the sentence. No need.

gWhich is why,h I said, trying to sound cheerful, gIfm so very glad your grandad had the foresight to buy a scorpion. No wonder he made a fortune in business. He obviously knew good stuff when he saw it.h

Took him a moment to figure that one out, by which time the moment had passed. gTherefs no arrows,h he said.

gWhat?h

gNo arrows,h he repeated, gjust the machine. Well,h he went on, gitfs not like we use the bloody thing, itfs just for show.h

I opened and closed my mouth a couple of times. gSurely there mustfve been\h

gOriginally, yes, I suppose so. I expect they got used for something around the place.h He gave me a thin smile. gWe donft tend to store up old junk for two hundred years on the offchance in my family,h he said.

I was trying to remember what scorpion bolts look like. Therefs a sort of three-bladed flange down the butt end, to stabilise them in flight. gNo matter,h I said. gBit of old rodfll have to do. Ifll get Moddo to run me some up.h I was looking at the machine. The lead screws and the keyways the slider ran in were caked up with stiff, solid bogeys of dried grease. gDoes it work?h

gI assume so. Or it did, last time it was used. We keep it covered with greased hides in the root store.h

I flicked a flake of rust off the frame. It looked sound enough, but what if the works had seized solid? gGuess Ifd better get it down off the cart and wefll see,h I said. gWell, thanks again. Ifll let you know how it turns out.h

Meaning: please go away now. But Marhouse just scowled at me. gIfm staying here,h he said. gYou honestly think Ifd trust you lot with a family heirloom?h

gNo, really,h I said, gyou donft need to trouble. I know how to work these things, remember. Besides, theyfre pretty well indestructible.h

Wasting my breath. Marhouse is like a dog I used to have, couldnft bear to be left out of anything; if you went out for a shit in the middle of the night, she had to come too. Marhouse was the only one of us in Outremer who ever volunteered for anything. And never got picked, for that exact reason.



SO, THROUGH NO choice or fault of my own, there were nine of us: me, Ebba, Marhouse, the six men from the farm. Of the six, Liutprand is seventeen and Rognvald is twenty-nine, though he barely counts, with his bad arm. The rest of us somewhere between fifty-two and sixty. Old men. We must be mad, I thought.

We rode out there in the flat-bed cart, bumping and bouncing over the ruts in Watery Lane. Everybody was thinking the same thing, and nobody said a word: what if the bugger swoops down and crisps the lot of us while wefre sat here in the cart? In addition, I was also thinking: Marhouse is his own fault, after all, hefs a knight too, and he insisted on butting in. The rest of them, though\my responsibility. Send for the knight, theyfd said, not the knight and half the damn village. But a knight in real terms isnft a single man, hefs the nucleus of a unit, the heart of a society; the lance in war, the village in peace, he stands for them, in front of them when therefs danger, behind them when times are hard, not so much an individual, more of a collective noun. Thatfs understood, surely; so that, in all those old tales of gallantry and errantry, when the poet sings of the knight wandering in a dark wood and encountering the evil to be fought, the wrong to be put right, eknightf in that context is just shorthand for a knight and his squire and his armour-bearer and his three men-at-arms and the boy who leads the spare horses. The others arenft mentioned by name, theyfre subsumed in him, he gets the glory or the blame but everyone knows, if they stop to think about it, that the rest of them were there too; or who lugged around the spare lances, to replace the ones that got broken? And who got the poor bugger in and out of his full plate harness every morning and evening? There are some straps and buckles you just canft reach on your own, unless you happen to have three hands on the ends of unnaturally long arms. Without the people around me, Ifd be completely worthless. Itfs understood. Well, isnft it?

We set the trap up on the top of a small rise, in the big meadow next to the old clay pit. Marhousefs suggestion, as a matter of fact; he reckoned that it was where the flightlines the thing had been following all crossed. Flightlines? Well yes, he said, and proceeded to plot all the recorded attacks on a series of straight lines, scratched in the dried splatter on the side of the cart with a stick. It looked pretty convincing to me. Actually, I hadnft really given it any thought, just assumed that if we dumped a bleeding carcass down on the ground, the dragon would smell it and come whooshing down. Stupid, when you come to think of it. And I call myself a huntsman.

Moddo had fitted the trap with four good, thick chains, attached to eighteen-inch steel pegs, which we hammered into the ground. Again, Marhouse did the thinking. They needed to be offset (his word) so that if it pulled this way or that, therefd be three chains offering maximum resistance\well, it made sense when he said it. Hefs got that sort of brain, invents clever machines and devices for around the farm. Most of them donft work, but some of them do.

The trap, of course, was Plan A. Plan B was the scorpion, set up seventy-five yards away under the busted chestnut tree, with all that gorse and briars for cover. The idea was, we had a direct line of sight, but if we missed and he came at us, he wouldnft dare swoop in too close, for fear of smashing his wings on the low branches. That bit was me.

We propped the poor dead goat up on sticks so it wasnft actually pressing on the floorplate of the trap, then scampered back to where wefd set up the scorpion. Luitprand got volunteered to drive the cart back to Castle Farm; he whined about being out in the open, but I chose him because hefs the youngest and I wanted him well out of harmfs way if the dragon actually did put in an appearance. Seventy-five yards was about as far as I trusted the scorpion to shoot straight without having to make allowance for elevation\we didnft have time to zero it, obviously\but it felt stupidly close. How long would it take the horrible thing to fly seventy-five yards? I had no idea, obviously. We spanned the scorpion\reassuringly hard to do\loaded Moddofs idea of a bolt into the slider groove, nestled down as far as we could get into the briars and nettles, and waited.

No show. When it got too dark to see, Marhouse said, gWhat kind of poison do you think itfd take to kill something like that?h

Ifd been thinking about that. gSomething we havenft got,h I said.

gYou reckon?h

gOh come on,h I said. gI donft know about you, but I donft keep a wide selection of poisons in the house. For some reason.h

gTherefs archerfs root,h Ebba said.

gHefs right,h Marhouse said. gThat stufffll kill just about anything.h

gOf course it will,h I replied. gBut nobody around here\h

gMercel,h Ebba said. gHefs got some.h

News to me. gWhat?h

gMercel. Liddafs boy. He uses it to kill wild pigs.h

Does he now? I thought. It had occurred to me that wild boar were getting a bit hard to find. I knew all about smearing a touch of archerfs root on a bit of jagged wire nailed to a fencepost\boar love to scratch, and itfs true, they do a lot of damage to standing corn. Thatfs why I pay compensation. Archerfs root is illegal, of course, but so are a lot of useful everyday commodities.

gIfd better ask him,h Ebba said. gHe wonft want to get in any trouble.h

Decided unanimously, apparently. Well, we werenft doing any good crouching in the bushes. It did cross my mind that if the dragon hadnft noticed a dead goat with a trap under it, there was no guarantee itfd notice the same dead goat stuffed full of archerfs root, but I dismissed the idea as unconstructive.

We left the trap and the scorpion set up, just in case, and walked back to Castle Farm. To begin with, as we came over the top of the Hogfs Back down Castle Lane, I assumed the pretty red glow on the skyline was the last blush of the setting sun. As we got closer, I hoped that was what it was. By the time we passed the quince orchard, however, the hypothesis was no longer tenable.

We found Luitprand in the goose pond. Stupid fool, hefd jumped in the water to keep from getting burned up. Of course, the mudfs three feet deep on the bottom. I could have told him that.

In passing: I think Luitprand was my son. At any rate, I knew his mother rather too well, seventeen years ago. Couldnft ever say anything, naturally. But he reminded me a lot of myself. For a start, he was half-smart stupid, just like me. Hurling myself in the pond to avoid the flames was just the sort of thing I might have done at his age; and, goes without saying, he wasnft there when we dug the bloody pond, twenty-one years ago, so how could he have known wefd chosen the soft spot, no use for anything else?

No other casualties, thank God, but the hay barn, the straw rick, the woodpile, all gone. The thatch, miraculously, burnt itself out without taking the rafters with it. But losing that much hay meant wefd be killing a lot of perfectly good stock come winter, since I canft afford to buy in. One damn thing after another.

Opito, Larcanfs wife, was hysterical, even though her home hadnft gone in up flames after all. Larcan said it was a great big lizard, about twenty feet long. He got one very brief glimpse of it out of the corner of his eye, just before he dragged his wife and son under the cart. He looked at me like it was all my fault. Just what I needed after a long day crouched in a briar patch.

Luitprand played the flute; not very well. I gave him the one I brought back from Outremer. I never did find it among his stuff, so I can only assume he sold it at some point.



ANYWAY, THAT WAS that, as far as I was concerned. Whatever it was, wherever it had come from, it would have to be dealt with, as soon as possible. On the ride back from the farm, Marhouse had been banging on about flightlines again, where we were going to move the bait to; two days here, while the windfs in the south, then if thatfs no good, then another two days over there, and if that still doesnft work, wefll know for sure it must be following the line of the river, so either here, there, or just possibly everywhere, would be bound to do the trick, logically speaking. I smiled and nodded. Ifm sure he was perfectly correct. Hefs a good huntsman, Marhouse. Come the end of the season, he always knows exactly where all the game wefve failed to find must be holed up. Next year, he then says\

Trouble was, there wasnft time for a next year.



BY MIDNIGHT (COULDNfT sleep, oddly enough) I was fairly sure how it had to be done.

Before you start grinning to yourself at my presumption, I had no logical explanation for my conclusions. Flightlines, patterns of behaviour, life cycles, cover crops, mating seasons, wind directions; put them together and youfll inevitably flush out the truth, which will then elude you, zig-zag running through the roots of the long variables. I knew.

I knew, because I used to hunt with my father. He was, of course, always in charge of everything, knew everything, excelled at everything. We never caught much. And I knew, when hefd drawn up the lines of beaters, given them their timings (say three Glorious Sun Ascendants and two Minor Catechisms, then come out making as much noise as you can), positioned the stillhunters and the hounds and the horsemen, finally blown the horn; I knew exactly where the wretched animal would come bursting out, so as to elude us all with the maximum of safety and the minimum of effort. Pure intuition, never failed. Naturally, I never said anything. Not my place to.

So: I knew what was going to happen, and that there was nothing much I could do about it, and my chances of success and survival were\well, not to worry about that. When I was in Outremer, I got shot in the face with an arrow. Shouldfve killed me instantly; but by some miracle it hung up in my cheekbone, and an enemy doctor wefd captured the day before yanked it out with a pair of tongs. You should be dead, they said to me, like Ifd deliberately cheated. No moral fibre. Ever since then\true, I shuddered to think how the estate would get on with my brother in charge, but it survived my father and grandfather, so it was clearly indestructible. Besides, everyone dies sooner or later. Itfs not like Ifm important.



MARHOUSE INSISTED ON coming with us. I told him, you stay here, wefll need a wise, experienced hand to take charge if it decides to burn out the castle. For a moment I thought hefd fallen for it, but no such luck.

So there were three of us: me, Ebba, Marhouse. The idea was, wefd follow the Ridgeway on horseback, looking down on either side. As soon as we saw smoke, Ebba would ride back to the castle and get the gear, meet us at the next likely attack scene. I know; bloody stupid idea. But I knew it wouldnft happen like that, because I knew how itfd happen.

Marhouse had on his black-and-white\thatfs breastplate, pauldrons, rerebraces and tassets. I told him, youfll boil to death in that lot. He scowled at me. Hefd also fetched along a full-weight lance, issue. You wonft need that, I told him. Ifd got a boar-spear, and Ebba was carrying the steel crossbow my father spent a whole yearfs apple money on, the year before he died. gBut theyfre just to make us feel better,h I said. That got me another scowl. The wrong attitude.

Noon; nothing to be seen anywhere. I was just daring to think, perhaps the bloody thingfs moved on, or maybe itfd caught some disease or got itself hung up in a tree. Then I saw a crow.

I think Ebba saw it first, but he didnft point and say, gLook, therefs a crowh. Marhouse was explaining some fine point of decoying, how you go about establishing which tree is the principal turning point on an elliptical recursive flight pattern. I thought: thatfs not a crow, itfs just hanging there. Must be a hawk.

Ebba was looking over his shoulder. No, not a hawk, the profilefs wrong. Marhouse stopped talking, looked at me, said, gWhat are you two staring at?h I was thinking, Oh.

Ifm right about things so rarely that I usually relish the experience. Not this time.

Oh, you may be thinking, is a funny way of putting it. But that was the full extent of it: no elation, no regret, not even resignation; to my great surprise, no real fear. Just: oh, as in, well, here we are, then. Call it a total inability to feel anything. Twice in Outremer, once when my father died, and now. Ifd far rather have wet myself, but you canft decide these things for yourself. Oh, I thought, and that was all.

Marhouse was swearing, which isnft like him. He only swears when hefs terrified, or when somethingfs got stuck or broken. Bad language, he reckons, lubricates the brain, stops it seizing up with fear or anger. Ebba had gone white as milk. His horse was playing up, and he was having to work hard to keep it from bolting. Amazing how they know.

On top of the Ridgeway, of course, therefs no cover. We could gallop forward, or turn around and gallop back; either case, at the rate the bloody thing was moving, itfd be on us long before we could get our heads down. I heard someone give the order to dismount. Wasnft Marhouse, because he stayed mounted. Wouldnft have been Ebba, so I guess it mustfve been me.

First time, it swooped down low over our heads\about as high up as the spire of Blue Temple\and just kept on going. We were frozen solid. We watched. It was on the glide, like a pigeon approaching a laid patch in a barley field, deciding whether to pitch or go on. Very slight tailwind, so if it wanted to come in on us, itfd have to bank, turn up into the wind a little bit to start to stall, then wheel and come in with its wings back. I honestly thought: itfs gone too far, itfs not going to come in. Then it lifted, and I knew.

Sounds odd, but I hadnft really been looking at it the first time, when it buzzed us. I saw a black bird shape, long neck like a heron, long tail like a pheasant, but no sense of scale. As it came in the second time, I couldnft help but stare; a real dragon, for crying out loud, something to tell your grandchildren about. Well, maybe.

Ifd say the body was about horse-sized, head not in proportion; smaller, like a red deer stag. Wings absurdly large\featherless, like a bat, skin stretched on disturbingly extended fingers. Tail, maybe half as long again as the body; neck like a swan, if that makes any sense. Sort of a grey colour, but it looked green at a distance. Big hind legs, small front legs looking vaguely ridiculous, as if it had stolen them off a squirrel. A much rounder snout than Ifd expected, almost chubby. It didnft look all that dangerous, to be honest.

Marhouse is one of those people who translate fear into action; the scareder he is, the braver. Works against people. No warning\itfd have been nice if hefd said something first; he kicked his horse hard enough to stove in a rib, lance in rest, seat and posture straight out of the coaching manual. Rode straight at it.

What happened then\

Marhouse was five yards away from it, going full tilt. The dragon probably couldnft have slowed down if it had wanted to. Instead\it actually made this sort of epopf noise as it opened its mouth and burped up a fat round ball of fire, then lifted just a little, to sail about five feet over Marhousefs head. He, meanwhile, rode straight into the fireball, and through it.

And stopped, and fell all to pieces; the reason being, there was nothing left. Horse, man, all gone, not even ash, and the dozen or so pieces of armour dropping glowing to the ground, cherry-red, like theyfd just come off the forge. Ifve seen worse things, in Outremer, but nothing stranger.

I was gawping, forgetting all about the dragon. It was Ebba who shoved me down as it came back. I have no idea why it didnft just melt us both as it passed, unless maybe it was all out of puff and needed to recharge. Anyway, it soared away, repeated the little lift. I had a feeling it was enjoying itself. Well, indeed. It must be wonderful to be able to fly.

Ebba was shouting at me, waving something, the crossbow, he wanted me to take it from him. gShoot it,h he was yelling. Made no sense to me; but then again, why not? I took the bow, planted my feet a shouldersf width apart, left elbow tucked in tight to the chest to brace the bow, just the fingers on the trigger. A good archery stance didnft seem to have anything to do with the matter in hand\like playing bowls in the middle of an earthquake\but Ifm a good archer, so I couldnft help doing it properly. I found the dragon in the middle of the peep-sight, drew the tip of the arrow up to find it, and pressed the trigger.

For the record, I hit the damn thing. The bolt went in four inches, just above the heart. Good shot. With a bow five times as strong, quite possibly a clean kill.

I think it mustfve hurt, though, because instead of flaming and lifting, it squirmed\hunched its back then stretched out full-length like a dog waking up\and kept coming, straight at me. I think I actually did try and jump out of the way; just rather too late. I think what hit me mustfve been the side of its head.

I had three ribs stoved in once in Outremer, so I knew what was going on. I recognised the sound, and the particular sort of pain, and the not quite being able to breathe. Mostly I remember thinking: it wonft hurt, because any moment now Ifll be dead. Bizarrely reassuring, as if I was cheating, getting away with it. Cheating twice; once by staying alive, once by dying. This man is morally bankrupt.

I was on my back, not able or minded to move. I couldnft see the dragon. I could hear Ebba shouting; shut up, you old fool, I thought, Ifm really not interested. But he was shouting, gHold on, mate, hold on, Ifm coming,h which made absolutely no sense at all\

Then he shut up, and I lay there waiting. I waited, and waited. Ifm not a patient man. I waited so long, those crunched ribs started to hurt, or at least I became aware of the pain. For crying out loud, I thought. And waited.

And thought: now just a minute.

It hurt so much, hauling myself onto my side so I could see. I was in tears.

Later, I figured out what had happened. When Ebba saw me go down, he grabbed the boar-spear and ran towards me. I donft imagine he considered the dragon, except as an inconvenience. Hold on, Ifm coming; all his thoughts in his words. He got about half way when the dragon pitched\it mustfve swooped off and come in again. As it put its feet down to land, he mustfve stuck the butt of the spear in the ground and presented the point, like you do with a boar, to let it stick itself, its momentum being far more effective than your own puny strength. As it pitched, it lashed with its tail, sent Ebba flying. Whether or not it realised it was dead, the spear a foot deep in its windpipe before the shaft gave way under the pressure and snapped, I neither know nor care. By the marks on the ground, it rolled three or four times before the lights went out. My best estimate is, it weighed just short of a ton. Ebba\under it as it rolled\was crushed like a grape, so that his guts burst and his eyes popped, and nearly all his bones were broken.



HE WOULDNfT HAVE thought: Ifll kill the dragon. Hefd have thought, ground the spear, like boar-hunting, and then the tail hit him, and then the weight squashed him. So it wouldnft have been much; not a heroic thought, not the stuff of song and story. Just: this is a bit like boar-hunting, so ground the spear. And then, perhaps: oh.

I think thatfs all there is; anywhere, anytime, in the whole world.



I TRIED PRESERVING the head in honey. We got an old pottery bath and filled it and put the head in; but eight weeks later it had turned green and it stank like hell, and she said, for pityfs sake get rid of it. So we boiled it out and scraped it, and mounted the skull on the wall. Not much bigger than a big deer; in a hundred yearsf time, they wonft believe the old story about it being a dragon. No such thing as dragons, theyfll say.

Meanwhile, for now, Ifm the Dragonslayer; which is a joke. The duke himself threatened to ride over and take a look at the remains, but affairs of state supervened, thank God. Entertaining the duke and his court wouldfve ruined us, and wefd lost so much already.

Twice Ifve cheated. Marhouse was straight as a die, and his end, Ifm sorry, was just ludicrous. I keep telling myself, Ebba made a choice, you must respect that. I canft. Instead of a friend, I have a horrible memory, and yet another debt I canft pay. People assume you want to be saved, no matter what the cost; sometimes, though, itfs just too expensive to stay alive. Not sure Ifll ever forgive him for that.

And thatfs that. I really donft want to talk about it anymore.
* The Dragonslayer of Merebarton (PG-13 edited)
K J Parker



I WAS MENDING my chamber pot when they came to tell me about the dragon.

Mending a pot is one of those jobs you think is easy, because tinkers do it, and tinkers are no good or theyfd be doing something else. Actually, itfs not easy at all. You have to drill a series of very small holes in the broken pieces, then thread short lengths of wire through the holes, then twist the ends of the wires together really tight, so as to draw the bits together firmly enough to make the pot watertight. In order to do the job you need a very hard, sharp, thin drill bit, a good eye, loads of patience and at least three pairs of rock-steady hands. The tinker had quoted me a turner and a quarter; get lost, I told him, Ifll do it myself. It was beginning to dawn on me that some sorts of work are properly reserved for specialists.

Ah, the irony.

Stupid of me to break it in the first place. Ifm not usually that clumsy. Stumbling about in the dark, was how I explained it. You shouldfve lit a lamp, then, shouldnft you, she said. I pointed out that you donft need a lamp in the long summer evenings. She smirked at me. I donft think she quite understands how finely balanced our financial position is. Wefre not hard up, nothing like that. Therefs absolutely no question of having to sell off any of the land, or take out mortgages. Itfs just that, if we carry on wasting money unnecessarily on lamp-oil and tinkers and like frivolities, therefll come a time when the current slight reduction in our income will start to be a mild nuisance. Only temporary, of course. The hard times will pass, and soon wefll all be just fine.

Like I said, the irony.

gEbbafs here to see you,h she said.

She could see I was busy. gHefll have to come back,h I snapped. I had three little bits of wire gripped between my lips, which considerably reduced my snapping power.

gHe said itfs urgent.h

gFine.h I put down the pot\call it that, no way it was a pot any more. It was disjointed memories of the shape of a pot, loosely tied together with metal string, like the scale armour the other side wore in Outremer. gSend him up.h

gHefs not coming up here in those boots,h she said, and at once I realised that no, he wasnft, not when she was using that tone of voice. gAnd why donft you just give up on that? Youfre wasting your time.h

Women have no patience. gThe tinker\h

gThat bit doesnft go there.h

I dropped the articulated mess on the floor and walked past her, down the stairs, into the great hall. Great, in this context, is strictly a comparative term.

Ebba and I understand each other. For a start, hefs practically the same age as me\Ifm a week younger; so what? We both grew up silently ashamed of our fathers (his father Ossun was the laziest man on the estate; mine\well) and wefre both quietly disappointed with our children. He took over his farm shortly before I came home from Outremer, so we both sort of started off being responsible for our own destinies around the same time. I have no illusions about him, and I canft begin to imagine he has any about me. Hefs medium height, bald and thin, stronger than he looks and smarter than he sounds. He used to set up the targets and pick up the arrows for me when I was a boy; never used to say anything, just stood there looking bored.

He had that look on his face. He told me I wasnft going to believe what he was about to tell me.

The thing about Ebba is, he has absolutely no imagination. Not even when roaring drunk\whimpering drunk in his case; very rare occurrence, in case youfve got the impression hefs what she calls basically-no-good. About twice a year, specific anniversaries. I have no idea what theyfre the anniversaries of, and of course I donft ask. Twice a year, then, he sits in the hayloft with a big stone jar and only comes out when itfs empty. Not, is the point Ifm trying to make, prone to seeing things not strictly speaking there.

gTherefs a dragon,h he said.

Now Ossun, his father, saw all manner of weird and wonderful things. gDonft be bloody stupid,h I said. He just looked at me. Ebba never argues or contradicts; doesnft need to.

gAll right,h I said, and the words just sort of squeezed out, like a fat man in a narrow doorway. gWhere?h

gDown Merebarton.h



A BRIEF DIGRESSION concerning dragons.

Therefs no such thing. However, therefs the White Drake (its larger cousin, the Blue Drake, is now almost certainly extinct). According to Hrabanusf Imperfect Bestiary, the White Drake is a native of the large and entirely unexpected belt of marshes you stumble into after youfve crossed the desert, going from Crac Boamond to the sea. Hrabanus thinks itfs a very large bat, but conscientiously cites Priscian, who holds that itfs a featherless bird, and Saloninus, who maintains that itfs a winged lizard. The White Drake can get to be five feet long\thatfs nose to tip-of-tail; three feet of that is tail, but it can still give you a nasty nip. They launch themselves out of trees, which can be horribly alarming (I speak from personal experience). White Drakes live almost exclusively on carrion and rotting fruit, rarely attack unless provoked and absolutely definitely donft breathe fire.

White Drakes arenft found outside Outremer. Except, some idiot of a nobleman brought back five breeding pairs about a century ago, to decorate the grounds of his castle. Why people do these things, I donft know. My father tried to keep peacocks once. As soon as we opened the cage they were off like arrows from the bowstring; next heard of six miles away, and could we please come and do something about them, because they were pecking the thatch out in handfuls. My father rode over that way, happening to take his bow with him. No more was ever said about peacocks.

Dragons, by contrast, are nine to ten feet long excluding the tail; they attack on sight, and breathe fire. At any rate, this one did.



THREE HOUSES AND four barns in Merebarton, two houses and a hayrick in Stile. Nobody hurt yet, but only a matter of time. A dozen sheep carcasses, stripped to the bone. One shepherd reported being followed by the horrible thing: he saw it, it saw him, he turned and ran; it just sort of drifted along after him, hardly a wingbeat, as if mildly curious. When he couldnft run any further, he tried crawling down a badger hole. Got stuck, head down the hole, legs sticking up in the air. He reckoned he felt the thump as the thing pitched down next to him, heard the snuffling\like a bull, he reckoned; felt its warm breath on his ankles. Time sort of stopped for a while, and then it went away again. The man said it was the first time hefd pissed himself and felt the piss running down his chest and dripping off his chin. Well, there you go.

The Brother at Merebarton appears to have taken charge, the way they do. He herded everyone into the grain store\stone walls, yes, but a thatched roof; youfd imagine even a Brother wouldfve watched them making charcoal some time\and sent a terrified young kid off on a pony to, guess what. Youfve got it. Fetch the knight.



AT THIS POINT, the story recognises (isnft that what they say in Grand Council?) Dodinas le Cure Hardy, age fifty-six, knight, of the honours of Westmoor, Merebarton, East Rew, Middle Side and Big Room; veteran of Outremer (four years, so help me), in his day a modest success on the circuit\three second places in ranking tournaments, two thirds, usually in the top twenty out of an average field of forty or so. Through with all that a long time ago, though. I always knew I was never going to be one of those gaunt, terrifying old men who carry on knocking fem down and getting knocked down into their sixties. I had an uncle like that, Petipas of Lyen. I saw him in a tournament when he was sixty-seven, and some young giant bashed him off his horse. Uncle landed badly, and I watched him drag himself up off the ground, so desperately tired. I was only, what, twelve; even I could see, every last scrap of flesh and bone was yelling, donft want to do this any more. But he stood up, shamed the young idiot into giving him a go on foot, and proceeded to use his head as an anvil for ten minutes before graciously accepting his surrender. There was so much anger in that performance\not at the kid, for showing him up, Uncle wasnft like that. He was furious with himself for getting old, and he took it out on the only target available. I thought the whole thing was disturbing and sad. I wonft ever be like that, I told myself.

(The question was, is: why? I can understand fighting. I fought\really fought\in Outremer. I did it because I was afraid the other man was going to kill me. So happens my defence has always been weak, so I compensate with extreme aggression. Never could keep it going for very long, but on the battlefield thatfs not usually an issue. So I attacked anything that moved with white-hot ferocity fuelled entirely and exclusively by ice-cold fear. Tournaments, though, jousting, behourd, the grand melee\what was the point? I have absolutely no idea, except that I did feel very happy indeed on those rare occasions when I got a little tin trophy to take home. Was that enough to account for the pain of being laid up six weeks with two busted ribs? Of course it wasnft. We do it because itfs what we do; one of my fatherfs more profound statements. Conversely, I remember my aunt: silly woman, too soft for her own good. She kept these stupid big white chickens, and when they got past laying she couldnft bear to have their necks pulled. Instead, they were taken out into the woods and set free, meaning in real terms fed to the hawks and foxes. One time, my turn, I lugged down a cage with four hens and two cocks squashed in there, too petrified to move. Now, what draws in the fox is the clucking; so I turned them out in different places, wide apart, so they had nobody to talk to. Released the last hen, walking back down the track; already the two cock birds had found each other, no idea how, and were ripping each other into tissue scraps with their spurs. They do it because itfs what they do. Someone once said, the man whofs tired of killing is tired of life. Not sure I know what that means.)



A PICTURE IS emerging, I hope, of Dodinas le Cure Hardy; while he was active in chivalry he tried to do what was expected of him, but his heart was never in it. Glad, in a way, to be past it and no longer obliged to take part. Instead, prefers to devote himself to the estate, trying to keep the ancestral mess from collapsing in on itself. A man aware of his obligations, and at least some of his many shortcomings.

Go and fetch the knight, says the fool of a Brother. Tell him\



ON REFLECTION, IF I hadnft seen those wretched White Drakes in Outremer, therefs a reasonable chance Ifd have refused to believe in a dragon trashing Merebarton, and then, who knows, it mightfve flown away and bothered someone else. Well, you donft know, thatfs the whole point. Itfs that very ignorance that makes life possible. But when Ebba told me what the boy told him hefd seen, immediately I thought: White Drake. Clearly it wasnft one, but it was close enough to something Ifd seen to allow belief to seep into my mind, and then I was done for. No hope.

Even so, I think I said, gAre you sure?h about six or seven times, until eventually it dawned on me I was making a fool of myself. At which point, a horrible sort of mist of despair settled over me, as I realised that this extraordinary, impossible, grossly and viciously unfair thing had landed on me, and that I was going to have to deal with it.

But you do your best. You struggle, just as a man crushed under a giant stone still draws in the last one or two desperate whistling breaths; pointless, but you canft just give up. So I looked him steadily in the eye, and I said, gSo, what do they expect me to do about it?h

He didnft say a word. Looked at me.

gThe heck with that,h I remember shouting. gIfm fifty-six years old, I donft even hunt boar any more. Ifve got a stiff knee. I wouldnft last two minutes.h

He looked at me. When youfve known someone all your life, arguing with them is more or less arguing with yourself. Never had much joy with lying to myself. Or anyone else, come to that. Of course, my mother used to say: the only thing I want you not to be the best in the world at is lying. She said a lot of that sort of thing; much better written down on paper rather than said out loud in casual conversation, but of course she couldnft read or write. She also tended to say: do your duty. I donft think she ever liked me very much. Loved, of course, but not liked.

He was looking at me. I felt like that poor devil under the stone (at the siege of Crac des Bests; man I knew slightly). Comes a point when you just canft breathe any more.



WE DO HAVE a library: forty-seven books. The Imperfect Bestiary is an abridged edition, local copy, drawings are pretty laughable, they make everything look like either a pig or a cow, because thatfs all the poor fool who drew it had ever seen. So there I was, looking at a picture of a big white cow with wings, thinking: how in Godfs name am I supposed to kill something like that?

White Drakes donft breathe fire, but therefs this stupid little lizard in Permia somewhere that does. About eighteen inches long, otherwise completely unremarkable; not to put too fine a point on it, it farts through its mouth and somehow contrives to set fire to it. You see little flashes and puffs of smoke among the reed beds. So itfs possible. Wonderful.

(Why would anything want to do that? Hrabanus, who has an answer for every darn thing, points out that the reed beds would clog up the delta, divert the flowing water and turn the whole of South Permia into a fetid swamp if it wasnft for the frequent, regular fires, which clear off the reed and lay down a thick bed of fertile ash, just perfect for everything else to grow sweet and fat and provide a living for the hundreds of species of animals and birds who live there. The fires are started by the lizards, who appear to serve no other function. Hrabanus points to this as proof of the Divine Clockmaker theory. I think they do it because itfs what they do, though Ifm guessing the lizards who actually do the fire-starting are resentful younger sons. Tell you about my brother in a minute.)



SHE FOUND ME in the library. Clearly shefd been talking to Ebba. gWell?h she said.

I told her what Ifd decided to do. She can pull this face of concentrated scorn and fury. Itfs so intensely eloquent, therefs really no need for her to add words. But she does. Oh, she does.

gIfve got no choice,h I protested. gIfm the knight.h

gYoufre fifty-six and you get out of breath climbing the stairs. And youfre proposing to fight dragons.h

Itfs a black lie about the stairs. Just that one time; and that was the clock-tower. Seventy-seven steps to the top. gI donft want to do it,h I pointed out. gLast bloody thing I want\h

gLast bloody thing youfll ever do, if youfre stupid enough to do it.h She never swears, except when quoting me back at myself. gJust think for a minute, will you? If you get yourself killed, whatfll happen to this place?h

gI have no intention of getting myself\h

gFlorianfs too young to run the estate,h she went on, as though I hadnft spoken. gThat clown of a bailiff of yours canft be trusted to remember to breathe without someone standing over him. On top of which, therefs heriot and wardship, thatfs hundreds and hundreds of thalers we simply havenft got, which means having to sell land, and once you start doing that you might as well load up a handcart and take to the roads, because\h

gAbsolutely no intention of getting killed,h I said.

gAnd for crying out loud donft shout,h she shouted. gItfs bad enough youfre worrying me to death without yelling at me as well. I donft know why you do this to me. Do you hate me, or something?h

We were four and a quarter seconds away from tears, and I really canft be doing with that. gAll right,h I said. gSo tell me. What do I do?h

gI donft know, do I? I donft get myself into these ridiculous messes.h I wish I could do that; I should be able to. After all, itfs the knightfs move, isnft it? A step at right angles, then jump clean over the other manfs head. gWhat about that useless brother of yours? Send him.h

The dreadful thing is, the same thought had crossed my mind. Itfd be\well, not acceptable, but within the rules, meaning therefs precedents. Of course, Ifd have to be practically bedridden with some foul but honourable disease. Titurel is ten years younger than me and still competing regularly on the circuit, though at the time he was three miles away, at the lodge, with some female hefd found somewhere. And if I really was ill\

I was grateful to her. If she hadnft suggested it, I might just have considered it. As it was; gDonft be ridiculous,h I said. gJust think, if I was to chicken out and Titurel actually managed to kill this bloody thing. Wefve got to live here. Hefd be insufferable.h

She breathed through her nose; like, dare I say it, one of the D things. gAll right,h she said. gThough how precisely itfs better for you to get killed and your appalling brother moves in and takes over running the estate\h

gI am not going to get killed,h I said.

gBut there, you never listen to me, so I might as well save my breath.h She paused and scowled at me. gWell?h

Hard, sometimes, to remember that when I married her, she was the Fair Maid of Lannandale. gWell what?h

gWhat are you going to do?h



gOH,h HE SAID, sort of half-turning and wiping his forehead on his forearm. gItfs you.h

Another close contemporary of mine. Hefs maybe six months older than me, took over the forge just before my father died. Hefs never liked me. Still, we understand each other. Hefs not nearly as good a tradesman as he thinks he is, but hefs good enough.

gCome to pay me for those harrows?h he said.

gNot entirely,h I replied. gI need something made.h

gOf course you do.h He turned his back on me, dragged something orange-hot out from under the coals, and bashed it, very hard, very quickly, for about twenty seconds. Then he shoved it back under the coals and hauled on the bellows handle a dozen times. Then he had leisure to talk to me. gIfll need a deposit.h

gDonft be silly,h I said. There was a small heap of tools piled up on the spare anvil. I moved them carefully aside and spread out my scraps of parchment. gNow, youfll need to pay attention.h



THE PARCHMENT IfD drawn my pathetic attempts at sketches on was the fly-leaf out of Monomachus of Teanafs Principles of Mercantile Law. Ifd had just enough left over to use for a very brief note, which Ifd folded four times, sealed, and sent the stable boy off to deliver. It came back, folded the other way; and under my message, written in big crude handwriting, smudged for lack of sand\

What the heck do you want it for?

I wasnft in the mood. I stamped back into the house (Ifd been out in the barn, rummaging about in the pile of old junk), got out the pen and ink and wrote sideways up the margin (only just enough room, writing very small)\

No time. Please. Now.

I underlined please twice. The stable boy had wandered off somewhere, so I sent the kitchenmaid. She whined about having to go out in her indoors shoes. I ask you.



MODDO THE BLACKSMITH is one of those men who gets caught up in the job in hand. He whinges and complains, then the problems of doing the job snag his imagination, and then your main difficulty is getting it away from him when itfs finished, because hefs just come up with some cunning little modification whichfll make it ever so slightly, irrelevantly better.

He does good work. I was so impressed I paid cash.

gYour design was useless, so I changed it,h hefd said. A bit of an overstatement. What hefd done was to substitute two thin springs for one fat one, and add on a sort of ratchet thing taken off a millersf winch, to make it easier to wind it up. It was still sticky with the oil hefd quenched it in. The sight of it made my flesh crawl.

Basically, it was just a very, very large gin trap, with an offset pressure plate. gItfs pretty simple,h I said. gThink about it. Think about birds. In order to get off the ground, theyfve got very light bones, right?h

Ebba shrugged: if you say so.

gWell,h I told him, gthey have. And you break a birdfs leg, it canft get off the ground. Ifm assuming itfs the same with this bastard. We put out a carcass, with this underneath. It stands on the carcass, braces it with one foot so it can tear it up with the other. Bang, got him. This thing ought to snap the buggerfs leg like a carrot, and then it wonft be going anywhere in a hurry, you can be sure of that.h

He frowned. I could tell the sight of the trap scared him, like it did me. The mainspring was three eighths of an inch thick. Just as well Moddo thought to add a cocking mechanism. gYoufll still have to kill it, though,h he said.

I grinned at him. gWhy?h I asked. gNo, the heck with that. Just keep everybody and their livestock well away for a week until it starves to death.h

He was thinking about it. I waited. gIf it can breathe fire,h he said slowly, gmaybe it can melt the trap off.h

gAnd burn through its own leg in the process. Also,h I added\Ifd considered this very point\geven without the trap itfs still crippled, it wonft be able to hunt and feed. Just like a bird thatfs got away from the cat.h

He pulled a small frown that means, well, maybe. gWefll need a carcass.h

gTherefs that sick goat,h I said.

Nod. His sick goat. Well, I canft help it if all my animals are healthy.



HE WENT OFF with the small cart to fetch the goat. A few minutes later, a big wagon crunched down to the yard gate and stopped just in time. Too wide to pass through; itfd have got stuck.

Praise be, Marhouse had sent me the scorpion. Rather less joy and happiness, hefd come along with it, but never mind.

The scorpion is genuine Mezentine, two hundred years old at least. Family tradition says Marhousefs great-great-and-so-forth-grandfather brought it back from the Grand Tour, as a souvenir. More likely, his grandfather took it in part exchange or to settle a bad debt; but to acknowledge that would be to admit that two generations back they were still in trade.

gWhat the heck,h Marhouse said, hopping down off the wagon box, gdo you want it for?h

Hefs all right, I suppose. We were in Outremer together\met there for the first time, which is crazy, since our houses are only four miles apart. But he was fostered as a boy, away up country somewhere. Ifve always assumed thatfs what made him turn out like he did.

I gave him a sort of hopeless grin. Our kitchenmaid was still sitting up on the box, hoping for someone to help her down. gThanks,h I said. gIfm hoping we wonft need it, but\h

A scorpion is a siege engine; a pretty small one, compared to the huge stone-throwing catapults and mangonels and trebuchets they pounded us with at Crac des Bests. Itfs essentially a big steel crossbow, with a frame, a heavy stand and a super-efficient winch. One man with a long steel bar can wind it up, and it shoots a steel arrow long as your arm and thick as your thumb three hundred yards. We had them at Metouches. Fortunately, the other lot didnft.

I told Marhouse about the dragon. He assumed I was trying to be funny. Then he caught sight of the trap, lying on the ground in front of the cider house, and he went very quiet.

gYoufre serious,h he said.

I nodded. gApparently itfs burned some houses out at Merebarton.h

gBurned.h Never seen him look like that before.

gSo they reckon. I donft think itfs just a drake.h

gThatfs\h He didnft get around to finishing the sentence. No need.

gWhich is why,h I said, trying to sound cheerful, gIfm so very glad your grandad had the foresight to buy a scorpion. No wonder he made a fortune in business. He obviously knew good stuff when he saw it.h

Took him a moment to figure that one out, by which time the moment had passed. gTherefs no arrows,h he said.

gWhat?h

gNo arrows,h he repeated, gjust the machine. Well,h he went on, gitfs not like we use the bloody thing, itfs just for show.h

I opened and closed my mouth a couple of times. gSurely there mustfve been\h

gOriginally, yes, I suppose so. I expect they got used for something around the place.h He gave me a thin smile. gWe donft tend to store up old junk for two hundred years on the offchance in my family,h he said.

I was trying to remember what scorpion bolts look like. Therefs a sort of three-bladed flange down the butt end, to stabilise them in flight. gNo matter,h I said. gBit of old rodfll have to do. Ifll get Moddo to run me some up.h I was looking at the machine. The lead screws and the keyways the slider ran in were caked up with stiff, solid bogeys of dried grease. gDoes it work?h

gI assume so. Or it did, last time it was used. We keep it covered with greased hides in the root store.h

I flicked a flake of rust off the frame. It looked sound enough, but what if the works had seized solid? gGuess Ifd better get it down off the cart and wefll see,h I said. gWell, thanks again. Ifll let you know how it turns out.h

Meaning: please go away now. But Marhouse just scowled at me. gIfm staying here,h he said. gYou honestly think Ifd trust you lot with a family heirloom?h

gNo, really,h I said, gyou donft need to trouble. I know how to work these things, remember. Besides, theyfre pretty well indestructible.h

Wasting my breath. Marhouse is like a dog I used to have, couldnft bear to be left out of anything; if you went to the outhouse in the middle of the night, she had to come too. Marhouse was the only one of us in Outremer who ever volunteered for anything. And never got picked, for that exact reason.



SO, THROUGH NO choice or fault of my own, there were nine of us: me, Ebba, Marhouse, the six men from the farm. Of the six, Liutprand is seventeen and Rognvald is twenty-nine, though he barely counts, with his bad arm. The rest of us somewhere between fifty-two and sixty. Old men. We must be mad, I thought.

We rode out there in the flat-bed cart, bumping and bouncing over the ruts in Watery Lane. Everybody was thinking the same thing, and nobody said a word: what if the bugger swoops down and crisps the lot of us while wefre sat here in the cart? In addition, I was also thinking: Marhouse is his own fault, after all, hefs a knight too, and he insisted on butting in. The rest of them, though\my responsibility. Send for the knight, theyfd said, not the knight and half the darn village. But a knight in real terms isnft a single man, hefs the nucleus of a unit, the heart of a society; the lance in war, the village in peace, he stands for them, in front of them when therefs danger, behind them when times are hard, not so much an individual, more of a collective noun. Thatfs understood, surely; so that, in all those old tales of gallantry and errantry, when the poet sings of the knight wandering in a dark wood and encountering the evil to be fought, the wrong to be put right, eknightf in that context is just shorthand for a knight and his squire and his armour-bearer and his three men-at-arms and the boy who leads the spare horses. The others arenft mentioned by name, theyfre subsumed in him, he gets the glory or the blame but everyone knows, if they stop to think about it, that the rest of them were there too; or who lugged around the spare lances, to replace the ones that got broken? And who got the poor bugger in and out of his full plate harness every morning and evening? There are some straps and buckles you just canft reach on your own, unless you happen to have three hands on the ends of unnaturally long arms. Without the people around me, Ifd be completely worthless. Itfs understood. Well, isnft it?

We set the trap up on the top of a small rise, in the big meadow next to the old clay pit. Marhousefs suggestion, as a matter of fact; he reckoned that it was where the flightlines the thing had been following all crossed. Flightlines? Well yes, he said, and proceeded to plot all the recorded attacks on a series of straight lines, scratched in the dried splatter on the side of the cart with a stick. It looked pretty convincing to me. Actually, I hadnft really given it any thought, just assumed that if we dumped a bleeding carcass down on the ground, the dragon would smell it and come whooshing down. Stupid, when you come to think of it. And I call myself a huntsman.

Moddo had fitted the trap with four good, thick chains, attached to eighteen-inch steel pegs, which we hammered into the ground. Again, Marhouse did the thinking. They needed to be offset (his word) so that if it pulled this way or that, therefd be three chains offering maximum resistance\well, it made sense when he said it. Hefs got that sort of brain, invents clever machines and devices for around the farm. Most of them donft work, but some of them do.

The trap, of course, was Plan A. Plan B was the scorpion, set up seventy-five yards away under the busted chestnut tree, with all that gorse and briars for cover. The idea was, we had a direct line of sight, but if we missed and he came at us, he wouldnft dare swoop in too close, for fear of smashing his wings on the low branches. That bit was me.

We propped the poor dead goat up on sticks so it wasnft actually pressing on the floorplate of the trap, then scampered back to where wefd set up the scorpion. Luitprand got volunteered to drive the cart back to Castle Farm; he whined about being out in the open, but I chose him because hefs the youngest and I wanted him well out of harmfs way if the dragon actually did put in an appearance. Seventy-five yards was about as far as I trusted the scorpion to shoot straight without having to make allowance for elevation\we didnft have time to zero it, obviously\but it felt stupidly close. How long would it take the horrible thing to fly seventy-five yards? I had no idea, obviously. We spanned the scorpion\reassuringly hard to do\loaded Moddofs idea of a bolt into the slider groove, nestled down as far as we could get into the briars and nettles, and waited.

No show. When it got too dark to see, Marhouse said, gWhat kind of poison do you think itfd take to kill something like that?h

Ifd been thinking about that. gSomething we havenft got,h I said.

gYou reckon?h

gOh come on,h I said. gI donft know about you, but I donft keep a wide selection of poisons in the house. For some reason.h

gTherefs archerfs root,h Ebba said.

gHefs right,h Marhouse said. gThat stufffll kill just about anything.h

gOf course it will,h I replied. gBut nobody around here\h

gMercel,h Ebba said. gHefs got some.h

News to me. gWhat?h

gMercel. Liddafs boy. He uses it to kill wild pigs.h

Does he now? I thought. It had occurred to me that wild boar were getting a bit hard to find. I knew all about smearing a touch of archerfs root on a bit of jagged wire nailed to a fencepost\boar love to scratch, and itfs true, they do a lot of damage to standing corn. Thatfs why I pay compensation. Archerfs root is illegal, of course, but so are a lot of useful everyday commodities.

gIfd better ask him,h Ebba said. gHe wonft want to get in any trouble.h

Decided unanimously, apparently. Well, we werenft doing any good crouching in the bushes. It did cross my mind that if the dragon hadnft noticed a dead goat with a trap under it, there was no guarantee itfd notice the same dead goat stuffed full of archerfs root, but I dismissed the idea as unconstructive.

We left the trap and the scorpion set up, just in case, and walked back to Castle Farm. To begin with, as we came over the top of the Hogfs Back down Castle Lane, I assumed the pretty red glow on the skyline was the last blush of the setting sun. As we got closer, I hoped that was what it was. By the time we passed the quince orchard, however, the hypothesis was no longer tenable.

We found Luitprand in the goose pond. Stupid fool, hefd jumped in the water to keep from getting burned up. Of course, the mudfs three feet deep on the bottom. I could have told him that.

Luitprand reminded me a lot of myself. For a start, he was half-smart stupid, just like me. Hurling myself in the pond to avoid the flames was just the sort of thing I might have done at his age; and, goes without saying, he wasnft there when we dug the bloody pond, twenty-one years ago, so how could he have known wefd chosen the soft spot, no use for anything else?

No other casualties, thank God, but the hay barn, the straw rick, the woodpile, all gone. The thatch, miraculously, burnt itself out without taking the rafters with it. But losing that much hay meant wefd be killing a lot of perfectly good stock come winter, since I canft afford to buy in. One darn thing after another.

Opito, Larcanfs wife, was hysterical, even though her home hadnft gone in up flames after all. Larcan said it was a great big lizard, about twenty feet long. He got one very brief glimpse of it out of the corner of his eye, just before he dragged his wife and son under the cart. He looked at me like it was all my fault. Just what I needed after a long day crouched in a briar patch.

Luitprand played the flute; not very well. I gave him the one I brought back from Outremer. I never did find it among his stuff, so I can only assume he sold it at some point.



ANYWAY, THAT WAS that, as far as I was concerned. Whatever it was, wherever it had come from, it would have to be dealt with, as soon as possible. On the ride back from the farm, Marhouse had been banging on about flightlines again, where we were going to move the bait to; two days here, while the windfs in the south, then if thatfs no good, then another two days over there, and if that still doesnft work, wefll know for sure it must be following the line of the river, so either here, there, or just possibly everywhere, would be bound to do the trick, logically speaking. I smiled and nodded. Ifm sure he was perfectly correct. Hefs a good huntsman, Marhouse. Come the end of the season, he always knows exactly where all the game wefve failed to find must be holed up. Next year, he then says\

Trouble was, there wasnft time for a next year.



BY MIDNIGHT (COULDNfT sleep, oddly enough) I was fairly sure how it had to be done.

Before you start grinning to yourself at my presumption, I had no logical explanation for my conclusions. Flightlines, patterns of behaviour, life cycles, cover crops, mating seasons, wind directions; put them together and youfll inevitably flush out the truth, which will then elude you, zig-zag running through the roots of the long variables. I knew.

I knew, because I used to hunt with my father. He was, of course, always in charge of everything, knew everything, excelled at everything. We never caught much. And I knew, when hefd drawn up the lines of beaters, given them their timings (say three Glorious Sun Ascendants and two Minor Catechisms, then come out making as much noise as you can), positioned the stillhunters and the hounds and the horsemen, finally blown the horn; I knew exactly where the wretched animal would come bursting out, so as to elude us all with the maximum of safety and the minimum of effort. Pure intuition, never failed. Naturally, I never said anything. Not my place to.

So: I knew what was going to happen, and that there was nothing much I could do about it, and my chances of success and survival were\well, not to worry about that. When I was in Outremer, I got shot in the face with an arrow. Shouldfve killed me instantly; but by some miracle it hung up in my cheekbone, and an enemy doctor wefd captured the day before yanked it out with a pair of tongs. You should be dead, they said to me, like Ifd deliberately cheated. No moral fibre. Ever since then\true, I shuddered to think how the estate would get on with my brother in charge, but it survived my father and grandfather, so it was clearly indestructible. Besides, everyone dies sooner or later. Itfs not like Ifm important.



MARHOUSE INSISTED ON coming with us. I told him, you stay here, wefll need a wise, experienced hand to take charge if it decides to burn out the castle. For a moment I thought hefd fallen for it, but no such luck.

So there were three of us: me, Ebba, Marhouse. The idea was, wefd follow the Ridgeway on horseback, looking down on either side. As soon as we saw smoke, Ebba would ride back to the castle and get the gear, meet us at the next likely attack scene. I know; bloody stupid idea. But I knew it wouldnft happen like that, because I knew how itfd happen.

Marhouse had on his black-and-white\thatfs breastplate, pauldrons, rerebraces and tassets. I told him, youfll boil to death in that lot. He scowled at me. Hefd also fetched along a full-weight lance, issue. You wonft need that, I told him. Ifd got a boar-spear, and Ebba was carrying the steel crossbow my father spent a whole yearfs apple money on, the year before he died. gBut theyfre just to make us feel better,h I said. That got me another scowl. The wrong attitude.

Noon; nothing to be seen anywhere. I was just daring to think, perhaps the bloody thingfs moved on, or maybe itfd caught some disease or got itself hung up in a tree. Then I saw a crow.

I think Ebba saw it first, but he didnft point and say, gLook, therefs a crowh. Marhouse was explaining some fine point of decoying, how you go about establishing which tree is the principal turning point on an elliptical recursive flight pattern. I thought: thatfs not a crow, itfs just hanging there. Must be a hawk.

Ebba was looking over his shoulder. No, not a hawk, the profilefs wrong. Marhouse stopped talking, looked at me, said, gWhat are you two staring at?h I was thinking, Oh.

Ifm right about things so rarely that I usually relish the experience. Not this time.

Oh, you may be thinking, is a funny way of putting it. But that was the full extent of it: no elation, no regret, not even resignation; to my great surprise, no real fear. Just: oh, as in, well, here we are, then. Call it a total inability to feel anything. Twice in Outremer, once when my father died, and now. Ifd far rather have wet myself, but you canft decide these things for yourself. Oh, I thought, and that was all.

Marhouse was swearing, which isnft like him. He only swears when hefs terrified, or when somethingfs got stuck or broken. Bad language, he reckons, lubricates the brain, stops it seizing up with fear or anger. Ebba had gone white as milk. His horse was playing up, and he was having to work hard to keep it from bolting. Amazing how they know.

On top of the Ridgeway, of course, therefs no cover. We could gallop forward, or turn around and gallop back; either case, at the rate the bloody thing was moving, itfd be on us long before we could get our heads down. I heard someone give the order to dismount. Wasnft Marhouse, because he stayed mounted. Wouldnft have been Ebba, so I guess it mustfve been me.

First time, it swooped down low over our heads\about as high up as the spire of Blue Temple\and just kept on going. We were frozen solid. We watched. It was on the glide, like a pigeon approaching a laid patch in a barley field, deciding whether to pitch or go on. Very slight tailwind, so if it wanted to come in on us, itfd have to bank, turn up into the wind a little bit to start to stall, then wheel and come in with its wings back. I honestly thought: itfs gone too far, itfs not going to come in. Then it lifted, and I knew.

Sounds odd, but I hadnft really been looking at it the first time, when it buzzed us. I saw a black bird shape, long neck like a heron, long tail like a pheasant, but no sense of scale. As it came in the second time, I couldnft help but stare; a real dragon, for crying out loud, something to tell your grandchildren about. Well, maybe.

Ifd say the body was about horse-sized, head not in proportion; smaller, like a red deer stag. Wings absurdly large\featherless, like a bat, skin stretched on disturbingly extended fingers. Tail, maybe half as long again as the body; neck like a swan, if that makes any sense. Sort of a grey colour, but it looked green at a distance. Big hind legs, small front legs looking vaguely ridiculous, as if it had stolen them off a squirrel. A much rounder snout than Ifd expected, almost chubby. It didnft look all that dangerous, to be honest.

Marhouse is one of those people who translate fear into action; the scareder he is, the braver. Works against people. No warning\itfd have been nice if hefd said something first; he kicked his horse hard enough to stove in a rib, lance in rest, seat and posture straight out of the coaching manual. Rode straight at it.

What happened then\

Marhouse was five yards away from it, going full tilt. The dragon probably couldnft have slowed down if it had wanted to. Instead\it actually made this sort of epopf noise as it opened its mouth and burped up a fat round ball of fire, then lifted just a little, to sail about five feet over Marhousefs head. He, meanwhile, rode straight into the fireball, and through it.

And stopped, and fell all to pieces; the reason being, there was nothing left. Horse, man, all gone, not even ash, and the dozen or so pieces of armour dropping glowing to the ground, cherry-red, like theyfd just come off the forge. Ifve seen worse things, in Outremer, but nothing stranger.

I was gawping, forgetting all about the dragon. It was Ebba who shoved me down as it came back. I have no idea why it didnft just melt us both as it passed, unless maybe it was all out of puff and needed to recharge. Anyway, it soared away, repeated the little lift. I had a feeling it was enjoying itself. Well, indeed. It must be wonderful to be able to fly.

Ebba was shouting at me, waving something, the crossbow, he wanted me to take it from him. gShoot it,h he was yelling. Made no sense to me; but then again, why not? I took the bow, planted my feet a shouldersf width apart, left elbow tucked in tight to the chest to brace the bow, just the fingers on the trigger. A good archery stance didnft seem to have anything to do with the matter in hand\like playing bowls in the middle of an earthquake\but Ifm a good archer, so I couldnft help doing it properly. I found the dragon in the middle of the peep-sight, drew the tip of the arrow up to find it, and pressed the trigger.

For the record, I hit the darn thing. The bolt went in four inches, just above the heart. Good shot. With a bow five times as strong, quite possibly a clean kill.

I think it mustfve hurt, though, because instead of flaming and lifting, it squirmed\hunched its back then stretched out full-length like a dog waking up\and kept coming, straight at me. I think I actually did try and jump out of the way; just rather too late. I think what hit me mustfve been the side of its head.

I had three ribs stoved in once in Outremer, so I knew what was going on. I recognised the sound, and the particular sort of pain, and the not quite being able to breathe. Mostly I remember thinking: it wonft hurt, because any moment now Ifll be dead. Bizarrely reassuring, as if I was cheating, getting away with it. Cheating twice; once by staying alive, once by dying. This man is morally bankrupt.

I was on my back, not able or minded to move. I couldnft see the dragon. I could hear Ebba shouting; shut up, you old fool, I thought, Ifm really not interested. But he was shouting, gHold on, mate, hold on, Ifm coming,h which made absolutely no sense at all\

Then he shut up, and I lay there waiting. I waited, and waited. Ifm not a patient man. I waited so long, those crunched ribs started to hurt, or at least I became aware of the pain. For crying out loud, I thought. And waited.

And thought: now just a minute.

It hurt so much, hauling myself onto my side so I could see. I was in tears.

Later, I figured out what had happened. When Ebba saw me go down, he grabbed the boar-spear and ran towards me. I donft imagine he considered the dragon, except as an inconvenience. Hold on, Ifm coming; all his thoughts in his words. He got about half way when the dragon pitched\it mustfve swooped off and come in again. As it put its feet down to land, he mustfve stuck the butt of the spear in the ground and presented the point, like you do with a boar, to let it stick itself, its momentum being far more effective than your own puny strength. As it pitched, it lashed with its tail, sent Ebba flying. Whether or not it realised it was dead, the spear a foot deep in its windpipe before the shaft gave way under the pressure and snapped, I neither know nor care. By the marks on the ground, it rolled three or four times before the lights went out. My best estimate is, it weighed just short of a ton. Ebba\under it as it rolled\was crushed like a grape, so that his guts burst and his eyes popped, and nearly all his bones were broken.



HE WOULDNfT HAVE thought: Ifll kill the dragon. Hefd have thought, ground the spear, like boar-hunting, and then the tail hit him, and then the weight squashed him. So it wouldnft have been much; not a heroic thought, not the stuff of song and story. Just: this is a bit like boar-hunting, so ground the spear. And then, perhaps: oh.

I think thatfs all there is; anywhere, anytime, in the whole world.



I TRIED PRESERVING the head in honey. We got an old pottery bath and filled it and put the head in; but eight weeks later it had turned green and it stank like heck, and she said, for pityfs sake get rid of it. So we boiled it out and scraped it, and mounted the skull on the wall. Not much bigger than a big deer; in a hundred yearsf time, they wonft believe the old story about it being a dragon. No such thing as dragons, theyfll say.

Meanwhile, for now, Ifm the Dragonslayer; which is a joke. The duke himself threatened to ride over and take a look at the remains, but affairs of state supervened, thank God. Entertaining the duke and his court wouldfve ruined us, and wefd lost so much already.

Twice Ifve cheated. Marhouse was straight as a die, and his end, Ifm sorry, was just ludicrous. I keep telling myself, Ebba made a choice, you must respect that. I canft. Instead of a friend, I have a horrible memory, and yet another debt I canft pay. People assume you want to be saved, no matter what the cost; sometimes, though, itfs just too expensive to stay alive. Not sure Ifll ever forgive him for that.

And thatfs that. I really donft want to talk about it anymore.
* Love is a Fallacy
Max Shulman



Cool was I, and logical. My brain was as powerful as a dynamo, as precise as a chemist's scales, as penetrating as a scalpel. And - think of it! - I was only eighteen.

It is not often that one so young has such a giant intellect. Take, for example, Petey Burch, my roommate at the University of Minnesota. Same age, same background, but dump as an ox. A nice enough fellow, you understand, but nothing upstairs.

One afternoon I found Petey lying on his bed with an expression of such distress on his face that I immediately diagnosed appendicitis.

"Don't move," I said, "don't take a laxative. I'll get a doctor."

"Raccoon," he mumbled thickly.

"Raccoon?" I said, pausing in my flight.

"I want a raccoon coat," he wailed.

I perceived that his trouble was not physical, but mental.

"Why do you want a raccoon coat?"

"All the Big Men on Campus are wearing them. Where've you been?"

"In the library," I said, naming a place not frequented by Big Men on Campus.

He leaped from the bed and paced the room,

"I've got to have a raccoon coat," he said passionately. "I've got to!"

"Petey, why? Look at it rationally. Raccoon coats are unsanitary. They shed. They smell bad. They weigh too much. They're unsightly. They -"

"You don't understand," he interrupted impatiently. "It's the thing to do... I'd give anything for a raccoon coat. Anything!"

My brain, that precision instrument, slipped into high gear.

"Anything?" I asked, looking at him narrowly.

"Anything," he affirmed in ringing tones.

I stroked my chin thoughtfully. It so happened that I knew where to get my hands on a coat. My father had had on one in his undergraduate days; it lay now in a trunk in the attic back home. It also happened that Petey had something I wanted. Well, he didn't HAVE it exactly, but at least he had first rights on it. I refer to his girl, Polly Espy.

I was a freshman in law school. In a few years I would be out in practice. I was well aware of the importance of the right kind of wife in furthering a lawyer's career. The successful lawyers I had observed were, almost without exception, married to beautiful, gracious, intelligent women. With one omission, Polly fitted these specifications perfectly. Beautiful she was. Gracious she was. Intelligent she was not. In fact, she veered in the opposite direction. But I believed that under my guidance she would smarten up. At any rate, it was worth a try. It is, after all, easier to make a beautiful dumb girl smart than to make an ugly girl beautiful.

"Petey," I said, "are you in love with Polly Espy?"

"I think she's a keen kid," he replied, "but I don't know if you'd call it love. Why?"

"Do you," I asked, "have any kind of formal arrangement with her? I mean, are you going steady, or anything like that?"

"No. We see each other quite a bit, but we both have other dates. Why?"

"Is there," I asked, "any other man for whom she has a particular fondness?"

"Not that I know of. Why?"

I nodded with satisfaction. "In other words, if you were out of the picture, the field would be open. Is that right?"

"I guess so. What are you getting at?"

"Nothing, nothing," I said innocently, and took my suitcase out of the closet.

"Where are you going?" asked Petey.

"Home for the weekend." I threw a few things into the bag.



"Look," I said to Petey when I got back Monday morning. I threw open the suitcase and revealed the huge, hairy, gamy object that my father had worn in his Stutz Bearcat in 1925.

"Holy Toledo!" said Petey reverently. He plunged his hands into the raccoon coat, and then his face.

"Holy Toledo!" he repeated fifteen or twenty times.

"Would you like it?" I asked.

"Oh, yes!" he cried, clutching the greasy pelt to him. Then a canny look came into his eyes. "What so you want for it?"

"Your girl," I said, mincing no words.

He flung the coat from him. "Never," he said stoutly.

I sat down in a chair and pretended to read a book, but out of the corner of my eye I kept watching Petey. He was a torn man. First he looked at the coat with the expression of a waif at a bakery window. Then he turned away and set his jaw resolutely. Then he looked back at the coat, with even more longing in his face. Then he turned away, but with so much resolution this time. Back and forth his head swiveled, desire waxing, resolution waning. Finally he didn't turn away at all; he just stood and stared with mad lust at the coat.

"It isn't as though I was in love with Polly," he said thickly, "Or going steady or anything like that..."

"Try on the coat," said I.

He complied. The coat bunched high over his ears and dropped all the way down to his shoe tops. He looked like a mound of dead raccoons.

"Fits fine," he said happily. I rose from my chair.

"It is a deal?" I asked, extending my hand.

He swallowed.

"It's a deal," he said and shook my hand.

I had my first date with Polly the following evening. This was in the nature of a survey. I wanted to find out just how much work I had to do to get her mind up to the standard I required.

I went back to my room with a heavy heart. I had gravely underestimated the size of my task. This girl's lack of information was terrifying. Nor would it be enough merely to supply her with information. First she had to be taught to think. This loomed as a project of no small dimensions, and at first I was tempted to give her back to Petey. But then I got to thinking about her abundant physical charms and about the way she entered a room and the way she handled a knife and fork, and I decided to make an effort.

I went about it, as in all things, systematically. I gave her a course in logic.

"Polly," I said to her when I picked her up on our next date, "tonight we are going to go over to the Knoll and talk."

We went to the Knoll, the campus trysting place, and we sat down under on old oak, and she looked at me expectantly.

"What are we going to talk about?" she asked.

"Logic."

She thought this over for a minute and decided she liked it.

"Magnif." she said.

"Logic," I said, clearing my throat, "is the science of thinking. Before we can think correctly, we must first learn to recognize the common fallacies of logic. These we take up tonight."

"Wow-dow!" she cried, clapping her hands delightedly.

I winced, but went bravely on.

"First let us examine the fallacy called Dicto Simpliciter."

"By all means," she urged, batting her lashes eagerly.

"Dicto Simpliciter means an argument based on as unqualified generalization. For example: Exercise is good. Therefore everybody should exercise."

"I agree," Polly said earnestly, "I mean exercise is wonderful. I mean it builds the body and everything."

"Polly," I said gently, "the argument is a fallacy. EXERCISE IS GOOD is an unqualified generalization. For instance, if you have heart disease, exercise is bad, not good. Many people are ordered by their doctors NOT to exercise. You must QUALIFY the generalization. You must say exercise is USUALLY good FOR MOST PEOPLE. Otherwise you have committed a Dicto Simpliciter. Do you see?"

"No," she confessed. "But this is marvy. Do more! Do more!"

"...Next we take up a fallacy called Hasty Generalization. Listen carefully: You can't speak French, I can't speak French, Petey Burch can't speak French. I must therefore conclude that nobody at the University of Minnesota can speak French."

"Really?" said Polly, amazed. "NOBODY?"

I hid my exasperation.

"Polly, it's a fallacy. The generalization is reached too hastily. There are too few instances to support such a conclusion."

"Know any more fallacies?" she asked breathlessly. "This is more fun than dancing even."

I fought off a ware of despair. I was getting nowhere with this girl, absolutely nowhere.

"Next comes Post Hoc. Listen to this: 'Let's not take Bill on our picnic. Every time we take him out with us, it rains.'"

"I know somebody like that," she exclaimed. "A girl back home - Eula Becker, her name is. It never fails. Every single time we take her on a picnic -"

"Polly." I said sharply, "it's a fallacy. Eula Becker doesn't CAUSE the rain. She has no connection with the rain. You are guilty of Post Hoc if you blame Eula Becker."

"I'll never do that again." she promised contritely. "Are you mad at me?"

I sighed deeply.

"No. Polly. I'm not mad."

"Then tell me some more fallacies."

I consulted my watch.

"I think we'd better call it a night. I'll take you home now and you go over all the things you've learned. We'll have another session tomorrow night."

I deposited her at the girl's dormitory, where she assured me that she had had a perfectly 'terif' evening, and I went glumly to my room. Petey lay snoring in his bed, the raccoon coat huddled like a great hair beast at his feet. For a moment I considered waking him and telling him that he could have his girl back. It seemed clear that my project was doomed to failure. The girl simply had a logicproof head. But then I reconsidered. I had wasted one evening: I might as well waste another. Who knew? Maybe somewhere in the extinct crater of her mind, a few embers still smoldered. I decided to give it one more try.

Seated under the oak the next evening I said, "Our first fallacy tonight is called Ad Misericordiam."

She quivered with delight.

"Listen closely," I said. "A man applies for a job. When the boss asks him what his qualifications are, he replies the he has a wife and six children at home, the wife is a helpless cripple, the children have nothing to eat, no clothes to wear, no shoes on their feet, there are no beds in the house, no coal in the cellar, and winter is coming." 

A tear rolled down each of Polly's pink cheeks. 

"Oh, this is awful, awful," she sobbed. 

"Yes, awful," I agreed, "but it's no argument. The man never answered the boss's questions about his qualifications.  Instead of he appealed to the boss's  sympathy. He committed the fallacy of Ad Misericordiam. Do you understand?"

I handed her a handkerchief and tried to keep from screaming while she wiped her eyes. 

 "Next," I said in a carefully controlled tone, "we will discuss False Analogy. Here is an example: students should be allowed to look at their textbooks during examinations. After all, surgeons have X-rays to guide them during an operation, lawyers have briefs to guide them during a trial, carpenters have blueprints to guide them when they are building a house. Why then, shouldn't students be allowed to look at their textbooks during an examination?" 

 "There now," she said enthusiastically, "is the most marvy idea I've heard in years." 

 "Polly," I said testily, "the argument is all wrong. Doctors, lawyers, and carpenters aren't taking a test to see how much they have learned, but students are. The  situations are entirely different, and you can't make an analogy between them." 

 "I still think it's a good idea," said Polly. 

 "Nuts." I muttered. Doggedly I pressed on. "Next we'll try Hypothesis Contrary to Fact." 

 "Sounds yummy," was Polly's reaction. 

"Listen: 'If Madame Curie had not happened to leave a photographic plate in a drawer with a chunk of pitchblende, the world today would not know about radium.'" 

"True, true," said Polly, nodding her head, "Did you see the movie? Oh, it just knocked me out..." 

 "...I would like to point out that the statement is a fallacy. Maybe Madame Curie would have discovered radium at some later dates. Maybe somebody else would have discovered it. Maybe any number of things would have happened. You can't start with a hypothesis that is not true and then draw any supportable conclusions from it."

 One more chance, I decided. But just one more. There is a limit to what flesh and blood can bear. 

 "The next fallacy is called Poisoning the Well." 

 "How cute!" she gurgled. 

 "Two men are having a debate. The first one gets up and says, 'My opponent is a notorious liar. You can't believe a word that he is going to say.' ...Now, Polly, think. Think hard. What's wrong?" 

 I watched her closely as she knit her creamy brow in concentration. Suddenly, a glimmer of intelligence - the first I had seen - came into her eyes. 

 "It's not fair," she said with indignant. "It's not a bit fair. What chance has the second man got if the first man calls him a liar before he even begins talking?" 

 "Right!" I cried exultantly. "One hundred percent right. It's not fair. The first man has POISONED THE WELL before anybody could drink from it. Polly, I'm proud of you."

"Pshaw," she murmured, blushing with pleasure. 

 "You see, my dear, these things aren't so hard. All you have to do is concentrate. Think - examine - evaluate. Come now, let's review everything we have learned." 

 "Fire away," she said with an airy wave of her hand. 

 Heartened by the knowledge that Polly was not altogether a cretin, I began a long, patient review of all I had told her. Over and over and over again I cited instances, pointed out flaws, kept hammering away without let-up. It was like digging a tunnel. At first everything was work, sweat, and darkness. I had no idea when I would reach the light, or even if I would. But I persisted. I pounded and clawed and scrapped, and finally I was rewarded. I saw a chink of light. And then the chink got bigger and the sun came pouring in and all was bright. Five grueling nights this took, but it was worth it. I had made a logician out of Polly; I had taught her to think.

My job was done. She was worthy of me at last. She was a fit wife for me, a proper hostess for my many mansions, a suitable mother for my well-heeled children. It must not be thought that I was without love for this girl. Quite the contrary. I determined to acquaint her with my feelings at our very next meeting. The time had come to change our relationship from academic to romantic. 

 "Polly," I said when next we sat beneath our oak, "tonight we will not discuss fallacies." 

 "Aw, gee," she said, disappointed. 

 "My dear," I said, favoring her with a smile, "we have now spent five evenings together. We have gotten along splendidly. It is clear that we are well-matched." 

 "Hasty Generalization," said Polly brightly. 

 "I beg your pardon?" said I. 

 "Hasty Generalization," she repeated. "How can you say that we are well-matched on the basis of only five dates?"

 I chuckled with amusement. The dear child had learned her lessons well. 

 "My dear," I said, patting her hand in a tolerant manner, "five dates is plenty. After all, you don't have to eat a whole cake to know it's good." 

 "False Analogy," said Polly promptly. "I'm not a cake. I'm a girl." 

 I chuckled with somewhat less amusement. The dear child had learned her lesson perhaps too well. I decided to change tactics. Obviously the best approach was a simple, strong, direct declaration of love. I paused for a moment while my massive brain chose the proper words. Then I began: 

 "Polly, I love you. You are the whole world to me, and the moon and the stars and the constellations of outer space. Please, my darling, say that you will go steady with me, for if you will not, life will be meaningless. I will languish. I will refuse my meals. I will wander the face of the earth, a shambling, hollow-eyed hulk." 

 There, I thought, folding my arms, that ought to do it. 

 "Ad Misericordiam," said Polly. 

 I ground my teeth. Frantically, I fought back the tide of panic surging through me. At all costs I had to keep cool. 

 "Well, Polly," I said, forcing a smile, "you certainly have learned your fallacies." 

 "You're darn right," she said with a vigorous nod. 

 "And who taught them to you, Polly?" 

 "You did." 

"That's right. So you do owe me something, don't you, my dear? If I hadn't come along you never would have learned about fallacies." 

 "Hypothesis Contrary to Fact," she said instantly. 

 I dashed perspiration from my brow. "Polly," I croaked, "you mustn't take all these things so literally. I mean, this is just classroom stuff. You know that the things you learn in school don't have anything to do with life." 

 "Dicto Simpliciter," she said, wagging her finger at me playfully. 

 That did it. I leaped to my feet, bellowing like a bull. 

 "Will you or will you not go steady with me?" 

 "I will not," she replied. 

 "Why not?" I demanded.

"Because this afternoon I promised Petey Burch that I would go steady with him.

I reeled back, overcome with the infamy of it. After he promised, after he made a deal, after he shook my hand!

 "The rat" I shrieked, kicking up great chunks of turf. "You can't go with him, Polly. He's a liar. He's a cheat. He's a rat."

"Poisoning the Well," she said, "and stop shouting. I think shouting must be a fallacy too." 

 With an immense effort of will, I modulated my voice. 

 "All right," I said. "You are a logician. Let's look at this thing logically. How could you choose Petey Burch over me? Look at me - a brilliant student, a tremendous 

intellectual, a man with an assured future. Look at Petey - a knothead, a jitterbug, a guy who'll never know where his next meal is coming from. Can you give me one logical reason why you should go steady with Petey Burch?" 

 "I certainly can," declared Polly. "He's got a raccoon coat." 
