* Caine
LHUN EFSEF LC H TCCU HSY IF AHUUE OCD TCCUKEI

ACDEFHIKLNSTUY



LHUN EFSEF LC H TCCU HSY IF AHUUE OCD TCCUKEI
ha         he a  ee  a   i   a     e   ee   i
CDFKLNSTUY

if in is it
he
an as at

* Garrison 1
.AG. = LAGS WAGS SAGA
.VA. = OVAL
AV.. = AVOW AVOS
GA.. = GALL GALS GADS

AAAOO DLLLSWY
YODA LOLA OSLA SOLA OLDS GALA

.GA. = AGAS
.AV. = LAVA LAVS
GA.. = GALL GALS GADS
AV.. = AVOW AVOS

.VA. = OVAL
.AG. = LAGS WAGS SAGA
VA.. = 
AG.. = 


.AV. = LAVA LAVS
.GA. = AGAS
AG.. = 
VA.. = 

* Imperial Tarot

Imperial Tarot
Goal: 666 points (or more?)

Player: 1, 2, 2, 1
Player with higher score gains score; if loser has Rupture, they lose 99.

Cards may belong to multiple classes.

Book of Thoth may complete a Triplet or cause a Rupture

14 classes of hands (cards?)
    ?
    Bewitched
    Celestial
    Duality
    Enchanted
    Feminine
    Gifted
    Imperial
    Insidious
    Masculine
    Perdition
    Rhadamanthine
    Treacherous
    Worldly
Hands
    Triplet
    Doublet
    Singlet
    Rupture

Thoth ruptures:
    Judgment + Lovers = Rhadamanthine
    Strength + High Priestess = Enchanted
    Temperance + Hanged Man = Enchanted
    Lovers + Hanged Man = Gifted
    Magician + Temperance = Enchanted
    Hermit + Judgment = Rhadamanthine
    Judgment + Magician = Rhadamanthine
    Justice + Fool = Perdition Triplet
    High Priestess + Hierophant = Insidious Triplet
    Magician + Prince = Imperial
    Magician + Death = Rhadamanthine
    Magician + High Priestess = Duality
    Sun God + Judgment = Rhadamanthine
    Sun God + The Star = Celestial

Emperor + Hanged Man + Lovers = Imperial Singlet. Does rank outweigh max?





Justice OR Prince = Insidious
Moon God OR Prince = Insidious
Fool OR Moon = Insidious
Devil OR Prince = Insidious
Moon + Prince + Temperance = 2/3 Insidious

Justice, Prince, Moon, Moon God, Fool, Devil, Temperance

Devil OR Star = Rhadamanthine

Justice OR Temperance = Enchanted
Strength + Devil + Moon God = 2/3 Enchanted
Devil OR Hierophant = Enchanted

High Priestess + Magician + Wheel = 2/3 Duality
Fool + Magician + High Priestess = 2/3 Duality



Main
    Wheel of Fortune + Sun God + Moon God = Duality Doublet
    Empress & Prince seem to be Imperials; tend to outweigh other stuff?
    World & Sun are Celestial, outweigh Imperial?
    "Rhadamanthine" = "Metaphysical"?

    Does lower Doublet outweigh higher Singlet?

Cards
    Book of Thoth       |
    Chariot             |
    Death               |
    Devil               |
    Emperor             |
    Empress             |
    Fool                |
    Hanged Man          |
    Hermit              |
    Hierophant          |
    High Priestess      |
    Judgment            |
    Justice             |
    Lovers              |
    Magician            |
    Moon                |
    Moon God            |
    Prince              |
    Star                |
    Strength            |
    Sun                 |
    Sun God             |
    Temperance          |
    Tower               |
    Wheel of Fortune    |
    World               |
* Jasper

DEEINTV
EEHIRSS

.E.....
AFFLRU

FE AFLRU
LE AFFRU
RE AFFLU
* Lawley 5
Abc Dehbilamenic opbcpn iae Stnw.

abcdehilmnopstw


Abc Dehbilamenic opbcpn iae Stnw.

abcdehilmnopstw


123456789012



123456789012
Tower
Magician
Star
Hermit
Strength
Devil
Hierophant
Empress
Chariot
Justice
Death
Lovers
123456789012
Payne
Ursula
Lawley
Wyck
Needham
Garrison
Quintin
Moxley
Sabina
Jasper
Agar
McGucken
Horton
Caine
Voorst
Massey
Wallop
123456789012
Pringle
Buckbee
Radcliff
Norfolk
Gliston
Yapp
Hayden
Roderick
Vibbard
Lommis
Cutting
Jost
Rymore
Argyle
Snodgrass
Ingram
Wentworth
Riason
Handel
123456789012
Percy
Telfair
Nairne
Harleigh
Girdwood
Soule
Thwaie
Augustine
Chrichton
Huddleston
Iacobbe
Tilton
Vranken
Jeckel
Lydia
Hyde
Tassel
Weir
123456789012
Playfair
Zachariah
Granville
Jurchik
Vanderveer
Ostheim
Iver
Conklin
Skidmore
Ockley
Laroche
Hernshaw
Nisbett
Olmstead
Aldridge
Wickliff
* Ursula
1   0|
2   0|
3   0|
4   0|
5   0|
6   0|
7   1|.

BBETTRRAYaaLLL
aRAAA

BBETTRRRYaaaLLL = 7+1

......7..11..15..19

T, L, TTTLL, TTLLL
TTLLYY = 1+2
BBTTLL = 4+2
LLRRAA = 7+2
AYaE = 2,3,5,6+2
B T Y RRR AA a EEE = 4+3, 7+1
R EE aa BB YYY T A = 1+3, 7+1

21,33,45,57  changes
 7,11,15,19  moves
 5  8 12 15  extra rollovers

B   135
E   246
T   357*
R   123
A   234
Y   345
a   456
L   147*

1   BRL   !
2   ERA   !
3   BTRAY !
4   EAYaL !
5   BTYa
6   Ea
7   TL
