* routines
** PPL
https://archive.fo/gMUfM
* posture mantras
mantra: shoulders down, shoulders back, chin level
mantra: butt down, hips forward (tuck your tail)
mantra: sit like you have a tail
trick: look all the way up, then move only your head back down
** response to "shoulders back"
Do not pull your shoulders back, that is doesn't address the actual issue. Instead you want your chest out, back of your neck back.
...
This. My mantra has always been "Shoulders back (meaning "up"), Chest out". It corrected the damage done by a number of years worth of bad posture.
** "extra tips that work for me"
Extra tips that work for me: + Keep your thumbs pointed forward when your hands are by your side (lets shoulders in-line with joints) +push off with toes when walking (allows your calves and hamstrings to take the force of your step keeping pelvis in line) +Keep your abdomen always engaged, as if you're preparing for someone to lightly slap you in the stomach (abs straighten the spine and keep pelvis in place) +tighten your butt when standing/walking (essentially, your ass is made to support your posture [pelvis, spine, lower back])
* 10,000 kettlebell swings

guide to the swing...
https://www.t-nation.com/training/master-the-kettlebell-swing

2 days on, 1 day off
500 swings per day = 10,000 swings in 30 days
males 35 lbs? or 53?
35/15 reps
35 - weight/mobility exercise - 15 - rest 30-60 sec ^^or 2 min^^ - repeat
* healthy amount of exercise
https://www.reddit.com/r/Fitness/comments/54s6hd/studies_indicate_that_endurance_training_seems_to/d84m5ci/
""
There's a big difference between endurance exercise and endurance training. Endurance exercise is good for you. Serious endurance training is actually not really. We know this from the inverted U-shaped association between the dose of strenuous exercise and longevity (e.g. the Copenhagen jogger study: casual jogging is best, serious jogging is no healthier than being sedentary).

I strongly suspect the same is true for resistance exercise (casual lifting is healthy, serious bodybuilding/powerlifting training is not).

Endurance exercise is not going to tank your testosterone without you noticing. You'll feel run down. If your priority is health rather than performance improvement, simply stick to the amount of exercise that makes you feel better rather than worse than usual. The typical recommended amount of endurance exercise (30-45 min, 2-3x/week) does not make most people feel run down. Most people feel better and more energetic.
* one arm pull up tutorial
https://www.reddit.com/r/bodyweightfitness/comments/39peun/one_arm_pull_up_tutorial/
* breakfast options

Kashi GoLean           180c 13p ?s 10f
Edge Protein           220c 11p 11s 7f
Special K Protein      120c 10p 7s 3f
Special K Protein Plus
Bran flakes
* cheap micro plates
http://www.mcmaster.com/#catalog/118/3217/=j1scp4

Part number 91081 A046
2.125" internal diameter plate that weighs 0.625lbs and costs $1.90
