* clean, short

Do you know the joke they only tell smart people?

What happens when you drink food coloring? You dye a little on the inside.

Why do ducks have flat feet? To stamp out forest fires. (pause...follow with:) Why do elephants have flat feet? To stamp out burning ducks.

Where do you find a dog with no legs? Where ever you left it.

Have you heard about that new movie Constipation? It hasn't come out yet.

Job interview: "What's your greatest weakness?" "Honesty." "I don't think honesty is a weakness." "I don't give a fuck what you think."

It's hard to explain puns to kleptomaniacs because they always take things literally.

What do you get when you cross a joke with a rhetorical question?

* clean, long

Switched the heads






An Englishman, a Frenchman, a ravishing blonde and a homely brunette...









An Englishman, a Frenchman, and an American get stranded on an island. They are taken captive by the natives there, bound, and dragged into a tent. After about an hour, the chief of the tribe comes in.

"I have good news, and I have bad news," he tells them. "The bad news is we are going to kill you, eat you, and make your skins into canoes. The good news is you get to choose how you die."

The Englishman asks for a gun. "Long live the Queen!" he says, and shoots himself in the head, and dies.

The Frenchman asks for poison. He lifts the glass, says "Viva la France!", drinks, and dies.

The American asks for a fork. The natives are confused, but they hand over a fork. He starts stabbing himself all over with said fork... his arms, legs, torso, everywhere.

"What are you doing?!" The chief asks finally, perplexed. The American grins at them.

"So much for your canoe, you assholes."








Paddy Englishman, paddy Scotsman and paddy Irishman were all deciding how much money they would donate to the church.

Paddy Englishman said "I draw a chalk circle on the ground and throw all my money up in the air ; everything that lands in the circle I give to the church and everything that lands outside the circle I keep to myself."

Paddy Scotsman said "I draw a chalk line on the ground and throw all my money up in the air and everything that lands to the west of the line I give to the church, and everything that lands to the east of the line; I keep to myself."

And then Paddy Irishman said; "I just throw all my money in the air. What god doesn't want; he throws back down."














There once was this guy who worked for the Railroad as a conductor. Let's say his name was Joe. Well, Joe was walking through the train, en route, collecting tickets from the passengers. He comes to car 12, booth 3. In it was a man.

So, he asked him for his ticket: "Excuse me sir, do have your ticket?"

"Oh, I am soooo sorry, I dropped it out the window by accident," he replied.

"Sorry sir, can't have any passengers without tickets." He grabbed him by the scruff of the neck and threw him out of the train. Well, he landed on the tracks and was run over by the train. Naturally, the conductor was arrested and thrown in jail. He was convicted of murder before a jury of his peers, and sentenced to death by electrocution.

The day of his execution came up, and he was asked what he would like for his last meal. He asks for a banana. They gave it to him, he ate it, received his last rites, and was escorted to the chair. The executioner strapped him in, hooked everything up. Last, he threw the big switch once, and nothing happened. So, he did it again, and nothing happened. Well, by law the guy was legally dead, so they had to release him.

Oddly enough, the guy got a job on another railroad, as a conductor! One day, he was gathering tickets, and came to a booth with a little boy.

"Young man, do you have your ticket?", asked the conductor.

"A-a-a, I'm sorry, I ate it by mistake..", said the little boy.

And.. the same thing happened -- the boy was thrown off the train and killed. The guy was arrested, sentenced to death by electrocution. It came to him last day. The death row guard asked him what he would like for his meal. He asked for banana again. He ate it, and a priest gave him last rites.

He was escorted to the death chamber. This time, though, they were smart.

They washed his hands to get rid of any banana slime, they washed up the chair. Next, they placed him the chair, and hooked him up. The switch-puller pulled the switch once, and nothing happened. The switch-puller pulled the switch twice, and nothing happened, not even a single hair raising on the guy's chest.

Well, as the law says, they had to let him go...

Even more amazingly, he got a job on yet another railroad.

This time it was a rabbi. Same old stuff. Rabbi had no ticket (he forgot to buy it). Guy threw him off the train, rabbi died. Guy was arrested, convicted, sentenced to death by electrocution.

When the guard asked him what he would like for a last meal, he asked for a banana. He ate it, received last rites, and was escorted to the chamber.

However, this time the officials where going to get it right! They scrubbed his body with a brillo pad. They scrubbed the chair with steel wool. They tried the chair on a few other prisoners...

Okay, they strapped him in, and threw the switch once, nothing happened. Threw the switch a second time, nothing happened. At this point the guy was legally dead, etc, etc.

But, before the guy could leave, the executioner, extremely frustrated (he'd seen this same guy three times already). asked, "What is it with the banana!"The guy replied, "I just like bananas."So, the executioner screamed, "THEN HOW COME YOU DON'T DIE!!!!!"

"I dunno," replied the guy, "I guess I'm just not a very good conductor."















Face rings a bell....




Dude drinks three shots, switches to two because he quit drinking...

* dirty, short

Why can't Helen Keller masturbate with two hands? She needs one to moan.

A pirate walks into a bar with a steering wheel in his pants. The bartender asks: Hey mate, What's with the steering wheel in your pants? The pirate replies: Yarrr, it be drivin' me nuts!

What's the difference between a chickpea and a garbonzo bean? I wouldn't pay $29 to have a garbonzo bean on my face.

A family walks into a hotel and the father goes to the front desk and says "I hope the porn is disabled." The guy at the desk says, "It's just regular porn, you sicko!"

A man goes to the doctor for his annual check-up, and the doctor tells him, "You need to stop masturbating." The man asks, "Why?" The doctor replies, "Because I'm trying to examine you."

What did the leper say to the prostitute? "Keep the tip."

* dirty, long

Woman in coma, oral sex, must've choked







them two assholes








It was the mailman's last day on the job after 35 years of carrying the mail through all kinds of weather to the same neighborhood. When he arrived at the first house on his route he was greeted by the whole family there, who congratulated him and sent him on his way with a big gift envelope. At the second house they presented him with a box of fine cigars. The folks at the third house handed him a selection of terrific fishing lures.

At the fourth house he was met at the door by a strikingly beautiful woman in a revealing negligee. She took him by the hand, gently led him through the door (which she closed behind him), and led him up the stairs to the bedroom where she blew his mind with the most passionate love he had ever experienced. When he had had enough they went downstairs, where she fixed him a giant breakfast: eggs, potatoes, ham, sausage, blueberry waffles, and fresh-squeezed orange juice. When he was truly satisfied she poured him a cup of steaming coffee. As she was pouring, he noticed a dollar bill sticking out from under the cup's bottom edge.

"All this was just too wonderful for words," he said, "but what's the dollar for?" "Well," she said, "last night, I told my husband that today would be your last day, and that we should do something special for you. I asked him what to give you." He said, "Fuck him, give him a dollar." The lady then said, "The breakfast was my idea."






Did you get twins every time? 
Nah, there's hundreds of times we didn't get anything at all! 





I read this one ages ago, can't remember where. Also, depends if they have the time to listen, it takes about 5 minutes to tell, but here:

(Helps if you act along with it too)

A man walks into a bar to meet some friends. He sees them and heads to the bar first to order a beer. While the bartender is getting it, he spies a sizeable jar stuffed full of 10 Euro(Or dollar, pounds, w'ev) notes. He asks the bartender "What's up with the jar?"

"It's simple, you pay a tenner, it goes in the jar, if you complete three tasks you get the contents of the jar and the keys to a new (fancy car, pander to your audience's tastes and car knowledge!)"

"Woah, what are the tasks??"

"Nope, tenner first, then I tell you"

The guy nearly tears the note in his haste, and the bartender stuffs it in the jar.

"Ok, task 1. You have to drink a litre bottle of Tequila in less than 60 seconds, without coughing, stopping or moaning."

"O..ok, the second task?"

"Second task. There's a large Rottweiler tied up in the back passage, he's got a bad tooth. You have to go extract it and bring it back inside."

"Fuck...what's the third task?"

"Task number three. There is a 90 year old woman in a bed upstairs, never had sex a day in her life. You need to go show her a good time.

"Fuck that, keep the ten!"

"Yeah, we get that a lot, offer stands until close anyway"

The guy takes his beer and joins his friends.

A few hours pass, and bolstered by liquid courage (and some peer pressure) the man walks back up to the bartender and says "Gimmie the tequila"

"Ok man, just so you know, you don't finish the three, you pay for the bottle"

"Gimmie"

So he does. The guy pulls the lid off, contemplates his decision and puts the bottle to his lips. Upends it and he's off. The burning liquid is filling his mouth and firing down his throat, but he's not complaining. His eyes begin to water as the crowd start counting down his last ten seconds. When they reach '2', he puts the now empty bottle back on the bar and opens his mouth to prove the foul liquid has gone down, for now at least. The bartender nods and points to the back door, which he stumbles towards in a zig zag path.

Everyone is watching him, but as he reaches the door and opens it, the crowd decides that following him to be trapped in the narrow passage with him and an angry dog would not be ideal, and they settle in to await his return.

The dog is angry. The guy shuts the door behind him and the noise grows. The crowd hear him shout, the dog barking, a scream from the guy, more barking, growling, thumping, more shouting and screaming and finally a whimper from the dog followed by a triumphant grunt from the man.

Everyone is silent. The man opens the door and stumbles back in. He's in a bad state, his shirt is ripped open in places and he's bleeding from multiple bites and scratches all over his torso, arms and even face.

He stops, and looks up at the bartender

"Righ'.. where's that aul woman with the bad tooth?"











Stanley died in a fire and his body was burned badly. The morgue needed someone to identify the body, so they sent for his two best deer hunting friends, Cooter and Gomer. The three men had always hunted and fished together and were long time members of a hunting camp.

Cooter arrived first, and when the mortician pulled back the sheet, Cooter said, "Yup, his face is burned up pretty bad. You better roll him over." The mortician rolled him over and Cooter said, "Nope, ain't Stanley ."

The mortician thought this was rather strange, So he brought Gomer in to confirm the identity of the body. Gomer looked at the body and said, "Yup, he's pretty well burnt up. Roll him over." The mortician rolled him over and Gomer said, "No, it ain't Stanley."

The mortician asked, "How can you tell?"

Gomer said, "Well, Stanley had two ass-holes."

"What! He had two ass-holes?" asked the mortician.

"Yup, we never seen 'em, but everybody used to say, there's Stanley with them two ass-holes."









Jane and Arlene were outside their nursing home, having a drink and a smoke, when it starts to rain. Jane pulls out a condom, cuts off the end, puts it over her cigarette, and continues smoking.

Arlene: What in the hell is that?

Jane: A condom. This way my cigarette doesn't get wet.

Arlene: Where did you get it?

Jane: You can get them at any pharmacy.

The next day, Arlene hobbles herself into the local pharmacy and announces to the pharmacist that she wants a box of condoms. The pharmacist, obviously embarrassed, looks at her kind of strangely (she is, after all, over 80 years of age), but very delicately asks what size, texture, brand of condom she prefers.

'Doesn't matter Sonny, as long as it fits on a Camel.'

* offensive

Take it easy on pedophiles. They find it hard to fit in.

Pedophiles are born losers, what with always coming in a little behind.

What's the difference between Michael Phelps and Adolf Hitler? Michael Phelps can finish a race.

One time I saw a black dude walking out of my building carrying a tv. Normally, I wouldn't have paid attention, but I noticed it looked a lot like mine. So I jogged upstairs and burst into my apartment to see if it was still there. It was; shining my shoes.

What do bikes and black people have in common? They both stop working when you take their chains off.

Statistically, 9 out of 10 people enjoy gang rape.

How do you turn a fruit into a vegetable? AIDs.

Why can't you fool an aborted baby? It wasn't born yesterday.

What kind of file do you need to turn a 15mm hole into a 40mm hole? A pedophile.

What do you get when you cross a black person with an octopus? I don't know either but it sure as hell would be great at picking cotton.

What's better than winning a gold medal in the Special Olympics? Not being retarded.

What's ten inches long, stiff, and makes women scream at night? Crib death.

What's the best part of doing a nine year old boy? Watching him break down on the witness stand.

How many feminists does it take to change a lightbulb? It doesn't matter, feminists can't change anything.

Here's my favorite joke of all time: What did the blind and deaf kid get for Christmas? Cancer.

How do you impregnate a 9 year old Ethiopian girl? You cum on her foot and let the flies do the rest.

So I was going down on this chick the other day, and I tasted horse cum. I looked at her and said, "So THAT'S how you died, Granny!"

Why can't Helen Keller masturbate with two hands? She has to use one hand to moan.

What do you call four lepers in a hot tub? Soup.

* unsorted

A family walks into a hotel and the father goes to the front desk and says "I hope the porn is disabled." The guy at the desk replies. "It's just regular porn you sick fuck."

I still remember the last thing my grandfather said before kicking the bucket. "Hey wanna see how far I can kick this bucket?"

I recently bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.

Good jokes are like children with cancer. They never get old.

Whats the difference between a terrorist training camp and an orphanage?
I don't know I just fly the drone.



Why did the old man fall in the well?
He couldn't see that well.





Friend: 'How did your date go?'
Man: 'I talked too much about my obsession with simplifying fractions'
Friend: 'That wasn't a very good idea'
Man: 'Yeah, well hindsight is 1'






A Soldier, a Marine, and an Airman were each asked what they would do if a scorpion crawled into their tent during a field exercise.
Soldier: crush it with my boots and Charlie Mike. Marine: catch it and fry it up with some Tobasco, anything is better than field chow. The Airman stood confused for a minute, and finally: why would there be a tent in my hotel room?



A boy asks his mom, "Why am I black and you're white?" She says, "Don't even go there. The way that party went, you're lucky you don't bark."




Why couldn't the lifeguard save the drowning hippie?
He was too far out, man.





3 guys are hiking through the woods when they find a lamp
One of them picks it up, rubs it, and out pops a Genie.
It booms "You have finally freed me after all these years, so I'll grant each one of you 3 wishes." The first guy immediately blurts out "I want a billion dollars." POOF, he's holding a printout that shows his account balance is now in fact 1,000,000,003.50
The second man thinks for a bit, then says "I want to be the richest man alive." POOF, he's holding papers showing his net worth is now well over 100 billion.
The third guy thinks even longer about his wish, then says "I want my left arm to rotate clockwise for the rest of my life." POOF, his arm starts rotating.
The Genie tells them it's time for their second wish.
First guy says: "I want to be married to the most beautiful woman on earth." POOF, a stunning beauty wraps herself around his arm.
Second guy says "I want to be good-looking and charismatic, so I can have every girl I want." POOF, his looks change and the first guy's wife immediately starts flirting with him.
Third guy says "I want my right arm to rotate counter-clockwise until I die." POOF, now both his arms are rotating, in opposite directions.
The genie tells them to think very carefully about their third wish.
First guy does, and after a while says "I never want to become sick or injured, I want to stay healthy until I die." POOF, his complexion improves, his acne is gone and his knees don't bother him any more.
Second guy says "I never want to grow old. I want to stay 29 forever." POOF, he looks younger already.
Third guy smiles triumphantly and says "My last wish is for my head to nod back and forth." POOF, he's now nodding his head and still flailing his arms around.
The genie wishes them good luck, disappears, and the men soon go their separate ways.
Many years later they meet again and chat about how things have been going. First guy is ecstatic: "I've invested the money and multiplied it many times over, so me and my family will be among the richest of the rich pretty much forever. My wife is a freak in the sheets, and I've never gotten so much as a cold in all these years." Second guy smiles and says "Well, I built charities worldwide with a fraction of my wealth, I'm still the richest guy alive and also revered for my good deeds. I haven't aged a day since we last met, and yes, your wife is pretty wild in bed."
Third guy walks in, flailing his arms around and nodding his head, and says:
"Guys, I think I fucked up."





Why did the old lady fall in the well.
Because she didn't see that well.




The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.






What happened to the man running in front of the car?
--He was tired
What happened to the man running behind the car?
--He was exhausted





Why do blind people hate skydiving?
It scares the hell out of their dogs.





I finally bought the limited edition Thesaurus from Amazon that I've always wanted. When I opened it, all the pages were blank.
I have no words to describe how angry I am.




What do you call a deer with no eye?
I have no ideer



What do you call a fish with no eyes?
"Fsh"



What did the buffalo say when his son went to college?
Bison









A bird was sleeping very cozy in his nest at the top of a pine tree Suddenly, he heard a lot of noise and the whole tree started to shake. He looked down and saw there was a very fat and clumsy elephant climbing the tree. The bird said: "Hey! What are doing?!!? Why are you making so much racket???" The elephant said: " I just want to climb up there and eat some pears!" The bird said: "there are no pears here, you stupid elephant! this is a pine tree!!" The elephant said: "I know! I brought my own pears!"




What goes down but doesn't come up?
A yo




Thats nothing. I bought a dictionary from a second hand shop the other day.
I flipped the front cover to find that some douche bag had ripped out the first hundred pages.
No 'Aardvark'. No 'Axe'. No 'Backgammon'...
So I flipped to the end and discovered that they'd also ripped out the last hundred odd pages.
No 'Wretched'. No 'Xylophone'. No 'Zebra'...
It just went from 'Bad' to 'Worse'...











He tells the attendant that he is chasing something a little different, ¡°everyone has dogs and cats and birds and fish, I want something different¡±

The attendant says ¡°I¡¯ve got just the thing, here, we have a talking centipede¡±

¡°Perfect says the man, that sounds great ill take one of those¡±

He gets the centipede home and says ¡°Mr. Centipede, would you like to go down the pub and have a couple of beers?¡±

The man gets no response. Maybe he is a little shaken up from the ride home he thinks. I¡¯ll give him 10 mins and ask again.

10 mins later the man says ¡°Would you like head down the pub for a beer?

Again no response. The man thinks to himself. I¡¯ll give him another 15mins and if he doesn¡¯t reply I¡¯m taking him back.

15 mins later the man says to the centipede ¡°mate, do you want to go down the pub for a beer or not?!¡±

The centipede replies ¡°I¡¯m putting my shoes on, you impatient bastard!¡±

Edit! I¡¯m an Aussie hence the use of both ¡°Pub and Bastard¡±

Edit edit - I thought i would keep it a bit cleaner instead of writing what my natural Australian dialect would generally of placed in the position of ¡°Bastard¡±


















"Mind if I say a word?"

She says: "Please do."

The man clears his throat and says: "Plethora."

The widow replies: "Thanks, that means a lot."
















He sits down at the the bar and start drinking a beer. The guy next to him ask: you know kung fu or karate or any or this shit? The asian guy replies: why you ask this, is because I chinese? The other guy replies no it¡¯s because you¡¯re drinking my fucking beer.















What's the fastest liquid on earth?
Milk. It's pasteurized before you see it.

