* emails (active)
** Important if True re: burping

S: I have forgotten how to burp.
When I was a child I had, as many (?) children do, a mortal fear of throwing up. I considered it to be the most undesirable outcome possible, short of major injury. One time I burped and then immediately threw up, and after that I concluded that burping had the potential to cause throwing up, so I resolved to not burp if I could help it. Whenever I felt the urge to burp, I would simply swallow. I did this for years. Now I'm an adult, and I've found that I've completely forgotten how to burp. When the urge arrises, I try contracting and relaxing the muscles around my throat, but I just can't figure out how to make a burp happen. This can be very annoying, especially if I'm doing something like running, which tends to cause the urge to burp

** Nick re: LoL progress, CS drills

Nick re: LoL

So this is probably my last update in the context of you introducing me to LoL, as I transition fully into your friend who's simply not quite as good at LoL.

Role selection: I've more or less decided to go Support main and ADC secondary, and Top last. Support because I already like it and its champions, and it's a fairly unpopular role (including among the friends I play with), meaning that I can pretty much always get it when I want it, and it will reduce the chance of my team containing an autofill. ADC for similar reasons, except that it tends to have a narrower pool of less interesting champions. I feel like ADC is the role most dependant on fundamentals and consistent, conservative playing, which makes it a good counterpart to the sort of nonsense you get up to as a Support.

My strongest champions:
Top: Kayle or Mordekaiser I guess
Jng: still Warwick
Mid: still Zilean
Bot: Jinx > Twitch
Sup: Blitzcrank > Bard, Soraka

I still have enough RP left to get two more 6300 IP champions on sale, but I'm not sure who to get. There are some non-Support champions who look really fun to me (Aurelion Sol, Ekko, Zac), but I might not end up playing them that much. On the Support side, I might go for Braum or Rakan or Nami. Although Thresh is cool, I'm resistant to playing literally the most popular champion in the game (with a bad winrate, as well).

reflecting on the game that went bad...
practicing would imply ffing a lot of games...
reflecting on "always trying to get better"

PRACTISING

THAT GAME

** Oscar re: games and books

games: Space Engine, Outer Wilds, vignettes; Deus Ex?
literature: The Fifth Head of Cerberus, Lord of Light
Locke Lamora: issues ... book 2, sailing took a long-ass time
SCPs: 2774 (sloth picture), meme that makes you forget it, the toaster, unfinished chronicle, Reagan video

** Pearl re: stuff

Okja, Arrival, Great Comet, MCU

** Sander re: LoL complaints
** Sarah re: date

> I started by making a offhand introductory comment which I thought was merely a mutually understood observation about a difference between how our minds operated (and by extension, the minds of men and women in general). This comment went something like, "You know how men sometimes think about one thing at a time, or can even have nothing on their mind, but women always have multiple things they are thinking about all at once?" I was not expecting my husband to take disagree with that statement and spend the next hour to 2 hours trying to reason/argue out whether his and my brains really actually operate differently. In the course of the conversation, he made an assertion which contradicted something that he had previously told me, then acted like I had been at fault for believing the first thing he had told me because, obviously (to him), the first thing he had told me was impossible. I felt outraged because he has so many times complained about my hyperbole. I have made a point of believing him when he tells me something about himself because the only times he has ever really gotten angry with me were times when I indicated I didn't think he was telling the truth. To be chided for taking him seriously was insulting.  But even more outraging was the fact that because I believed his initial assertion, I had interpreted other behavior as innocent, which, given that he didn't believe his initial assertion himself, actually represented either evasiveness/secrecy or an unwillingness to engage in intimate self-revelation. 

Sarah and I were talking in the car, and I was feeling pretty good, and Sarah made a comment that seemed a little odd to me, like maybe I didn't entirely agree with it. It wasn't very important, so normally I wouldn't have said anything about it, but I was feeling kind of playful, so I playfully challenged her to be more precise about what she meant. I also genuinely wanted to know what she meant. I also thought it was a pretty safe disagreement to have, because I felt like I probably agreed with her.

willing to take responsibility for that

> What am I talking about, you must wonder: 
> Going back in our relationship, I have tried, as most women have, to get my husband to engage in intimate conversation. I want to get to know him. I feel lonely when he is silent or paying attention to something else when I am present with him. So, often when we are in the car and he is silent for a while, I'll ask him what is on his mind or what he is thinking about. About 25% of the time (and he's gotten better), he says, "Nothing." I see only three possible interpretations: Either he is really not thinking about anything, or he is thinking about something specific that he doesn't want to share with me, or he doesn't think his thoughts are worth sharing with me. At first I had thought it was the third option, so I tried to tell him that I wanted to share whatever he was thinking about no matter how trivial it might seem. As I recall, he specifically explained that there were times when he really wasn't thinking about anything, just kind of spaced out with his mind a blank. I accepted this explanation and incorporated it into how I understood and interpreted my husband's response of, "Nothing." My sister and I had shared with each other similar conversations with our husbands and laughed at how different this descriptions seemed from our experience of always having at least 3 major different trains of thought running simultaneously with others thoughts in the background. The only time we really feel our consciousness is occupied by only a single thought is when we are deliberately concentrating hard on one mental process, say, writing this email or an academic paper, and even then I'm mentally outlining several paragraphs ahead while I'm phrasing and writing the current paragraph. This, we felt, seemed to be a significant difference between men and women. 

> But now my husband suddenly revealed to me that he believed we were incorrect in this belief. Not only was I incorrect, but he thought it should have been obvious to me that it would be impossible for someone to have nothing in their consciousness that they were considering at a given moment. He employed a reductio ad absurdum, referring to awareness of bodily processes as being present in the consciousness, but not really being described as "thoughts" per se. He declared that there were no times when there was "Nothing" on his mind and expressed his surprise at my credulity. I was upset because; 1. he clearly thought I was rather foolish to have taken him seriously and literally in the past, even given his stated demand early in our marriage that I never question his honesty. 2. If he always had thoughts but sometimes said that he didn't when I asked him what he was thinking, it logically follows that he had been deliberately choosing to withhold self-revelation. He didn't want to be intimate with me in sharing his mind. This sudden understanding hit me like a ton of bricks and a slap in the face. I tried to explain to him that a woman asking a man, "What are you thinking about?" is essentially a bid for connection, and to turn that down is essentially to refuse an opportunity for connection. He continued talking about the minutia of consciousness and how different categories of thoughts could be ranked, and whether intrusive thoughts count, and whether random thoughts that linger for less than a second count, and so on and so forth. I felt like he had missed my main point and I told him so. I asked him if he understood that to me his saying, "Nothing" when I asked him what was on his mind felt like a refusal of self revelation. He said, "Yes, but do you understand..." I think it was something about it being impossible for the consciousness to be entirely empty. By this time, we had finished eating. I usually eat an enormous amount (I maintain a normal weight, have a pretty high metabolism and am currently nursing an infant as well and have actually been losing weight significantly), but couldn't even finish half of my meal. We no longer had any time to go bowling. We decided to head home since we would only have a little over an hour to make love once we got home and it usually takes us an hour due to my issues and hangups. I felt completely out of sorts. I knew that the date was supposed to help me feel loved so that I could turn around and meet his needs. I felt that I had ruined our date and ruined my chance to feel connected to him ahead of sex. I expressed my disappointment that we hadn't really gotten to do anything recreational. My husband sensed I was upset. I had a hard time verbalizing why and I really didn't want to rehash the same conversation over and over. I tried to explain, but I feel I did a very bad job. I tried to explain that there were a lot of things I had wanted to talk to him about and that my comment was never meant to be the main discussion, only an introductory observation. My husband asked if I we could talk about some of those things that I had originally been eager to talk to him about. I tried, but I really didn't feel like talking about the positive or neutral things and it seemed like a really bad time to bring up the concerns/complaints I had wanted to discus at a time when we were both happy and relaxed. I did ask him to, in the future, please try to offer at least one of his thoughts when I asked him what he was thinking about and he agreed. On the way home, we passed a small gun shop we had both always wanted to explore but never could with our children, and my husband had the very good impulse to suggest we stop and do so. We spent about 15 min talking to the proprietor and looking at firearms and I started to feel a little better. 

> We headed home and I began realizing that the only thing we had time left for on our date was sex and I didn't remotely feel like having sex. I felt hurt and disrespected. I felt let down that the date I had so looked forward to had turned into an exercise in frustration at the end of which I was expected to act like I had had a great time and was in love. He hadn't touched me the entire date. He had complimented my appearance at the beginning, but hadn't said or done anything else affectionate the entire time. The conversation we had had, although intimate, had made me feel bad, not good. We got home and he asked me something further about our interaction and my state of mind as we were tidying up in the bathroom. While I was trying to explain my emotional responses (I don't remember exactly what I had said, but I do remember that it felt risky to admit whatever I was saying and I was nervous about how he would respond), he walked out of the room, I heard his shoes hit the floor loudly, and I heard the back door slam. My heart started racing and I felt angry that he would behave like that. He walked back down the hall looking completely calm and I was livid! I asked him, "How could you do that?" He said, "Do what?" looking very confused. I said, "walk away from me when I'm trying to talk to you, throw your shoes, and then I heard the door slam and thought you had walked out of the house. I thought you were angry with me." He tried to put his arm around me and I pulled away. He looked very concerned and said that he had just realized that he was still wearing his shoes and had walked down the hall while listening to me in order to take them off and put them away and then he noticed the dog needed to be let out so he opened the door. I realized that I had completely misunderstood his actions, but I was still shaken. I said, "You haven't touched me this whole date!" He said, "I just tried to and you wouldn't let me!" I said, "You didn't even offer to stop saying, 'nothing', until I specifically asked you to!" He said, "That's right, until you asked me to, then I did." (I feel like he should have offered that and I shouldn't have had to ask him, once I made it clear how offensive that behavior was to me.) He said, "I can see you are not in the mood to make love. Can we sit on the couch together?" We sat on the couch and I cried because I felt I had ruined the date and I wasn't going to have another chance to date him until next week because of how much I am working this week. I let him hold me and I realized I was exhausted, so he told me to go take a nap and he laid down next to me and held me for a short time until his parents dropped off our children.  

** Sarah re: stuff

+ Want me to share my thought but I can't
+ Feel like if I share my thoughts they'll get stuck to and repeated for years
+ I want to talk through things
+ I never said that you shouldn't be offended, or had to back up your offenses with a rational argument, like you couldn't be offended without that
+ But I will employ rational argument if I feel like you are saying something that is factually incorrect, or if you misunderstand me
+ With the "thinking nothing" issue, your main offense seems to be from thinking that I've been insincere or dishonest, e.g., something factual about me; yet you don't want us to go into the details of why that may or may not be true
+ If you say that something I do hurts you, I can try to not do that anymore; if I'm not exactly clear on what the behavior is, I will want to ask questions to clarify; if it's something where I think you have an incorrect view of certain facts, I will want to correct you so that we can determine whether it really is a problem with my behavior, your behavior, or a simple misunderstanding, so that we can fix it
+ If you say that something I do hurts you and I'm not allowed to ever say anything in response, then how can I end up anything but neurotic?

+ The issue of whether it's accurate/honest for me to say "nothing" is a complex issue to me. It just is. I do not see it as simple. I do not see a simple solution that I'm just refusing to talk about or admit. It's possible that a simple solution exists, but that I do not know it. I cannot progress in my understanding of it, cannot work it out, without facing my complex conception of it. I'm not trying to obfuscate the issue or outtalk you. I am trying to use my reasoning, to the best of my ability, to face my best understanding of the issue. Maybe it seems like a simple issue to you, that I've been lying or insincere or inconsiderate, and that everything I say after that admission is just some made up rationalization. I realize that I've dug myself into a hole by having the discussion at all, that you're more upset than if we never had had the discussion at all. Well, if we're going to get through it, it can only be through. 

+ I've brought up intrusive thoughts in the past and have pretty much always regretted it.

** Sarah: what do I say now?

+ Write a response.
+ Yes, we need to talk about it, now.
+ Yes, we need to talk about it, at some point.
+ No, we don't need to talk about it.

I delay that conversation, the meta-issue or super-issue of disagreements, of superficial disagreements that trace back to fundamental disagreements (as most superficial disagreements do), not because it's unimportant (it isn't), or because it might not come up again (it will), but because One Things at a Time. OTT. It can actually wait. A certain amount of control must be exercised here. By me.

The difficulty to reconcile is that I feel I legitimately will damage our present (already precarious) situation by bringing up this issue (in the near future), this me-issue, but it may be (accurately) construed as dishonest or at least insincere if I *don't* bring it up.

+ So I give Sarah a 4-year plan. If I do it flippantly, off-handedly, that's a bad reaction. Either I didn't really try this time, or I wasn't really trying for the past 7 years, or both.
++ So, I make it purpuseful. Something that I put work into. Something that was difficult to come up with and involved thought.

** Sarah re: tonight

Sorry for tonight.

Angry with myself for letting Gwen poop her pants. Knew what was coming, thought about putting her back on the potty...

Cyprian took his socks off, I forgot to put new ones on him, he scratched his leg open. I wiped the blood off and put a band-aid on it but didn't actually clean the wound.

Cried when I tried to apologize to the kids.

Held Curdie for a while.

No energy. Can't concentrate for shit when the kids are around. Can only concentrate at 2 am or whatever.

** Dr. Harley

Dr. Harley,

I want to ask your advice something. Last night something happened which has happened a couple of times in our marriage. Sarah had what I would describe as a very depressed, hopeless episode. It seemed to be triggered by a combination of unrelated stressful things that happened today, including things at Sarah's job, and also me not finishing a task that Sarah asked me to do today.

Sarah was noticeably dispirited when she came home from work today. We talked a bit. After we put the kids to bed, we finally ha the chance to really talk. I asked her if there was anything I could do for her, and she broke down crying, saying that she couldn't do it anymore, she wasn't sure if the marriage would work, and she felt like she ruined both our lives.

I really don't know what to do in these situations, or what to say. I feel like I can only say "I love you" and "I'm sorry" so many times before it sounds insincere. If I say anything along the lines of how I'll be there for her or things will be okay, she challenges it. If I say nothing, she eventually says something sour like "I guess I just have to bury it all and buckle down and keep trying harder." Or something like that.

I don't quite know how seriously / literally to take her words when she has one of these episodes. I want to take her literally, but she usually seems to be in an entirely different mood the following morning after one of these episodes.

* emails (inactive)
** Nick re: Battle for Middle-earth 2

I wanted to share a few more of my criticisms of Battle for Middle-earth 2. I didn¡¯t want to annoy the Tribbles or sound ungrateful - you know I can be very critical.

I have three main issues with the game. The first is that the game is heavily reliant on special, not very RTS-y moves, by which I mean Heroes and Palantir Powers. And although you technically end up with a lot of dudes on the battlefield, you don¡¯t end up with that many independent units. Furthermore, there are a lot of bonuses that encourage you to bunch all your dudes into one army (Heroes with leadership bonuses, Palantir Powers that give AoE healing or whatever), further decreasing how much RtS type stuff you¡¯re doing. Note this stuff isn¡¯t necessarily bad, it¡¯s just not what I want from an RTS. I prefer RTSs more straightforward, with all special attacks being derived from normal units.

The other two main issues are connected: terrible user interface and complex, arbitrary rules. Terrible interface includes: buttons for buildings are frequently attached to the buildings themselves, and therefore move around on the screen. Game does not tell you how much health, damage, armor, speed, etc, any unit has. All you get are these little hints (¡°strong vs archers¡± or whatever). This is a big deal in a game where every unit is unique, and where the differences in units (like the whole infantry > pikes > cavalry > infantry thing) is so important. Also, because every unit is so unique, there¡¯s a ridiculous amount of stuff to remember if you actually want to play well. Here are a few of the notes from the [[https://www.gamereplays.org/community/index.php?showtopic=937340&mode=linear][latest patch of the game]]:

-All Pikeman Crush Revenge now deals 45% against Treebeard, from 100%
-Elven Mallorn Tree fire fuel rate decreased
-Mithlond Sentry Heavy Armor now takes 60% Slash, from 80%
-Mithlond Sentry Heavy Armor now takes 50% Uruk, from 70%
-Mithlond Sentry Heavy Armor now takes 60% pierce, from 80%
-Sunflare now deals 300% vs heroes(not flyers)
-Rivendell lancer now takes 115% poison, from 130%
-Mithlond Sentry weapon now deals 150% vs Spider Riders

All incredibly specific, and none of it clearly indicated in the game.
You have poor controls over your units. You can make them move and attack, and que up moves, make them stop, and that¡¯s about it. Consider the movement options for another old RTS, Ground Control: in Ground Control, each unit has three possible movement modes, and three possible attack modes:
	Movement:
		Obey move order (or halt order) no matter what.
		Obey move order, but stop to engage enemies.
		Obey move order, but pursue any enemies seen.
	Attack:
		Open fire at any enemy in range.
		Return fire if attacked.
		Do not attack under any circumstances.

Those two settings are very clear and concise, and together give you an enormous amount of control over your units. AoE has similar settings, I think. But BfMe2 is unclear; if I hit ¡®s¡¯ to stop a unit, will they stay put indefinitely? Will the stop attacking, or just stop moving? If I right-click to move them, will they engage enemies along the way?

All that being said, it¡¯s worth noting that I¡¯ve never taken to RTSs the way I have to action games, either in terms of enjoyment or skill. So far I tend to prefer what people usually call ¡°tactics¡± games, which is basically any RTS where you don¡¯t build anything. These include Bungie¡¯s Myth series, as well as the previously-mentioned (and now free) Ground Control 1.

** Pearl re: Mad Max, gender politics

I know it was a while ago, but I had some more thoughts about our discussion of Mad Max.

The issue that I keep coming back to is this: many people, including myself, 




There are undoubtedly enough books written by and about females that I will never run out of them.



Not that I'm looking for a particular number, a particular ratio, 50% PoC, etc, but rather, what rubric you're using, since you're definitely using one. Maybe one based off of who gets work and who gets screentime...


...


I've thought about our phone conversation a lot, but it's hard to put my thoughts into words precisely. I guess what I'm looking for is some kind of test, something I can apply to movies and get back "positive" or "negative". So many movies I feel could plausibly be taken as pro- or anti-. 



I guess what I'm looking for is some consistent criteria by which we can judge films. Even if it's subjective, just so long as it's consistent. Something falsifiable.

But a sufficiently ambiguous criteria can be used to arbitrarily praise or condemn any film, and therefore is not useful as a guide for criticism, understanding, or policy; in fact has no use other than to amplify the whims of the person wielding it.



Further consideration of our conversation has clarified my thoughts somewhat. I guess what I'm looking for is some consistent rule or set of rules that can be used to criticize films (or other things). They might end up being subjective - something like "I get the feeling from this movie that..." - just so long as we're using the SAME subjective measure each time. 

I'm not saying you have to have this all written out; you don't need to account for every possibility; in fact, since you're not a professional critic or whatever, you're not actually REQUIRED to figure ANY of this out. But if you judge any film to be good or bad, to succeed or fail, then you are implicitly using some set of criteria, even if you never state it aloud.




I'm looking for some sort of consistent test which is falsifiable. Something that I can apply to one movie and another, and to which I can hold them (and my own criticism) accountable. As it is, so many different standards are used that I find it relatively easy to construct arguments for or against egalitarianism/equality/feminism/etc. in any given movie. Mad Max, for instance, fails because it stars a man; because the cast is overwhelmingly male; because the only females who get screentime are beautiful and/or super deadly, implying that any female who isn't is valueless; because the females in the movie ultimately need Max to save/help them. And Mad Max succeeds because it stars a woman; because all the women in the movie are good, or at least sympathetic, whereas the overwhelming majority of the males are evil; because the males are treated as disposable whereas the few female deaths are portrayed as huge tragedies; because (by modern standards) many of the males are grotesque and ugly, but the only females who could qualify as that might be the lactation-slaves, implying that the natural state of women is to be beautiful, as opposed to the natural state of men; of all the characters who get any real screentime, all the males of Joe's tribe are completely deluded into believing he's some sort of God, with just one of them (Nux) ever being convinced otherwise, whereas all the females (Furiosa and the Brides) don't buy it for a second.

I asked my question (in my previous email) because a lot of people feel this dissatisfaction with modern films (/etc), as do I, but I've not yet been able to formulate an answer to my question (what OUGHT the ratios be?), nor have I found anyone else willing to. Saying "there ought to be more females in movies" (or more PoC, or my LGBTQ+, etc.) might be true, but even if so, does not provide us with enough precision to really make any useful criticisms on a per-movie basis.

Here are some questions.
What ought the ratio of different races be? Should it be an equal representation of each distinctly recognized group? Or should it be proportional to the people currently alive on the planet? Or should it be proportional to the people actually in the situation portrayed in the film? If so, does this mean that mean that we should alter the number of movies we're making about certain subjects? I mean... so far as I know, nearly all of the soldiers in nearly all of the armies in recorded history have been male. This implies that movies about historical wars will mostly have males. Since war movies have always been popular, this means we've always had a lot of movies that are basically all male. If this is bad, does this mean that we ought to muddle with history, or does it mean that we ought to make fewer war movies?

And suppose a movie takes place in a fictional world. Are the filmmakers obligated to create a world with demographics similar to the real world? Or dissimilar?



Bechdel test only fills in some of these gaps


I also have to point out, at the risk of offending you deeply offending you, that the only real social criticism I've seen of Mad Max has come from the farthest left and the farthest right, reinforcing my belief in the Horseshoe Effect




I see the sex-equality thing as a good thing that MM COULD have done, but didn't; similarly, there are an endless number of good things that the film could have, but didn't, do (it was not a good kids' movie; it's not educational; it's not expressive of joy; it doesn't promote autism awareness; etc). I suppose it's easier to see how it could have been more sex-equal, it's easy to IMAGINE the difference, but we know neither the creative process of the creators, nor the hoops they had to jump through to get the film made. We don't know that Miller didn't have to fight just to get as many females in the movie as he did. It's true that every one of these could be and is a real issue, but they should be approached as separate issues; to fight against the movie itself 

* notes in gifted books
** ~2014-12 Zack Candy

book: The Fifth Head of Cerberus: Three Novellas
author: Gene Wolfe
address: 163 Fifth Ave., Ottawa, ON, K1S 2M8. Care of Annalise Harrison
note: accidentally ended up sending him two identical copies

Respected Zack,

I mentioned Gene Wolfe (and, in connection, The Fifth Head of Cerberus) during your recent visit - at Fiddler's Hearth, I believe it was. Now, I admit readily that I am far from grasping the totality (or even the lion's share) of the nuance and deep meaning of Wolfe's work. Wolfe exemplifies a certain ethos of literature which I can best articulate as "rarely describing things outright". His narrative voice is always inured deeply to the culture of his imaginary world, as though he were telling the story to an inhabitant of it who did not need to be reminded of the physical particulars; consequently, it is possible to get many pages into his work with a relatively poor idea of what planet or age or technology level you are reading about.

I say that as a disclaimer, because I also think he is a very good writer, and I want to get the jump on anyone claiming that my impetus for saying so is merely that I do not understand him. I am not a fan of the idea that vagueness is equal to quality, and that the only truly artistic work is one which is so obtuse that after two readings an intelligent person could not say who the characters were or what happened to them. But the sense I get overwhelmingly with Wolfe is that he is not a hack; my intuition tells me that, even if I miss it, there is a sturdy and intricate logic to the worlds and situations he crafts; it is the same intuition that allows me to hear that someone speaking a foreign language is in fact saying somethinig, and not making random noises - despite the fact that I cannot readily understand them.

** ~2014-12 Stephen Erdel

book: The Man Who Mistook His Wife For A Hat: And Other Clinical Tales
author: Oliver Sacks
note: I think I sent this via a third-party, probably Adam

Respected Stephen,

You and I spoke at your cousin Adam's farewell party at Bethel about a year ago. I believe at that time I had you write down your E-mail address for me, while I said something regarding a recent resolution on my part to keep in better communication with my friends and acquaintances. Keeping this resolution firmly in mind, I promptly filed your E-mail address somewhere and forgot about it entirely.

The part of our conversation that I remember most clearly is a discussion of what we had been reading lately, and on the merits of fiction versus nonfiction, and the occasional difficulty one may find in being really interested in the latter, lacking as it is in certain admirable literary qualities. Not to mention faeiries and aliens and so forth. I recall that I mentioned then Oliver Sacks, a neurologist who wrote case-studies of his patients. Sacks' insight into the human mind is precise, fascinating and relatively unique, and he is able to write such that a nonmedical person (such as myself) is able to follow his train of thought.

As a follow-up to our conversation, you now have a copy of one of Sacks' most well-known books (Adam was kind enough to furnish me with your address). It comes with no requirements or expectations; only the hope that your life continues to be full of words and ideas; and, once more, the assurance of my pleasure at having had a good conversation.

** ~2014-12 Nicholas Strickland

book: Thinking in Pictures, Expanded Edition: My Life with Autism
author: Temple Grandin
address: 24639 US Highway 12, Edwardsburg, MI, 49112

Respected Nicholas,

While we were talking at Adam's farewell party, this book occured to me, and I forgot to mention it. In truth, I do not remember precisely why I thought of the book in connection with you - possibly it related to our brief discussion of the slaughter of cows. Well, beef is not the central thesis of this book, but it is certainly one of the largest themes (the original title was something like "A Cow's Eye-View", if I recall correctly). In any case, autism has always fascinated and elicited a good deal of sympathy in me, and your tastes and mine seem generally to be close to one other. It is a well-written book, and even a passing interest in the topic of how different minds work should prove sufficient to make it a very worthwhile read.

In the event that you already own the book, I am informed that it also has uses in the realms of fly-swatting.

