* God creating history (evolution, age of the Earth, etc.)
The wedding at Cana. Jesus turned water into wine. Given that wine is defined as fermented grapes, what is the identity of the grapes used to make this wine?
A - Wine does not need a history to be wine; it never needed to exist as grapes; wine is simply an arrangement of atoms.
A1 - Therefore, the world (and humanity) could be created in an aged state, without the necessity of the aging process ever occuring.
B - Wine requires the history of the grapes to be wine; this history was created along with the wine.
B1 - Therefore, there is precedent for God creating a history to go with something.
C - Wine-ness is something other than merely history or molecules; the wine Jesus made at the wedding did not have the history, and may or may not have had the molecules, but its wine-ness was something beyond either, and this is what He added.
C1 - No response.
* Paul on the slave trade
https://www.patheos.com/blogs/geneveith/2015/10/the-new-testament-on-the-slave-trade/#more-21871
