* Chapter one: Lycaon's Youngest Son

Birthed from the warm iron of a shapeless factory into the wet snow of a shapeless Winter night was the sullen figure of a man beset with demons. His name was Nikolai (though he was called other things during his life) and his demons were two: first, that Darwin, his friend, his good friend, had come into the factory with him, but would not leave it. They had parted ways in the factory, which was very large, as they knew the danger stalking them and wished to play the odds that at least one of them would survive. And so one of them had. Darwin was the stronger of the two of them, and the more resourceful. Darwin was the better man. Yet Darwin was dead, dead, dead; and there was no doubt about that. Nikolai had not seen the thing happen but he had heard a scream which he was sure could mean nothing else. That scream, that yelp, like the sound a big dog might make if you crushed its head in a vice, coming from the throat of the man who had stood next to him at his wedding, that scream would not leave Nikolai, would never leave him, he knew [this passage must be fixed on two counts].

If his first demon had been transformed by the lens of this world into the death of his nearest friend, the second one had taken a less circuitous route; large it was, muscular and clawed. It seemed nothing less than a monster pulled from the very gates of Hell to torment him. Indeed it was certainly the root of all evil in the new life that Nikolai found was his own, the life that began with his transition into the snow. For after it killed his friend it had longed for his blood as well, and come after him. Actually, he had killed it - the small knife kept in his inside pocket finding use for the first time - but what did that matter? There is no triumph in the death of a foe that has already lost its life, and there is no repair for some injuries. The diseased arm may be cut off, but that is not a victory over disease, only a lesser defeat.

For Nikolai it was not hypothetical. He had suffered both the lesser and the greater defeats. His arm really had been cut off - his right arm, midway between the shoulder and the elbow. It was another thing he left in the factory.

Nikolai found that he had come out a back exit of the factory, and stood at the bottom of a long stone staircase cut into the earth. He knew the top would give him the street, but the snow was so thick and the darkness so impenetrable that he could not see the top. Thus, when he reached his left arm across his body to grip the hand-rail and took his first step, it was the first step of an uphill journey which apparently had no end. There was a heaviness in his feet; they did not want to leave the ground, they nearly cried out in their longing to be beneath it. In his head was a pounding so acute Nikolai felt he could discern individual blood vessels. His chest, tired, protested against the ascent. His eyes, dry, protested. And the monster - standing before him, blocking his path, looking down on him from a great height - the monster, too, protested.

In the absence of hope and light, Nikolai clutched logic to his breast. Some things were alive and some things were dead and even a werewolf could not survive such a fall as he had seen this one suffer. Its head was crushed into a shape almost unrecognizable, and its right arm was simply gone, as his. Some things were dead, and this was one of them.

"Move aside," said Nikolai. His breath was less, and his throat drier, than he expected, and the words sounded weak and childish. Coughing, he said again, "Move aside!" and accomplished the sound of a child shouting.

The monster considered him, or seemed to. Its one eye (for the other, even were it present, would be hidden entirely by the swelling from its wound) looked Nikolai over. It was an accusatory gaze. It struck through to Nikolai's mouth, which became dry; it seemed to say, "You have no weapon. Your knife put out one of my eyes, but you have nothing to put out the other." It struck through to the back of Nikolai's neck, whose hair stiffened; it seemed to say, "Your friend could not resist me. You shall not resist me." Then the monster opened its mouth, and its true voice struck through to Nikolai's heart, whose beating faltered. The monster said, "Not for the likes of you."

Nikolai lunged forward and swung at the monster, his hand passing through air. He slipped, and clutched the hand-rail again to keep from falling. Still the monster stood in front of him. Carefully, Nikolai lowed one knee to the wet stair, released the hand-rail, and thrust his left hand forward again. It entered the space where the monster stood without touching it. The snow, too - though Nikolai could not see well - the snow seemed not to settle on the monster's shoulders, nor in its fur.

"Phantasm," said Nikolai.

"A dream, more-like," said the thing. "But did you not know? You have left the waking world behind. I have dragged you into my domain."

The wind picked up, and the falling snow, swept by the wind around Nikolai and through the monster, described spirals and vortices in the air. Nikolai's knee rested yet on the stair, and he dropped his eyes from the horrible image that stood before him. But as he turned his head and looked around, he seemed caught in something like a vision, for the stairs and the railing and the factory behind him were gone, and he saw himself and the monster atop a high pillar amidst an endless black void; and in that other place he felt a great weight of time, and it seemed to him that in a moment the monster would fall upon him and devour him forever.

But the cold bit at him, and woke him from his vision, and though the monster had not left, Nikolai saw again the solidity of the world around him. The knee of his pants was wet where it rested on the stone stair, and there was sweat turning cold on his forehead. Nikolai put his left hand on the railing and it stuck slightly. He had lost his glove. He forced himself to stand, though it made him feel sick.

"You hold no sway over me," he said slowly and after some thought. He turned his eyes once more to the monster. He found that with effort he could continue to look at it. It said nothing, so he continued. "Dream, are you? What power does a dream have over the dreamer?"

The werewolf seemed to be smiling - if such a thing could smile. "Power enough to appear before you when you latch your door and shut your eyes."

There was temptation to test these words [There was temptation in these words], and Nikolai fought to keep his eyes open. If this dark creature had come to test him by strength, he would have long resigned himself to defeat, for he was wearied beyond words, and reckoned from his blood loss that he would be dead soon. But on this hopeless night, even resignation was denied him; for he felt that the thing in front of him, were it even a mere dream, had by the throat a part of him more dear than his dying [broken?] body. He understood neither the shape nor species of his peril, but felt instinctively the magnitude of it [, and it pressed [hard] at the very core of his being]. Lacking understanding, it seemed to Nikolai that at the very least, it was better to die with quiet grace than diminish to nothing, drowning in ever higher waves of panic and dismay. It is, he thought, better to fight. He swallowed.

"[Yet] the dreamer awakens at the end of the night," he said.

The monster's eye gleamed like a satellite in a cloudless sky. "And your friend, when shall his night end? I that bit you was once a man. When will his?"

The mention of Darwin made Nikolai's own eyes sting. He dropped his gaze from the monster and said, "Yes, he's dead. I know he's dead. I know you killed him."

The wind moved though the space between Nikolai and the monster with a sound that suggested the earth itself labored in its breath. He kept his eyes down for a time. Against his will, the thought of Darwin filled his mind, and he was unable to check his tears.

Though Nikolai held on to logic, he began to find that the loss of one of his hands had lessened considerably the strength of his grip. From his remaining hand the sensation of the steel railing was fading, to be replaced by a pain in each of the joints of his fingers. He knew that numbness was forthcoming, and did not know if he wanted it. The child within him rose up, irrepressible, huge, and it said, "I don't want you here."

The werewolf began to laugh. The sound was like thunder, and shocked the air in the same way[, and Nikolai trembled to hear it]. "Go away!" he persisted. "I don't want you. You've already hurt me so much. I gave you my arm." The anger of futility burned then in Nikolai's chest and moved him to look again at the monster and shout, "I gave you my arm! You have taken what you've claimed. Leave! I must be content with what you have left me of my body - and so must you. Go away! Go away."

The laughter ceased and the werwolf thrust out its clawed hand and seized Nikolai's throat, and Nikolai cried out [/aloud] [in spite of himself], for the claws were sharp, and they burned. "I am not content with swine!" said the werewolf. "I am not content with arms! I am not content with body and blood! Only let me drink of your soul."

The werewolf stood, then; for although Nikolai had taken it to be standing, it had been stooped on its knees; but now it rested its enormous feet on the ground, and stretched out its long and powerful legs; and, holding Nikolai aloft, it rose to a terrible height, and its eye flared [became very bright], and its mouth slowly opened, and in the blackness of its mouth could be seen the movement of inumerable snakes and flies and eyeless maggots; and Nikolai stood in the awe of the certainty of death [? perhaps, and Nikolai was struck dumb ... by the vision of death ... the certainty of death].

But [yet] the wind roared, and it seemed that the burning eye of the werewolf was smothered in snow; and with a pained thrashing like animal pulled underwater, the image of the dread beast was removed from Nikolai's sight, and he stood alone on the stone steps, and a distant voice shouted his name.

Nikolai stood for a moment quite still, transfixed and trembling. His left hand still clutched the handrail, and was entirely numb now. But the sweat on his brow compelled Nikolai to stoop and press his forehead against one of the steps above him, and he felt the coolness of the snow. Then he stood again and, his mind overcome by the simplicity of exhaustion, tried to walk up the stone steps. He found that he could. Moving his eyes from his feet to his hand in succession, he slowly climbed the remainder of the stairs, taking care to move his hand up the railing before each step. He thought he heard his name shouted again, but the sound was very remote. At the street at the top of the stairs, Nikolai released the handrail and fell to one knee, clutching his right shoulder. The fury of the storm seemed to be spent, or else was less here than on the ageless stair, and the night was growing calm and peaceful, though still very cold. Nikolai could see an ancient tenement house across the street, and small shops and stalls beside it, lit weakly by streetlamps, and he could make out the outline of buildings further on. Here and there Nikolai saw people moving along the street, unaware of him. Again he heard his name, closer now, and in response he said as loudly as he could, "I'm here!"

After about a minute, a figure, a man, detached himself from the shadows of a nearby building and ran to Nikolai. He slipped slightly but regained his balance and reached Nikolai, whereupon[?] he went quickly to his knees, grasping Nikolai around the middle and shaking him roughly. Then he put one hand behind Nikolai's head to hold it steady, and moved himself to face the Nikolai more directly. Nikolai was becoming more alert, and he was turning his eyes left and right, for it seemed to him that his name was still being shouted, and he was looking around for the person shouting it. "Where," he said, "where are you? Where are you?"

Nikolai saw the man's face move more in line with his own vision and he could see sweat on the man's nose, and the man's mouth opening and closing, though he could not connect this with anything in his mind. He saw the man as a wild animal, running and barking from blind excitement. The man's body was strange to him; his eyes had a feral look, and the arms that reached to clutch his own body looked stretched and wrong. The one on his side ended in something that might have been a hand. Nikolai doubted that a hand ought to look that way. While he watched, the hands produced a length of cord and bound it tight around Nikolai's bleeding arm.

"Nikolai," said the strange man.

Nikolai focused directly on the man, and as he did, the myriad shapes resolved, and Nikolai saw that he was a young man, and a man he knew.

"Randolf?" said Nikolai.

"Yes, yes, it's me. What happened? Where's Darwin?"

Nikolai turned his gaze downward, and only Randolf's grasp prevented him from falling.

"Was it the police, Nikolai? Did they kill him? Is he dead?"

"There were no police. Yes, he's dead."

"No police? Are you sure? How did he die?"*

"They've loosed a werewolf in the place."

Randolf stared at Nikolai for a moment, then straightened and looked at the factory. Then he tried to pull Nikolai to his feet.

"It's dead," said Nikolai.

"Are you sure?" said Randolf, still pulling at Nikolai. "Did you see it?"

"Yes. I killed it. Give me a moment."

"There's no time. There may be more of them."

"They only sent one."

Randolf shook his head vigorously. "They have not [do not have] the means to send any."

"Then the devil sent only one! Give me a moment. Please, let me stay here for just a moment."

Randolf let go of Nikolai and stood upright, clenching his fists and staring at the factory. "We may have only minutes. If we can get to Keane's - or even to my house - we will have a better chance of avoiding their searchings."

"Nothing else is searching. Nothing for miles. Randolf, there was only one. Listen. We came in through the northern breach. Darwin had information it would be empty. It was. No police, no soldiers. No one at all.

...

“Can you walk?” said Randolf.

“Yes.” Nikolai wiped his face with his sleeve.

“Do you need any help?”

“No.” He put his weight on his legs and stumbled, and Randolf held him under his left shoulder and helped him walk.

...

Like a soldier who forced to march for days, Nikolai slept while they walked; while Randolf carried him. His dreams were dark and formless and without meaning. He woke and slept freely, unable to tell the black shapes of his sleeping mind from the black shapes of the ghostly buildings, just visible through the Winter night. He felt the vague pressure of Randolf’s shoulder against his own side, which had only started to go numb with cold, and Nikolai was seized with the belief that nothing but this was real, nothing but he and his stark companion, walking from a place that did not exist to a place that would never exist, and at every moment passing through a new sea of unmeaning shapes in the snow. The snow itself was eternal; the heavens gave it up at no loss and the ground consumed it with an appetite never sated. He felt that black had more shades than any color, and that he saw them all that night. In his most lucid moments, he felt the snow crunch dryly beneath his shoes and could make out the shapes of street lights and the edges of buildings. In his most dreamlike moments, he saw only the most basic shapes, his eyes trained to see crude paintings where they looked upon reality.

Whether Nikolai’s consciousness wholly faded he could not determine; during the walk the walls of black that barred his vision closed in upon him, and when they had been lifted, he was lying in a room of absolute white. Randolf was at his side, looking away. His coat was dirty and heavy with melted snow. Young though he was, he stood very still and very solemnly, and he had the look of a warrior-angel, or one of the legendary Knights.

As Nikolai lay, he became aware that he was not dressed in his own clothes; what he wore was white and soft, and though it was thin, he was not cold. He did not feel his arm, but his eyes stung with that pain which makes one realize that one is alive - but Nikolai was not sure. He tried to speak to Randolf, to ask him, but he found that he could not move.

Randolf turned, and saw that Nikolai was awake. He leaned down to speak quietly.

“It’s alright, Nikolai. We’re safe now.”

Nikolai tried to say, “Are we dead?” but his mouth was weak, and he did not know how much Randolf heard.

Randolf’s face changed, and in a voice not his own he said, “You will never die.”

An intense, burning fear arose in Nikolai’s chest, and he strained to look at Randolf’s face, to tell whether it was Randolf who had spoken or someone else, but his own body was idle to his commands. Gradually the fear subsided, and after another long period Randolf said something and moved away from his field of vision. When he returned, he bent close to Nikolai and said,

“We can’t replace your arm. We don't have time. They’re giving you a fake.”

Nikolai nodded, or thought he did, and he closed his eyes again. When he opened them he was lying in the same place, but the lights felt dimmer and he felt as though he might not immediately fall asleep again.

Randolf was still there, slouched in a chair and reading from the gently-illuminated screen of a book. Nikolai found that he could not move any part of his body below the neck, though he strained.

Randolf looked up. “You awake again?”

“Yeah,” said Nikolai. “I can’t move. Why can’t I move?”

“They paralyzed you for the operation. You wouldn’t stop struggling. They said they can take it off whenever you’ve calmed.”

“I’ve calmed. Take it off.” Nikolai shook his head, and saw that his right shoulder was connected to something smooth and gray. It was thicker at the top, but

* notes and lines

(While the shock still hid the pain from him, he had used his belt to bind what remained as well as he could.)

Nikolai could not remember at first who the man was or how to speak to him, so great was his absence from the world of humans.

"I could not remember at first who he was..."

It is as your great pretender has said: my ways are not your ways.

I know the world better than you do. I have lingered longer. Which of us was cast out of Paradise first?

I have lingered longer in this world than you have. I know it better. Which of us was cast out of Paradise first?

The old legends say the shapeshifters come out under the full moon. The new legends say there are no shapeshifters. You have seen that both legends are false.

Markku: There's only me.

* plot sketching

Somehow Darwin and Nikolai are alerted to, and retrieve, an item which is Markku's signaler. Perhaps they take it from the "real" rebels, the ones who wish to destabalize the country? Anyway, upon realizing that it's signalling (after Nikolai takes it to the bar or wherever), they vacate the bar and enclose the device in a nullifying box. But Markku has detected the signal, so she quickly puts on civilian clothing and goes to Kean's public house. She asks for her contact, "Malcolm" or whoever. She is insistent, and agitated. Before Nikolai and the others slip out, they see policemen entering the bar. The policemen are actually there because they're investigating on behalf of Kellan, who knows that something is up because his werewolf went missing (why did they get sent to that particular bar? Either he had some idea of where Nikolai went, or he just sent people to every bar. Probably the latter.) The policemen are distracted by the sight of Markku, who is their chief or captain or whatever. Nikolai et al thinks they're distracted by seeing a lawbreaker, and they quickly sneak out before finding out what happens next. Markku assumes that she was insufficiently careful in asking for Malcolm (she knows that the police were sent everywhere - she knows they didn't follow her), and assumes further that Malcolm saw the police, and thought that she (Markku) was trying to trick and catch him. Because of this, she spends the remainder of her offscreen time trying to fix things with Malcolm, or with the Rebels, or whatever.

Markku has friends within the police, or at least, there are people she wants kept alive. Her bead is unique to her. Other policemen of similar rank (a very few) have beads with the same information, but she is unwilling or unable to steal them. Markku was going to entrust her bead to her contact with the other country (or rebels?). She does not have the means of copying it - or, she does not trust anyone but her contact with it. So, when she learns from Nioklai that her contact is dead, and that he is sort of a rebel, sort of affiliated with them, she gives it to him, either (if she cannot copy it) so that someone will have it, or (if she has been reluctant to give it to any), in the realization that she has wasted too much time. It has all the names on it, but is more important for the other military-type information it carries. After looking through it, Nikolai gives it to Randolf.

Nikolai knows, because of his pre-novel mission with Darwin through the Northern breach, that the man who is Markku's contact, is dead.
* quotes from other media
** John Ciardi, Abundance
“. . . Once, twice a year, partially, 
and once, twice a lifetime, perfectly, 

that snow falls. In which I ran 
like a young wolf in its blood 
leaping to snap the flower-flakes 
clean from the air; their instant on the tongue 
flat and almost dusty and not enough 
to be cold. . .”

** Into Death Bravely 
by Jimmy Santiago Baca 

Winter 
throws his great white shield 
on the ground, 
breaking thin arms of twisting branches, 
and then howls 
on the north side of the Black Mesa 
a deep, throaty laughter. 
Because of him 
we have to sell our cattle 
that rake snow for stubble. 
Having lived his whole life 
in a few weeks, 
slow and pensive he walks away, 
dragging his silver-stream shield 
down branches 
and over the ground, 
he keeps walking slowly away 
into death 
bravely. 

** The Knight's Tomb 
by Samuel Taylor Coleridge 

Where is the grave of Sir Arthur O'Kellyn?
Where may the grave of that good man be?—
By the side of a spring, on the breast of Helvellyn,
Under the twigs of a young birch tree!
The oak that in summer was sweet to hear,
And rustled its leaves in the fall of the year,
And whistled and roared in the winter alone,
Is gone,—and the birch in its stead is grown.—
The Knight's bones are dust,
And his good sword rust;—
His soul is with the saints, I trust.

** Midwinter 
by Sophie Jewett 

All night I dreamed of roses, 
   Wild tangle by the sea, 
And shadowy garden closes. 
   Dream-led I met with thee. 

Around thee swayed the roses, 
   Beyond thee sang the sea; 
The shadowy garden closes 
   Were Paradise to me. 

O Love, ’mid the dream-roses 
   Abide to heal, to save! 
The world that day discloses 
   Narrows to one white grave.

** Night Ferry 
by Peter Sacks 

Blood-drop, lung of fire setting past 
the sea bell and wave; why am I separate 
from that giant burrowing into further life? 

The body breathes and rides 
a heavy-netted ocean swollen 
by the tide. Under the half-moon 

it’s the lighthouse light that turns 
the rest of me to early nightfall, 
headland, home. I send it back, 

a mirrored flickering across cold waters. 
We allow ourselves the crest that breaks 
above the surface then re-forms. 

We make it human and we call it love. 
This wintering is my own and not the world’s, 
although the world is wintering.

** The Snowbound City 
by John Haines 

I believe in this stalled magnificence, 
this churning chaos of traffic, 
a beast with broken spine, 
its hoarse voice hooded in feathers 
and mist; the baffled eyes 
wink amber and slowly darken. 

Of men and women suddenly walking, 
stumbling with little sleighs 
in search of Tibetan houses — 
dust from a far-off mountain 
already whitens their shoulders. 

When evening falls in blurred heaps, 
a man losing his way among churches 
and schoolyards feels under his cold hand 
the stone thoughts of that city, 

impassable to all but a few children 
who went on into the hidden life 
of caves and winter fires, 
their faces glowing with disaster.

** Song 
by Sophie Jewett 

“O Love, thou art winged and swift, 
   Yet stay with me evermore!” 
And I guarded my house with bolt and bar 
   Lest Love fly forth at the door. 

Without, in the world, ’t was cold, 
   While Love and I together 
Laughed and sang by my red hearth-fire, 
   Nor knew it was winter weather. 

Sweet Love would lull me to sleep, 
   In his tireless arm caressed; 
His shadowing wings and burning eyes 
   Like night and stars wrought rest. 

And ever the beat of Love’s heart 
   As a chime rang at my ear; 
And ever Love’s bending, beautiful face 
   Covered me close from fear. 

Was it long ere I waked alone? 
   A snow-drift whitened the floor; 
I saw spent ashes upon my hearth 
   And Death in my open door.

** Jack Prelutsky, A Wolf Is at the Laundromat

“A wolf is at the Laundromat, 
it's not a wary stare-wolf, 
it's short and fat, it tips its hat, 
unlike a scary glare-wolf. 

It combs its hair, it clips its toes, 
it is a fairly rare wolf, 
that's only there to clean its clothes— 
it is a wash-and-wear-wolf.”

** The Bear Hunt
by Abraham Lincoln 

1. A wild-bear chace, didst never see? 
      Then hast thou lived in vain. 
Thy richest bump of glorious glee, 
      Lies desert in thy brain. 

2. When first my father settled here, 
      ’Twas then the frontier line: 
The panther’s scream, filled night with fear 
      And bears preyed on the swine. 

...

3. But woe for Bruin’s short lived fun, 
      When rose the squealing cry; 
Now man and horse, with dog and gun, 
      For vengeance, at him fly. 

4. A sound of danger strikes his ear; 
      He gives the breeze a snuff; 
Away he bounds, with little fear, 
      And seeks the tangled rough. 

5. On press his foes, and reach the ground, 
      Where’s left his half munched meal; 
The dogs, in circles, scent around, 
      And find his fresh made trail. 

...

6. With instant cry, away they dash, 
      And men as fast pursue; 
O’er logs they leap, through water splash, 
      And shout the brisk halloo. 

7. Now to elude the eager pack, 
      Bear shuns the open ground; 
Through matted vines, he shapes his track 
      And runs it, round and round. 

8. The tall fleet cur, with deep-mouthed voice, 
      Now speeds him, as the wind; 
While half-grown pup, and short-legged fice, 
      Are yelping far behind. 

9. And fresh recruits are dropping in 
      To join the merry corps: 
With yelp and yell,—a mingled din— 
      The woods are in a roar. 

10. And round, and round the chace now goes, 
      The world’s alive with fun; 
Nick Carter’s horse, his rider throws, 
      And more, Hill drops his gun. 

...

11. Now sorely pressed, bear glances back, 
      And lolls his tired tongue; 
When as, to force him from his track, 
      An ambush on him sprung. 

12. Across the glade he sweeps for flight, 
      And fully is in view. 
The dogs, new-fired, by the sight, 
      Their cry, and speed, renew. 

13. The foremost ones, now reach his rear, 
      He turns, they dash away; 
And circling now, the wrathful bear, 
      They have him full at bay. 

14. At top of speed, the horse-men come, 
      All screaming in a row, 
“Whoop! Take him Tiger. Seize him Drum.” 
      Bang,—bang—the rifles go. 

...

15. And furious now, the dogs he tears, 
      And crushes in his ire, 
Wheels right and left, and upward rears, 
      With eyes of burning fire. 

16. But leaden death is at his heart, 
      Vain all the strength he plies. 
And, spouting blood from every part, 
      He reels, and sinks, and dies. 

...

17. And now a dinsome clamor rose, 
      ’Bout who should have his skin; 
Who first draws blood, each hunter knows, 
      This prize must always win. 

18. But who did this, and how to trace 
      What’s true from what’s a lie, 
Like lawyers, in a murder case 
      They stoutly argufy. 

19. Aforesaid fice, of blustering mood, 
      Behind, and quite forgot, 
Just now emerging from the wood, 
      Arrives upon the spot. 

20. With grinning teeth, and up-turned hair— 
      Brim full of spunk and wrath, 
He growls, and seizes on dead bear, 
      And shakes for life and death. 

21. And swells as if his skin would tear, 
      And growls and shakes again; 
And swears, as plain as dog can swear, 
      That he has won the skin. 

22. Conceited whelp! we laugh at thee— 
      Nor mind, that now a few 
Of pompous, two-legged dogs there be, 
      Conceited quite as you.


** Isa 65:25 
"The wolf and the lamb will graze together, and the lion will eat straw like the ox; and dust will be the serpent's food. They will do no evil or harm in all My holy mountain," says the LORD.


** Christ Jesus Lay in Death's Strong Bands

       4. It was a strange and dreadful strife
       When Life and Death contended;
       The victory remained with Life,
       The reign of Death was ended;
       Holy Scripture plainly saith
       That Death is swallowed up by Death,
       His sting is lost forever.
       Hallelujah!
"Christ Jesus Lay in Death's Strong Bands"
                        by Dr. Martin Luther, 1483-1546
       Hymn #195 from The Handbook to TLH
       Text: Acts 2:24
       Author: Martin Luther, 1524, cento
       Translated by: Richard Massic, 1854, alt.
       Titled: Christ lag in Todesbanden
       Tune: Latin melody, c. 1100

* old
** chapter summaries
Note: Nikolai has to avoid any policeman with a circular DNA tester, because it would show him to be a werewolf (werewolves being either taken or killed without question).

Note: Nikolai must worry about transforming.

Note: Mr. W. H, the alchemist, the genie, the prestidigitator or illusionist, the magician, the god, the devil, the angel or demon, lost oneironaut, the fifth immortal, one of Pharoh’s magicians

At new moon, Nikolai visibly forces his way into the factory.

Characters:
Nikolai
Kellan
Demon
Bartholomew
Jacob
Rin
Deamia
Markku
The City
The Rebels
Broderick
The sword


*** CHAPTER 1: .995-.976: Nikolai, Jacob

Moonsign: The factory, perhaps? Nikolai being made 'whole'?

OK. It starts out with a guy, Nikolai. He walks out of a factory. It's a large factory, and it's unused. It's been abandoned for decades. But, it's still running, because somewhere along the lines someone forgot to turn it off, and its nuclear generators simply never run out of energy. So, this guy, Nikolai###û, He walks out of the factory and into the snow. There's snow because it's winter out. It's also dark, like the middle of the night. Very dark. The way the factory is set up, there's a huge steep ramp leading from the ground to this lower level, with a stone staircase on either side. Nikolai is at the bottom of one of them.

He steps out and he looks like shit. He's bruised, dirty, there are nasty gashes on his face still bleeding, and he's missing his left arm. You can tell it was cut off quite recently, because the wound is rather clean and bleeding badly. So yeah, he just looks like shit. He's also rather dazed, like he just woke up after being knocked out. He's wearing an old jacket that's not nearly thick enough for a cold winter night on the outskirts of New York City. He's also wearing some sort of insulated pants and fairly nice boots, and sure, a cap as well. He's missing gloves though, or rather, glove###Ã.

He steps out of this factory and just looks up the steps. The air is completely filled with snow. There's a full moon, and there are some man-made street-lamp sort of lights along the stairway, and the way it lights the snow up you cant's see more than fifteen or twenty feet in front of you. Given the staircase is something like a hundred and fifty or two hundred or even more feet long, he can't see if there's anything or anybody at the end of it. If he didn't know better he'd question if there was a world beyond those steps that he can see.

(On either side of the staircase-lined ramp is just wall)

He begins to walk up the stairs, slowly, pulling himself forward on the hand-rail with his right hand. He's very weak. He reflects sort of abstractly on his situation, which is this: he and his companion, Rin, entered this old factory looking for information regarding Agency. Agency is sort of the police of the somewhat totalitarian government. I'll go int###Æo details later. The point is, because of their militaristic hold on the city, it doesn't make any sense to fight them in any tangible way, so what the Requiars do ñ Requiar is the name given to those who hold allegiance to an underground society attempting to overthrow the government ñ what the Requiars do is simply gather information, figure things out, and try to change public opinion or subtly sabotage Agency operations. Nikolai and Rin entered the old factory, which was at one time used by Agency (this was at the end of its useful lifetime) for research. They were looking for some rumored clues pertaining to Agency's original rise to power, perhaps thirty or forty years ago. They find nothing of more than curious value, but while they are there, a werewolf enters the factory and begins to stalk them. They split up, but the werewolf (who is faster, stronger, and has a very keen sense of smell) first kills Rin (Nikolai hears ###ôhim screaming), then find Nikolai. Nikolai tries to fend it off, but the werewolf first hits him in the face with one of its claws, then bites him on the left arm. At that point Nikolai grabs the throwing knife that he kept with him and stabbed the werewolf in the eye. The werewolf stumbled backwards, and off the high platform on which they were standing, and crashes to the ground dead. Thinking quickly, feelings the venom being to seep through his arm, Nikolai runs to one of the machines still running in the factory, a huge, repeatedly descending blade, and sticks his arm into it, severing it just below the shoulder. This puts him into shock, which is why he wasn't totally awake until he got to the door of the factory and stepped out into the snow.

So he's walking up the stairs. He's very cold and, as said, very weak. His mind is now running again, and the first thing he thinks about is Rin. He mourns sho###{rtly for Rin, but then he begins to think of the werewolf's bite and he quickly forces himself to think about something else.

He thinks about his family, which is brief. He thinks about the other Requiars, but there is little to say. He thinks about he and Rin's mission, in the factory, and how they found nothing more than some human adult corpses, hidden deep in the levels of the factory. In a world such as theirs, it was not such a big shock. They also found things like hypodermic needles, unintelligible paper reports, outdated computers that have been wiped, and perhaps an Irish painting or other sentimental memorabilia, perhaps with the name ìLoganî attached.

When he thinks about a paper or book or whatever that they found relating to werewolves, his mind is inevitably brought back to the thought of the one that bit him. He remembers very bitterly the bite and he hates t###òhe werewolf for it. He curses it. He reflects that, surely he did the right thing, when with no other thought he cut off his own arm? But, somehow it wasn't enough, and its venom, or a portion of it, is still in him, because he can feel it distinctly, an evil sort of burning feelings, and something stirring in the back of his mind.

The thought of all this brings on a physical attack of some sort. Since his body doesn't know how to deal with it, he coughs and wretches and tries to throw up, and he falls to the ground in pain. The attack passes, eventually, and he continues upward, now without doubt that he is infected, that he is a werewolf, at least in some form.

Nikolai considers his situation. He is infected. He must keep reminding himself of this because his mind is constantly trying to ignore or forget it. He is infected. But it is the full moon, and he did not transform. Is he able to resist it? Is###¡ he not fully infected? Will he be able to resist it tomorrow, and the next full moon, and the next, and will there ever be a cure? Will he be able to continue in service of the Requiars, or even continue his relationships with his acquaintances, or even function rationally at all? Will his erratic behavior cause him to be shot by the police as soon as he returns to the main city? Would it be better, simpler for him to simply die right now?

Perhaps he is dead, perhaps he is the waking dead, the living dead, the walking dead. Perhaps he will never again be happy, never again see the sun shine, never taste water or feel the warm wind across his face. Perhaps he will never again taste sugar or smell flowers, perhaps books will be nothing to him and music less than nothing. What, what was he, and why did he still exist?

Of course, to imagine that he would want to die is ridiculous. Not him. Not before now. And maybe not now. Maybe.

Nikolai feels an eerie presence in his mind, the cause of which he is unable to determine. He demands mentally to know who is in his mind. He receives, after much prodding, a reply, in the form of convoluted emotions of fear and hatred and despise; they come from within him and almost take the form of words. The shock of this is almost too much for Nikolai, staggering him. He yells mentally and literally for the thing to speak again, but he senses nothing, and wonders if he only imagined it, and if so, how much else of this is he imagining? He looks around him and sees nothing a thousand times over. He sees Winter and snow and death. All he sees is death.

He reaches the top of the staircase, realizing bitterly that he's still basically in the middle of the empty road. Then he realizes he can make something out in the falling snow, the figure of a man. The man rushes forward to Nikolai, who feels numb in many ways, and realizes finally and truly as this man ñ Jacob ñ reaches him that he is not dreaming, that it is all real, that he is the waking dead and Rin is the dead and gone. He collapses in tears or agony. Jacob helps him up, grabbing his arm. He asks if Nikolai needs help walking and Nikolai says no, but needs his help anyway. He walks with his and Jacob's arms over each other's shoulders to support Nikolai. Nikolai fades between consciousness and unconsciousness as they make their way to a (NEW) hospital or prosthetic limb clinic.

When they get there, there is a wait as Nikolai is measured and his new arm is fabricated. Jacob pays for it. They talk, and Jacob needs to convince Nikolai that he is or may still be useful. Jacob reminds him that the Requiars do not rely on strength or fighting, and that Nikolai's physical condition is not really a factor. Nikolai argues that as a werewolf he will be unable to control himself enough to rationally be of prolonged use to anyone, against which Jacob points out that Nikolai has not transformed now, even though it is a full moon, and that that, along with the nature of his wound and cutting off his arm, he may not be completely infected, or rather, though he is infected, he may not be entirely lost to its influence, and promises to help if he can find any way to help Nikolai in this matter, that is, to cure him. Nikolai is grateful, despite how unrealistic this is. He is put unconscious during the procedure to attach his new, metal arm, and stays asleep for a while.



*** CHAPTER 2: .810: Nikolai, Bartholomew

Moonsign: at the church, one-fifth of either the large windows or the pillars are destroyed.

We enter on Nikolai looking at his new arm. He considers its pros and cons; it is heavy, and needs maintenance. It is nowhere near as delicate or sensitive as a real arm. However, it is strong, durable, easily repaired. He notices that if he thinks too hard about it ñ if he remembers that it is not a real arm ñ it becomes harder to control it. He has to focus on something else for it to work best.

Nikolai is at someplace someplace old, a section of bombed-out buildings most likely. It is cool and dusty here, but feels strangely clean because of how calm and still and silent it all is. The specific building he is at is an old church, relatively well-preserved, with only 20% of its structure destroyed. While he is standing there he is approached by Bartholomew, with whom he'd arranged a meeting. They greet each other, briefly discussing how Jacob helped arrange this (somewhat impromptu?) meeting. Nikolai is silent for a moment, sizing Bart up momentarily for no particular reason (of which he knows...). Nikolai tells him about he and Rin's exploits in the factory. He tells Bart about how they entered the building through a deserted parking lot, how they searched around it for a bit before they found a control room, near the bottom basement floor. There they found nothing but paraphernalia of the old (not the old-old, just old) regime along with probably outdated research on the werewolf infection. They checked the rest of the bottom floor but found little or nothing of interest, and then they heard the screaming roar of the werewolf. They split up, Rin heading towards the upper exit and Nikolai towards the lower. Nikolai heard Rin scream and knew that he died then. He froze then, out of fear, and when he started moving again it was slowly, quietly; but, as he paused to look around him, he saw that the werewolf had already reached him and was watching him silently. He tried to fight it with a metal bar, but it easily knocked him to the ground and bit his arm. Nikolai then, with his other arm, took his throwing knife and stabbed it into the werewolf's eye, which caused it to release him and stumble backwards, into the railing of the old platform on which they were standing. The rusted railing fell apart and the werewolf fell to its death below. Nikolai then, in some state of shock, left the building and was alone until Jacob found him.

Bart muses aloud about how alone Nikolai and Rin had been until the point at which the werewolf had arrived, and how the mutual events of there having been werewolf research at the factory and a werewolf there are both unlikely events and possibly more than coincidence. Nikolai is skeptical about the latter thought, and dismissive about the first. Bart takes the opportunity to make Nikolai elaborate on the werewolf's bite and his physical sensations and phenomena immediately thereafter, especially concerning the moon and the strange voice that he heard. Nikolai is annoyed at having to recount such a thing but answers the questions. Bart asks him straight out whether or not he thinks he is a werewolf, and Nikolai says no. Bart confronts him and tells him that he is one, to which Nikolai is indignant, stating that he knows his own body well. Bart challenges him with the very words Nikolai has just uttered about what he went through on the steps leading out of the factory, which Nikolai dismisses. Bart argues against him using simple logic, and Nikolai becomes defensive and offensive. Bart continues and continues until he forces Nikolai to admit that yes, he is different from before, and that, with no reason to believe otherwise, they should take him as a full and complete werewolf. Nikolai stops arguing but avoids actually agreeing. Tired of talking about werewolves, he instead goes to the other thing Bart mentioned (though he was dismissive about it before), the fact that he and Rin's path to the factory and once they got inside it was so clear. Bart tells him that Agency certainly knew they were there, which shocks Nikolai, who does not understand why the police did not come to take him and Rin when they could've. At that point Bart takes on a somber tone and tells him that it was Christopher who did it. Nikolai asks how and Bart says that Christopher died. Nikolai is momentarily silent, during which Bart explains how Christopher incited a riot, which drew all the nearby police to it. Nikolai demands to know why this wasn't the first thing Bart told him, and Bart says that he didn't know best how to say it (or some other lame excuse like that). Nikolai gets angry at him and Bart apologizes, saying he should have told Nikolai immediately, because of the event's importance.

They are silent for a time. Nikolai curses the factory and all that it has caused, citing its useless nature ñ the meaningless work it did for no one, and the power it used up for no gain. Bart tells him it is a remnant of the end of an age that was more focused on scientific gain and power than the one they were in now, that its seemingly useless activity was probably meant as some sort of test, rather than actually producing something usable. Nikolai states that at that very time, scientific gain was a very large goal, and he couldn't see how it could've been significantly larger before. Bart tells him that it was an all-encompassing passion of America (and the world in general) for a while partially because of their goals; AI, self-sustaining machines, data storage capable of storing every book, movie, song, show, etc. ever created, essentially all of human knowledge piled into a single device. Bart states how all of this was achieved (significant space travel excepted), but how little it meant: few read any more and TV shows and movies were already easily available, AIs were vastly intelligent and convincing but held no great power of sentience/sapience/consciousness/etc. The big issue was the self-sustaining machine, for this was thought to unlock some great doors of understanding towards prolonging human life, an endeavor which had gained little headway in decades. When the self-sustaining machines finally came to be, however, they brought nothing of any more than superficial and practical value ñ nothing in regard to human health, no great lifting of the burden of work off of man's shoulders ñ not to mention that, if applied to something with constant human interaction, such as the Internet or a public space, the system still would require manual repair, not because of any inherent flaw but simply because of the strains of human interaction. Bart explains that this disappointment was ultimately the catalyst for the (second?) atom war, which was in a sense the nations of the world taking out their rage on each other. After that even the counties and cities that were very much destroyed (America, NYC) tended to have very current technology in terms of computers and cars and things, and thus the thirst for greater technology was overshadowed to whatever extent by the need to simply rebuild and expand and reproduce.

Nikolai asks Bart why he has gone into so much detail concerning the psychology of the past few decades. Bart replies with a quote by some philosopher/psychologist/historian/whatever, which is that all things human deny death when it is upon them. Nikolai asks what he means by this, but Bart will not elaborate. Nikolai falls into silence.

Bart says that, before he left, Christopher left the access code to a safe deposit box in a neighboring city ñ a box which contains something pertaining to an alleged rebellion within Agency's ranks. Nikolai asks what it is or how Christopher had become aware of its existence, but Bart says that Christopher never told them, and they will have to take him at his word It was simply all Christopher could tell him before he had to do what it was he had to do to save Nikolai (and try to save Rin). Because of how the cities are layed-out ñ how inefficiently Agency runs them, how crowded with people they are and the lack of attention payed to public transportation ñ the trip will take a full day or two. Nikolai asks if Bart is asking him to go to the city to get it, and Bart says that yes, he thinks Nikolai should. Bart also tells him that, at the same bank or a nearby one or some other type of safe-house is a box that was held in Rin's name, and now that he's dead it will be cleared out shortly if no one comes to claim its contents. Nikolai thinks for a while, some confusing thoughts running through his head, and then agrees to go.



*** CHAPTER 3: .723: Nikolai, NYC

Moonsign: only one fourth of the city Nikolai visits (the non-Agency bank) is covered in snow.

The lift-train ride is horrible. Nikolai feels as if everyone is staring at him, knows what he is, and hates him for it. He imagines tearing out their eyes so that they can't look at him any more ñ though in reality, he is ignored by everybody. He sweats, and fidgets. Finally it arrives at the proper city and he gets out. The air is somewhat cool against his face ñ it is mid-December and snowing, but the carefully and mechanically heated ground and buildings means that, for the most part, there is no snow on the ground, while Nikolai's totally thermal clothes keep him warm (thus his exposed skin is his only worry). Nevertheless, he occasionally and only semi-consciously fidgets and adjusts his clothing to be more comfortable. He wanders past a section of tall, modern Agency buildings into the city proper, which is less clean. There is a fair crowd ñ people talking on cell- or video-phones as they walk with specially-made earplugs so they don't walk into each other, and some business men with computer-visors over their eyes, perhaps riding cheesy scooter-things. Nikolai realizes that he doesn't know in which direction the bank is, and he DOES NOT WANT to enter any of the antiseptic Agency buildings. There are many people whom he could ask for directions, but the crowdedness of the place makes him uncomfortable so he simple walks for a while into (as before-stated) the city proper.

There is snow on some buildings and many parts of the ground. He goes into a sort of park area, where there is an old man on a bench (the only human in sight, aside from some dirty children who stare at him quietly with fearful eyes from the corners of buildings) tossing out birdseed ñ however, since most birds have migrated (a few staying because of the confusing weather), mostly only squirrels are at his feet. They scatter as Nikolai approaches. He asks the old man if he knows the way to the bank (the old man is surprised, not having seen him approach). The old man, who represents NYC, is bemused that Nikolai would talk to him at all. He asks why Nikolai does not use his PDA, or one of the disposable PDAs Agency gives out. Nikolai responds by saying that he can never seem to find his PDA when he has one, and he is bothered by the disposable ones because they are full of ads ñ the real reason, however, is that he does not want to be tracked or bugged. The old man seems to like Nikolai's reasons, saying he relates to them, and he's actually never had a PDA (which is quite rare), though people had tried to give him one before. Once he had tried to use one to go on the Internet, and it hadn't been ten minutes before he was overrun with holo-porno ads, and he didn't have the patience to learn how to control the thing delicately enough to avoid them. He points the direction of the bank out for Nikolai, who thanks him, and walks on, as the squirrels return to the old man and his birdseed.

As he passes an alley that goes between two abandoned buildings, with a fair about of snow in the alley, two or three of the children he saw earlier ask him shyly for money. They are wet from snow, though they do not seem to mind. Nikolai sees that they are a bit older than he assumed before; their appearance has been made more haggard because of attacks by various diseases. One of them, perhaps, has cancer, because he was never vaccinated. He asks, do I look like the sort of man who has money? They seem to think he does. He asks where their parents are, and they (one of them) say that they and their mother had run away from their father, but their mother had been killed because she was seen with a gun ñ a gun she had only picked up because she happened to find it moments earlier. The other boy says that he never knew who his parents were. Nikolai feels sorry for them and gives them three or four hundred-dollar small plastic cards of money ñ the equivalent of perhaps ten to fifteen dollars. The boy who takes him gets Nikolai's hand wet, and as they run off Nikolai wipes his hand on his jacket/coat/whatever. He sees some anti-Agency graffiti on the side of a building and is reminded that what he just did ñ giving money to the homeless ñ is a crime, and that he is in a sort of shady part of town anyway, so he hurries along into the next heavily-populated part of the city, which is an old part of the city, with little Agency control (relative to where he entered the city).

The three-quarter moon : of the four places Nikolai visits ñ the lift train depot, the park-area, the first bank and the second bank ñ only one of them is hidden by snow.

Anyway. Nikolai arrives at the bank, which is owned by a company with a name like Shakespeare Enterprises, or Washington or Lincoln or something. It is named after a person to reflect the fact that the whole city is human ñ perhaps some street corners or buildings are also named after people. It is the only major company that is not really under Agency control ñ that is, either A. it's under Agency control technically but not in practice or B. it is technically not under Agency control and in practice it only is if it is seen somehow as a threat. On second thought, that's the SECOND bank he arrives at (sic). This first one is Agency-controlled. Nikolai considers this briefly, in relation to the supposed rebel on whose behalf he is acting. He enters the building, and basically walks straight to the back (using the key-card and/or passcode he was given). He opens the appropriate box, or it is opened for him, and there is a small paper package inside, with something inside the size of a box of cigarettes (or half a cell phone, or whatever analogy of which I can think at such a time as becomes necessary so to do). He walks back out without opening it. He heads straight in the direction of the second bank but, while examining the package and wondering what might be inside of it, he doesn't notice (as he heads into another alley) the small gang beginning to surround him. Just as he reaches the alleyway he sees they are around him, and by then it is too late. He slows to a stop, and tenses slightly

The leader of the gang taunts Nikolai a bit. Nikolai, meanwhile, berates himself mentally, because he knew there were gangs that would do exactly this, wait for people to come out of the bank (presumably with money). As he considers if he could possibly defend himself against them, the leader, continuing to taunt him, tells him to hand over the package or else they'll take it from him by force ñ and as he says so, the gang members close in a bit and start pulling out weapons ñ knives, batons, short staves, steel knuckles, etc. The leader himself puts on a leather glove with short, stubby nails stuck onto the front (or possibly steel knuckles with nails). The infection tells Nikolai that they are scum for him to destroy, or something to that effect, which causes Nikolai to twitch slightly. The leader picks up on this and taunts Nikolai for it. Trying to decide what to do, a task made more difficult by the infection's thoughts, Nikolai is sickened by himself as the gang leader steps forward and he (Nikolai) simply hands him the envelope. The leader talks for a moment, wondering what such a man as Nikolai goes to a bank to get, while Nikolai thinks desperately for some plan, the infection causing him to stare at the man's throat and wonder if he could incapacitate the man if he hit it hard and fast enough. While he is bracing himself to move, however, the man tears the envelope open and drops into his hand a small black box, like a cell phone battery. He hands it to one of the other members, who claims it's just rubbish. He hands it back to the gang leader, who looks at it appraisingly and asks Nikolai (while perhaps not looking at Nikolai) what value this is to him. Nikolai tells him flatly that it has sentimental value. [note: perhaps the leader's name is Liam]. The leader then asks him if he has any money for them. Nikolai, very angry and tense now, and beginning to agree with the infection (that they are murderers, or at least Liam is, and there is no sin in killing a murderer, or something to that effect), fully planning to attack the man, glares straight at him and says no. Their eyes meet for a number of seconds while Nikolai fully expects a fight to break out, and is checked from attacking the man only by his consciousness of logic and of the duty he is attempting to fulfill. He continues staring at the leader, and the leader shows just as much resolve until right at the end, when there is a momentary flash of fright as he realizes how ready Nikolai is to kill him. He dismisses Nikolai as some idiot who wasn't wealthy enough to bother with (sic) ñ that is, he considers or says he considers Nikolai to be somehow below them, beneath them, not to be dealt with, that he has seen such people in his time or in his work (Liam, as a murderer, recognizes Nikolai properly). This includes an allusion to having been in his ìbusinessî for a great deal of time (at least relatively). He tosses the black object back to him (Nikolai catches it, which distracts him from any attack he might've made as they leave) and the gang move on, brushing just past him (just barely failing to touch him as they pass). Nikolai stands unmoving as they pass, still very tense. It is not until several seconds (like ten or so) after they are gone that he is able to calm down enough to continue. He first looks at the thing that was in the package, however, noting that it was angular, oblong, and looked entirely like nothing at all. He cannot identify what its purpose might be. He puts it in his pocket and continues towards the second bank, this time more aware of those around him.

He reaches the other bank, which is described above; part of Shakespeare Enterprises or whatever. Hardly matters. He finds Rin's box ñ both he and the staff and friendlier to each other than either were at the first bank ñ and opens it with a key. Inside is a sword ñ a smallsword (court sword), old, well-made, in good condition, with a sheath made to be attached to the belt. With it is a note in Rin's hand(writing) that reads something like: ìTo whomever takes this: I have carried this weapon with me the greater part of my life, and it has never aided me. May it serve you better.î Something like that, ish. At least an allusion to not being useful, not necessarily this direct. Nikolai thinks about it for a moment, wondering, Why carry a sword? The infection thinks, What is a werewolf without its claw/teeth/tooth/bite/whatever? Nikolai walks out of the bank. When he's outside, as the sun is going down, he puts on the sword. He walks back to the train station, this time unimpeded.



*** CHAPTER 4: .625: Nikolai, Deamia, Jacob, Bartholomew

Moonsign: something about bar. They are in one third of it, perhaps?

Nikolai is meeting the others in the lower or back room of a bar ñ someplace not exactly unsuspicious, but someplace that is in itself, safe. When he gets there Bart is the only one who's arrived. Bart's first comment is about the sword; Nikolai tells him that it was what he found in Rin's box. At this Bart remembers Rin having the sword, how he found it by coincidence and carried it around occasionally (but never used it). Nikolai pulls out the device and begins to describe his finding it, but Bart immediately makes him stay quiet; Nikolai realizes that this is because it could be a bug. He chastises himself for not having realized this, and he and Bart talk about a totally fake subject until Deamia and Jacob arrive. Interrupting them before they can speak with an obvious lie (calling them by false names), Bart motions to the device Nikolai is holding. Deamia takes out a device that will decipher and (if she so wishes) block any sort of signal the thing may be sending. Once it begins working, Bart asks if it was sending anything. Deamia says that it was/is (Nikolai tenses), but that it's A. too weak to be read from more than perhaps a few hundred feet away and B. it's regular, i.e., it's not sending their voices. Nikolai is relieved. Deamia and Nikolai are introduced to each other (they are meeting for the first time). Bart says something about Deamia's history while, perhaps, Jacob mentions her abilities with computers. They confirm the device is the thing found in the safety deposit box, and Deamia takes it over to a counter or whatever in the bar and examines it, leaving the guys to themselves.

Jacob notices the sword, now, that it was the one Rin found. When Nikolai asks him what he means by this, Jacob (Troy?) describes the mission he and Rin went out on a few years before, where Rin found the sword. He said they got an anonymous tip from some imagined rebellion within Agency, and that to meet the informant they went out to some alley behind a factory. Waiting there, however, they found nothing except the sword (apparently tossed, with its sheath, onto the ground at random), and they had to leave quickly because there were Sentinels searching the area. Jacob says he hopes this tip is a bit more useful than that one was.

Deamia now identifies the device as a high-frequency vibrator, and says she cannot think of what its use might be. Nikolai asks if it would be strong enough to be used as a communications device, but Deamia says that since the range would be severely limited and they cannot change the frequency, she can hardly see how. Somewhat disheartened by this not-too-exciting proceeding, they continue on; Bart asks Deamia about the acid/virus/whatsit (nanobots?) that she put on the sentry robots; Deamia gives the surprising answer that they have all been rendered incapable of their intended functions by it. She says that, on this note, this will allow her to go to the outskirts, something she has been needing to do; but, she wonders if someone could escort her, to be safe ñ she says while looking at Jacob. Jacob, however, says dismissively that he has business that must be attended to, unfortunately. Either Bart or Nikolai at this point suggest the latter escorting her (Bart as a command or firm suggestion, Nikolai for the sake of being around her, or for something to do), and in either case Deamia silently looks to either Bart or Jacob ñ probably both, in the reverse order ñ to see if they approve, that is, if Nikolai is safe to guard her, and she gets the affirmative. Looking somewhat relieved, she tells Nikolai that the best time would be four nights from now, for a blah blah blah reason, and to expect to be get back two mornings after. Nikolai nods vaguely, and agrees.



*** CHAPTER 5: .199-.114/.049: Nikolai, Deamia, maybe Tommy?

Moonsign: ?
** characters
Nikolai Danilov
The poetic narrator of his own tragedy
	"What is a wolf without its teeth?"

Lauren Deamia Green
Young and poetic.
	"

Caroline Danilov
The bride.
	Deceased.

Christopher.
The savior.
	Temporally deceased.

Darwin.
The martyr.
	Deceased.

Markku Gairden
The life old and wasted; even sadness has gone.
	""

Bartholomew
Wisdom of the elder. The pastor.
	""

Randolf
Idealistic and brave. The warrior and man of God.
	Randolf does not need to ask. Perhaps Bartholomew doesn't, either.

Broderick Danilov
Nikolai's brother, who did not know him.
	"I don't know."

Kellan Logan
Nikolai's mortal foe.
	"For killing."

Tommy
A child who fancies himself an adult; probably superfluous.
	""
The city
The community of sinners.
	""
The demon
Sin.
	""
** names and meanings
+ Nikolai Danilov
+ Broderick/Brody Danilov
+ Bart(holomew) Stillman
+ Lauren Deamia Green
+ Tommy
+ Darwin
+ Markku
+ Randolf

.

OLD:

Danila God is my judge

Kirill Master

Danilov

Kirillov

+ Bartholomew  (Disciple), Philip (Disciple),  Stillman (fisher)
+ Kellan (power) Logan (?) or Prata (silver)
+ Deamia Lauren (laurel)/Alanna (young child) Green
+ Tommy (twin)
+ Rin (companion) or Darwin (dear friend)
+ Markku (rebel)
+ Nikolai (victory of the people) and Broderick (brother) Ilyavich (the Lord is my God) or *Mikhailovich (who is like the Lord?) or Danilov
+ Simon (disciple w/ sword) or Peter (likewise) Alders (defender?) or Alderson (likewise)
+ Christopher (Christ-bearer)
** moon percentages by day
(dates used: June 18 - July 17, 2008)


1	.995
2	.976
3	.938
4	.882
5	.810
6	.723
7	.625
8	.519
9	.409
10	.300
11	.199
12	.114
13	.049
14	.010
15	.001
16	.020
17	.066
18	.133
19	.215
20	.308
21	.406
22	.505
23	.602
24	.694
25	.778
26	.851
27	.912
28	.959
29	.988
30	.999
** notes
"It's not right" matched with "nothing's right." or "It's unjust" matched with "What? To kill a criminal and a demon?" so on. This next one breaks the pattern.

"We're brothers!"

"All men are brothers."

"Your name is Danilov! My name is Danilov! We have the same father!"

.

Note: Mr. W. H, the alchemist, the genie, the prestidigitator or illusionist, the magician, the god, the devil, the angel or demon, lost oneironaut, the fifth immortal, one of Pharoh’s magicians. Genie grants three wishes, no death or life or love. Alchemist, command elements of water, fire, earth and air. Immortal, given secret of death by the second immortal, Hyradaga or whoever. Nth tale of the princess Scheherezade. God, angel, archangel, fallen angel, demon, legion, Sorcerer, alien, mutant, machine, conductor of certain natural forces. "Perhaps I am Mr. W. H."

At new moon, Nikolai visibly forces his way into the factory.

I am Pharoh's magician, the lost oneirenaut, the elementalist, the alchemist, the sorcerer, the immortal, the god, the angel, the demon, the devil, the dream, the genie, the djinn, the spirit, the creator.

You, a sinner, do not know what a terror it is to live among sinners! You do not know what a special horror it is to tread among men! In the ancient places of the Earth I saw the evils of man, and I see them again, reflected in this younger place like a pool of black oil in pale sunlight. One of us is the Beast, Nikolai, and it must not be me.

Blood pounded in Nic's ears as he rolled onto his stomach and pushed himself to his knees, and when he could hear again, the first thing he heard was Randolf saying, "You son of a bitch. You son of a bitch." Nicholai was trying to rise, but it felt as though his throat had closed and refused to open.

.

WEREWOLF NAMES
conriocht, faoladh
vurdalak, oboroten
lycan, lycanthrope
skinshifter, shapeshifter, etc.

Wolves in the Bible? With antithesis, same-book or same-verse-number passage? (For line such as... "There are 76 of them. No wait, 42." or "Romans! No, more like Ephesians..." Better disguised than that, obviously, but yeah.)

.

MAGIC:

So, the werewolf curse, and Kellan's thing, are both magic. They come and go in moon cycles. I THINK that the moon blocks magic, but it might enable it.

IF MOON BLOCKS: Then God set the moon in place long after the creation of the initially ungoverned night. The werewolf comes when there is no moon. The moon may be associated with science. The moon may contain a substance which, with the sun's light, blocks magical energy.

IF THE MOON ENABLES: Then God set the moon in place with the creation of the sun, but in the first Flood-analog, he modified the orbit of the moon. The werewolf comes with the moon. Science will be the light that is made in place of the moon. The moon may contain a substance which, with the sun's light, enables magical energy. In this case, I'm not sure exactly how magic works out in the deep of space.
** scraps
[An enormous wave of nasuea rose up around Nikolai and crashed upon him. He doubled over. While the other man moved behind him and prevented him from falling, Nikolai's body was struck by a blinding pain. The muscles of his throat contracted so hard he was unable even to wretch. But the nausea and the pain lasted only seconds, ]

.

.

... thoughts wandered to himself and his pains, and what he might do about them. 

The mention of Darwin made Nikolai's own eyes sting. His own death, imminent though it seemed to him, was theoretical and easier to contemplate [an erasure of the world? an end to all pains?]. The thought of his friend, gone, was hard and actual. It was a blow to the stomach, and it robbed Nikolai of breath.

.

.

A thing made of flesh and bone, Nikolai said to himself, finding his footing again. A thing with hair. A thing with a heart and a brain that will stop if you drain its blood and smash its head. Nikolai summoned to his mind the images of carcasses he had seen at various times in his life - a cow he had witnessed slaughtered and butchered, a cousin's old pet dog taken into the woods to be put to sleep, a sun-dried raccoon with no head on the side of the road - and he said, "Move aside!"
	
"What reason do I have to obey you?

"Obey your flesh!" It occured to Nikolai that he had once determined never to reason with the dead. He pushed the thought aside. "Obey the laws that tie this universe together! Obey God!"

"Foolish man. Have you not been shown already that my ways are not your ways? God does not command me."
	
"If my mind has any strength, it will endure at least as long as my body. I suppose that I've bled too much. I am going to lie down now, and you must leave me alone to do it."

As a dog tilts its head in a pantomime of understanding, the beast tilted its head and peered deep into Nikolai's eyes, deep into his head.

"Came in darkness the wolf in man's clothing, and he turned his eyes first to the deep sands, and then to his own navel."
	
Nikolai noted that its blood was not red but black literally like pitch.

.

.

“Foul thing,” said Nikolai, and he stepped into the beast. It dissipated like vapor, but appeared again some steps up.

“Wretched thing,” he said, and stepped into it again. Again it shifted positions.

“Damned thing! I renounce you!”

“That is not your decision to make,” said the apparition

.

.

But even as he looked, the beast shook itself and the head reformed, the arm grew back like water filling into a crevice. 

.

.

It was Randolf.

“Nikolai! Nikolai!”

Nikolai lifted his head with a great struggle. “Werewolf,” he managed to say, his voice little more than breath.

“What?”

“Werewolf.” He felt that if he did not tell Randolf now, he would never have the courage to do so.

“In the factory?”

“Yes.” Nikolai fought against the ground beneath him, and managed a kneeling position. “It killed him, it killed Rin.”

Randolf said nothing, but his eyes were of sorrow.

Eventually he asked, “Did it bite you?”

The word was blood and foul ash in Nikolai’s mouth: “Yes.”

“Your arm? Is that what happened to your arm?”

“The machines,” said Nikolai, feeling a need to explain and not knowing how. “The machines, they still run. I don’t know why. One of them had a blade. It kept coming down on the metal. I felt my arm. . . I saw where the blade came down, and I put my arm there, and I looked away.” He stopped to sniff. “I should’ve bit on something.”

Still crouched at his side, Randolf looked at Nikolai, at the broken wreck in front of him. There are few times when a man may be as weak, as vulnerable and as pitiable as Nikolai was, bleeding and crying into the snow, not dead but perhaps wishing it. Randolf knew this, and he had the respect to remain silent. He put his hand on Nikolai’s shoulder, and Nikolai held it with his left hand, and after a long time he was able to control his shuddering.

“Can you walk?” said Randolf.

“Yes.” Nikolai wiped his face with his sleeve.

“Do you need any help?”

“No.” He put his weight on his legs and stumbled, and Randolf held him under his left shoulder and helped him walk.

“What were you saying, on the stairs?” said Randolf.

“What?”

Randolf hesitated. “Never mind.”

Nikolai didn’t see the demon, and he did not look around for it.

“I wasn’t talking to anyone,” he said.

Randolf was silent then, and Nikolai also, and he kept his head down, away from the light of the moon.
** three outlines
*** 1
(?)	<?>Christopher dies.
1	<Night> Nikolai is infected. Rin dies.{a}
2	<Mid-night> Nikolai gets prosthetic arm with Randolf's help.{b}
3	
4	
5	<Afternoon> Nikolai talks to Bart, is told Christopher's sacrifice.{c}
6	Nikolai goes to a bank and gets Markku's signaler & Rin's sword from a safety deposit box.{d}
7	Nikolai returns to his home/Requiar base/wherever. He shows the others the device, which Deamia
	identifies. They talk about how Christopher knew where to find the device (he met Markku in a context
	where they had to, well, act natural), and about the factory, if what was in it had any significance.
	Bart or one of the others comments on Nikolai's sword, that Rin found it by accident during a mission
	a while back due to some other supposed rebellion within Agency (which was actually Markku, as well).
	Since, unfortunately, Christopher told them nothing else about the signaler/rebellion, they have no
	choice but to do, for the moment, nothing.
8	
9	
10	
11	<Morning?> Nikolai sets out with Deamia on a mission, on a train (?), to a place outside of the city.
	{z}
12	<Morning?> Nikolai and Deamia arrive at the outskirts, which is mostly wastelands/ghostlands, though
	much of it (that is, that which isn't irradiated) is inhabited by a group of outcasts, illegals or
	moneyless. There are also Requiars there. Deamia is there to do tech support, basically (the reason
	she was willing to go so far was because of the connection she had to the Requiars there; they gave
	her books, or something).
13	<Afternoon> Nikolai and Deamia return on the train. Nikolai attacks Deamia, but is stopped by the appearance of Randolf.{x}
14	
15	<Midday> Nikolai retrieves ring.
16	
17	<Afternoon> Nikolai meets Markku - by chance then by (subtle) appointment. She tells him about Director
	Logan, and his son, and about Agency, and about their experiments and stuff. She promises to help him
	get in to an Agency base. She sees his sword, but too briefly to see that it's the one she purposefully
	dropped, before, and she doesn't guess because she doesn't learn that Nikolai knew Christopher and
	knows Bartholomew - because, as she says, the less she knows about the Requiars, the better.{x}
18	<Early morning> Nikolai talks with Randolf about his meeting with Markku (they determine to trust her,
	and that the best time to go is in eight days).{z} Suddenly, Nikolai stopped by some police, who have
	been told to seize people with a missing/prosthetic right arm (Randolf walks on and acts as if he does
	not know him, so he will not risk capture). The reason for this is that Kellan, who personally visits
	the old factory, found the dead werewolf and the severed arm. They would question him there, but the
	fact that he was acting suspicious (in a bad part of town, whatever) make them, uh, suspicious of him,
	so they drive him to the nearest police interrogator, who is at the bank Nikolai originally visited to
	get Markku's signaler (technically such interrogations should be done at an Agency base, but they
	slack on the rules a bit), in a back room (there were two policemen who picked him up, plus the
	interrogator). They talk to him for a while, but the infection's presence in Nikolai's body and mind
	prevent his body from acting normally, and they are unable to tell that he's lying. They suggest doing
	a DNA check, however (which would immediately prove Nikolai to be lying), and Nikolai and Randolf end
	up killing all three. They leave the city separately. OR that all happens tomorrow.
19	
20	
21	
22	
23	
24	
25
26	
27	Nikolai discusses the plan at the Requiar base: He is to enter the city unobtrusively, while Randolf
	sneaks in to give him the keycard he stole. Randolf will not be the one to enter because Markku does not
	know him, and Nikolai will not steal the card because he is not able to go through a DNA test.
28	<Early morning> Randolf (the invisible) gives Nikolai Markku's keycard. <Noon> Nikolai, while waiting,
	experiences *something* to do with Kellan. He lays low for the night, preparing for the next day.{e}
29	<Morning> Nikolai meets Broderick.{d} <Nikolai stays away from Requiars for fear of being followed.
	Broods over the fact that what Markku told him turned out not to be true - he found no mysterious
	Director or science experiments or anything of that nature. Perhraps at a bar?> <Nikolai has sudden
	insight concerning the factory, realizing that what Broderick said implies that	"Director Logan" is
	at the factory right now. He goes there quickly. <Afternoon> Nikolai fights Minion and meets Kellan.{c}
30	<Early morning> Nikolai talks to Deamia.{b} <Mid-night> Nikolai & Kellan die.{a}


*** 2
(?)
1	.995
Darwin dies. Nikolai is bitten. Randolf finds him at factory.
2	.976
Nikolai gets prosthetic arm with Randolf's help.
3	.938	
4	.882	
5	.810
Nikolai talks to Bart. Bart tells him about Christopher.
6	.723
Chapter three begins and ends. Nikolai retrieves Markku's signaler and Christopher's sword.
Nikolai asks. (when he gets it. "What is a Werewolf without its...?")
7	.625
Chapter four begins and ends. Nikolai meets the others at a bar(?).
Bart asks. (at the bar. "It was in Rin's box.")
8	.519
9	.409
10	.300		
11	.199
Nikolai and Deamia leave on train.				
12	.114
Nikolai and Deamia reach outskirts.
Requiars ask. (Deamia's friends. "A friend gave it to me.")
13	.049
Nikolai and Deamia return and part ways.
Deamia asks. Death of burgeoning friendship. (return from outskirts. "It was Rin's..." etc.)
14	.010
15	.001
Nikolai retrieves ring.						
16	.020													
17	.066
Nikolai meets Markku.
Markku asks. (only meeting. "A friend gave it to me.")
18	.133
Nikolai talks to Randolf, is taken by Agency.
Randolf doesn't need to ask. Agency asks. (interrogation. "It's a dangerous world out there.")
19	.215
20	.308
21	.406
22	.505
23	.602	
24	.694	
25	.778														
26	.851														
27	.912
Nikolai meets the others at a bar(?).			
28	.959
Nikolai enters NYC, prepares to enter Agency building.
29	.988
Nikolai meets Broderick, later goes to factory, etc.
Broderick asks. (only meeting. "I don't know.") NYC asks. (at the bar. "Because I am weak.")
30	.999
Nikolai talks to Deamia. Nikolai and Kellan die.
Kellan asks. (second meeting. "For killing.")





*** 3
C-1
Nikolai lives and loves Caroline. He is a 

C0
Nikolai and Darwin 

C1
Nikolai is bitten, meets up with Randolf, gets new arm.														
C2
Nikolai talks with Bart, Bart tells him about Rin.

C3
Nikolai goes to both banks, gets signaler and sword.

C4
Nikolai goes to bar to meet others.

C5
Nikolai and Deamia go to outskirts.

C6
Nikolai and Deamia return from outskirts.

C7
Nikolai retrieves ring.

C8
Nikolai talks with Randolf, is taken by police.

C9
Nikolai meets others at a bar.			

C10
Nikolai enters city, meets Broderick.

C11
Nikolai visits bar, then factory.

C12
Nikolai speaks with Deamia.

C13
Nikolai returns to factory, he and Kellan die.
Old chapter 1 things, and elsewise
** draft -1
There was a stone staircase, and on the staircase was Nikolai. There was snow on his shoulders, and the darkness of the night sky in his eyes, and the coldness of the air throughout his body; he walked up the stone staircase, and demons walked around him.

They flitted in and out of view, just there, not quite clear enough to focus on. Nikolai saw them in the shadows of the steps and heard them in the sound of the snow beneath his feet, and he felt them in his numb left hand, gripping the hand-rail.

The demons spoke,

(We are without number,)

And then,

(We are all.)

Nikolai closed his eyes to make the demons go away. His mind was reeling. He had stepped out of the factory, pushing aside the heavy iron door, and the cold air had knocked both the breath and the thought from him. When he opened his eyes, there was only one demon, standing before him.

“Stay away from me!”

The demon changed, moved. It flowed around Nikolai, and through him.

“Stay away from me!”

The demon was at Nikolai’s side, its hand at his throat; and its hand was fire.

(We are as a circle, without end,) said the demon.

“You are a trick of the night!” shouted Nikolai, and he passed his hand through the empty air near his neck.

(We inhabit one flesh,) breathed the demon from behind him.

Nikolai spun to face the falling snow.

“You are nothing! You are nothing, damn you! Get away from me! You are nothing! You don’t exist!”

(We are you,) said the demon, from within.

Nikolai screamed and tore at himself. He beat his fist against the wall, and stared into the sky. The moon shone at him and burnt his eyes, but he could not look away.

“Murderer!” Nikolai gasped, his breathing heavy and almost beyond his control. “You killed Rin!”

The demon said nothing, but breathed.

“You killed him. . . ” Nikolai fell to his knees, and cold tears ran between his cheeks and his nose. He cried out in bitter sorrow and physical pain. He felt the demon’s presence in his body.

“Why? Why did you have to kill him?”

Nikolai received no answer. He was, of course, alone.

“Why did you have to kill me?”

(You are not dead. You will never die.)

Nikolai raised his head, turned his eyes, but there was nothing to see. There was only the snow and stone steps and the trail of blood behind him.

“Why me?” said Nikolai. “Why me? Why are you here? Why do I see you? Why are you here? Why are you with me? Why?” His jaw shook with the words.

(You were bitten,) said the demon.

Of course he was bitten! Was there any world, any reality apart from that? How long had it stood there, Nikolai wondered. He had been hiding, yes, hiding in the factory, with Darwin. Crouched behind a box, he was not aware of those black eyes so close to his. Of course it had bitten him!

“It bit my arm!” said Nikolai, to the demon. “It bit my arm! But I did right, didn’t I?”

His arm had burned, when it was bitten.

“I cut it off! I GAVE YOU MY ARM!”

Nikolai moved his right shoulder, and the length of his right arm, which was perhaps two inches. It was bleeding freely.

His whole body burned, now.

The demon spoke: (You were too late. The venom travels quickly.)

And it laughed, and Nikolai screamed. After some time he quieted, and he climbed the rest of the stairs as in a trance.

The staircase, cut into the ground and leading from the basement of the factory, ended at street level. His legs were weak, he did not feel his hand, and his head felt split with pain. He looked across the street in front of him, and to either side, but he could see nothing apart from gray snow. The stars, too, might have been snowflakes, and the moon was a great eye, watching him. He was weak from loss of blood.

“I am going to die here,” said Nikolai. “I am going to die here, like Rin.”

(No,) said the demon. (You will live. We will live. And we will rise.)

Nikolai fell again to the earth, to the cold, inviting snow. He lay there for some time, and then he cried in earnest, for there was a man calling his name, and he knew, now, that he was not in a dream.

** draft -2
Chapter 1: Fall

Breathing hard, Nikolai leaned against the elevator's railing. Beside him, Darwin was panting, looking over the edge of the steadily rising platform. The thing was still down there, pounding on the door, the heavy iron lock shuddering with each blow. It would not hold for long. Very soon they would have to be running again.

"A minute," said Darwin, his eyes fixed on the door below them. "At the most."
Nikolai was silent. His heart was pounding painfully from somewhere in his chest, and his hands were clenched on the railing of the elevator, a feeble attempt at solidity. Calm. Calm, he said to himself so forcefully he wondered if he was defeating the word's meaning. He was trying to think logically, but images of the thing behind that door and of what it could do to him or Darwin were flooding his mind, leaving little room for anything else.

"You okay?"

Nikolai glanced up. Darwin was looking at him. He looked as tired as Nikolai felt, but the concert was evident in his face. The elevator continued to rattle as it ascended.

Nikolai sighed heavily and shook his head. It was more of a gesture of his weariness than an answer to the question. They had been running for what seemed like hours, though he wasn't completely sure that it hadn't been. He wiped his forehead with his sleeve and felt sweat through his shirt. The door below them continued to rattle, the sound washing over them like waves breaking on stone in the relative silence.

The elevator shuddered to a halt. Darwin started out of it but Nikolai put a hand on his arm. He turned, and Nikolai pressed a gun into his hand. Darwin looked at it. Beneath them the door crashed to the ground, and the creature's howl filled the air, reaching to the farthest corners of the building. Darwin stared fixedly at Nikolai for a moment, then stepped off the elevator. Nikolai followed him.

At a platform connecting different areas of the factory together they stopped. They would have to split up. The Code. Follow the Code. Nikolai looked at his companion and gave him a quick nod. Darwin hesitated for a fraction of a second before returning it. Wordlessly he sped off down one of the catwalks.

Nikolai ran down the winding catwalks, checking over his shoulder every few minutes, ducking behind any machinery he could find. Every step echoed a thousand times over before it was swallowed up by the backdrop of machinery, seeming to his ears to point him out directly. He tried to keep his breathing under control, but every breath was an icy spike in his chest.

There had to be something he could do. To escape- no, to help Darwin. Something to help him, then escape. The Code. He shook his head angrily.  He couldn't recall where any of the other exits from the building were, or even if there were any.

...

"What's wrong? Why weren't they there?"

Darwin brushed past him, fire in his eyes.

"He set us up." he said through gritted teeth, checking the computer again.

"What? Who-"

"Who do you think?" Darwin shouted, rounding on him. "Broderick!"

Nikolai went cold. A quiet buzzing had started at the edge of his hearing.

"He. . . he went around to the back to scout. . ."

"He's gone." Darwin said with forced passiveness, turning back to the laptop. He stared at the screen a moment longer. "And," he growled, flipping it closed, "the entrance is closed. We're trapped."

Nikolai looked at him for a moment, then shook his head as if to clear away the situation. Broderick was gone - had betrayed them. 

Broderick. Broderick. He realized suddenly that he was gripping the handgun in his jacket, his knuckles turning white. He released it carefully.

Abruptly the high lights went out, jolting his attention back to where they were. Where he was.

"What about the vents?" he asked, not bothering to turn to where he knew Darwin stood.

Darwin snapped back into his role. Into duty. "Closed, during lockdown."

"Maintenance entrance?"

"No. Ten to twenty Sentinels standing guard."

Something flickered across Nikolai's eye. Broderick.

"Let's hope for ten, then."

...

Nikolai shook his head to clear the buzzing from the edges of his hearing. Always that damn buzzing.

He opened his eyes, suddenly remembering where he was. Focus!

He had to escape. If Darwin remember the Code. You cannot endanger yourself for him. Standing up, he looked around. He had no idea where an exit would be. With no better alternative in sight, he headed towards the source of most of the factory's sound. If nothing else, I can wait it out. Even as he thought it he knew he didn't believe it.

As he made his way carefully from platform to platform, he tried to run through everything he knew about this building, this factory. 

His prison. Hero's Lament. That's what this place was called. It had existed for as long as anyone could remember, and its purpose unknown for as long. Possibly since the early days after Shadowfall. Machinery was everywhere, both active and inactive, the obsolete left to gather dust where it was discarded. Hydraulic pistons shot, empty conveyor belts ran, large blades came together with sharp clangs. Nikolai couldn't tell what any of it was for.

A gunshot rang from somewhere behind him, and he stopped dead. Another followed it. Then, the sound of a scream, and something crashing to the floor.

Nikolai started running again, every step a reminder of what he was leaving behind.

...

Wordlessly Darwin flipped the computer open again and brought up some schematics. Nikolai realized he was whistling Ride of the Valkyries and stopped.

“Ok. . ." Darwin said, scrolling through windows, "looks like it makes no difference whatsoever when we go."

Nikolai rolled his head around his neck for a bit, stretching the muscles.

"Free will. Gotta love it." He cracked his knuckles. "If you'd be so kind. . ."

Darwin looked at him out of the corner of his eye, as if asking for confirmation, then pressed a small orange button on the side of the laptop. Immediately it began to smoke as its circuitry was melted from the inside. Nikolai opened the door and stuck his head out to check the hallway. A few seconds later they were walking quickly down it, Darwin shrugging into his jacket and checking the knives fastened to the insides of his sleeves. Their steps echoed dully on the uneven tiles. Nikolai's eyes slid from the decrepit wallpaper to the rusty door they were heading towards. He couldn't understand why Agency was using this old shell of a building as a base of operations. The fact that they were putting so much effort into keeping it unknown made him uneasy. Agency never did anything without a good reason.

They reached the door and Nikolai pressed his ear against it. All he could hear were the sounds of distant machinery vibrating through the building's structure.

"You ready for this?" Darwin said, nodding at the door.

"What?" asked Nikolai. "Facing ten to twenty Sentinels on open ground? Escaping an Agency stronghold? Whatever punishment the we'll get from the Reqs for failing our objective?"

"No, dying." The smallest grin was on Darwin's face.

"Oh. Well." He shrugged, not really knowing what to say. "I've been trying not to think about it."

Darwin smiled for another second, then shook his head. When he looked at Nikolai again, the smile was gone, as if it had never been there. Nikolai took his handgun out, gripping it tightly. Darwin mouthed the words one, two. . .

Simultaneously they spun and kicked the door open. The room was large, dark, and empty. Nikolai looked quickly from the peeling drywall on the left to the pile of boxes in the middle of the floor. He dashed over   ãto them and skidded to his knees, crouching with his back to them. He looked over to the corner where Darwin had flattened himself against the wall, in the shadows. Nikolai motioned to him, pointing at the corner across from Darwin, then turned around, rising slightly, bracing his gun on the boxes.

"Clear!" shouted Darwin, striding over to him, eyes still flitting around the room.

They went through room after room like this, each time finding nobody. It didn't make any sense. Agency knew that they were here, Broderick had made sure of that. As they reached the final door, Nikolai was practically shaking with apprehensiveness. They kicked in a door to reveal a starry, snow-filled night. The cold air sank into their skin in seconds. The full moon cast pale shadows over what looked like it had once been a parking lot, half-demolished walls and ancient machinery looming menacingly in the darkness. There was no one.

"This doesn't make any sense. They know we're here. Where are they?" Nikolai was looking carefully around the wreckage, waiting for a glint of silver metal, or the flash of a flashlight.

Darwin started to reply but was cut off by a long, echoing roar from the building they had just left. Nikolai jerked his head around, the blood draining from his face. "No* they wouldn't. . ."

"They- Broderick knows us. . ." Darwin's voice had lost all of its cool confidence from the minute before. "They'll know there's no way we could stop it. . ."

"But they could as easily send two dozen Sentinels why would they*"

"I don't know!" Darwin shouted, his calm entirely vanished. "But obviously they have. We have to run. Now."

"They'll have blocked the roads".

"I know. Maybe we can hide back in there. . ." Darwin said, turning slightly to the building.

"Suicide. It's too quiet. And there's no way to hold it off."

Silence. Then another roar.

Nikolai shook his head angrily. "This is useless. We can escape it in the factory." After a moment he added, "if we're  lucky."

Again, the roar. Closer. Already so much closer.

"How will we*" Darwin began.

"Now. We have to go now."

They ran.

...

Nikolai discovered he had stood up without thinking, and crouched back down again hastily. It was several seconds before he realized he was crying. He clenched his teeth and wiped his eyes with his sleeve, but the tears wouldn't stop. Darwin.
Around him were the remains of a dozen generations of mechanics, most of it disabled or dismantled, but some still moving; conveyor belts rattled along with nothing on them, towards large blades clanging together periodically, making the platform vibrate in a steady rhythm. None of it seemed to have any rational purpose; it was as if the failed attempts of centuries of mechanical engineering had been brought together in one place, into some sort of ghost town of machines. The fact that much of it still had power was something Nikolai didn't know what to make of.

Wearily he picked up what appeared to be a complex disk  organizer and blew some dust off of it. Stamped on the bottom of it in small, red letters was "CDP513-008". On the top was a large letter A overlapping a letter X. The old logo of Agency. He picked up a bent metal plate with screw holes on each corner. "CDP514-060". The same thing, or something similar, seemed to be stamped on most of what was around him. He couldn't think if he knew what CDP stood for. 

Werewolf.

It was standing there, at the top of the stairs leading up to the floor. Watching him. Breathing. Nikolai had gone rigid. The buzzing in his ears had increased dramatically. Numbly, Nikolai felt behind himself for something, anything. He hand closed on a long steel rod. 
Trying not to lose his balance, he stood up, slowly, steadily.

Suddenly the werewolf roared at him, rendering everything else silent. Letting go of his concentration Nikolai stepped forward and swung the rod at the thing with all his might. The werewolf caught the rod and pulled it out of his hands, jerking  Nikolai off his feet, and hit him in the face with one of its claws. Nikolai screamed as he fell to the ground, pain flooding his head. He rolled over in time to see one of the werewolf's arms darting at him, and he stopped it with his own. The werewolf roared again, and brought its head down to fasten its jaws over his left arm. Nikolai screamed again as his vision blurred, his mind blanked. Desperately he felt around with his right hand until he felt the throwing knife that had fallen out of his back pocket. He gripped it tightly, its small handle digging into his fingers. Through tears and blood he could just make out the werewolf's face. It had released his arm and was staring at him, almost smiling, its head mere inches from his own. With a burst of fury Nikolai swung his right arm, and stabbed the knife into the thing's eye.

The werewolf let out a terrible shriek and released him immediately. As Nikolai scrambled away it stumbled blindly backwards. Now screamed something in Nikolai's head, and he ran forward, hitting the werewolf in the middle of the chest with his right shoulder. The beast lost its balanced and fell backwards, into the railing; the feeble metal bar gave way under the weight, and the werewolf fell. For a few seconds all that could be heard were its howls and shrieks as it fell through the empty air, then a loud thump. . . and silence.

Nikolai just stood there, shuddering. Trying to take in what happened. His left arm was twitching. Abruptly it flared into white-hot pain as something seemed to grip it from within. He could feel it, the werewolf's venom, in his arm, spreading through him, slowly. 
Slowly, but surely. His arm began to shake uncontrollably, and he staggered over to the edge of the platform, next to the blades. Clang. 

He couldn't think. A mist had gathered around the edges of his vision, obscuring proper sight. Clang. His body was going numb. His arm felt like it was on fire, a fire that was infecting him, the rest of his body.

The blades seemed to be getting louder and louder. He stared at his arm, letting the sound wash over him. Clang. Clang. Clang. He closed his eyes, took one long breath. . . and put his arm into the blades.

...

Nikolai staggered out of the factory several minutes - or was it hours? later. He felt like he was walking through a dream. Holding on to the hand railing with his right hand he made his way up half of the stairs leading down to the entrance before his strength failed and he fell heavily to the ground. He rolled over, eyes closed, pain racking his body and mind  ç. Dust had gotten into the cuts on his face and blood was flowing freely from the place where his left arm had been. Each heartbeat brought with it a hammering of agony. He couldn't move, couldn't think. Straining, he opened his eyes and looked into the sky;

He couldn't see any stars. The mist at the edges of his vision had blocked most of his sight. With his last remaining strength he turned his head and looked into the full moon. Its presence burned into his mind like a branding iron - and he felt something else, too, another entity in his head.

I am going to die here. I am going to die here, like Darwin.

No. . . said the Other, the alien in his mind. You will live. We will live. And we will rise.

Nikolai faded off into dream.

...

Chapter 2: Beta York

A low hum.

Damn humming, though Nikolai, staring at the backs of his eyelids. The light passed over him, again, again. It was very dreamlike, the shifting of the lights, the pitch of the humming wavering slowly. How long was it? An hour? Two hours? Time meant little in here, in the lights.

"APS at seventy-four percent, fifty-one percent above minimum. Outer casing integrity at ninety-eight percent, repair unneeded. Inner frame integrity at seventy percent horizontal, ninety-five percent vertical. Inner circuitry integrity at eighty-two percent. . ."
Nikolai didn't pay very much attention. He didn't open his eyes, either, even though the lights were gone. The humming, too, had gone, but he thought he could still hear it, somehow.

Humming. . .

The next time he opened his eyes, it seemed, he was outside. There were times when hours or entire days would seem to slip past him if he wasn't careful, if he closed his eyes for too long. He turned his head to look at the clouds, and a light breeze brushed his cheek. 

He shivered, and scratched his left arm.

". . . Current temperature is ten degrees Celsius, fifty degrees Fahrenheit. Time is nineteen-thirty-seven. The day is Wednesday, the twelfth. The next scheduled gun drop-off is on the thirteenth. Citizens are reminded that any working gun carries a bounty of five thousand dollars. Citizens carrying guns outside of a designated drop-off point will be arrested and sentenced to life imprisonment. 

Citizens wielding guns outside of a designated drop-off point will be terminated on sight. . ."

The sound passed over Nikolai the way it might over a brick wall, and he showed as little emotion. He could've recited most of it without trying. Anyone could. They played the tapes again and again and again, every day¹, until it was nothing but another piece of the background, as normal as the drone of a nearby factory, or the incessant wind. It seemed to him that the wind had gotten worse in recent years, and especially in the past few months, though he couldn't imagine why. It wasn't helped by the planes and helicopters that flew forever overhead, always to and from unknown locations, always leaving that distinct metallic taste to the air.

Nikolai walked along the dull beige tiling of the sidewalk, keeping his eyes forward and his stride stiff. It was far too easy to draw attention to yourself in the suburbs, and the Sentinels were long past displays of public violence. Now it was simply a matter of following the rules. There was nothing you could get away with here. Everyone else kept to themselves, too, especially if a Sentinel was nearby. It didn't really make a difference, considering the surveillance cameras every few hundred feet, but it was difficult not to shrink back from a Sentinel. Black armor gleaming, silver faceplate expressionless, voice cold and mechanical, it was difficult to tell whether they were human or machine. Sometimes Nikolai wondered about that.

. . . seemed to glow in the dim light. . .

Jerking his head to clear it, Nikolai kept his mind set on what he was doing, and tried not to think about anything else. There were rumors that the cameras scanned your eyes to detect emotions of fear or edginess. Best to stay safe, anyway.

After what seemed like a while, he reached the Gatekeepers. The Gate between Alpha and Beta York was lined with people, as was usual. 

Agency never wanted anyone to leave without a thorough examination into their intents. Still, there was always a strong tide of people trying to go through the Gate one way or another, and the system had never been airtight.
"Business or pleasure?" said one of the Sentinels to him, in that robotic voice. If he wasn't so used to it, Nikolai might have found the phrase amusing. Pleasure? No part of New York was built for pleasure.

Nikolai handed the Sentinel his fake career ID card, and waited passively as it was scanned into the computer. At first he had hadn't been able to stop feel nervous when they scanned it. He had seen people shot without question over a phony ID. But he had learned to ignore it, now. Either they accepted it, and he had nothing to worry about, or they didn't, and he would be dead before he could worry about it anyway.

Or we could kill him, instead the Other said in his mind. Nikolai flinched, but didn't say anything. The Gatekeeper eyed him silently, or at least Nikolai thought he did. Without seeing their eyes, you could never tell exactly where they were looking.

The computer beeped, and released the card. The Gatekeeper handed it back to Nikolai. "Confirmed. Welcome to Beta York."

Two years had passed since the Dividing of York, when the state had been converted to Agency's new order. It was one of the last states of the original United States of America to do so, and about the most stubborn. In as many years as the state had existed it seemed to be the central hub for the crime and mob activity of the continent. Now it was divided into two quadrants: Alpha York, which was pure Agency, lined in white tiling, teeming with surveillance cameras and Sentinels, and Beta York, the waning majority of the state, which was ever resisting the grip of Agency and the new world order. Almost the entire continent had been taken over by Agency, and some of Europe and most of Japan as well. But that was just as Nikolai knew it two years ago. . . international relations had ceased on all but a core level, and all communication in and out of the US had been cut.
But that didn't matter now. There were no other continents, as far as Nikolai was concerned; New York was his world, and Beta York his home.

The air was both fresher and dirtier here. It lacked the antiseptic-like cleanness of Alpha York, but there was something else missing as well, something far more difficult to discern.

The air is untainted here, thought Nikolai. Untainted by what? By Agency.

A taint which we long to destroy.

It was visible everywhere. Old-fashioned cement-tile sidewalks were torn out to be replaced with cold steel instead. Brick and mortar buildings were taken apart piece-by-piece in admittance of the dark, towering buildings of Agency. The Sentinels moved against the city with care and precision, and the people of Beta York lived and died to rebel against them. Slowly, inevitably, Agency crept its way in. But Nikolai believed there was a way to stop them. There had to be.

Nikolai made his way along the streets slowly. He didn't own a car; no one did. Public transportation was an expensive memory in Alpha York, and mere memories here. Not that it mattered; over time the population had grown so much and so much had been packed into a small area that it was unlikely you ever needed to get very far. Nikolai had seen cars, when he was younger, and had ridden on the very last public subway ever to run. That was something he'd rather he didn't remember. The Sentinels did have their hovercopters, sleek black things that skidded across the air a few feet from the ground, but as far as he knew no one had ever managed to steal one.

Eventually he reached his destination: a bar. Or rather, the back door of a bar, guarded by a hard, muscular man who was busy with a handheld computer.

"Door's off limits." he said without looking up. Sharp as ever, thought Nikolai.

"I'd give you the password, Blake, but I doubt you've kept the same one for four

...

Nikolai had become aware, in stages, of the cold of the outside air, the heat emanating from the factory door behind him, and the snow that was already forming a layer on his shoulders. He could not remember, immediately, what he had been feeling just before he walked out of the factory, because upon walking out into the December night the cold had hit him and knocked the breath and the thought out of him in one blow. After that, as I said, he remembered the hot factory, not but a few feet behind him, yet so weak-seeming; and then the snow, which was not easy to see but not difficult to discern, for nothing but snow can make the idea of cold so very solid, save ice. Nikolai's thoughts lingered on the idea of cold and of ice, and then they wandered away again and, fearing where they might end up, he started to walk up the stone steps.

Nikolai had become aware, in stages, of the heat emanating from the factory, the cold of the outside air, and the heavy snow that fell around him. He stood now in the middle of the staircase that led from the lower level to the street, making his way upwards, very slowly, using the hand-
railing to pull himself forward. It was very dark; looking up, all he could see was swirling gray snow.

My father was always right. . .

His thoughts were abstract and without meaning, simply something to occupy his mind between steps, and the pain they brought.

Every war is the same, the same people fighting for the same reasons, and they all look back on the last war and say, 'At least we aren't like them.'

He took another step.

Every new technology is another pair of wax wings, and we fly higher and closer to the sun than all those before us, and then we fall farther and harder than any of them; and we never realize the truth until we are among their ruined corpses. . .

Another step.

My brother – ah! Did I ever have a brother? No, I don't think so. A brother is someone you grow up with and are friends with and know and love, not a single memory of a boy whom the police carried away a lifetime ago.

He hesitated as he thought of the figure whom he knew only as his brother, and then thought of his sister and his father and his mother, and of himself when he was a boy and the house where he lived- he took another step.

If I had had a brother, though, he probably would agree with me, when we talked about wars and technology and other things. He would nod and smile and say, Yes, that sounds right, and then he would say something else and we might talk about that as well. . .

Another step. Nikolai didn't look at the trail of blood he was leaving.

And I, I've always liked the cold, the snow and the ice and the wind. And when it gets too cold you hardly feel it at all.

As he took the next step he looked down at the place, just below his left shoulder, from which blood was flowing freely – the place where his arm had been. It was true; his right arm ached and there were deep cuts on his face and he was exhausted, but his left shoulder felt completely untouched.

I can still feel it. . .

He looked up. His eyes were tired and unfocused, and the snow blocked the night sky from view, but he could still see the moon, the full moon, shining brightly. He felt his hand slip, and as his breath left him the cold stone steps rose up and hit him, and for a while he simply lay there. Snow began to settle on his back.

I am going to die here. I am going to die here, like Darwin.

No. . . said the Other, the Alien in his mind. You will live. We will live. And we will rise.

Nikolai faded into dream.

Stepping out into the snow was like stepping into life for the first time, like being born. The thick iron door closed itself behind him. He reached his hand towards the black of the sky dumbly, like a retarded man seeing something for the first time. The snow settled on his shoulders and on the taut, bare skin of the back of his hand. It began as coldness and moved quickly to a throbbing numbness, which his left arm felt and, he thought, perhaps the right, as well, although he couldn't be sure because he did not know where that one was at the moment.

Nikolai had become aware, in stages, after he walked out of the factory, of the cold of the outside air, the darkness of the sky, and the brightness of the snow, thick as it was in the air around him; the first was such a shock that it was responsible for the arrest in his movement, and the second  and third were simply the results of the season, but they were still rather striking. From the pitch of the sky the snow fell, tossed and swirled gray in the air, and when it came finally to rest on the ground it seemed to reflect more light than hit it (more light, surely, than even the night's full moon could be providing). Nikolai swayed for a moment, his arm still stretched out, and then he shook himself from his stupor and his mind wandered again.

Maimed! he thought. Damaged. Wounded. If I have just now been born, than I have been born maimed. He looked at the short sort of cylinder of skin and flesh that extended from his right shoulder, which, aha! was still still disgorging blood very wetly, and seemed to strengthen his assertion.

The long stone staircase he was now ascending linked the basement of the factory to the sidewalk outside; it lined the bottom of a diagonal cut into the ground, open to the air, and the hewn-stone stood oppressively on both sides of Nikolai as he climbed. With his hand on the railing he pulled himself forward, as his legs alone seemed weak and insufficient. The steps were short but many, and when he had taken the first half of them he sat and leaned against the wall. He curled his left arm against himself and again, his mind wandered. It touched his past and his family, and his friends,  and then something it did not want to feel, and it recoiled. Habitually, he considered the past day, and as he considered it he remembered – well, he remembered Darwin dying.

Dying! Nikolai shivered with more than just cold as he thought about it. He had not seen it happen, no, but screams as terrible as he had heard could scarcely mean anything else. Darwin, whom he had known for years, whom he had trusted. Darwin, his friend, his good friend, whom he loved as he might've loved his brother. Nikolai clenched his eyes but they were wet regardless, and his face was buried in his hand as he sat on the snow-covered stair. He shook. Abruptly he straightened, and was quite still.

“Who said that?”

The air breathed around him but was otherwise silent. Nikolai's eyes darted around like one who is listening to someone he cannot see. His breathing grew slow and harsh. He asked the question which he did not want to hear the answer to, and when it was given he did not pay attention. He began to ascend the stairs again with renewed strength, and all the while his ears burned and his mind struck furiously against the dark spot it found within itself. Nikolai did not acknowledge it.

As he reached the top of the stairs, and stepped onto the level of the street, the sky above him bent downwards. The glow of the moon threatened to overtake him, but he turned from it, preferring its light on his back. He tried to think of something, anything, but as he stood still he saw the moon shift and refocus in front of him instead. Finally he fell to the ground, burying his head in his arm and shutting his eyes, while the spotlight of the moon burned his back.

“Damn...” his throat constricted, then, “...it. Damn it. Get – away from me! Get away-” He rose to face the bright circle in the sky, and his voice was suddenly weak and fearful.

“No...” He lifted his arm to block the light, and when he did it stiffened and seized up, just like-

How long had it stood there, watching him, its great black eyes upon him? Nikolai had time enough to see the the thing bristle and brace itself for the jump before he felt its weight on his body, its claw in his face and its teeth on his arm-

He screamed, both then and now, and the world shook around him-

And his hand found his knife from where it had fallen to the ground, and with his thumb on the blade he struck upwards into the beast's eyes, and pushed until the knife met resistance and blood gushed over his hand. It released him in its howl and it staggered backward, too far; the old railing buckled and tore behind it and it fell from their high platform. And then-

He had done right, hadn't he? He ran, even as his face bled and his arm burned from its bite, he searched among the machines until he found one with a blade large enough and then, with no other thought in his mind, he put his tainted arm into the ancient thing. Hadn't he let it fall from him?

His arm had burned then and his whole body 

What is life, what is the use of a name when... etc.
