* Wall-E rough timeline

+ Before-time. Things are cool.
+ BnL takes over. Pollution.
+ Axiom into space, Wall-Es left behind.
+ 700 years. All Wall-Es except MC break. 
+ Eve returns to Earth, meets Wall-E and the cockroach.
+ Courtship & discovery of plant.
+ Eve and Wall-E are taken to the Axiom.
+ Meets GO4 and MO.
+ Wall-E follows Eve to the bridge. Meets the Captain and Auto.
+ Wall-E and Eve sent to repair ward.
+ Wall-E and Eve and broken robot gang escape repair ward.
+ Eve tries to send Wall-E back. Wall-E and Eve discover GO4 trying to dispose of the plant. Wall-E almost dies.
+ Dancing. Captain is learning about Earth.
+ Eve returns plant to Captain. Captain confronts Auto. Auto and GO4 lock up captain, Wall-E, Eve.
+ Wall-E and Eve in the garbage room. Eve falls in love with Wall-E. They escape with MO.
+ Meet up with gang. Take out security bots.
+ Captain fights Auto, gets return process started.
+ Auto fights back; throws off captain, tilts ship, begins to crush Wall-E.
+ Captain overpowers Auto; humans and gang help each other; return process started.
+ Everyone returns to Earth. Eve repairs Wall-E.
+ Wall-E's memory is jogged by a kiss.
+ Restarting life on Earth.

* characters
+ Humans: regular people
+ Captain: King
+ Auto: counselor with evil eye
+ Wall-E: gardener
+ Cockroach: various cute animals
+ Eve: woman warrior
+ MO and GO4: goblins

* The Story of the Two Goblins

Once upon a time there was a mighty nation, with a good king. And they possessed a secret grove of magic plants that could heal all wounds and give strength to the weak. Though many wanted these plants, there were precios few of them, and the king was good and just, and had them guarded and hidden, and he gave them only to those who had the greatest need. And so it was from king to king.

But there was a tribe of barbarians who jealously wanted the magic plants. But the good king would not give them to them, for he knew that they would take all of them, and squander them; for the magic plants had to be carefully tended. And one day the barbarians attacked the peaceful nation, and burned their cities. The brave soldiers of the peaceful nation fought back, and with the strength of magic plants and the wisdom of their king, they might have prevailed; but, unbeknownst to them, the barbarians had a spy among them: a warlock with an evil red eye who could bend men's will to his own. He had become the king's advisor, and under the spell of his evil red eye, the king told the counselor where the magic plants were hidden. And the barbarians came and took the plants, and killed the good gardeners who were entrusted to care for them.

In time, the war ended. The nation still remained, but they had lost very much, and much of their spirit, and they became despondant, and there was no joy in that land. The barbarians took the plants and, as the king had known, squandered them and fought over them, until they were each dead by their greed and malice. And the good people of the nation grew old and a generation passed unto another, and few remembered the joy that had been, and the magic plants. The sick, the infirm, and those injured, simply died, without the plants to help them. The king, too, died. Only the evil warlock, with his magic eye, lived, for he had stolen many of the magic plants for himself, and had them secreted away, and used them to give himself long life, though he did not deserve it. And he stood each day at the side of the king's son, the new king, and used his eye to bend the new king's will to his own; and so it was with that king's son, and his son, and the next. And, because he was jealous of the plants he had stolen, he kept all knowledge of the plants secret. He had only two confidants: two little white goblins that he had bought in a distant lands. These goblins served his bidding, not because of his eye, for they were immune to such magic, but because they were simply creatures, who joyed in serving their master. The warlock used these goblins to trace out any mention of the magic plants, and had killed all who spoke of them.

So it was for many years and many generations.

But not everyone forgot the plants. In secret books, in secret meetings, in stories and rhymes whispered to young children in the night, the legend of the magic flowers remained. At times, through the years, a child, a young man, and old woman, would leave the city, and go in search of the secret garden where the magic plants had grown. But many of these were caught by the warlock's goblins; and many died in the wilderness beyond the city; and even those who didn't never found the secret garden, and they gave it up for lost and dead. And the warlock, too, gave it up for lost and dead.

But they were wrong.

For, unbeknownst to anyone, the plants still lived. For when the barbarians slew the good gardeners, there was one who lived: a quiet, gentle, but very clever man; when the barbarians attacked, he was digging a grave for one of his friends, and when he saw that the barbarians were killing his brethren, he put on old rags and dirtied his face so that he had the look of one who is three days dead, and smeared on body foul-smelling oils; and, putting a seedling of one of the magic plants in his rags, he hid himself in the grave he had dug; and when the barbarians saw him, and smelled the oils, they took him for a corpse. And, after waiting in the grave for three days, so that he was almost too thirsty to move, the gardener climbed out of the grave, and beheld that the barbarians were gone, and all the other gardeners had been killed, and all the plants taken. All but the seedling that he had saved. And he gave that seedling earth and water, and cared for it as a mother cares for her own child, and in time it grew into a small grove; and because he ate of the plants, that gardener lived a great long life; but he was alone, with only the animals as his companions.

One day, a young warrior-woman from the town set out into the wilderness in search of the magic plants. She had little hope of finding them, when so many before her had failed, but she had been raised from a young age with the legend of the plants in her ears, and had been trained in the arts of war and hunting, and she knew she had a duty to search for the plants, and find them or die in the attempt. So she took a good sword from her father's house, and the swiftest steed from her father's stables, and she set out to find the plants.

She searched and searched for many months, but even with her good training, she could not find the secret garden, so cunningly was it hidden.

The warrior-woman had a sheath, but she carried her sword in her hand, ever wary of danger from the warlock's agents. And it happened that one day she was walking over a hill, with her sword in her hand, and the gardener happened to be in a forest some ways a way, and he saw the glint of steel of her sword.
