* The Complete Stories of Flannery O'connor (never finished)
This was the Complete Stories of Flannery O'connor, which may not have been the wisest choice. As a rule, "Best of " is a more palatable thing than "The Complete ", which is of interest primarily to those with a particular interest in . I certainly have an interest in Oconnor's stories, but I do not think that it is particular. It is general. It is not love, which is attracted in spite of or even because (in part) of faults, bit like/fondness, which is attracted provided that the flaws become not too evident.

Aside: Is is that love acts in spite of flaws, or that it acts because of flaws, or that it does not perceive flaws at all?

I do enjoy the writing, but I'm sure I don't understand it. I mean firstly that it's often difficult to follow the action, difficult to decipher the implicit relationships between characters, and secondly that there are whole passages whose intended purpose is unknown to me.

Good and bad reasons for every word/part/passage... Good reasons: advance plot, advance characterization (find relevant quote). What about clarity? Entreaties to the reader? Political messages are difficult to defend, because even if your intention is to communicate a political message, what we are critiquing is specifically the parts of fiction in the form/medium of fiction ("medium" vs. "media"?). Bad reasons for parts/words include personal preaching, thinking they're a requirement (perhaps a novelist you admire tends to describe his characters' appearances in minute detail. It does not necessarily mean that you should do likewise), inane editors... trying to shock people with impropriety...
* The God Delusion (never finished)
Hardcover, silver-covered cover

		Preface
	2-
Expository index of chapters. "Chapter 1: A Deeply Religious Non-Believer"
	3
"Catholic child" vs. "child of Catholic parents"
	5
"If this book works as I intend, religious readers who open it will be atheists when they put it down."
	11
Partial Darwin quote: "...all [is] 'produced by laws acting around us'..."
	12
Referencing Carl Sagan, from the same's book "Pale Blue Dot". Quote is about a scientific view of the universe seeing a far larger, grander, subtler, etc. thing than any religion does.
	13-14
Quote by Julian Baggini, from same's book "Atheism: A Very Short Introduction": 
"What most atheists do believe is that although there is only one kind of stuff int he universe and it is physical, out of this stuff come minds, beauty, emotions, moral valuesÅ\in short the full gamut of phenomena that gives richness to human life."
	14
"If there is something that appears to lie beyond the natural world as it is now imperfectly understood, we hope eventually to understand it and embrace it within the natural. As ever when we unweave a rainbow, it will not become less wonderful."
	14
"Great scientists of our time who sound religious usually turn out not to be so when you examine their beliefs more deeply."
	15 
Quoting Einstein...
"I have never imputed to Nature a purpose or a goal, or anything that could be understood as anthropomorphic. What I see in Nature is a magnificent structure that we can comprehend only very imperfectly, and that must fill a thinking person with humility."
	15
"By 'religion' Einstein meant something entirely different from what is conventionally meant." (this seems to be true)
	16
"The Notion that religion is a proper FIELD, in which one might claim EXPERTISE, is one that should not go unquestioned... 'fairyologist'... Einstein understood very well exactly what he was denying."
	17
The "devastatingly revealing letter" from the president of a historical society in New Jersey, to Einstein.
	20-21
Dawkins & Douglas Adams (via quote) make statements interestingly similar to ChestertonÅ\Chesterton saying satirically that opinions about the beginning of the universe are inappropriate, the formers saying satirically that the same are disallowed.
	26
Religious folk assume that the values of their beliefs trump all others (which of course is true).
	27
"I should not go out of my way to offend..."

		Chapter 2: The God Hypothesis
	31
Many insults directed at YHWH.
	31
Dawkins' "more defensible" "God Hypothesis":
"there exists a superhuman, supernatural intelligence who deliberately designed and created the universe and everything in it, including us."
Note the incorrectness of starting religion out on the same foot as science. Anyway, Dawkins' alternative:
"any creative intelligence, of sufficient complexity to design anything, comes into existence only as the end product of an extended process of gradual evolution."
	
* Silence
I enjoyed the book a lot, although perhaps "enjoy" isn't precisely the word I mean. Perhaps I should say instead that I got a lot out of it. It's a book that's been on my to-read list for a long time, and has been recommended to me several times, but because it's a translation, and because it's set in both a time and place unfamiliar to me, I'd assumed that the book would be fairly difficult to follow, or even understand at all. Happily, this was not the case, and I found that, technically speaking, it was a relatively easy read.

From early on in the novel, I found it difficult to understand why Rodrigues seemed to read Christ's words, "What thou dost, do quickly", in such a negative light; he seems to read them as "Get away from me". This necessitates his revelation, at the end of the book, that Christ's real meaning in those words was "Do this quickly, because you are in pain, and I want you to be done with this burden". Whereas, my interpretation of those words of Christ has generally been something like "Do this quickly, because I am in pain, and I want to be done with this burden." Considering the enormous importance the meaning of these words has to the story, I'd be interested in knowing what the standard interpretation of them was by the Catholic church of that era (as well as by the modern day church).

The aspect of Rodrigues which stood out to me most strongly was his preoccupation with images, or with initial impressions, or with a certain kind of simple evaluation of things, an evaluation which had as its end the placing of things (especially people) into one of a small number of relatively simple categories. I forget where, but there's a place in the novel where he outright says, in one of his letters, that people come in two categories; categories which essentially amount to "good" and "bad". Kichijiro is the prime example of a person who placed quickly and firmly in the "bad" category (more on Kichijiro in a moment). Additionally, you have his preconceived notion of his own martyrdom - what it will look like, and how heroic it will be. Finally, you have his obsession with the face of Christ.

That is another difference between Rodrigues and myself; whereas Rodrigues thinks (at least for most of the of the novel) of Christ's face as absolutely beautiful, I have always taken the words of Isaiah to mean that Christ the man was, to put it simply, average looking, or even less-than-average looking (Isaiah 53: 2b - "He has no stately form or majesty / That we should look upon Him, / Nor appearance that we should be attracted to Him."). Of course, the face of God in Heaven, or the face of Christ as described in Revelations (1:14-15), is a different matter; but if I recall correctly, Rodrigues' impression of Christ's face is made with specific reference to the human body of Christ. Anyway; Rodrigues writes and thinks of the face of Christ in such strong terms, and with such near-obsession, that it led me to wonder whether his faith would be shaken by the idea of an average looking Christ.

Likewise, since, as I said, my strongest impression of Rodrigues (or at least, my strongest negative impression of him - on the positive side of things, he seems like a fine priest and a pleasant fellow) was of his preoccupation with images and first impressions. Because of this, I quickly began to suspect that much of his epiphany at the novel's climax would have to do with a realization that images can be misleading, and first impressions can fail to speak the real truth of a thing. This brings me back to Kichijiro. Because while Rodrigues was quick to sort Kichijiro into the category of "bad" or "weak" or "cowardly" people, I felt that the novel hinted from pretty early on that Kichijiro should not be dismissed so quickly. As the novel progressed, Kichijiro's significance only grew, and as he vacillated between betraying his friends and faith, and coming back to Rodrigues in repentance, I began to feel a kinship with him. For, although my sinful nature prohibits me from being placed in the "good" category, I also am loathe to believe that I ought to be permanently left in the "bad" category to rot. Rather, I, like Kichijiro, am continually falling into depravity, continually facing my own wretched state, and continually crawling back to God for forgiveness.
* Sum
** The stories:

01 Sum
Relive life in alphabetical order. Mild longing for original life. Note twenty-seven hours of pain, fourteen minutes of pure joy (& 1 year of reading) (vs 18 months waiting in line).

02 Egalitaire
God gives up, puts everyone in Heaven. No one likes it, calls it Hell.

03 Circle of Friends
Only people you knew are in your afterlife.

04 Descent of Species
Reincarnate as horse (for instance). My favorite of the stories.

05 Giantess
Universe is god. Don't itch god. Not about afterlife after all?

06 Mary [Mory?]
All creatures turn against creators.

07 The cast
Actors in dreams.

08 Metamorphosis
Wait until your name is last spoken. Lose control of life.

09 Missing
God is married couple.

10 Spirals
Brutes made humans as computers. Solve meaning of life (but humans can't).

11 Scales
We are god's cancer.

12 Adhesion
We are experiment by Collectors. Love baffles them.

13 Angst
We hold reality together. Lives on Earth are vacations.

14 Oz
God is shriveled old man behind curtain (bravery of atheists).

15 Great Expectations
Heaven is worse than computer simulation.

16 Mirrors
We are destroyed by truly seeing ourselves.

17 Perpetuity
God is sick of immortality, makes bad people suffer it too.

18 The Unnatural
Technicians offer one change. Curing death leads to Who Wants to Live Forever scenario.

19 Distance
God leaves Earth so people take him more seriously.

20 Reins
God loses control of Heaven to angels with computers.

21 Microbe
God and people are microbes. We are irrelevant.

22 Absence
Heaven in war over dispute re: absence of god.

23 Will-o'-the-Wisp
In afterlife, watch Earth. Good people spared the worst of it, though they don't know.

24 Incentive
Death = becoming an actor. Eventually reincarnate, ignorant again. Preferable.

25 Death Switch
Our fake E-mail selves continue on. "We are quite satisfied with this arrangement, because reminiscing about our glory days of existence is perhaps all that would have happened in an afterlife anyway."

26 Encore
We are re-created by entities. This causes deja vu.

27 Prism
In Heaven you are every age. The Earthly you is "utterly lost", and this is realized "with a shudder".

28 Ineffable
Communities have afterlives. Humans are communities of atoms.

29 Pantheon
Lots of arguing, mundane gods. They like us because their problems and ours are similar.

30 Impulse
Humanity = computer chip(s). Consciousness / love / self-preservation is anomalous.

31 Quantum
All states exist at once. Joke. Love is inscrutable.

32 Conservation
All of matter is one quark. We will sleep for years while it unravels reality. Then it tries again.

33 Narcissus
Humans created as cameras, but only look at each other. Love vs. love??

34 Seed
God created everything accidentally. Like a great grand-father.

35 Graveyard of the Gods
Everything persists, including all gods, who are sick of each other, and perhaps of existing.

36 Apostasy
God relishes giving answers to the dead. Apostates are punished. But the believers hold to their Earthly beliefs.

37 Blueprints
Everything is deterministic, mostly. "...the network of numbers is so dense that it transcends simple notions of cause and effect." Humans are insufficiently impressed by determinism.

38 Subjunctive
Spend afterlife with all possible yous. Possibly best story of the bunch.

39 Search
Consciousness as being persists in our atoms. We live on as ghosts in the machine. Occasional atomic reunions.

40 Reversal

** Themes

Incompetent god
Distant god
The real death
Reincarnation
No death?
Who wants to live forever?
Heaven is basically Earth
Cynicism. Things basically suck.
Poetic justice
Regular justice
It's all about scale
Eternity is/is not mutable.
