* Kubo and the Two Strings
** https://www.reddit.com/r/movies/comments/4yg8m5/official_discussion_kubo_and_the_two_strings/d6u8vve/

I was ready to absolutely fall in love with this movie after his mother's sacrifice. There was a great mystery behind why his family became so divided, why his eye matters so much, and why his mother had fled. It had all of the elements of a great story waiting to be told: a great thematic setup, a wondrous artistic backdrop and a clear end goal to work towards, but Kubo and the Two Strings complete fumbles it. It's shocking to me how poorly written the middle and end sections of this movie are when the beginning is so well done.

Kubo has an interesting story setup as it's a clear Hero's Journey narrative (He's literally in the belly of a whale at one point) but with the Hero entirely aware that he is the Hero because he is a storyteller himself, and aware of how the story ought to go. This is a great setup for a subversion of the Hero's Journey when things don't go according as planned.

The problem with the middle parts of this movie is the three trials in this movie don't follow the Hero's Journey in revealing Kubo's character nor are they a subversion of the trials that makes the Hero self-reflect on what he should be learning. They just exist as action set pieces and mediocre joke setups that don't fit tonally with the rest of the movie. The first trial is literally just a giant skeleton that serves no characterization purposes. The second trial is explained as the trial that tempts the heart of the hero, but it did nothing of the sort except to reveal that the Monkey was his mother.

The reveal that his mother was not only alive, but also his nagging over-protective companion had little emotional impact on Kubo other than relief; when it should have been a crowning dramatic moment where Kubo reconciles with the fact that mother's character isn't as he expected. The third trial relies on Kubo being incredibly dense as he follows the advice of his evil grandfather, the Moon King, in a dream and goes straight into a trap. And it wasn't as if the Moon King tricked Kubo, he told Kubo who he was and Kubo still fell for it. Neither his father, nor mother, nor the origami Hanzo who guided them to the two other sacred armor pieces, questions the idea of following Kubo's dream.

The third trial's execution is bizarre to watch. His goofy stag beetle companion is revealed to be his father whom he has admired for his entire life, vows to protect Kubo, and then just dies without consequence. And his mother is then murdered for the second time in front of Kubo. We should be feeling the extent of Kubo's loss here, but we aren't given the emotional space to feel it. The movie instead goes straight into the next action scene. The reveal that the helmet was where his home village was, isn't set up enough to be meaningful. Was this done by his mother before her amnesia? Is there a reason it was the sunset bell that called Kubo home before dark? And more importantly, why is there a magical set of armor in this story in the first place?

The overall world of Kubo is not fleshed out enough. We are told that the Gods sent Kubo's mother and her sisters to kill anyone who tried to complete the set of magical armor as they would become too powerful. But what does the armor do? The armor isn't completely worthless as they clearly are magical, so it's not a subversion of the Hero's Journey; nor are they the key to defeating the Moon King as that was the Two Strings that Kubo use to re-string his Shamisen. They are neither useful nor useless which makes them just a MacGuffin to pad out the story.

The motivation of the Moon King is comically one dimensional. He hates humans and that's about it. What exactly separates him from humans is meant to be explained by him wanting to take Kubo's remaining eye, but I didn't hear a satisfactory reason as to why sight was key to the condition of humanity. Thematically, Kubo's main problem is that it is simultaneously anvilicious with its main message yet it also feels muddled when you look at the action leading up to that message. I'm sure the writers intended to have a message beyond "the dead live on within you" but can't justify it with enough evidence within the movie. It's also annoying to have both of his parents literally explain that "the dead live on within you" to Kubo in the middle of the movie and then have no nuance added through action by the end of the movie.

I do see flashes of great story in here though. When Kubo prays to his parents, we see the part of the story that was heavily under-utilized in this movie; that Kubo is a storyteller that is aware that he is the hero in a story. Kubo laments that while this is a good ending overall, he can't help but feel sorrow as both his parents are still dead after he finally got to know them. Kubo in the beginning of the movie wanted to know more about his father, not just his deeds but his personality as well. And his father was surprisingly not a stern samurai, but a lovable goofball. Kubo in the beginning of the movie never truly had a mother, as he was the caretaker of his mother who fed her and made a living for their family. He finally gets a lucid version of his mother, and she nags him and is over protective. He finally gets to know and love these real versions of his parents and then they are suddenly taken away from him again. These are great subversions of his expectations of a Hero's Journey that aren't fully explored enough. This movie was begging for a bittersweet ending instead of the happy one that it got with the literal spirits of his parents watching over him.

In my opinion, the correct ending for Kubo is dead obvious. Kubo's prayers aren't met and he doesn't see his parent's spirits. Later, Kubo is in the market square again, finally performing the ending of his play for the villagers. Except this time, he talks about the personalities of his heroes instead of their deeds. He immortalizes his parent's spirit through his actions because they are truly gone. His stories have changed because he's lived through them and he's matured as a storyteller. He finally knows how stories end; bittersweet.

* MCU

Characters simultaneously too at ease and insufficiently powerful, etc.

* Schindler's List

What a perfect image. The girl in the red dress - what a perfect bit of filmic technique. And how much worse it would have been if she was bright red. And to do something which would be difficult or impossible to do in any medium very different from film... To show an effect that is common and real and impactful but frequently difficult to describe or get across. This effect - that I think everyone has felt at some point, but at very different times and for very different reasons, very different triggers - this sudden and enormous welling up of empathy and pathos towards a fellow human being, whether it is a face in a crowd or a name in a book or just someone in an old photograph - especially someone who has suffered - something about that person breaks through the scab and misunderstanding that normally coats are sympathies and prevents us from feeling all the pain of the world at once. Something breaks through, whether it is because the subject is like us, similar to us, or because it's someone very young or very old, very vulnerable, who seems so innocent or defenseless or underserving, that we are surprised that such injustice can actually exist in the world...

That image of Schindler looking down and seeing so many people being treated so cruelly, being hurt and tortured and murdered, and at some level he knows that it's wrong, but he manages to push it aside, or ignore it, or look past it. But somehow he sees this girl, and he sees her as a human being - like himself - more so than himself, even. And it's a subtle thing! The coat is not bright red! There is barely any color at all! But it is so striking, because it is so like every other person in the film, every other person that Schindler can see. Of course, we know that the film really portrays people wearing colors, and only post-processing has made it seem black and white. So likewise, Schindler knows that all those people are indeed human beings, with hopes and dreams and pains. But he sees that girl... a senteince, valuable, suffering person. He sees the grotesque tragedy of a little girl, a very little girl, no parents, no one to protect her, running in this horrible, dangerous, place, where she will of course eventually be killed. And even though Oscar is a businessman, even though he's callous, even though he's a capitalist, a "member of the Nazi party", and has no children of his own, something wells up deep within him and he knows, he knows that a small girl should not be alone and in constant danger of death. Something deep within himself breaks through all his learning as a businessman, all his conceit, and speaks this knowledge to his soul: a little girl should not have to hide under a bed, or in a closet, or in a toilet, to avoid being taken away and murdered by grown men.

And of course, that is the turning point of the film. And it speaks to him so clearly that he almost entirely destroys himself, everything he's created, for the sake of other people - not even for the sake of the girl, who is beyond his ability to save. 

* Star Wars
** VIII - The Last Jedi

- Order corners Rebellion on planet. Dreadnaught appears. Poe disobeys Leia and sends bombers, destroys Dreadnaught. Scene with Rose's sister.
- Rebellion goes to lightspeed, Order follows. Kylo almost kills Leia, then the top Rebellion brass is killed.
- Londo appears, takes control.
- Finn tries to escape, meets Rose, they decide to find the codebreaker.
- Poe helps them, then mutinees, is knocked out by Leia.
- Finn and Rose go to the casino.
- Finn and Rose are arrested and meet the other codebreaker.
- Finn and Rose and the codebreaker get onto Snoke's ship, and are captured.
- Finn and Rose fight their way out when the ship is damaged.

- Luke refuses to talk with Rey.
- Rey and Kylo start seeing each other.
- Luke tells Rey a bit, trains her a bit.
- Rey goes to the black cave, has a vision.
- Rey hears different versions of Luke and Kylo's falling out.
- Rey leaves.

- Salt planet battle.





Additional, spoilery thoughts on The Last Jedi.

Sorry if I annoyed anyone with my last post. I suppose talking about "what the people who hate the movie want" is a bit judgmental

I may have annoyed some people with my previous comments. I'm sorry if I did. It's not my intention to 



My intention isn't to put people into various boxes for the purpose of judging them.

I see the new Star Wars movies (Force Awakens on) as much like the MCU movies: 





Freaking bomber-bay doors + gravity + everything?
Why is everything so not-remote-control that you have to get into a swiveling belly gun?
Finn tries to escape?
Londo doesn't tell Finn her plan, for no reason?



Some of the quips were out-of-tone with the Star Wars universe. Consistency... I guess some people would consider this a lame argument, especially when it centers on something as lovable as Oscar Isaac pretending to have phone trouble. But tone is one of the few things Star Wars usually is fairly consistent on. There's a reason people go out of their way to point out that it's "space opera", not "science fiction". 

Didn't have much lightsaber fighting... I'm just glad the series is actually going somewhere. Doing something a bit different. Similarly, I will defend the Guardians movies because they manage to actually do interesting things with colors and music... I don't want all these movies to be the same. I am frankly shocked if people find Luke getting old and crusty and having nuanced views on his old beliefs worse than Han Solo returning and literally pulling most of his lines from movies IV-VI. My greatest fear, frankly, was that VIII would end with Poe getting frozen, and IX would end with Kylo throwing Snoke down the reactor core of Death Star #4.

I don't know, man. Do people really want more of Episde VII? Is that really what people want? A 1-to-1 remapping of the original trilogy? While I agree that it's vital that the films remain "Star Wars" (else, what's the point of calling them that?), they also have to add SOMEthing to the formula (else, what's teh point of having them at all?).

** headcannon - technology

Things that are missing because they're unnecessary:
- paper
- toilets

Things that would be useful
- remote control ships
- AI-controlled ships
- ultrasound
- not putting control bridges on the outside of the ship with breakable windows

Things that are very convenient
- people can understand wookies, droids
- clothes don't get very dirty

** institutionalization aka Star Wars ification

EP 4
Jedi (& Sith?)
Wookie life debt
Jedi mind trick?

OT
Force Lightning

* Unbreakable

The somberest, most restrained, slowest, least action-packed film that is definitely a superhero film (there are lots of action films with, depending on how you look at it, you might call them superhero films; James Bond etc.; but this is definitely a superhero film).

The least silly, most serious ... not that these things necessarily make it the best, not that these things are always desirable, but it does make it the epitome of this particular style, subgenere, or message... it does kind of make it the best for me, though, with my particular tastes and preferences.

"Logan" went into bloody details of taking a superhero trope very seriously (the trope being, a hero with powerful, entirely destructive abilities). Other gritty, R superhero movies tend in that direction; more blood on the screen, on the ground. More death. There's not much blood in Unbreakable. There's just tragedy and sadness and melancholy. There's this character who has basically two abilities: he has the ability to sense evil things that people have done when he is near them or touches them, and he is physically very strong - very hard to injure. He does not sense crime BEFORE it happens, but AFTER. And there's nothing he can really do with the perpetrator except hurt them. The one real altercation in the film, he kills (apparently) the bad guy, or at least hurts him very badly. He rescues the kids, but the parents are already dead.

There's this sadness with David - that he's wasted, partially, his life. He's not happy. And he's not young, either. He's not old, but he's not a young man. So many superhero origins are about someone very young. They're coming-of-age stories. They become a superhero and this is the way they both mature emotionally and mature into their fictional superpower. Other superheros are redemptive, such as those who were given their powers by a life-saving operation following a mortal accident, for instance. But David Dunn is the oldest superhero origin I can think of. And he's sad because, he hasn't done much. He hasn't accomplished much, and he has a bad relationship with his small family. And it's not a horrible, tragic, farsical mess, either. It's just... the energy and the light isn't quite there. The man yearns in his heart to exert himself and to do good but he is punching far below his weight. Likewise, David doesn't bawl, doesn't drink himself to death, he simply is subdued, as though he is waiting for things to make sense, or has given up and is steadily accepting his mediocre life.

The most generous possible count of all fights in the movie - all times when two characters set their wills against each other in a way that involved force or the threat of force - would be three or four. A more realistic number would be two: there is the Orange Man pushing David off the balcony, apparently to his death, and there is David choking the Orange Man, apparently to death. The next closest thing to a fight is the epilogue, in which we are told that David literally calls the police on Elijah, who doesn't resist, and has in fact effectively turned himself in. There again we see the somberness of the movie. Not only was David unable to prevent any of Elijah's evil acts, but he is almost the cause of them. Not really, perhaps, but one could easily imagine him blaming himself. The fact that he exists, or rather, the fact the Elijah correctly intuited his existence, led to all those deaths. We're not even assured that turning Elijah in has prevented future deaths - Elijah has given himself up, and it's not apparent that he would have killed anyone else, regardless. The bad guy has won before the good guy realizes who he is. He won in the first scene of the movie.

(It's probably fair to say that the film has exactly one fight scene, which is one with exactly one move.)

The movie takes the essential moments of the modern superhero mythos and distills them to such a small number of very small moments and scenes, that would mean very little without context, but mean everything with context. In other superhero films... if it's an origin story, and the character has powers (which is more or less what makes a superhero film what it is), you have to see them use them, develop them at some point. And the moment that does this in Unbreakable is - I would argue it's not when he lifts the weights (although that's part of it), and it isn't when he defeats the Orange Man (though that's part of it - he used no special techniques and the Orange Man had no chance in that fight), and it isn't even when he tears the car door off the car, although that's part of it - well, maybe that's half of it. The other half is when he looks at the wreckage of the train. And we don't even see him use his powers! We do not see a single moment of that crash. We see only what happens before, and what happens much, much after. It is ENTIRELY context. The context is the twisted wreckage of that train that it was so implausible for anyone to survive.

(Note also... David never receives a superhero name. The Orange Man is only so-named in the credits. Only Elijah, the one who sees clearly - for what is his super-power, but intelligence and understanding? - has and notices and accepts his villianous name.)

Connects to another thought - David is so unaware of his own power that he seems to sort of hide his own memories. Whereas it makes sense that he wouldn't remember the train crash well - he was probably knocked out or thrown far enough that he didn't get a good look at things - he was quite unhurt by the car crash, and conscious for most of it, but the way the memory plays implies that it is a revelation for him. I feel like the implication is that he really buried that memory, almost convinced himself that he really was injured. Not out of self-deception - that's not his flaw, his flaw is intertia. He doesn't hate himself, he doesn't stop himself, he just failed to ever start. He lacked Uncle Ben's death. His identity as a hero was latent, almost permanently.

That thought connects to this idea that the reality of super powers is so astonishing that even with the relatively modest powers/weaknesses of David and Elijah, they are somehow hard to look at, hard to focus on. People don't realize that David's never been sick; he doesn't realize it himself. The only person who realizes these things is Elijah, and he then wears it, donning striking purple apparel, but still nobody else sees it; no one else sees this villain in their midst.

Anyway, it seems that in this world, extraordinary abilities/people are somewhat difficult to see. Not because of some active hiding, but because sightlines seem to go around them. We see this in the cinematography, how we frequently can only see people through the cracks in objects. Elijah is not known as a supervillain; the crimes he commits are seen as accidents; not because he hides, and only partially because there's no clear motivation; but because "supervillain" is not a concept people are accostomed to seeing, and therefore prepared to see the pattern of. 

...

What a good film. "Split" is a fine film, but Unbreakable is something else. 

Note also, the importance (though of a secondary nature) of the scene where the kids save him from the pool. I feel like the implication is that he would have died - water really IS his weakness. Anyway, this is another thing that makes it a superhero movie, because superhero movies often show that as powerful as the hero is, they can't do what they do without the help of other, non-powered, good people. 

...

By a wide margin, the most restrained, melancholy, and least action-packed superhero film that I know of.

...

You may disagree, but I think Elijah also fulfills the often failed promise of being a sympathetic villain, someone who is the hero of their own story (until the final scene, that is). So many villains fall into the megalomaniac trope, the iron-fist dictator, who either sanely and remorselessly wants to destroy everything, or insanely thinks that their absurd plot will work (or are just sociopathic, and therefore not very sympathetic). But Elijah is definitely criminally insane. He's not insane because his idea is implausible - his idea works! He successfully finds and informs a real superhero. He's insane because he genuinely did not see what he was until the end. But he's not so insane that he doesn't, upon this realization, *immediately* turn himself in.

* The Village

If there's ever a film that prompts us to ask whether it ought to be critiqued as the sum of its parts, or something else - if a film can indeed live or die based on one scene or aspect - this is it. The people most (?) people don't like this movie, or at least the reason I've seen given by most people who don't like the movie, is the twist ending. And in my opinion, the twist is not very good. For a number of reasons. There's the thing that people usually mention, the thing that's probably not Shyamalan's fault - that after The Sixth Sense and Unbreakable and Signs, he was the director who had big "twists", and the the promotional material was all about the "twist". That's one part of it. Another is that aesthetically it's not satisfying. With the Sixth Sense's twist, you get to see the blood on his back, you see the ring not on his finger - these are very powerful images. In Unbreakable, you see the fight scene, the memories, the twisted train, the memories of Elijah's murders - all powerful images. Signs - you get to see the alien. With The Village... it's just so hard to see the mundane things of modern life as romantic or poetic or imposing, except in a sort of existential way.

When I first saw the film, I thought that the ending of the film was going to be something like Dark City or The Signal or The Forgotten. I thought the twist would be alien, that it would be an artificial reality of some kind.

If I rewrote the movie, I would keep it all the same, I would have the monsters turn out to be costumes, but I would make just two changes. First, when they went through the memories of what happened before the village was founded, I would make it a little more vague and ominous exactly who the elders were and what they did to create the village, what their resources were. And then I would change the ending completely: instead of finding the wall, the edge of the reserve, and then the road and the ranger, who she then gave a list of modern medications, for which she traded a gold pocket watch - that instead, she would reach a real monster, something very strange and alien, though not as obviously terrifying as the fake monsters. It would be quiet, so she, being blind, wouldn't understand how strange it was. She would unwrap and give the alien the note, but instead of being modern medications written in English, it would be something much more arcane, like a strange symbol written in blood. For an exchange, instead of a gold watch, she might give a lock of hair or a tooth or something. And what she received in return would be something both mundane and ominous, like a spore plucked from the body of one of the creatures, or the crushed body of a beetle. The girl would return to the village, and the final scene would be exactly the same. There would be *no additional explanation*. This is the key to this. Not because it's always better when things are unexplained, but because in this case it is. 

