* notes on an earlier draft
Respected Ethan,

This is a critique, and will therefore focus on the critical. I will arrange my points from most minute to most broad. Given that you describe this as a rough draft, I will skip over any issues of grammar, style, or typography - with the exception of one error that I want to make sure you catch.

1. Near the end of "10. SNAFU", just after Pete calls Mehmet a towelhead, you write,

> "So I was," said Reed. He stared at Manson, who stared back, leaning forward slightly, brow furrowed so close his blond eyebrows were almost one.

Of course, you meant Pete, not Manson.

2. At the beginning of that same scene, I couldn't remember who Pete was, and it wasn't until I searched for and found his first scene that it came back to me. You may need to find a way to mention Pete and the earlier scene once or twice in the interim so that the reader doesn't forget.

3. In "1. Zero hour minus", you write,

> ...Reed's scrawny frame concealed a well developed set of both muscles and reflexes, honed ... by the fact that he made anyone he met who had any knowledge of combat teach him stuff.

Quite honestly, this seems like a childish idea, or a childish way of expressing something more substantial. It would be better if you could point to just one or two concrete things, like practicing boxing for a while, or a history of getting into fights, or an old friendship with a martial arts instructor.

4. At the beginning of "11. Detective Work", you write,

> Since [Katie] didn't officially start until four, and since in her uniform she was invisible to these children of privilege...

First, are Erika et al wealthy? I don't think that's ever mentioned. Second, this seems like a sentiment more appropriate to the very upper class. I'm not sure that upper-middle-class teenagers are particularly less aware of custodial workers than lower-middle-class teenagers are. I think if you want this particular sentiment to work, you need to say or imply that Erika's group is particularly haughty or entitled.

5. Mehmet's outburst near the beginning of "9. Morning" is completely out-of-character. I can definitely imagine Jack's attitude rubbing a sore spot and mildly upsetting him, but shouting? Clio explains it by saying, "He picks fights when he's stressed," but this is the only time that it happens.

6. The episode with Charlie was bizarre on a few counts. We know there were two people involved (the driver and the kid), and the kid was a "skinny boy" and therefore not one of Manson's football players. Probably the driver was Charlie. Was Charlie really so gung-ho about carrying out Manson's revenge that he got one of his own pals and, against Manson's wishes, tried to outright murder one of Reed's friends? Additionally, Boomer seems remarkably unconcerned about the possibility of another attack, and simply goes home, has supper, calms down, makes a phone call, and THEN makes sure he and Alice relocate to a (slightly) safer location.

7. Did Boomer's ploy (the fake breakup) accomplish anything? It didn't last very long, in any case.

8. Kurt's influence with the police is vital to the story, as it shapes the main characters' actions. For most of the novel, they don't even consider calling the police. It's also kept fairly mysterious; as I recall, the only detail given is "...some of the football kids had relatives who were cops...", but it's implied that Kurt has his own, better connection. Considering how important the connection is, it would be helpful if the reader got some hints as to what it was, or some proof that it was real. This is a minor problem that becomes a major problem at the end of the novel, when a single entreaty to Alice's Dad's retired friend apparently obviates all of Kurt's influence with the cops, leading the reader to question how strong Kurt's influence really was, and also, why Alice didn't make that phonecall quite a bit earlier.

9. Reed's competency seems inconsistent and inadequately explained. How exactly did he attack the drug network? I mean, that can remain mysterious, but we need some other clues that he's got these powerful talents or connections. You could reason that the three weeks' attack was powered more by relentlessness and recklessness than cunning, but that makes Reed's subterfuge at the end of the novel anomalous as the only really "brainy" thing he does, in a novel that otherwise makes it clear that Reed is an emotional character and other characters (Mehmet and Hat) are the methodical ones.

10. The last part of "3. Alice" (from the line "Why the FUCK do you care so much about me?" till the end of the chapter) feels about one step away from being your own thoughts, or having the character of your own thoughts, when it ought to be two or three steps away at least.

11. Jackson seems like simply a big bowling pin introduced for Reed to knock down. The surprise that Jackson was put-over along with Manson in the end felt predictable to me. If Jackson is meant to be one of the "big dogs", with "some bite", the story fails to communicate that.

12. Following that last thought, the final conflict is resolved too easily and perhaps with too little pain. For me, the exact moment that the tension went away was Reed's line, "You mean that? You'll give me twenty-four hours?". The line disarmed the till-then volatile and unpredictable Manson, and by the time he became actively hostile again, the novel had essentially told me that Reed had some amazing master plan that was likely to solve everything.

13. Following THAT last thought, it furthermore turns out in the end that Reed's brilliant plan was apparently "Record Manson indicting himself, then the police come and round up all the bad guys." Just like the connected issue I mentioned in point #7, it seems kind of like this could have been the solution at any previous point in the novel.

14. Connected to point #10: I was struck by Jack Collin's remark, "I don't believe in any organized religion's version of God...", as well as some similar stuff in that chapter ("7. The House that Jack Built"). What struck me was this: the novel is too arrhythmic in how and when the characters explain their personal theologies, philosophies, and political views. In real life, such frank discussions tend to happen pretty rarely, or all at once in one big conversation. If, in a novel, it's going to happen relatively frequently - as it does in "Three Weeks" - it should have more of a rhythm or pattern. You must ask yourself: in the fictional universe created/occupied by this story, what causes a character to declaim their innermost theo-philo-poli opinions? The answer should not be (but sometimes feels as though it is), "I, Ethan, got to a part where I personally was reminded of them." or "I got to a part where they were relevant to the action."


X. Noncritical comments, ramblings, musings, and personal suggestions.

When I first read through the novel, I made a note that you mixed POVs without warning at about the 63% mark ("10. SNAFU"), which is a serious red tick in my book (er, metaphorical book). However, upon going back, I couldn't find that you did that at all, so I probably misread it (you do switch POVs pretty frequently there, but always with appropriate line breaks).

A lot of your chapter titles seem like placeholders, which I assume they are (especially given that the last two are untitled). As they are, they're pretty stark and straightforward - which is of course a very valid choice, as far as chapter-naming conventions go. If you keep them that way, though, I would consider the following changes: 14: "Rumors" instead of "Rumor", 16: "The Quarry" instead of "Quarry", and 7: something less poetic than "The House that Jack Built". Also, the acronym/word "SNAFU" kind of bugs me as a chapter title, but that's probably entirely personal on my end (it does admittedly fit with the vaguely militaristic language you use throughout the novel).

I am fond of deliberate, overt structure in fiction, and so I enjoyed the format of "1. Zero hour minus", as well as the isolated conversations of "14. Rumor". It made me want a bit more of that, especially considering that the first third of the novel is both the most structured (the rest of the novel is entirely chronological, I think) and the most well-written. Though, I don't know exactly how you'd put more overt structure in there - mixing the chronology of parts two or three would be an enormous change, and probably require a lot of rewriting to not seem gimmicky.

My favorite character was Boomer, possibly because he was big and he was called Boomer. If I had to pick a girl it would probably be Clio. Daphne's the runner-up, but Clio seems more real.

I am happy to clarify or defend any of my points, as it please you.
* characters
** Clio

    Raised Catholic

** Alice

    Clio's best friend
    Dating Boomer
    Attends Peace Lutheran
Works at the Koffee Kiosk

** Jonas Polanski

    Reed's older brother
    Intuitive?

** Reed Polanski

    Jonas' younger brother
    In deep shit
    Protestant?

** Mehmet

    Egyptian

** Travis "Boomer" Adams

    Dating Alice
    Big guy
    Black
    From Chicago

** Pete

Local farm boy, asshole
Doesn't care for Manson

** Nathan

    17, bulky
    Likes Clio
    Cook at The Shake Place

** Kurt Manson

    Clio's new BF
    Draco Malfoy
    Captain of the football team
    Father is chief of police
    Cousin arrested ~0 hour

** Ryan "Hat" Lawson

    Cello player
    Cindy Lawson's younger brother
    Where's a Jayne hat

** Erika

    Broke up with Reed

** Angela & Mags

    Erika's friends

** Louise

    Reed Jonas' current foster mother

** Laurences

    Beagles: Jumbo and Valkyrie

** Alex Lincoln

    Kurt's go-to guy
    Running-back on football team
    Dating Cindy Lawson
    Same person as Ryan Strong?

** Cindy Lawson

    Hat's older sister
    In Erika's clique
    Dating Alex Lincoln
    (was? dating Ryan Strong)

** Coach Jefferson

    Football coach
    Answers to Kurt

** Tommy

    Special ed kid
    Big

** Pastor Bensen

    Pastor at Peace Lutheran

** Pastor Hubble

    Had something to do with getting Boomer out of his "drunk boxer" phase.
    Pastor at St. Paul's Lutheran Church in Milwaukee

** Alex "Bozo" Behmer

Kurt's goon, dealer, and cousin
18
arrested (during the amnesia, I think)

** Jack

Prepper guy.

** Tacitus

Jack's son.

** Daphne

Jack's daughter.

** Ryan Strong

(was?) Dating Hat's sister. Reluctant Manson-follower.
Same person as Alex Lincoln?

** Candace

Alice's co-worker at the Koffee Kiosk
sulky

** Linda

Alice's GM at the Koffee Kiosk

** Lakshmi

Works at Esmeralda's Beauty Salon
willowy

* places
** Shake Palace
** Daisy's
** Jack's house
** The Ninth Circle

country diner
(one of) Pete's hangout(s)

** Koffee Kiosk

where Alice works

** Esmeralda's Beauty Salon
* outline
** ONE: ZERO HOUR
*** Zero Hour minus twelve minutes

    1-2
    Clio is upset; call from Alice; time-to-go call from Jonas

*** Zero minus eleven hours

    2-3
    Reed wakes up with amnesia

*** Zero hour minus seven days

    3-8
    Clio calls Jonas, says Reed told her he was sorry for something; Mehmet says Reed is with him; Jonas goes to Mehmet's house; Mehmet intro; flashback to Shake Palace; they hear sirens; Reed slips out

*** Zero minus eleven hours

    8-

*** Zero minus nine hours
*** Zero minus seven hours
*** Zero minus three hours
*** Zero minus two hours
*** Zero minus one hour
*** Zero minus two hours thirty minutes
*** Zero minus one hour thirty minutes
*** Zero minus two and a half hours
*** Zero hour minus forty-five minutes

        34-37
        Reed leaves Mehmet's for Louise's
        Reed attacked by skinny kid in SUV with gun
        Mehmet and Jonas pick up Reed

*** Zero hour minus fifteen minutes

        37-40
        Boomer and Alice's dad
        Kurt comes to Daisy's, leaves with entourage
        Boomer gets Alice
        Mario bros. get their bobs and have a final chat with Louise

*** Zero hour

        40-41
        Erika comes to Louise's house, Louise brushes her off
        the gang leaves town

** TWO: THE HOUSE THAT JACK BUILT

        41-

** THREE: INFORMATION
** FOUR: CHARMS
** FIVE: THE FIGHT
** SIX: NEGOTIATIONS
** SEVEN: THE STORY
** EIGHT
** NINE
** TEN
** ELEVEN
** TWELVE
** THIRTEEN
** FOURTEEN
** FIFTEEN
** SIXTEEN
* critique
** INTRO

So, funny story: the very same week you sent me this draft of Three Weeks, another friend sent me THEIR story to critique! Crazy! And then, I procrastinated on both of them for half a year! What a hilarious random happenstance.

Anyway,

I'm going to refer to page numbers from a pdf version I created from the file you sent me, but I'll also try to copy enough of the text that you can just search for the passage I'm talking about.

Unless otherwise specified, assume I am *moderately certain* about each of my critiques.

In the past, when I've critiqued my friends' writing, I've tried hard to avoid rewriting their prose. So I might say, "This sentence should emphasize such-and-such more", but I would avoid saying, "I would write the sentence like this: ...". But I find this tiring, as very specific suggestions keep popping into my head, so I'm going to go ahead and just tell you the way I would write things. Please tell me whether you find this style of critique more or less helpful than the alternative.

** TYPOS
*** 54

> This was Smoker's Paradise 

Missing period.

*** 73

> ...the long-distance impact she could feel almost as if she were a part of the bulle...

"bullet"

*** 78

> Boomer went back into Hat's room. He climbed back onto Hat's bed and reported the conversation with Reed.

"conversation with Jonas"

*** 85

> Then, in the pin-drop momenet of silence...

"moment"

*** 99

> As Jonas looked up from his phone he saw that Daphne was making eye contact from across the room, though she appeared to be nonchalantly looking over her should at the clock. 

"shoulder"

*** 107

> "No. Not only no, but hell now."

"hell no"

*** 115

> "Ironically," Reed said. "That's how we found out this entrance existed."

Should be a comma instead of a period after "said", and then don't capitalize "That's".

** STYLE
*** 5

> Jonas, Reed and Clio had met Mehmet at the tail end of winter break last school year.

I'm not confident about this, but I feel like "last school year" should either be "the last school year" or "the previous school year".

*** 6

> It almost looked like Mehmet didn't see Pete's fist approaching from his left, though Reed did. Reed jumped out of the booth but Jonas grabbed his arm. Reed looked back at him. "Wait," Jonas said, eyes on the action.

> At the last possible moment Mehmet blocked Pete's punch...

It sounds like Reed and Jonas have this whole interaction, with Reed jumping out of the booth and Jonas grabbing his arm and telling him to wait, in the space of time between Pete starting his punch and Mehmet blocking it, which would definitely be less than one second.

*** 6

> Pete's friends were up now: they might not have agreed with Pete's harassment, but you didn't let someone hit your pal, especially not, let's face it, some foreigner.

Offset the clause "let's face it" with dashes instead of commas.

*** 12

> Clio's expression had gone from narrow-eyed suspicion to wide-eyed worry. Jonas wasn't sure which one ate at him more. "A couple of the football players like me."

Not immediately apparent that this is Clio's line. Add "she said" to the end of the sentence.

*** 22

> When he picked up, with as little preamble as her father when she walked in the door, Alice gave a tirade about having an awful father who wanted to treat her like a ten-year-old forever—a tirade phrased both for Boomer's benefit and with the possibility in mind of her father listening in.

Couple nitpicks here. I would write it this way:

>> When he picked up (with as little preamble as her father when she had walked in the door), Alice gave him a tirade about having an awful father who wanted to treat her like a ten-year-old forever--a tirade phrased both for Boomer's benefit, and for the possibility of her father listening in.

*** 24

> [Boomer's three memories]

If you're going to offset the memories by line breaks, you should offset the first one, too. Probably better to offset none of them, though, since you have a lot of memories in the novel and none of the other ones (as far as I can remember) were offset in this way. In fact, I can't think of any other time when you use line breaks for something other than a scene change.

*** 30

> There were a couple half-hearted attempts at spray paint graffiti, half-heartedly painted over.

Good line.

*** 33

> Jonas stared at Reed. For a moment Reed met his eyes, but then he turned away, refusing to meet Jonas' gaze.

Redundant. Remove "refusing to meet Jonas' gaze".

*** 46

> This was the first time Clio had seen him look anything less than certain.

Weird phrase to use for someone Clio has only known for a few minutes. Change to

>> For the first time, he looked less than certain.

*** 49

> And Clio had clutched her grandmother's arm, and Clio had cried. Clio's grandmother's bony fingers had tightened on Clio's arm, but Clio's grandmother--a hardy old Irishwoman who had divorced her grandfather half a lifetime ago--had been able to do nothing else.

The first time I read the second sentence, I had difficulty parsing what it was that Clio's grandmother could do nothing else other than. I think this is because I expected the clause to refer directly back to the verb, but the verb is actually done by Clio's grandmother's bony fingers, rather than Clio's grandmother. Also, there's a parenthetical separating the verb and the clause. I suggest

>> And Clio had clutched her grandmother's arm and cried. Her grandmother had tightened her bony fingers around Clio's arm, but her grandmother--a hardy old Irishwoman who had divorced Clio's grandfather half a lifetime ago--had been able to do nothing else.

*** 50

> Daphne and Jonas left, exchanging smiles friendlier than Clio suddenly realized she was okay with.

Good line. Although I'd get rid of the "inexplicably" in the following sentence.

*** 53

> "I'm balls-deep in an op."

This is not a problem, but a decision that I want to make sure you're aware you're making. The brothers use sort of quasi-military speak when they're talking and planning things ("dead drops" etc). It gives a certain tone to their interactions, especially with each other. This line of Manson's was the moment when it felt to me like this was no longer the tone of the brothers' interactions, but actually the tone of all such interactions in your novel's universe. This feeling was later reinforced by Jackson speaking very much the same way (as well as a few comments by other characters, like Erika's "Here's the play.").

That being said, I don't have much insight into what different ways Manson and Jackson could speak, if you want to avoid this effect.

*** 56

> [Hat's note to Alice]

Shouldn't the contents of Hat's note, read aloud by Alice, be italicized? Other notes in the novel are italicized, including the one repeated aloud by Hat on p81 ("Your dealer was just the beginning...").

*** 57

> With the traditional prayer he barely remembered being taught, he included an apology for the wine he had drunk last night, and when he saw the girls sitting in the kitchen a further apology for lust.

I'm not confident about this, but personally I would put a comma after "kitchen" and a semicolon after "night".

*** 57

> Daphne seemed to think of Clio by turns as an older sister and a younger one.

This line struck me as odd, since Daphne and Clio have only just met. Change to

>> Daphne seemed to be thinking of Clio by turns as an older sister and a younger one.

*** 76

"What could you possibly have to say at this point?"

Good line. Good paragraph. Good scene.

*** 77

> Though Alice was keeping an eye on Esmeralda’s, it was Erika’s laugh she heard first...

This threw me off a bit when I first read it. I didn't expect the shift from visual to audio. It would read better something like

>> Though Alice was keeping an eye on Esmeralda's, she first became aware of Erika's group when she heard Erika's laugh...

I'm not super confident about that, though.

*** 81

> Defying the world to throw him from its surface he lurched to his feet and staggered forward.

Good line. Reads true to Reed's personality. Put a comma after "surface".

*** 85

> Reed made his way dizzily down the stairs, paused in the kitchen for a glass of water, then managed the journey across the yard to the barn. Reed joined the others in front of a monitor the size of a large flatscreen TV. On the other end of the feed were Alice, Boomer and Hat, covered from a dizzying number of angles what Reed assumed was Hat’s rig.

Second sentence should start with "He" instead of "Reed". Third sentence is missing a word or has an extra word or something. Also, do you abide by the Oxford Comma? If so, you need a comma after "Boomer". If not, you're wrong, and you need a comma after "Boomer".

*** 93

> Between everybody sorting themselves out post-Reed’s departure, it took too long for anybody but Mehmet and Tacitus to join her in the loft.

"too long" for what? I'm assuming "too long, as far as Daphne was concerned," but it's not clear.

*** 93

> Daphne paced back and forth across the creaking floor, her shadow twice her size, whipping off the floor and the walls in the barn’s midnight light. 

Sounds like Daphne's the one whipping off the floor and the walls, rather than her shadow.

*** 103

> Here town suddenly ended, replaced by tall trees roads suddenly twisting,
meandering.

You're missing a comma or something.

*** 113

> Jonas took another drink and handed the flask to Reed, who took a small swallow. "I'll pocket this, if it's okay with you." Jonas nodded.

Add a "said Reed" or similar after the dialogue.

** PROSE
*** 6

> The Norwegian lady was screeching. First she screeched at the boys, then when they ignored her, she screeched into the phone to the police. As the sirens grew louder down the street...

It felt like the police arrived really quickly, to be called after the fight starts and arrive while it's still going. This isn't a big issue, since there's a definite sense of the scene getting sort of summarized as it comes to a close, but it still felt weird to me as I read it. I would either add some preliminary altercation before the fistfight that might incite the Norwegian lady to call the police several minutes before the fight starts, or some sort of shouty stand-off after the fight; or even a comment beforehand about how there happens to be a policeman parked just down the block, or a police station across the street (which would necessitate an additional comment about how stupid Pete was to start a fight with a policeman right outside).

*** 28

> "Why the FUCK do you care so much about me?"

I remember criticizing this scene as seeming not very authentic, and you defending it. Well, whether because I've changed, or the scene changed, or I've just gotten used to it since the last time I read it, it seems much better to me now.

*** 32-33

This section ("Zero minus two and a half hours") is a Jonas PoV, but this doesn't become apparent until many paragraphs in ("Jonas stared at the air, let the thoughts trickle into place inside him."), which threw me off. I would put in something in the first or second paragraph of the section to alert the reader that it's a Jonas PoV.

*** 39

> "Whatever," Kurt said. He rolled his eyes at Alice, breathed a sigh of annoyance, and yanked open the door of his big red pickup.

I feel like it should be clearer here (if not this sentence, then a recent one) that they're leaving Alice behind.

*** 44

> Reed snorted. "They think we're feds."

I know Reed's cool under pressure and all that, but I think he'd be a little more giddy at him and his friends just being shot at and possibly about to be shot at again. He was definitely rattled at the encounter with the skinny kid in the SUV, and the skinny kid didn't even get a shot off.

*** 46

> I'll be your fucking fed.

I like this speech for a couple reasons. But I think it's a little too eloquent, too prepared-sounding. Your call on what kind of feeling you want the speech to have, but, for me, I would like just a little bit of stuttering or something to illustrate that this is coming from a place of anger and adrenaline, rather than carefully reasoned argument. Something like

>> You want us to be feds? Yeah, okay. Fine. I'll-- I'll be your fed. If it'll make up for the fact that you felt the need to fucking shoot my friends tires out, to fucking threaten us all with guns ... you wanna, what, you wanna torture me? Yeah, go ahead and, and waterboard me, I don't fucking care...

Something along those lines.

This would a great opportunity for one of those out-of-the-box writing exercises, like sprinting until you're out of breath, then shouting Reed's speech from memory into a voice recorder, and transcribing it verbatim.

*** 51

> "Please don't drink if you feel allegiance to the government's arbitrary drinking-age laws ... I don't believe in any organized religion's version of God..."

So another thing I complained about last time was the times and ways that the different characters got around to discussing their religious and philosophical beliefs. Once again, either I've changed or the novel has, because it seems much more natural to me now. (Especially the canned Libertarian stuff.)

*** 57

> He just could not help thinking that the girls ... were very cute.

I think this would be better if it were much more subtle. Just your description should suffice:

>> He looked back at the girls once more. They were sitting cross-legged in their chairs, in their t-shirts and long pajama pants, both of them with their long hair flowing softly over their shoulders and down their backs...

(the ellipsis is optional)

Given the context of the paragraphs immediately before and after this one, I don't think the point will be lost on the reader.

I will admit to some personal bias in this matter. We all have some passages that we read at certain times in our lives that hit us hard and never seem to leave us. One such passage for me is the third paragraph of Joyce's "Araby". The narrator tells us in the fourth paragraph that he loves a certain girl, but we already know this from the third paragraph, simply because of the way he takes the time to look at and describe her.

*** 96

> [Erika being seductive]

Good scene.

*** 96

> Before I bring it to him, I break it, and I break it back bad.

I didn't know what this meant when I read it. I decided it probably meant removing a portion of the coke and mixing in an equal amount of something that would make the rest less potent and/or have undesirable side-effects. But anyway, other readers who aren't familiar with drug terminology will also have to stop and think about this one, if you don't find a way to introduce the terminology at some point beforehand. Your call on whether you want readers to have to stop and think.

*** 98

> "Hey, Q," she said.

Who's "Q"? Manson? "Quarterback"? Was this something brought up previously and I just forgot about it?

*** 103

> Jack had picked up a big box of coffee, which he put on one of the picnic tables and said that everyone could help themselves.

So is it a box of coffee grounds, or carefully-balanced Styrofoam cups, or what?

*** 103-104

> “For a lot of reasons, I don’t want to reveal my master plan in a big supervillain speech here..."

Alright, alright. You made me laugh.

*** 120

> He dove forward, his hand cupping the front of the gun, pulling it away from Kurt's temple.

I strongly recommend specifying which hand. It will make the pain of the injury more vivid, as the reader naturally starts to think about what parts of their life would become more difficult if their, say, left hand had a hole in it.

** PLOT
*** time-hopping

So, I don't know if this is feasible, but... is there any way you could tone down the time-hopping in part 1? Or somehow make it clearer? My concern is that it comes off as more confusing than it needs to be. As I read through the novel, I basically gave up trying to follow where I was in the timeline. Afterwards, I wrote down all the subchapter headings and was surprised to see that it's pretty straightforward: aside from "twelve minutes" and "seven days", it's entirely chronological. But I think the fact that it starts off by jumping around, and the fact that "seven days" itself contains an extended flashback, and the fact that all of the sections in part 1 are labeled very exactly, made me feel like it was all some intricate jigsaw puzzle that I didn't have the energy to figure out.

I don't really know what to suggest, though. All of your individual decisions in this regard make sense to me, and the two out-of-sequence sections make sense dramatically. What I want to suggest is that you remove the heading from "seven days", and just make it a flashback portion of "eleven hours", but then "eleven hours" will be kind of long, and include a flashback within a flashback, which seems like a bad idea. It might work if you found somewhere else to put the flashback where the brothers first meet Mehmet, but... eh. I dunno. What you have already might be the best possible arrangement.

*** the other brothers

Louise's two younger (adopted?) sons are mentioned so infrequently (I think just pages 2, 39, and 41) that I had a very hard time remembering whether they existed at all. Either mention them more or remove them.

*** Jack's prepping

I'd like some more details of Jack's prepping, specifically the technology side of things. You'll have to forgive me if I missed some of these details - I skimmed back through a bit and couldn't find them. What exactly does Jack need multiple "pretty state-of-the-art" computer setups for? And where did he get the $10k+ to pay for it all? And is his internet service provider the kind of crap you'd normally expect in rural northern USA, or something more in line with Jack's set-up? If the latter, does he have a satellite dish on top of the barn, or does he somehow have fiber running to his barn?

I don't mean to imply that I think you need loads of explanation for this. The whole set-up is plausible enough that my brain started filling in possible answers. But it's also abnormal enough that I was never sure about those answers. I think just a few sentences, maybe one paragraph, would be enough to answer the questions above.

Sidenote: there's a sort of quasi-subulture of geeks called "data hoarders", people who build servers with huge amounts of storage space, obsessively save things, and constantly max out their bandwidth limits. Jack's setup reminded me of a particular hoarder setup I saw on reddit, a 32 terabyte server mounted in someone's attic on shock absorbers - in case of earthquakes: http://imgur.com/a/A7Y9n

*** the confrontation at Jack's house

This is another thing I probably just missed, but when Manson & co showed up at Jack's and there was almost a shootout, I found myself wondering where Pete's gang was. I thought to myself, "Were they supposed to be helping out right now? If not, when are they supposed to help out? Some particular moment in the future, or just, "sometime"? Again, I might've just forgotten when you mention this.

*** Pete winning a fight against Reed

The timing of this scene didn't feel right to me. It felt like it was missing something, some additional connection to the plot or the flow of the story.

Actually, what I kind of thought was going to happen was that everyone except Reed would forget about it, and then at the end, at the hospital, Pete would walk in, acting all menacing, then tap Reed on the forehead and say, "There. I win.", and then they could be bros.

Obviously it doesn't have to happen that way, but... well, Vonnegut said that every sentence must either "reveal character or advance the action", and it's not clear to me that this scene does either. It doesn't reveal character, because it tells us nothing new about either Reed or Pete, and it doesn't advance the action, because it doesn't cause anything else to happen that wouldn't have happened anyway. But it DOES have to be in the book, since Reed and Pete have their agreement. So if you can't find a way to make it advance the action in some necessary way, then I would suggest taking the opportunity to let it reveal or advance some aspect of Pete's personality.

*** Daphne

Sooo, Daphne seems a bit too much the-whole-package. As brazen as Reed, as sexy as Erika, super self-confident, and rather quickly in love with the main(ish) character. I hate to be cliché, but you need to slap a flaw or two on her.

*** Kurt and the climax

I like the climax, and Kurt finally being pushed over a variety of edges. I have one strong suggestion, and one, uh, light one, enhance the overall effect of his downfall.

Strong suggestion: Tacitus should not film Kurt with his phone. Either he should start to, and Kurt should make him stop, or Kurt should preemptively make it clear that nothing's going down if he sees anyone pointing a phone at him. This will make Mehmet and Tacitus' pre-hidden cameras cleverer. Alternatively, or additionally, you could insert a comment in some earlier scene about Kurt being wary of phones recording him incriminating himself. For instance, maybe when he's going to beat up Reed in the basement of Daisy's, he could stop to smack one of his subordinates simply because they had their phone out.

Light suggestion: add a line to the effect that Kurt always managed a certain minimum of restraint and care, but that there in the quarry, when Reed calls him out, Kurt finally abandons all restraint, either because Reed discovered the perfect way to poke at his insecurities, or because Reed's insult was just the straw that broke the camel's back.

*** Reed's hand

My (limited) understanding of gunshot wounds suggests that a point-blank pistol shot through the hand would usually result in some permanent loss of strength/dexterity. You should consider stating this possibility, *if* you would like to increase the sense of pain and lasting damage. (Personally, I would. I like to make it clear that at least some of the changes suffered by the characters are objectively permanent.)

