* 2016 election eve
With election day looming tomorrow, I'd like to take a moment to offer the hand of solidarity to my fellow people who are completely uncertain about this election.

I often wish I had the certainty I see so frequently online.

I tried to investigate Trump's business acumen. My impression is that he's a very successful businessman - but that's just an impression. Some people say he's had loads of businesses go bankrupt. Others say that that's just the cost of starting lots of businesses. He's rich, right? But apparently he got all that money from his dad. How much money DID he get from his dad? And how much money does he have now? How much money would have have now if he'd taken all the money his dad gave him and, rather than start businesses, just put it all in the bank? I don't know.

What about Clinton and those emails? Did she really do something illegal? Or was it simply careless? 



Notes and reminders on the eve of election day:
1. Clinton is the favorite to win the Presidency, at about a 67 chance.
2. The Republicans are actually favored to retain control of the Senate, at 55%.
3. If you are voting for Evan McMullin (aka Hopeless Candidate #3), and your ballot has a separate spot for Vice President, make sure you write "Nathan Johnson" there.







This election has been a resounding mass of uncertainty for me.

I'm sufficiently utilitarian that I would gladly vote for Trump - or Clinton - if I was confident that one or the others's presidency offered a higher expected return (in terms of probability of innocent lives lost, dollars wasted, etc.). I'm not particularly fond of Clinton, and Trump is one of the most personally offensive public figures I've ever seen, but if I was confident about which one would, even inadvertently, do the most good, I would absolutely vote for them.

But I am not confident, not remotely. Despite watching and reading about this election more closely than any other election in my life, I feel profoundly unequipped to make an accurate assessment of almost any part of it. When I try to dig deeper into particular issues to find the truth, they only become more complex and uncertain. For instance, I tried to pin down whether Trump is, as his supporters claim, a good businessman. I've been under the impression that he is; but a lot of people point out that many of his businesses have failed. People respond to this and say that he's started so many businesses that it's no wonder some of them have failed - every entrepreneur fails a few times on their way to success. But maybe his "success" is due entirely to the loan he got from his father? But how much was that loan? And how much would it be worth if he had just invested it? For that matter, how much IS Trump worth? I am not certain of the answers to any of these questions.

Another example. Is Clinton's email server a crime for which any other citizen would be prosecuted and imprisoned? If so, why wasn't she prosecuted? Is it because of political corruption? Or has the FBI done its job correctly, and people are just blowing things out of proportion? Regardless, is it indicative of problems during a Presidential term? I heard somewhere that Clinton claimed some sort of memory loss when questioned about the emails, but that sounds kind of made up.

On abortion, the standard pro-Trump argument is that while Clinton is clearly pro-Choice, Trump is... unpredictable. Well, I suppose I can get behind that reasoning. After all, a public official's past actions are the most reliable predictor of their future actions, and Trump has never held a public office, so it's anyone's guess. Maybe he'll (try to) do what he's said he'll do. Maybe he'll do something completely different. Maybe he'll elect Republican-ish people to the Supreme Court. Maybe he'll elect his personal cronies. Maybe other Republicans will hold him accountable (is that a thing that can happen?).




My two biggest issues:
1. Preventing abortion
2. Avoiding major disasters (such as nuclear war)

Trump wins #1. Not because he's pro-life - I'd be pretty surprised if Trump were pro-life - but because he's so unpredictable, and Clinton is very predicatably pro-choice.

Clinton wins #2, again because of Trump's unpredictability.
* Libertarianism and harmful practices
The idea of vice sinkholes, e.g. casinos
* reverse racism
[[http://bleedingheartlibertarians.com/2014/11/on-reverse-racism-three-thought-experiments/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+BleedingHeartLibertarians+%28Bleeding+Heart+Libertarians%29][link]]

Reverse racism...

Serious liberalism... Somewhere above microaggressions, cultural appropriation, and triggers, but below men-cannot-be-raped, HAES, and otherkin.

Devil's advocate just means considering the other side
Also, innocent until proven guilty
Also, ignorance until proven animus
Also, principle of generosity

Difference between Reps and Dems:
	Reps think that the solution to people not being treated equally, is to treat them equally.
		Objection: there is an imbalance that won't be fixed by this approach.
			Response: that's not the most important thing. The most important thing is equal treatment and equal opportu
	Dems think that the solution to people not having the same advantages is to give disproportionate advantages to the currently-disadvantaged.
		Analogy: an unbalanced scales won't balance by putting the same weight on each side.

Equality of what? Opportunity, means, treatment, or outcome? And initial outcome, or final outcome? Financial outcome, or psychological outcome?

If racism is discrimination + power, is it general power or specific power?

Calling it "reverse racism" in the first place. Could crime committed by a white be called "reverse crime" or something? Maybe a child getting cancer is "anti-cancer"?
	> If because the "reverse" is in reference to frequency, yes.
	> If because the "reverse" is in reference to institutional power, no.
		I think this is using a very general concept to address a very specific one, and I'm not sure it's a good idea. This seems very ecological fallacy, like saying we shouldn't punish a woman murderer because women aren't usually murderers.

Maybe my point is really just more about interpreting and dealing with specific situations, rather than trying to cure-all? Or maybe rather than trying to generalize? Because defining people by anything other than their own actions/circumstances seems to be the thing we want to avoid?
	Maybe... it's not that I doubt racism exists, or that it even exists strongly in favor of whites etc., but rather, that I don't think it's so strong that it overrules every possible circumstance? E.g., the homeless white cis dude.

Men aren't supposed to hold doors open for women, but it seems like a lot of doors are being held open for a lot of unprivileged people. Is there a disconnect?
	Is it harmful to the oppressed to act as though they can't take it?
* voting
Reasons to vote:

1) Because the choice ought to reflect the consensus (and/or the consensus will tend to pick the best choice)
1.1) This is true even with a small sample.
1.2) Being uneducated/uninterested is probably a self-eliminating factor.
2) Because you want the right person to win (and/or you want the greatest overall net effect)
2.1) Insignificant probability.
2.2) Agree to mutually not vote.
2.3) Convince other people to not vote.
2.4) If uneducated, reasonable to not vote.
2.5) Vote for third party, even non-candidate.
3) Because civic duty.
3.1) ?

Questions: good idea to agree with opposite-party person to mutually not vote? good idea to convince opposite-party people to not vote? good idea to vote for write-in?

http://www.nytimes.com/2005/11/06/magazine/why-vote.html

http://freakonomics.com/2012/10/25/we-the-sheeple-full-transcript/

...

1) Civic duty
1.1) ???
2) Want results to reflect population
2.1) Good to mutually abstain
2.2) Voting low-value due to sample size already exceeding required
3) Want correct dude to win
3.1) Good to mutually abstain
3.2) Good to convince other partyers to not vote
3.3) Voting low-value due to low probability

...

1) Easier voting may decrease turnout
[[https://www.supportthevoter.gov/files/2013/08/Will-Vote-by-Mail-Elections-Increase-Turnout.pdf][link 1]]
[[http://www.researchgate.net/publication/227357057_Social_Incentives_and_Voter_Turnout_Evidence_from_the_Swiss_Mail_Ballot_System][link 2]]
