* ambiguity
In relation to Braid, Shutter Island, Cloud Atlas (slightly)—the idea of the audience finding their own meaning—especially using this as a response when there is genuine inquiry into what actually occurred during the narrative, or what the message is (when the message is stated strongly but not clearly)... usually strikes me (and I think I am probably backed up by evidence) as a case of an author using many different images or statements or plot points, which all relate to a common theme or motif, but... these images are used without the patience or care or skill or bother of arranging them such that they make a particular sense, and build to something, and mean more than the sum of their parts. To me this is analogous to writing a "normal" story with many plot holes, and brushing them off by saying that the audience can fill in the plot holes with their own meaning. It's not to say that it's impossible to create a good story which is surreal or postmodern or dreamlike...

The other objection I raise to "find your own meaning"ism is something that doesn't come up as frequently, but its these cases where, I feel, the author really did have a particular meaning or interpretation in mind when they created the story, but they have such a high opinion of vagueness or open ended-ness or whatever else that they are unwilling to say what the real meaning of the work is, and are coy about admitting that any such "correct" interpretation exists at all.

* averting your eyes
Perhaps being an artist means never averting your eyes. No, I posit that it does not. Never avert your eyes from the charred corpse, perhaps; the ugly childhood memory. But certainly avert your eyes from your neighbor's spouse! The question returns again to sexual content, and the like. Content which is likely to lead the viewer into sin, or require sin of the artist - and especially, content which is inherently sinful. I will not say that such things will make you a worse artist, per se. Rather that they will make you a worse human. And as artistry is a subset adjective of humanity, such sacrifices of your greater self... these indescretions... these instances of inhesitancy... are at the very best a case of following the letter of the law to the (unbenefit?) rather than the spirit. It is like preparing so carefully for the rehearsal that you miss the performance (if the greatest warrior is the one who makes himself unnecessary, perhaps the greatest artist... hmmm...). At worst, it is obtuse and dangerous, like using the last of your water supply (after a drought) to wash your cat (or windows).

At times during such discussions I have often heard the question, generally skeptically put, of whether a particular work (say, a movie) "needs" a particular element (say, a sex scene) at all. Whether it improves the story, whether it is really (actually) vital to its structure. The implication is that the offending element is like a mosquito on a man's arm, a blemish on a work of art, clearly alien to (of?) the man/work itself, to be removed without doing anything wrong... or like shackles on the legs of a runner... whereas I say it is like when a runner is running in completely the wrong direction, or for the wrong reason, or with a bad form which leads to his injury... (this is a hard one). I dislike such remarks (questioning the usefulness of obscene scenes) because they seem to make a work of art and fiction a simple thing, sum of its parts, from which one element may be removed without affecting the others... (such an attitude is a blow against the nature of art, which is metaphysical and vague... what I propose is a blow against the work, which is available and soft...) I say, look to the heart of the problem, and ask whether the work ought to exist at all. I will go that far. I say, break your body and your heart, if necessary, for art; but break your pen rather than let it lead you into sin (or: break your pen rather than break the Law). You think I am telling you to give up the greatest and most mysterious rewards (aspects? parts? fruits!) of art/istry; but I am telling you to avoid those habits and prejudices (things) which come at or after the far end of art, but are not art; are abomination (sin, vice, etc. Milk turns to cheese turns to mold).
* characters acting out of character
In response to the question: "What do I think of this character NOW that s/he has done THIS?"

. . .

Stories have to earn this question from me. I mean they have to fight for it. My default position every act performed by every fictional character is "I don't care. They're imaginary. They might do anything." It's only after I've experienced the character doing enough in-character things that my brain starts to react to them as though they are a real person; it's only then that I care about what they do or what happens to them.

Out-of-character acts (if they truly are out-of-character) allow for some of the most potent scenes of tragedy, redemption, and irony; but by their very nature every one of them burns away a bit of the authenticity that makes me care about the character in the first place.

. . .

FOLLOWUP, INCLUDING METAPHORICAL MATH

Much as I want to lay into all your arguments point-by-point, I think there's an important distinction to be made. There's out-of-character, and then there's, well, out-of-character. I really wanted to put that in italics, but Facebook won't let me.

> "There's a discussion to be had about whether this is just a completely out-of-character thing for Jim to do. I've had it. It's a boring discussion. The actually interesting discussion is about what this (potential) betrayal actually means for who Jim is, and his relationship with Huck."

If this IS out-of-character for Jim, I mean actually out-of-character, then it by definition tells us NOTHING about who Jim is. If my brain tells me that according to Twain's fictional universe (which is basically the real universe), and according to what I know about Jim — if my brain tells me that this is something Jim would absolutely never do, then my suspension of disbelief is broken. How could it not be? I'm being fed contradicting information.

We may still use the phrase "out-of-character" to describe Jim's actions, and I think in normal conversation that's fine; but strictly speaking, what we really mean is either that it's out-of-character-given-normal-circumstances (which implies that circumstances are not normal), or that it's unexpected (which implies that there are aspects of Jim's personality which we were not previously aware of, but which do not contradict what we already knew of him).

(Here I wish to insert a mathematical analogy. But I don't know how you feel about such things, so I will leave it for a subsequent comment.)

The thing is, short of absurdism (for instance: Jim abruptly becomes a Gaelic-speaking firefighter with telekinesis), there's no clear dividing line between "in-character" and "out-of-character", any more than there's a clear dividing line between "show" and "tell", or between "homage" and "derivation".. There IS a line, it's just not clear. It's up to the readers and the critics — if criticism has any use at all — to try to figure out whether the line's been crossed at any given moment. Which is why the question "Is this out-of-character?" is worth asking.

(Note that I'm speaking very philosophically, and I don't really have any comment on your assertion that critics over-use "out-of-character!" as a complaint. I don't read many reviews, so as far as I know, you're completely right on this front.)

Mathematical analogy:

+ Suppose I tell you I'm thinking of a number between 1 and 100.
+ Suppose I tell you it's more than 6.
+ More than 7.
+ More than 8.
+ Perhaps by now you have a vague idea of what the number is.
+ Suppose I say it's more than 97. Well, that might be unexpected, but it's not contradictory. It only tells you more about the number. In fact, it makes the idea of the number in your head far clearer.
+ Now suppose I then tell you that the number is less than 5. Does that make the number clearer to you? No. It contradicts what I've already said. Either it's false, or all of my previous statements were false. At best, you can try to ignore this final statement and proceed from only the previous ones; at worst, you may become skeptical that I'm actually thinking of a number at all.

* Conciliar Post ideas
In defense (or at least, less offense ) of: smoking, gambling, tattoos (maybe even drinking and drugs).

In defense of contrived and tired thought experiments, such as the trolley problem, the famous violinist, etc.

How to read about current events without reading into an echo chamber.
* constraints
In art, as in life (?), it is often good or desirable to reduce the number of things a particular work is beholden to; the number of things that constrain it (though I have difficult describing precisely what I mean by "constrain" in this context). It is good to reduce constraints, but never the last constraint. Some attempts at metaphors that explain why:

Suppose you are floating in space, tethered to a space station. The more tethers you have, the more constrained your movement will be, but the greater control you will have over it. With only one tether, you will have the maximum possible range of movement. But if that final one is cut, you have no freedom of movement at all.

(In relation to that: perhaps the amateur ought to use many constraints, to have the easiest time moving about; whereas the master uses few, relying on their greater ability to navigate a greater possibility space)

Alternately, suppose lowering yourself into a chasm by many ropes and pullies. The fewer total ropes you use, the further down (greater depth of meaning or achievement) you can reach, with a greater risk of falling. But if you ever cut the final rope, you will be lost.
* my overly rigid numeral framework

** Events
4) Inevitable
3) Makes previous events make more sense
2) No effect on previous events
1) Makes previous events make less sense
0) Impossible

** Characters and concepts
3) Fully introduced
2) Partially introduced
1) Hinted
0) Unforseeable / deus ex machina

** Major characters/concepts
3) Introduced
2) Hinted
1) Known to be possible

** notes
Try to hit all three? Special requirements for anything that hits 3 in the second half, or final act? Maybe, dividing the story into 3 or 4 acts, say that you can only increment a concept's value by 1 per act, with the exception of Act 1, when you can introduce them at any level.

To qualify as "Hinted", there must be some appearance, however slight, of the concept, which the reader can (when the concept is more fully introduced) unambiguously identify as having been the concept.

To qualify as "partially introduced", the concept must make some sort of definite appearance
* narrative modes
Rough.

Note. Past, present, and future tense are grammatical concepts, and thereby only really make sense when applied to literature, or things with the same form as literature (such as narration during a film or game). PoV is also a grammatical concept, but seems to be a facet of, or point to, or have a counterpart in, a broader concept or set of concepts.

addressing reader vs not? ambiguous, if second-person. Difference between addressing reader as audience to fiction, and addressing reader as audience to true story? Same as difference between an in-character narrator and not-in-character narrator? A not-in-character, reader-addressing, first-person narrator would be absurd.

Theoretically, a story could either first- or second- person, or both, or neither; and every story is third-person, if it has enough characters. The question is more like, what is the identity of the focal character?

Maybe easier to say... theoretically, basically any combination is possible. A story could be simultaneously first, second, and third person, simultaneously past, present, and future. These rules or categories basically describe limitations, self-imposed... but without which, the reader has no real bearing.

Reader-addressing vs not?

** Grammatical point-of-view
+ First-person
+ Second-person
+ Third-person
+ Third-person (narrator)
++ Often implies a technically first-person point of view (specifically, when the narrator speaks as though the story is true), but is //effectively// third-person in nearly all cases.
+ Diegetic
++ Also called "epistolary". The individual pieces of the narrative may themselves be from other points of view, just as the dialogue of a given character in a given story can be from a different point of view.

** Time
+ Past
+ Present
++ Uncommon.
+ Future
++ Extremely uncommon.

** Subjectivity
+ Objective
+ Subjective

** Honesty (usually called "reliability")
+ Honest
+ Dishonest

** Voice
+ Objectively limited
++ Uncommon. Contradictory to pair this with first-person.
+ Character-limited
++ If first-person, contradictory to pair this with anyone but the narrator.
+ Omniscient 

* originality
I do not lament the loss of the ease of the availability of originality to the creator of narratives, to the artist, really, to the author. Because I think writing (artistry in general) is seen incorrectly. Artistry and writing, writing specifically is not the creation of something new, but the discovery of something already extant.

. . .


Strictly speaking, any work of more than 20 or 50 words is practically guaranteed to be original.

. . .

Most importantly, this whole issue of imperfection, whence springs all purpose for not only the artist but (perhaps) the human being as well.

* pithy rules
Yes, but
No, and

Revelations must make previous events make more sense, rather than less.
Revelations must feel surprising yet inevitable.

End every chapter with the main character worse off than the beginning.
* purpose of art
Art necessarily becomes more undefinable as it becomes more artistic - finally, definitions/analyses come to a state such that they are ONLY useful when they are PERSONALLY useful. That is, when they are part of our own singular interaction with, and understanding of, an artwork. Similarly, each person has their own private revelations during life...

Unless you are writing in your own personal journal, for no one else to see, then fiction (or writing) exists to be read. If it is unreadable, it is useless - at least, it's useless as fiction.

Part of the reason the meaning of day to day life escapes us is that, while fiction essentially exists for the reader, your life - especially if you are blessed, like a Christian, even like an American - will be used by God for the benefit of others [remember: quote by Chesterton near beginning of Heretics, on why art must make more sense than life, or something like that].

* Rhein's Law
Law: That which takes place in the viewer's mind is more compelling than that which takes place in the work.

Corollary: However, its compelling-ness is multiplied by exactly how clear it is.

Conclusion: The most powerful images are those which the audience is 100% has occurred, and which they were never shown.

If that sounds absurd, it's probably because of the enormous limitations in place. In practice, you can rarely get the audience to that 100%, and even if you can, you'll never be able to give that implicit image as much detail as the explicit image that is actually in the work.

. . .

I speculate that one reason for the law is that it bypasses some of the analytical or fact-checking processes of the brain. If I read that the princess was terrified for the life of the prince, I evaluate that statement; it becomes something else by the time I digest it. But if I read that, when the prince was struck, the princess screamed, then I evaluate that; and after the digestion is done, what I conclude, of my own cognition, is that she's terrified for the life of the prince.

I also think that part of my mind just believes that any conclusion I've worked out for myself is more likely to be true than one that was handed to me.
* endings, destroying the universe
When things are ending, in a narrative... when an episode is ending, but far more importantly when a series, a book, a long story is ending... I like for things to break on the way out. By reasoning of ^^Fiction Physics^^, the great bodies of energy that are moving around at the end - things are moving that have not recently moved, old anchoring points are being uprooted, pulled free from the ground - you have a lot of kinetic energy, a lot of mass in motion. So it makes sense that things will break. Paradigms will shift, local geography will change, and there is danger in the air. It is no longer safe even to sit still. The very environment changes. It changes in such a way that people are FORCED to change, to adapt, or allow themselves to be changed. Now, it almost goes without changing the MAIN characters will be changed in some way, frequently in an enormous way.

As stories become more episodic, more ensembles, as they become more about a place or a particular group of friends or a circumstance, as they become quaint, as they become, in short, institutional, there is a great temptation to send the crew into the horizon with essentially the same set of rules and circumstances as they had at the beginning of it all (or if not the beginning, then the state that existed near or prior to the beginning of the final arc). And then you kind of say, "And they continued on forever!" I don't like this for two reasons: one is because I don't like sequels, and this sows seed for sequels, and the other is that I wish to emphasize the strength of the bodies of energy that have been moving around at the end of the narrative, even when that is entirely metaphorical/metaphysical. So of course, if it's a story about a war, and at the end of the story one of the sides is defeated, then, yes, obviously that's a lot of things changing. But the subtlety afforded by this when the conflict is far less literal or physical or concrete... it's great. For instance, if it's simply about... well, examples are difficult to come up with, but if the primary storyline, the main characters' storyline, does not really totally modify the world, it's more about just them, but the metaphysical, the fictional-physical strings pulled, things unhinged, things unbalanced by the ending acts... that's what causes the damage. When I say "damage", I don't necessarily mean things literally destroyed or killed or hurt, but rather things streteched to their extreme, and then a bit further; I mean order subjected to entropy; I mean certain stores of energy used up, exhausted, spent; the damage can be in a positive way... I mean things affected to such a degree (good, bad, literal, physical, or otherwise) that they cannot return to their previous value. Perhaps a person feels a pain that they have never felt before, or they say words that cannot then be unsaid (such as finally professing one's love for another). 

a quote:

“...the characters make it out alive, but at a terrible cost, usually by the skin of their teeth. I want to see what's at the core of them, and stripping them down to that core is rarely pleasant for them. But it does make them wiser, and often stronger people.”

― Alexandre Voinov 

I think this connects to my points above. Furthermore, in comparing my philosophy with a "status quo is god" philosophy, I have the sneaking suspicion that, when you make everything at the end fall back to the status quo, you run the risk of showing that there is nothing to strip back; that, rather than the status quo being the truest or most interesting expression of your characters', instead it is the entire sum of their existence and personalities.
