* Bethel
** appeal

# What policy are you appealing?
CLEP credits not being accepted within the last 30 hours of a Bachelor's Degree.

# What are you requesting?
I request that Bethel accept the CLEP tests I've already taken, as well as several more that I have been planning on taking, so that I can finish my Bachelor's Degree.

# Rationale for the appeal:
The "Academic Policies & Procedures" section of the official Bethel course catalog says:

"Traditional students may not obtain credit by CLEP examinations within these last 30 hours."

This wording implies that this restriction does not apply to non-traditional students such as myself. This wording is present in the version of this document that was in effect when I returned to Bethel as an adult student, and it is present in the version of the document that's in effect now, at https://www.bethelcollege.edu/assets/images/student/PDFs/2017-2018_Bethel_Catalog.pdf

I returned to Bethel several years ago as an adult student to finish the degree that I'd started a decade ago. I have limited time and availability now - I'm married, have three kids, and live in Michigan - but I worked out a way to get the remainder of my credits through online classes and CLEP tests. I only have a few credits remaining, but if I can't get them according to the plan that I made, I'm not sure how long it's going to take.

** PLA questions

~5 paragraphs per

*** 1. Describe the experience by telling who, what, when and why you participated in the training. Be specific in your response citing dates and places and the length of time of your certification. If you have a license, tell what was needed to obtain and maintain that license.

Early on in my job search, my girlfriend (now my wife) suggested that CNA work might be a good fit for me. With her help, I found a local CNA training program called Michiana Healthcare Training (MHT), which operates out of downtown South Bend.

MHT is a small, independent CNA training program, not affiliated with any college or technical school. While most CNA programs take anywhere from 8-15 weeks, MHT's program was short and intensive, comprising just 3 forty-hour weeks. Week 1 was entirely in the classroom, and weeks 2-3 were clinicals and took place at a local nursing home (Regency Place of South Bend).

MHT's class was taught by a small number of veteran nurses, mostly women, who had been involved with the program for a number of years. I was one of about 10 students, and one of only 2 males. The classes were based around lectures and short quizzes, but also involved a number of demonstrations and hands-on practice, including learning to take vital measurements (heartrate, respirations, and blood pressure), doing range of motion exercises, shaving, backrubs, bathing, and helping get around.

During the clinical portion of MHT's training, we worked in the nursing home, under the direct supervision of one of MHT's teachers. We were required to demonstrate our ability to perform a large variety of tasks, including all those previously mentioned. Of special importance were our ability to correctly carry out bed baths and other cleaning procedures.

To finally earn our CNA license, we were required to pass a test, which was held about a week after our clinicals ended. This test was very tightly controlled, administered by a nurse who worked for the State of Indiana. Each of us in turn went into a room with the test administrator and one of our teachers, who was there to act as our "patient." The administrator had a stack of envelopes, and we would pick one at random, and open it to find the name of one of the procedures we had memorized. We then had to carry out this procedure on our "patient," exactly as we had been taught. As I recall, we would fail the test (and the entire course) if we made three minor errors (such as touching the wrong thing or forgetting to say something to the patient), or one major error (such as dropping the patient). During my test, I made one minor error: I put a used washcloth on the side of the bed instead of in the dirty laundry hamper.

To maintain my licence after acquiring it, I had to work a minimum number of hours per year as a CNA, as well as go through an annual licence renewel process.

After this, to maintain my licence, I had to work a minimum number of hours per year as a CNA, as well as go through an annual renewel process.

*** 2. Reflect on your experience and relate your thoughts and observations. Was this experience valuable? Why? Why not?

In the most direct sense, my experience was valuable in that it allowed me to work as a CNA, which I did for about six years. I worked in two different assisted living facilities, in two clients' homes, and at a staffing agency which sent me to several additional locations.

Aside from the certification, I would say that MHT succeeded in teaching me what I needed to know to get started doing actual work as a CNA. The procedures I learned at MHT, as well as the general expectations of healthcare facilities, matched up pretty well with the places I actually worked, with a few exceptions where recent advances in medicine had made MHT's curriculum outdated.

The clinical portion of MHT was particularly helpful, and is now much easier for me to recall than the classroom portion. I recall seeing how effectively one of my teachers was able to communicate with patients, even those who were impatient, impolite, or barely coherent. I was able to see what the patients actually valued in what I was able to give them, and what they merely put up with. I also started to learn how to communicate with nurses, doctors, and other higher-up healthcare staff. As a CNA, I was often the first and closest level of care that my patients had.

While I have no particular complaints about the classroom portion of MHT's program, I am less inclined to say that it was exceptional. It was quite servicable, but I'm sure there are many other ways you could conduct such a class that would be just as effective.

*** 3. After reflecting, identify specific concepts, theories, rules or principles that would make this a college level learning experience.

MHT's program required a good deal of commitment and discipline to get through all three weeks, as well as the final test. For the classroom portion, we were given basic studying materials, and of course the classes themselves, but we were not given any special guidance as to how much or in what way we should continue our study of the material outside of classtime. This was left entirely up to us as students. The tests we had throughout the first week were comparable to many tests I've received during college classes, and the final test was certainly more strict than any I've had in a college class.

CNA's tend to work with very constrained time, and so they don't have the ability to refer back to educational materials or their supervisors about how to perform particular procedures or answer particular patient requests. There are also many safety concerns which they have to keep in mind during the course of their work, especially regarding those patients who are fall risks or choking risks, to say nothing of the particular behavioral, dietary, or other problems patients may have. Because of all this, CNAs can only function if they have a ready, working knowledge of a large number of standard procedures and policies. Learning these procedures and policies began in the classroom, but necessarily continued outside of it. In particular, I remember spending my evenings developing mnemonics and using flashcards to memorize key concepts and steps.

While many college classes are deal primarily in theoretical material, others are mostly practical, and it's to these classes that I would compare MHT's program. Like such college classes, we were expected to learn not only the specific policies and practices of our work, but also the reasoning behind them, the common pitfalls that inexperienced practitioners may fall into, and an overall philosophy of care that could serve us when we were faced with difficult decisions and ambiguous circumstances. As students, we sometimes had to work together, and sometimes on our own, to learn and carry out the various skills and competencies involved in CNA work.

Finally, the total amount of time required to complete the course was significant: 40 hours of classroom time (comparable to a college class), and 80 hours of clinicals.

*** 4. Tell how you have applied these learning concepts on your job and in your personal life.

MHT's program helped me learn to be rigorous and thorough in my work. Many of the procedures we learned are quite strictly defined, to the point that they regulate what you can and cannot touch, when you have to wash your hands, and what kinds of words to use with the patient. In particular, I recall that the bed bath routine - one of the most complex - involved changing gloves four times, changing water twice, and using five washcloths and two regular towels.

Other guidelines were also very important. We were taught to announce ourselves before entering a room, to explain to our patients everything that we were going to do with or to them, to patiently answer their questions, and (except in cases where patients had lost the legal ability to make their own decisions) to always honor our patients' right to refuse procedures or treatments. Outside of CNA work, these rules helped me learn to be clear and precise with the people with whom I work, to lay out expectations clearly, and to protect myself from a legal point of view.

I also learned to be a calm and collected presence in situations that others may find uncomfortable. Throughout my clinicals, I worked with bodily waste (many nursing home residents are incontenent), infectous diseases, disagreeable patients, narrow time constraints, and superiors who demanded a high level of care at all times. But because CNAs work directly with healthcare patients and their families, we were required to always be kind, curteous, and helpful in all our interactions. We were required to keep cool heads and always respond objectively, according to the guidelines of the current situation. This is a set of skills that can be applied to any job, but especially any job that is customer-facing. I have applied them not only to my work as a CNA, but to my work in other, non-healthcare jobs, and even in my personal life, especially with my children, who are 5 years, 4 years, and 2 months old, and to older relatives, such as my grandparents, some of whom are in the same medical categories as people whom I've worked with as a CNA.

* grad school admission process
** Andrews University

MBA, 33-credit, 3 full-time semsters
tuition reduction limited to 3+ incoming GPA
$1,073 per semester
various prerequisite classes

** Bethel College

MBA - $5555 per semester

** IUSB

Computer Science
General Business
Mathematical Sciences
MBA

*** application cover letter

Dear Sir or Madam,  

Thank you for considering my application to the IUSB College of Liberal Arts and Sciences. I’m grateful for the opportunity and would like to offer additional explanation of my academic record and why I believe I am a good candidate for graduate education at IUSB. 

When I started my undergraduate degree as a highschool guest at the age of 17 years old, I did not have a clear idea of what exactly I wanted to accomplish. I was also struggling with some personal problems which negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. Half a decade later, when I returned to finish my bachelor’s degree, I had a better understanding of myself. I earned ‘A’s in all my remaining classes, checked off the rest of my degree requirements with CLEP tests (following independent study of the subject areas), and finally graduated in May 2018. 

With the years I’ve spent outside of school, working and raising my family, I feel I’m now ready to confidently move my education and career forward. In particular, my lifelong interest in computers, combined with a year working as IT support for a local non-profit, solidified my decision to further my education in computer science. After some searching, I’ve determined that the College of Liberal Arts and Sciences at IUSB is the ideal place for me to pursue this end. 

Due to my poor performance at the beginning of my undergraduate career, my graduating grade point average was just over 2.7. However, this GPA does not take into account the 33 credits I earned through independent study and CLEP exams after my return to school as an adult. (CLEP scores contributed earned credits, but did not affect GPA at the institution I attended). I believe that my Graduate Record Exam scores are a more accurate reflection of my current preparedness for graduate work. On the general GRE, I received a 166 in Quantitative Reasoning, as well as a perfect 170 in Verbal Reasoning, and a 5.0 in Analytical Writing. These scores, and my successful undergraduate degree completion utilizing maximal self-study, demonstrate that, despite my spotty GPA, I am well positioned to succeed in the IUSB School of Liberal Arts and Sciences. I look forward to further learning and growing as I complete a master’s degree in applied mathematics and computer science and hope to be a credit to the institution. 

 

Nathaniel Rhein 

*** financial aid request letter
Thank you for considering my application. I'd like to tell you why I believe I am a good candidate for financial aid at Indiana University South Bend.

I wasn't always a good student. When I started my undergraduate degree ten years ago, I had little direction or motivation, and it showed in my poor performance. At the urging of friends and family, I took a break from school to explore volunteer and work opportunities. I spent several months as a volunteer grade school teacher in the Nairobi, Kenya, then became licensed as a Certified Nursing Assistant and worked in that capacity for several years. I got married and had three kids. Eventually, I stopped working to stay at home with my children while my wife became the primary breadwinner for our family.

I love taking care of our children. It reminds me of my time in Kenya, as well as the years I've spent teaching Bible classes and watching the nursery at my home church. However, the past few years have shown me that to truly provide for my family, I need to start working on my career. My wife wants and deserves more time at home with our kids. And, if I'm honest, I long for the challenge of new ideas and difficult classes again.

So, I resumed my latent Bachelor's degree. With the direction and motivation that I lacked ten years ago, I was able to earn A's in all my remaining classes, as well as 33 credits gained through CLEP tests and self-study. I also took the GRE, both as preparation for future coursework, and as a demonstration of my ability to complete that coursework. Finally, having decided that computer science and mathematics are the two fields that most interest me, and having investigated a number of universitiies across the country, I've determined that IUSB's graduate program is the best fit for me.

While my wife and I are excited and confident about my prospects at IUSB, our financial position does not provide a great deal of flexibility, especially considering our three young children, the oldest two of whom are just starting school themselves. We've crunched the numbers, and it looks as though we will only be able to pay for my Master's if we have some sort of financial assistance.

I thank you again for your consideration, and eagerly await your response.
** Western Michigan University

information requested

** SENT - Western Michigan University - MS in Statistics

Hello! I'm interested in applying for the MS in Statistics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

** SENT - University of Idaho - MS in Statistics

Hello! I'm interested in applying for the MS in Statistics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

** SENT - University of Oklahoma - Online Masters of Science in Data Science and Analytics

Hello! I'm interested in applying for the MS in Data Science and Analytics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and analytics and the opportunities they provide, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

** SENT - Emporia State University - Masters of Science in Mathematics

Hello! I'm interested in applying for the MS in Science in Mathematics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in math, especially statistics and analytics, and the opportunities they provide, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

** SENT - IUSB - Kelley School of Business - MS in Business Analytics

Hello! I'm interested in applying for the MS in Business Analytics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in analytics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

* analytics
** IUSB - Kelley School of Business - MS in Business Analytics
*** email

Hello! I'm interested in applying for the MS in Business Analytics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in analytics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

*** email response

Hi Nathaniel,

Thank you for your interest in our program.  Have you taken the GMAT or GRE?  The best way to try and ¡°over-shadow¡± a low GPA is to score well on the GMAT or GRE.  Our average GMAT score is around 640.  Please let me know if you have any questions.

Best,
Wendy L Shively

** University of Oklahoma - Online Masters of Science in Data Science and Analytics
*** email

Hello! I'm interested in applying for the MS in Data Science and Analytics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and analytics and the opportunities they provide, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

*** email response

Hello,

Thank you for your interest in our program.  Do not let a lower GPA stop you from applying, we look at you as a whole and not just a GPA. The program does have prerequisites, they are Calculus I, Calculus II and Linear Algebra.  We also ask that you have two semesters,  or at least a year work experience, of higher language programming (Java, Python, C++).

To complete the application you will need to:

Complete an online application through Graduate Admissions here
Attach your statement of purpose and resume
Submit three letters of recommendation
Send your official GRE score
Submit your undergraduate transcripts with degree and GPA posted

Please do not hesitate to contact me with any questions.

Kind regards,
Nicola Manos

* cybersecurity
** Masters degrees

[[https://www.cdm.depaul.edu/academics/Pages/MS-in-Cybersecurity.aspx][DePaul]]
[[https://www.davenport.edu/programs/technology/master-of-science/master-of-science-information-assurance-msia][Davenport]]
[[https://www.worldcampus.psu.edu/degrees-and-certificates/information-sciences-masters/overview][PennState]]

** certificates

https://www.burning-glass.com/blog/how-to-get-a-cybersecurity-job-in-three-charts-a-degree-a-certification-and-a-clearance/
https://www.isc2.org/Certifications/CISSP#
https://www.reddit.com/r/cissp/comments/7oaeay/passed_the_exam_cat/
https://www.reddit.com/r/cissp/comments/7mv3xo/will_cissp_eventually_become_a_joke_like_ceh/
https://www.reddit.com/r/cissp/comments/7t54nc/failed_cissp_123_advice_please/

* electrician

Still need to get Parchment to send my transcript to the union.

[[https://ask.metafilter.com/73618/What-are-the-pros-and-cons-of-an-electrical-apprenticeshipcareer][discussion on AskMeFi]]

* math
** Emporia State University - Masters of Science in Mathematics
*** email

Hello! I'm interested in applying for the MS in Science in Mathematics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in math, especially statistics and analytics, and the opportunities they provide, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

** IUSB
* MBA
** Andrews University

MBA, 33-credit, 3 full-time semsters
tuition reduction limited to 3+ incoming GPA
$1,073 per semester
various prerequisite classes

** Bethel College

MBA - $5555 per semester

** IUSB
* statistics
** [[https://www.worldcampus.psu.edu/degrees-and-certificates/applied-statistics-masters/overview][PennState - MS in Applied Statistics]]
** University of Idaho - MS in Statistics
*** email

Hello! I'm interested in applying for the MS in Statistics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

*** email response

Hello Nathaniel,

I apologize for the delay in getting back to you. The minimum GPA is 3.0; however, we do make exceptions to this rule occasionally and, in this instance, it sounds as if you would be able to explain that you were off to a rough start and improved. We understand life happens.

We do want to make sure that you would be successful in our program though. I cannot say whether this program would be a good fit for you or not; we would need to see your entire application in order to determine that. Have you taken the prerequisite courses for the stat program? We do have our admission requirements listed on the following page: http://www.uidaho.edu/sci/stat/admissions. If you have not, there are options for you, such as taking these courses as a non-degree seeking student.

Just in case you would like a bit more information about our program, the websites would be a great place to review:

Statistics Academic Description http://www.uidaho.edu/sci/stat/academics
Statistical Science Department http://www.uidaho.edu/sci/stat
Graduate Admissions  https://www.uidaho.edu/admissions/graduate  
Online degree https://eo.uidaho.edu/
Engineering Outreach (online courses) https://eo.uidaho.edu/  
Engineering Outreach Fees https://eo.uidaho.edu/fees

Please feel free to contact us at any time should you have any further questions!

Thank you,
Melissa

*** Admissions

Students seeking admission to M.S. graduate study in statistics at UI are requested to submit transcripts from undergraduate studies and three letters of recommendation along with a statement of purpose. All application materials should be submitted electronically to Graduate Admissions in the College of Graduate Studies. Completed application files are then sent from Graduate Admissions to the Department of Statistics Admissions Committee for consideration only after deemed complete by Graduate Admissions.

*** Prerequisites for Graduate Work

All students who wish to do graduate work in statistics should have a background in quantitative methods. Specific prerequisites include:

Math 175, Analytic Geometry and Calculus II
Six hours of statistics, including Stat 431 or its equivalent
Knowledge of at least one higher level programming language

*** Financial Assistance

Financial support is available in the form of academic year Teaching Assistant appointments. A limited number of TA positions are available each year. Details of stipends and application procedures are available upon request. Please note that TA applications from students who have not officially applied or have been accepted for admission to the Statistics program are not considered for assistantships.

** Western Michigan University - MS in Statistics
*** email

Hello! I'm interested in applying for the MS in Statistics, but I have some questions and concerns which I hope you might be able to help me with.

At the time I started my undergraduate degree, I was suffering from some personal problems that negatively affected my motivation and performance. Eventually, I took a break from school to focus on working, starting a family, and exploring my long-term goals. When I went back to finish my Bachelor's, with a better understanding of myself, I was able to able to get 'A's in all my remaining classes, and I am on track to graduate this May. However, due to my previous poor performance, I will be graduating with 2.7 GPA, and poor grades in most of the math classes I took.

I'm very interested in statistics and the opportunities it provides, and I believe I can succeed in the field. Do you think that your program would be a good fit for me? If so, what steps should I take before applying?

Thank you for your time,

Nathaniel Rhein

*** email response

Nathaniel,

It is hard to tell how well our program would fit you based on the information you gave. If you have all prerequisite math classes for the program, I suggest that you go ahead and apply. There is a personal statement you can upload that explains your specific circumstances.

Joshua Naranjo
Graduate Advisor, Statistics

* recommendation letter shortlist

Dave Smith
Rick Tribble
Dave Seyboldt
Rick Stuckwisch
Donna Harrison
Charley Horner
Bethel profs?

* Graduate school federal codes

Bethel
Fall 08-12
Spring 01-05?

Western Michigan University
002330
(Spring 2019) Information Security online MS (no CS or IS offered at branches within 2 hours)
"Western Michigan Universitys Graduate School Institution Code is 1902"

Michigan Technological University
002292
Master's of Engineering (MEng)
"Official test scores can be sent to the Graduate School using our School Code: 1464.
Official transcripts can be mailed to:  
      Graduate School  
      Michigan Technological University  
      1400 Townsend Drive  
      Houghton, MI 49931-1295  
      USA


University of Michigan - Ann Arbor
002325
Didn't apply. Very far away.

Indiana University South Bend
001816

* GRE
** 1. Verbal Diagnostic Test
14/20 = 155-157

hoi-polloi
peccadilloes

** 2. Math Diagnostic Test
14/20 = 155-157

negatives. fractionals.

** 3. Text Completions
118/144

lascivious
peccadilloes
garrulous
parlous
sangfroid
mercurial
distension
expatiation
arcadian
hinterland
parochial
scintillating
feckless
voluble
explicate
dilettantes
balkanized
patrician
dissembled

** 7. Arithmetic

27/28

proper unit conversion (mi/gal vs km/li, etc)

** 8. Algebra

23/35

lots
** 9. Inequalities and Absolute Values
35/41

A>B = -A<-B

Multiplying or dividing an inequality by a variable can only really be done if it's known whether the variable is positive, negative, or zero.

a^2 - b^2 = (a+b)(a-b)

sqrt(a) * sqrt(b) = sqrt(ab)

a/b * c/d = ac/bd

a/b + c/d = ad+bc/bd

(a/b = c/d) = (ad=bc)

a^6 - b^6 = (a^3 + b^3)(a^3 - b^3)
** 10. Functions, Formulas, and Sequences

50/57

Look for common factors before doing long form

Decimal to fraction via x/1 or whatever

sqrt(x) / sqrt(y) = sqrt(x/y)

** 11. Fractions and Decimals

33/38

Try to x100 multi-level fraction word problems? Unsure
** 12. Percents

48/54

Practise cross-multiplying

Write percents carefully

"Percent" vs "percent more"

Numeric answers only have *one possibility*

** 13. Divisibility & Primes

27/33

"decimal" = after the period

010 is not a three digit number

** 14. Exponents and Roots

23/30

b-sqrt(a) = a^(1/b)

sqrt(x^3) = x*sqrt(x)
** 15. Number Properties
??? lost
** 16. Word Problems
100% but lost
** 17. Two-Variable Word Problems
skipped
** 18. Rates and Work
in progress, did 1-18, lost paper, re-do later?
** 19. Variables-in-the-Choices Problems
2/2
** 20. Ratios
33/36

Values vs amounts (comparing currencies...)
** 21. Averages etc
33/37 (all dumb)

Read/do all problems twice, if possible.
** 22. Standard Deviation etc
23/31

MEMORIZE NORMAL DISTRIBUTION

BE STRICT

Percentiles correspond to actual datum/data

Does box-whisker correspond to quartiles or percentiles? Quartiles can be inbetween values, but percentiles cannot...

** 23. Probability
41/46 all dumb

4&9 are not prime

RE-READ
** 24. Data Interpretation

Got 19/19 correct, skipped the rest.

** 25. Polygons...

20/22

Total of interior angles of polygon
(n-2)180

** 26. Circles...

22/25

Central angle is double edge angle.

** 27. Triangles

33/42

Might not be necessary, but angles/area from lengths?

Likewise, quadratic formula...

30-60-90 triangles: x, 2x, x*sqrt(3)

** 28. Coordinate Geometry
18/24

Slope-intercept:
mx+b
m = slope
b = y-intercept

"Standard parabolic formula"??

Slope of perpendicular = -1(reciprocal)

** 29. Mixed Geometry
** 30. Advanced Quant
1-15: 4 wrong

Continuous probability = area under the curve

Practise reverse FOIL (factoring)

Trick! Questions! Is this question tricking you?
