* old CLEP notes
** US History notes

John Winthrop
The French and Indian War
Roger Williams
The Great Awakening
Sir William Blackstone
"Letters from a Farmer in Pennsylvania"
"The Articles of Confederation"
"The Articles of Confederation"
"The Articles of Confederation"
"The Treaty of Paris of 1783"
"Common Sense"
"The Bill of Rights"
"The Bill of Rights"
The Embargo Act of 1807
The Tax Act
Henry Clay
Henry Clay's American System
Louisiana Purchase
Monroe Doctrine
Civil War dates
Jacksonian banking policies
John C. Calhoun
"putting-out system"
Brook Farm
Oneida Community
Whig Party
Tariff of 1789
Bank of the United States (first)
Bank of the United States (first)
Bank of the United States (second)
Manifest Destiny
Kansas-Nebraska Act
Missouri Compromise
Northwest Ordinance of 1787
Northwest Ordinance of 1787
Compromise of 1850
Compromise of 1850
Fugitive Slave Act
"Moby-Dick"
"The Scarlet Letter"
"Leaves of Grass"
William Lloyd Garrison
Free Soil
1848 women's rights convention in Seneca Falls
"Uncle Tom's Cabin"
Louisa May Alcott
Herman Melville
Harriet Beecher Stowe
Harriet Beecher Stowe
Richard Henry Dana
Kate Chopin
Reconstruction (Abraham Lincoln)
Reconstruction (Andrew Johnson)
Radical Republican
Benjamin Bannker
Lemuel Haynes
Phillis Wheatley
Gabriel Prosser
Sojourner Truth
Sojourner Truth
Auburn system
Wilmot Proviso
"Incidents in the Life of a Slave Girl"
Frances Ellen Watkins Harper
Lydia Maria Child
Harriet Jacobs
Freedman's Bureau
Gadsden Purchase
Harvard College
Common School movement
William Lloyd Garrison
Harriet Tubman
Harriet Beecher Stowe
Roger Taney
John Peter Zenger
Bacon's Rebellion
Saratoga, Oct 1777
The Treaty of Paris of 1783
The War of 1812
"The Life and Times of Frederick Douglass"
Shays' Revellion
Whiskey Rebellion
Hartford Convention
Norwest Ordinances
New Harmony
Oneida Community
Brook Farm
The Shakers
disputed election of 1873
Puritans
Quakers
Jay Treaty of 1794
Mexican-American War
"Second Treatise on Government" (John Locke)
"Leviathan"
Thomas Hobbes
"Of Civil Liberty" David hume)
David Hume
Jean-Jacques Rousseau
"The Social Contract"
Pierre-Joseph Proudhon
"An Inquiry into the Princple of Right and Government"
Freedman's Bureau
Second Great Awakening
First Great Awakening
Federalist Party
Fugitive Slave Act of 1850
American Colonization Society
Freedman's Bureau
Reconstruction Acts of 1867
Sioux war
transcendentalism
pragmatism
the Gospel of Wealth
the Social Gospel
Social Darwinism
anticombination laws
William Jennings Bryan
Samuel Gompers
pure and simple unionism
political machines
Frederick Jackson Turner
Ernest Hemingway's
"The Sun Also Rises"
Sylvia Plath's
"The Bell Jar"
T. S. Eliot
"The Love Song of J. Alfred Prufrock"
Sinclair Lewis
"Babbitt"
Theodore Dreiser
"An American Tragedy"
Woodrow Wilson's Fourteen Points
Bonus Army
Wagner Act (National Labor Relations Act) of 1935
National Women's Party
Reagan Revolution
Korean War
Geneva Accords (1954)
Allen Ginsberg
Roy Wilkins
Martin Luther King, Jr.
James Farmer
Stokely Carmichael
Whitney M. Young, Jr.
Ngo Dinh Diem
American Indian Movement (AIM)
"silent majority"
Star Wars
Prairie School of architecture
Stanford White
Frank Gehry
Frank Lloyd Wright
Louis Sullivan
Daniel Burnham
Civil Rights Act of 1964
"The Fire Next Time"
James Baldwin
Aid to Families with Dependent Children (AFDC)
Equal Rights Amendment
Harriet Tubman
Ida B. Wells
Emma Goldman
Aimee Semple McPherson
Alice Paul
Chinese Exlcusion Act
Stonewall Riots
Reaganomics
Populism
Truman Doctrine
Gulf of Tonkin Resolution
Cuban missile Crisis
Federal Reserver System
Wade-Davis Bill
Hatch Act
Morrill Land Grant Act
Homestead Act
Dawes Severalty Act
Langston Hughes
Zora Neale Hurston
The Lost Generation
The Beat movement
The Black Power movement
The Niagara movement
The Harlem Renaissance
Boxer Rebellion
Russo-Japanese Wars
Mexican Revolution
Bolshevik Revolution
Women's Trade Union League
Title IX
Klu Klux Klan
Compromise of 1877
Good Neighbor policy
Carter Doctrine
"The Birth of a Nation"
Voting Rights Act
Betty Friedan
"The Common Sense Book of Baby and Child Care"
"Unequal Sisters"
"The Second Sex"
"The Feminine Mystique"
"The Beauty Myth"
Job Corps
Elementary and Secondary Education Act
Environmental Protection Agency
Gilded Age

** American lit notes

The Federalist
James Madison
Sky Woman, Wolverine, Turtle
Puritan allegorical tales
Frontier tall tales
African American animal fables
Native American oral tales
Hispanic American magical-realist stories
Roger Williams
John Smith
John Winthrop
The Virginia Colony
The Massachusetts Bay Colony
The Colony of Rhode Island
Puritanism
Transcendentalism
Naturalism
Realism
Deism
Thomas Paine
"Common Sense"
"The Autobiography of John Adams"
Crevecoeur
"Letters from an American Farmer"
Franklin
"The Way to Wealth"
Freneau
"On the Causes of Political Degeneracy"
William Bradford
"The History of Plimouth Plantation"
Jonathan Edwards
"Sinners in the Hands of an Angry God"
James Fenimore Cooper
"The Pioneers"
Washington Irving
"Rip Van Winkle"
Nathaniel Hawthorne
"The Scarlet Letter"
Anne Bradstreet
Margaret Fuller
Cotton Mather
Phillis Wheatley
Samson Occom
Mary Rowlandson
Elizabeth Ashbridge
Edward Taylor
postmodernism
naturalism
realism
sentimentalism
regionalism
Walt Whitman
"Out of the Cradle Endlessly Rocking"
Olaudah Equiano
William Wells Brown
Frederick Douglass
Charles Brockden Brown
Harriet Jacobs
Nathaniel Hawthorne
"the House of the Seven Gables"
Ralph Waldo Emerson
"Nature"
Edgar Allen Poe
"The Philosophy of Composition"
Walt Whitman
"Democratic Vistas"
Henry David Thoreau
"Walden"
Henry David Thoreau
"Civil Disobedience"
Ralph Waldo Emerson
"Self-Reliance"
James Russell Lowell
"Democracy"
Henry James
"The American"
Oliver Wendell Holmes
"The Autocrat of the Breakfast Table"
Jonathan Edwards
"Freedom of the Will"
Nathaniel Hawthorne
"The Scarlet Letter"
Herman Melville
"Typee"
Washington Irving
"The Legend of Sleepy Hallow"
Edgar Allen Poe
"The Fall of the House of Usher"
Gettysburg Address
Declaration of Independence
Preamble to the Constitution
Bill of Rights
"Common Sense"
Ethan Brand
Herman Melville
"Hawthorne and His Mosses"
Wal Whitman
"Leaves of Grass"
Ralph Waldo Emerson
"The Poet"
Theodore Dreiser
"True Art Speaks Plainly"
"The Philosophy of Composition"
Mary Wilkins Freeman
Sarah Orne Jewett
Harriet Beecher Stowe
Rebecca Harding Davis
Louisa May Alcott
Thomas Sutpen
Henry Fleming
Clyde Griffiths
Frederic Henry
Nick Carraway
Ernest Hemingway
"The Last of the Mohicans"
"Moby-Dick"
"The Scarlet Letter"
"Walden"
"Adventures of Huckleberry Finn"
"My Kinsman, Major Molineux"
"The Minister's Black Veil"
"Rappaccini's Daughter"
"Bartleby the Scrivener"
"Benito Cereno"
Henry James
"Daisy Miller"
Stephen Crane
"The Open Boat"
Kate Chopin
"The Awakening"
Emily Dickinson
William Dean Howells
Henry James
transcendentalism
symbolism
realism
romanticism
naturalism
James Fenimore Cooper
Harriet Beecher Stowe
Frederick Douglass
Edgar Allen Poe
Edith Whatrton
Sui Sin Far
Joy Harjo
Willa Cather
Diane Glancy
Zitkala-Sa
Edith Wharton
Sojourner Truth
Lydia Maria Child
Mary Wilkins
Freeman
Charlotte Perkins Gilman
Theodore Dreiser
George Washington Cable
Bret Harte
Emma Lazarus
"The New Colossus"
"The House Behind the Cedars"
"The Marrow of Tradition"
Mark Twain
Frederick Douglass
Theodore Dreiser
Charles W. Chesnutt
Paul Laurence Dunbar
Stephen Crane
Theodore Dreiser
Frank Norris
John Steinbeck
"The Grapes of Wrath"
Booker T. Washington
"Up From Slavery"
F. Scott Fitzgerald
John P. Marquand
John Steinbeck
Sinclair Lewis
Theodore Dreiser
"The Souls of Black Folk"
W. E. B. Du Bois
Richard Wright
Harriet Tubman
Langston Hughes
Jean Toomer
Ezra Pound
"In a Station of the Metro"
romanticism
surrealism
futurism
imagism
postmodernism
Harlem Renaissance
Frederick Douglass
Zora Neale Hurston
Phillis Wheatley
Alice Walker
James Baldwin
Sarah Orne Jewett
Willa Cather
Flannery O'Connor
"The Things They Carried"
"The Naked and the Dead"
"For Whom the Bell Tolls"
"The Great Gatsby"
Eudora Welty
Flannery O'Connor
Thomas Wolfe
William Faulkner
Robert Penn Warren
Edna St. Vincent Millay
Gertrude Stein
Marianne Moore
H. D.
Amy Lowell
Jessie Weston
"From Ritual to Romance"
Wallace Stevens
T. S. Eliot
Robert Frost
Marianne Moore
Langston Hughes
August Wilson
"The Crucible"
"A View from the Bridge"
"The Piano Lesson"
"Fences"
"The Iceman Cometh"
"Desire Under the Elms"
"Dutchman"
"The Slave"
"Cat on a Hot Tin Roof"
"Sweet Bird of Youth"
O. Henry
Frank Norris
Eugene O'Neill
"The Glass Menagerie"
"The Hairy Ape"
"Trifles"
"A Raisin in the Sun"
"Death of a Salesman"
Carl Sandburg
Upton Sinclair
"The Jungle"
Carson McCullers
"The BAllad of the Sad Cafe"
Richard Wright
"Native Son"
Nella Larsen
"Passing"
Thomas Wolfe
"Look Homeward, Angel"
Tennessee Williams
"The Glass Menagerie"
"The Golden Apples"
Eudora Welty
Sherwood Anderson
Dorothy Parker
John Cheever
Katherine Anne Porter
Harper Lee
"To Kill a Mockingbird"
"All the King's Men"
"The Age of Innocence"
"Henderson the Rain King"
"Invisible Man"
"The Catcher in the Rye"
Flannery O'Connor
"A Good Man Is Hard to Find"
"Mumbo Jumbo"
"If He Hollers Let Him Go"
"Beloved"
"The Color Purple"
"The Crying of Lot 49"
"Their Eyes Were Watching God"
"Go Tell it On the Mountain"
"Light in August"
Toni Morrison
"Song of Solomon"
"Beloved"
"The Bluest Eye"
"Sula"
"Tell Me a Riddle"
"House Made of Dawn"
N. Scott Momaday
Louise Erdrich
Leslie Marmon Silko
Toni Cade Bambara
Jack Kerouac
"The Crying of Lot 49"
"Night"
"Slaughterhouse-Five"
"Maus"
"Ceremony"
Paula Vogel
Tony Kushner
Suzan-Lori Parks
"How I Learned to Drive"
"Topdog/Underdog"
"Angels in America"

apostrophe
assonance
enjambment
iambic tetrameter
epigram

** English lit notes

"The Way of All Flesh"
"Through the Looking Glass"
"Gulliver's Travels"
"The Pilgrim's Progress"
"Robinson Crusoe"
"Macbeth"
"Julius Ceasar"
"King Lear"
"Othello"
"Hamlet"
Samuel Richardson
Henry Fielding
Tobias Smollett
John Donne
Edmund Spenser
Christopher Marlowe
William Shakespeare
John Milton
Geoffrey Chaucer
William Shakespeare
Alexander Pope
William Wordsworth
Ben Jonson
Alfred Tennyson
"Ulysses" (Alfred Tennyson"
T. S. Eliot
"The Love Song of J. Alfred Prufrock"
Alexander Pope
Robert Herrick
Samuel Taylor Coleridge
Samuel Johnson
John Donne
"The Waste Land"
"The Rime of the Ancient Mariner"
"Songs of Innocence"
"The Faerie Queene"
"The Rape of the Lock"
"Victory"
"A Portrait of the Artist as a Young Man"
"Tess of the D'Urbervilles"
"The Egoist"
"Sons and Lovers"
Romanticism
Neoclassicism
Expressionism
Naturalism
Abstractionism
heroic couplets
terza rima
ballad meter
blank verse
iambic tetrameter
popular ballad
pastoral elegy
courtly lyric
villanelle
chavalric romance
pastoral elegies
literary ballads
mock epics
dramatic monologues
irregular odes
an epix simile
a metaphysical conceit
an epic catalog
an alexandrine
sprung rhythm
synecdoche
pathetic fallacy
stream of consciousness
an eclogue
an epiphany
ballad meter
blank verse
elegiac stanza
rhyme royal
heroic couplets
Virginia Woolf
"Professions for Women"
Anita Desai
"In Custody"
"Hamlet"
"Beowulf"
"Paradise Lost"
"Lycidas"
"The Canonization"
W. B. Yeats
Elizabeth Barrett Browning
John Donne
John Milton
Gerard Manley Hopkins
"Pamela"
"Jane Eyre"
"Tom Jones"
"Tristram Shandy"
"Moll Flanders"
"Pride and Prejudice"
"The Rover"
"The Rivals"
"She Stoops to Conquer"
"As You Like It"
"Lord Jim"
"Briefing for a Descent into Hell"
"A Tale of Two Cities"
"A Passage to India"
"Ulysses"
"Riders to the Sea"
"Equus"
"Waiting for Godot"
"Look Back in Anger"
"Murder in the Cathedral"
Mill
Carlyle
Tennyson
Virginia Woolf
Doris Lessing
George Orwell
Margaret Atwood
E. M. Foster
William Shakespeare
Christopher Marlowe
John Milton
Percy Bysshe Shelley
Lord Byron
parody
pathos
propaganda
irony
harangue
mock epic
roman a clef
novel of manners
picaresque novel
romance
John Milton
"Paradise Lost"
Mary Shelley
"Frankenstein"
Emily Bronte
"Wuthering Heights"
Robert Louis Stevenson
"Dr. Jekyll and Mr. Hyde"
Bram Stoker
"Dracula"
"Sir Gawain and the Green Knight"
"Morte D'Arthur"
"The Faerie Queene"
"Visions of the Daughters of Albion"
"Idylls of the King"
epistolary novels
chronicles
social novels
vignettes
serealized novels
Daniel Defoe
Jane Austen
Charles Dickens
Matthew G. Lewis
Mary Shelley
Geoffrey Chaucer
"Troilus and Criseyde"
William Langland
"Piers Plowman"
Margery Kempe
"The Book of Margery Kempe"
John Gower
"Confessio Amantis"
Mary Wroth
"Pamphilia to Amphilanthus"
Wilfred Owen
Rupert Brooke
Edith Sitwell
"The Soldier"
"Anthem for Doomed Youth"
"Still Falls the Rain"
"A Clockwork Orange"
"Half a Life"
"Brave New World"
"Things Fall Apart"
"1984"
"Lyrical Ballads"
Samuel Taylor Coleridge
Percy Bysshe Shelley
William Blake
William Wordsworth
John Keats
Aphra Behn
Oliver Goldsmith
Samuel Johnson
Richard Sheridan
"The Vicar of Wakefield"
"Oroonoko"
"The School for Scandal"
"A Dictionary of the English Language"
"David Copperfield"
"The Old Curiosity Shop"
"Great Expectations"
Richard Aldington
Lonton Kwesi Johnson
Charles Dickons
William Blake
Imagism
Postcolonialism
romanticism
Ben Johnson
"Volpone"
tragedy
romance
history play
comedy
pastoral romance
Sir Walter Scott
James Macpherson
Robert Southey
Robert Burns
James Boswell
Virginia Woolf
George Orwell
Matthew Arnold
T. S. Eliot
Joseph Conrad
Richard Sheridan
Jane Austen
George Eliot
Charles Dickens
William Akepeace Thackeray
Joseph Conrad
John Ruskin
Algernon Swinburne
Oscar Wilde
William Hazlitt
aphorisms
euphemisms
conceits
complaints
colloquialisms
"Birthday Letters"
Siegried Sassoon
Sylvia Plath
D. H. Lawrence
W. H. Auden
Ted Hughes
R. S. Thomas
Lord Byron
William Morris
John Ruskin
Dante Gabriel Rossetti
Samuel Taylor Coleridge
Nadine Gordimer
Edna O'Brien
Alice Munro
Katherine Mansfield
William Butler Yeats
J. M. Synge
Paul Muldoon
Joan Lingard
Seamus
Heaney
George Gordon
Percy Bysshe Shelley
Dante Gabriel Rossetti
Gerard Manley Hopkins
A. E. Housman

** additional US History notes

Sixteenth Amendment
women's suffrage
The Department of Education
prohibition
schizophrenic
isolationist
apathetic
nationalistic
disjointed
grandfather clause
Father Coughlin
Franklin Roosevelt
Booker T. Washington
Truman Doctrine
NATO
NATO
Marshall Plan
MacArthur Program
League of Nations
United Nations
New Deal
Federal Emergency Relief Administration
Tennessee Valley Authority
Works Progress Administration
National Recovery Administration
Temporary National Economic Committee
Roosevelt Corollary
Pollock v. Farmer's Loan
Father Charles Coughlin
W. E. B. Du Bois
OPEC
"Liberator"
William Lloyd Garrison
John Greenleaf Whittier
Harriet Beecher Stowe
Frederic Douglass
John Brown
Pinckney's Treaty
Martha Washington
Abigail Adams
Mary Lincoln
Rachel Jackson
Martha Jefferson
Northwest Ordinance of 1787
Thomas Paine
"Plain Talk"
"Declaration of War"
"Uncle Tom's Cabin"
"Common Sense"
"Birth of a Nation"
Thurgood Marshall
John Jay
John Marshall
Roger B. Taney
Earl Warren
George Washington
John Adams
John Quincy Adams
Thomas Jefferson
James Madison
Albany Plan
Thomas Jefferson
Alexander Hamilton
Benjamin Franklin
George Washington
Aaron Burr
Treaty of Tordesillas
Balboa
De Soto
Ponce de Leon
Cortes
De Vaca
De Leon
Coronado
De Soto
Cortes
De Narvaez
Northwest Passage
Verrazzano
Jacues Cartier
John Cabot
Magellan
King Henry VIII
Catherine of Aragon
Sir Francis Drake
Queen Elizabeth
Virginia Companies
Jamestown
John Smith
Virginia Companies
Pilgrims
William Bradford
London Company
Mayflower
Cape Cod
Mayflower Compact
James, Duke of York
King Charles II of England
Colonel Richard Nicols
Amnesty Act of 1872
Dawes Act of 1887
Seminole
Choctaw
Powhatan
Apache
Cherokee
William Henry Harrison
Battle of the Thames
American Enlightenment
Slave Code
First New Deal
Second New Deal
Eugenics Movement
Nye Committee
Charles Townshend
Mutiny Act
Manifest Destiny
Sons of Liberty
Great Awakening
Boston Massacre
"Justification Papers"
"Proponents of Liberty"
"Common Sense"
"In Support of the Constitution"
"The Federalist Papers"
Chiang Kai-Shek
Mao Zedong
Saratoga
Chinese Exclusion Act (1882)
nativists
Know-Nothing Party

** additional English lit notes

Donne
Marvell
Herbert
metaphysical
realism
imagism
impressionism
surrealism
"Othello"
"Middlemarch"
Jane Austen
Charles Dickens
George Eliot
Herman Melville
Walter Scott
"Modest Proposal"
Jonathan Swift
sonney
limerick
panegyric
epigram
paean
Gerard Manley Hopkins
irony
assonance
alliteration
personification
allegory
reference
metaphor
compost
simile
allegory
metaphor
irony
simile
onomatopoeia
allegory
Jonathan Swift
cynicism
euphemism
metaphor
satire
irony
Age of Reason
Modernism
Romanticism
Ben Jonson
Gerard Manley Hopkins
Alexander Pope
William Shakespeare
Ann Radcliffe
"The Merchant of Venice"
Syllogism
Analogy
Ethos
Generalization

** additional American lit notes

Ernest Hemingway
"The Sun Also Rises"
"Islands in the Stream"
"The Old Man and the Sea"
"For Whom the Bell Tolls"
"To Have and Have Not"
"The House of Mirth"
Edith Wharton
"The Great Gatsby"
W. H. Auden
T. S. Eliot
John Berryman
Robert Lowell
H. W. Longfellow
"Winesburg, Ohio"
H. L. Mencken
Lionel Trilling
Thomas Wolfe
Sherwood Anderson
Ring Lardner
"Beloved"
William Faulkner
Maya Angelou
James Baldwin
Thomas Pynchon
Toni Morrison
Anne Bradstreet
alliteration
synecdoche
simile
metaphor
personification
epitaph
elegy
ode
paean
sonnet
Anne Bradstreet
"Before the Birth of One of Her Children"
"Upon the Burning of our House, July 10, 1666"
"Contemplations"
"A Dialogue Between Old England and New"
"A Funeral Poem on the Death of C. E."
Jonathan Edwards
"Sinners in the Hands of an Angry God"
John Winthrop
"A Model of Christian Charity"
William Bradford
"History of Plymouth Plantation"
Samuel Sewall
"The Diary of Samuel Sewall"
Cotton Mather
"Magnalia Christi Americana"
Henry Wadsworth Longfellow
William Cullen Bryant
Philip Freneau
Anne Bradstreet
Ebenezer Cooke
¡°The Journal of Madam Knight¡±
Sarah Kemble Knight
¡°A Farewell to America to Mrs. S.W.¡±
Phillis Wheatley
¡°The Narrative of the Captivity¡±
Mary Rowlandson
¡°Upon the Burning of our House¡±
Anne Bradstreet
¡°The Gleaner¡±
Judith Sargent Murray
James Fenimore Cooper
"A Pretty Story"
Francis Hopkinson
Washington Irving
Patrick Henry
Thomas Jefferson
Joseph Galloway
John Winthrop
Anne Bradstreet
¡°To My Dear and Loving Husband¡±
paradox
simile
iambic pentameter
foreshadowing
personification
parallelism
imagery
irony
hyperbole
metaphor
Michael Wigglesworth
"The Day of Doom"
Edna St. Vincent Millay
"The Great Gatsby"
"For Whom the Bell Tolls"
"Of Mice and Men"
"The Grapes of Wrath"
"As I Lay Dying"
Lost Generation
Gertrude Stein
Ernest Hemingway
William Faulkner
T. S. Eliot
F. Scott Fitzgerald
Henry Wordsworth Longfellow
Edgar Allen Poe
Emily Dickinson
Ralph Waldo Emerson
James Fenimore Cooper
metaphor
onomatopoeia
alliteration
epigram
simile

** consolidated CLEP notes

Louisiana Purchase
"Beloved"
"Common Sense"
"For Whom the Bell Tolls"
"Hamlet"
"Leaves of Grass"
"Letters from a Farmer in Pennsylvania"
"Letters from an American Farmer"
"Moby-Dick"
"Othello"
"Paradise Lost"
"Sinners in the Hands of an Angry God"
"The Articles of Confederation"
"The Bill of Rights"
"The Crying of Lot 49"
"The Faerie Queene"
"The Glass Menagerie"
"The Grapes of Wrath"
"The Great Gatsby"
"The Love Song of J. Alfred Prufrock"
"The Philosophy of Composition"
"The Scarlet Letter"
"The Sun Also Rises"
"Ulysses" (Alfred Tennyson"
"Uncle Tom's Cabin"
"Walden"
Alexander Pope
Anne Bradstreet
Bank of the United States (first)
Bank of the United States (second)
Ben Jonson
Booker T. Washington
Boxer Rebellion
Brook Farm
Charles Dickons
Chinese Exclusion Act (1882)
Christopher Marlowe
Compromise of 1850
Cortes
Cotton Mather
Dante Gabriel Rossetti
De Soto
Edgar Allen Poe
Edith Wharton
Edna St. Vincent Millay
Emily Dickinson
Ernest Hemingway
Eudora Welty
F. Scott Fitzgerald
Father Charles Coughlin
Flannery O'Connor
Frank Norris
Frederick Douglass
Freedman's Bureau
Fugitive Slave Act of 1850
George Eliot
George Orwell
Gerard Manley Hopkins
Gertrude Stein
Harriet Beecher Stowe
Harriet Jacobs
Harriet Tubman
Henry Clay's American System
Henry David Thoreau
Henry James
Henry Wadsworth Longfellow
Herman Melville
James Baldwin
James Fenimore Cooper
James Madison
Jane Austen
John C. Calhoun
John Donne
John Milton
John Ruskin
John Smith
John Steinbeck
John Winthrop
Klu Klux Klan
Know-Nothing Party
Langston Hughes
League of Nations
Lord Byron
Louisa May Alcott
Louisiana Purchase
Lydia Maria Child
Manifest Destiny
Marianne Moore
Mark Twain
Mary Rowlandson
Mary Shelley
Mary Wilkins Freeman
NATO
Nathaniel Hawthorne
Naturalism
Northwest Ordinance of 1787
Northwest Passage
O. Henry
OPEC
Oneida Community
Oscar Wilde
Percy Bysshe Shelley
Phillis Wheatley
Puritanism
Puritans
Quakers
Ralph Waldo Emerson
Reagan Revolution
Reaganomics
Reconstruction (Abraham Lincoln)
Reconstruction (Andrew Johnson)
Richard Sheridan
Richard Wright
Roger Williams
Romanticism
Samuel Johnson
Samuel Taylor Coleridge
Sarah Orne Jewett
Saratoga, Oct 1777
Seamus
First/Second Great Awakening
First/Second New Deal
Shays' Revellion
Sherwood Anderson
Sinclair Lewis
Sojourner Truth
Stephen Crane
Sylvia Plath
T. S. Eliot
The Beat movement
The Black Power movement
The Lost Generation
The Shakers
The Tax Act
The Treaty of Paris of 1783
The Virginia Colony
The War of 1812
Theodore Dreiser
Thomas Jefferson
Thomas Paine
Thomas Wolfe
Toni Morrison
Truman Doctrine
United Nations
Virginia Companies
Virginia Woolf
W. E. B. Du Bois
W. H. Auden
Walt Whitman
Washington Irving
Whiskey Rebellion
Willa Cather
William Blake
William Bradford
William Faulkner
William Lloyd Garrison
William Shakespeare
William Wordsworth
an alexandrine
an eclogue
an epic catalog
an epic simile
anticombination laws
apostrophe
assonance
ballad meter
blank verse
chavalric romance
chronicles
colloquialisms
compost
conceits
courtly lyric
dramatic monologues
elegiac stanza
elegy
enjambment
epigram
epistolary novels
epitaph
harangue
heroic couplets
history play
iambic pentameter
iambic tetrameter
imagism
impressionism
irregular odes
limerick
literary ballads
mock epic
nationalistic
nativism
naturalism
novel of manners
ode
onomatopoeia
paean
panegyric
parallelism
pastoral elegy
pastoral romance
pathetic fallacy
pathos
picaresque novel
political machines
popular ballad
postmodernism
pragmatism
prohibition
propaganda
pure and simple unionism
realism
regionalism
rhyme royal
roman a clef
romanticism
satire
sentimentalism
serealized novels
social novels
sonnet
sprung rhythm
stream of consciousness
surrealism
symbolism
synecdoche
terza rima
the Gospel of Wealth
the Social Gospel
tragedy
transcendentalism
vignettes
villanelle

