* unfiled notes

Emily Roos
GreenEcho
IT Help Desk Analyst
+1.417.234.5952

!!!
Hi, Emily. my name is Nathaniel Rhein. I'm calling in regards to the IT Help Desk Analyst position (with GreenEcho). You emailed me and requested that I call you to follow-up on my application.

MESSAGE: I'm sorry I didn't catch you this time; I'll try again tomorrow morning. In the meantime, if you don't already have it, my cell number is (313) 908-0706. Once again, that's (313) 908-0706. Thanks, and have a lovely day.

WHY LATE?: My current employer had a minor emergency the other day that required some extra attention.
!!!

Hi, Emily. This is Nathaniel Rhein. You asked me to call you regarding my application... for the IT Help Desk Analyst position.

Q: Please tell us a little bit about your BACKGROUND and EXPERIENCE.
My professional background is in healthcare, where I worked as a CNA for several years before transitioning to being a stay-at-home-Dad. Over the past year, I've started doing part-time tech support for a local nonprofit.

Q: Please tell us why you are INTERESTED in this position and how you can MAKE A DIFFERENCE.
I feel that I work well with computers and helping people. I'm patient and detail-oriented, and I don't mind tackling large or annoying jobs.

Q: Please tell us about a PAST ACCOMPLISHMENT that you are especially proud of and why.
I convinced my client not to buy an off-the-shelf desktop PC they had found recommended on some random website. I convinced them instead to let me source parts and build a desktop for them, with much more value for their money.

Q: Please describe a DIFFICULT SITUATION you encountered in a previous job and how you resolved it.
I was given what was supposed to be a relatively small job, coordinating the transportation to and from the airport for a number of guests attending a conference. But due to poor management before I came along, I was given the task with little time to prepare, and about 80 people to contact. To resolve this, I spent extra time at work (and at the conference) contacting every person on the list, manually confirming all their flight details, matching them up with drivers, and doing much of the driving myself. It was a lot of work, over the course of about a week, but I received many compliments that I had handled the job well and acted professionally.

...

Q: Where do you see yourself in FIVE YEARS?
It's going to take a lot of work to get where I want to get to, but I don't know exactly what the path is going to look like. For now, I'd like to play to my strengths - mainly computers - develop my skills, take advantage of any good opportunities that are given to me, and prove to an employer that I'm worth having.

Q: WHY should we hire YOU?
I have a lot of practical knowledge when it comes to IT. I build my own computers and do my own troubleshooting, and I'm a quick learner. When I was younger, I used to worry about a job being too "hard" or not "fun" enough, but at this point in my life, I just want something stable to support my family, and I know that I can work hard enough to accomplish anything.

Q: WHY do you want to WORK HERE?
I'm going to be honest, I'm not that concerned with where I start work. I believe that so long as my employer is honest and recognizes my commitment to good work, then that will be a good fit for me.

Q: QUESTIONS for us?
- pay: $15-17 an hour
- hours
- requirements

OTHER
- ...tasks, certifications, whatever. location, I guess.
- can start this coming Monday.


GREEN ECHO DEETS
IT consulting and ... support?
Clients include CDE Consolodated Electrical Distributor (over 600 locations over US, called "Profit Centers"). GreenEcho helps them. Profit Centers have 5-50 PCs.
Two different Help Desk locations, Texas and St. Joe Michigan.
Would be working in St. Joe facility, on GreenEcho's payroll.
CDE does not hire internally (?) or something. GreenEcho migrates employees over to CDE. Normally this happens after 1 to 1.5 years.

In-office position. Entry-level IT. Tier 1. 
Hours of operation, Mon-Fri 06:30-20:30
1ast 6:30-3:30
mid 8-5 or 8-6
last 11:00-8:00

Schedule based on seniority, newbiews usually get 11A to 8P.

Sitting for extended periods of time, on phone for 7.5 hours, sometimes remoting into someone's PC...

Training probably mid shift.

Minor overtime. Holiday pay. PTO available. For GreenEcho, there's health insurance ... individual, not ... dental and vision available at employee's cost...

If employed by CDE, more insurance stuff available, details unclear.

1st phone interview
2nd interview in St Jo, hiring manager,
3rd interview in St Jo, assessment test and job shadowing
official offer, prolly after a few weeks
then background checks etc

Laura Mullins, CDE hiring manager

3399 South Lakeshore Dr.
St Joe, MI

