* quotes and single lines

"It's sort of an acrostic. No, wait, not an acrostic; the other thing... a war crime."

. . .

"Don't borrow money from your parents."
"But I thought you said the only people you could borrow money from were banks and one's parents."
"Yes, but it's a bad thing to be in debt to bad people."

. . .

I wouldn't marry him with a ten-foot pole.

. . .

¡°The fates have conspired to give you another chance. Will you laugh at them again?¡±

. . .

"Are you cold?" "No." "Then why are you wearing a coat?" "If I wasn't wearing a coat, I would be cold."

. . .

Go outside. Walk around a bit. Walk until you find what you're looking for, or realize you that you don't need it.

. . .

"I feel it all in my fingers. They are sensitive to all things. My stomach is not. I have spent my life training my fingers to feel and my gut not to."

. . .

This is our Department of Redundancy.
...
They don't get a very good budget.

. . .

"I was going to pun on that, but on second thought it wasn't that funny."
"Well, at least you had the enjoyment of the first thought."

. . .

He died the way he lived... under a big fucking rock.

. . .

Let Peter and Paul tend the flock. I shall tend the field.
Or:
Let Peter and Paul tend the flock. Carl shall tend the field.
R: And what will you tend?
R: The wolves.

. . .

"Did you explain it to them?"
"Yes."
"Then why do they not know?"
"Because I spoke in a way that they could not understand."
"Then you did not explain it to them."

. . .

The Irish blessing:
"May you live a hundred years, with an extra one to repent."
Response, a little dry, but a little nonplussed:
"So... a hundred and one years?"

. . .

(Maybe related to my own SCP Foundation?)

A character, describing the trend of a mass, of a particular people group, their agenda...

I don't think that's how most X think. Most X lack an agenda.

Yes, but the totality equals a definite trend... bolstered by the few who actually have the agenda...

I think we should think of the needs of the people involved, not the possible effects of their agenda.

When the day comes that we are not in danger from the agenda, from the trend, and we need not fight it, in that day we shall direct the greater part of our effort towards the (common) good of the common man.

. . .

Seneca's quote: "What difference does it make how much you have? What you do not have amounts to much more."

So the one says to the other,

"Why do you seek to gain so much? What you do not have will always be more."

"That is where you are wrong. I mean to own more than I do not own. I mean to e the first person in history to do so. Even Adam could not; he lacked the technology. God gave him the Earth, but even before the Fall he could not travel it and tame it as I can/have."

"A story: when I was a boy, I knew another boy. He and I grew up together. We hepled each other in many times and ways. When he was ill at ease, he spoke to me; he said things both sober and drunk that he said to no other; and many times were we each other's stick when the trials of life made us for a day or more old before our time, and unable to walk without assistance. Now this man is now grown, as I am, and he lives far away; and I see him only once a year, perhaps; yet when he sees me, he does not hesitate to place all his cares and secrets in my keeping; and were I set upon by savage beasts, he would not hesitate to risk himself to save them."

"What do you mean by this?"

"This man has given me more than he will ever give you, my king, and not because you are less worthy, but only because you have not the time-forged bonds that I have. And I have other friends of this caliber, but only a few; in my many years, I have had time for only a few. To truly win this friendship, this camraderie... to have so much life given to you, requires that you give so much life in return. And my kind, you have only one life to give. So how could you ever own more than you do not own?"

. . .

Listen, I have about eighty men working for me. I can get some guys in, draw up some rough drafts and... you know, it'll take some work, but I think if we hit it hard, pull some long hours, and call in a few favors, we might be able to come up with an idea that's worse than that one.

. . .

A story about two soldiers, Old and Young. We follow Young. He's alone, cut-off. Not super-experienced, but battle-weary enough, and he survives because he's got concentrated food or whatever. He trades some shots and wits with a far-off bad guy, which turns out to actually be an ally; Old. They end up talking about whether war is just. Young makes the argument that we act like wars are noble, fought between nations, for differing ideals, etc. But really, war is about hatred, and it's messy, and it's all individual. Old makes the counterargument that, just as you have to get your hands dirty to build a house, so you have to accept a few deaths to topple a regime, build a country, defend a country, etc. Young says that people cannot be equated in this way... Old says, perhaps.

. . .

Age: "Have you never considered that in my many more years than you, I may have had the same thoughts as you, I may have been at your point, but that I have gone beyond that, and think different things now, and I see things that you do not see, due to my years and my experience, I have learned things that can only be learned through experience? Have you considered that?"

Youth: "I have considered that. But I am given to reason only with the tools that I possess; I cannot draw directly from your experience. I have logic, and I have my own experience. I have done my equations, and to the best of my abilities, determined what is right. [Advanced version:] I have yet to determine, via my own best processes, that your difficult-to-define experience is great enough to supersede my processes."

OR

Age: "You and I think alike. This has been shown, has it not?"

"Certainly."

"We interpret the world in similar ways. We use similar senses."

"Certainly."

"Then have you not considered that during my eighty years of experiencing the world via these methods, I have learned things that you, during your twenty years of experiencing the world via these methods, have not? Furthermore: are there not things which you have difficulty expressing? And yet you know - or at least believe - them to be true. So you know that a lack of expression does not spell the doom (falseness) of a statement."

"Certainly, certainly, certainly all around."

. . .

Char1 opens gift, pulls out tissue wrapping, jokes, "It's a box of tissues!" Then, "...it IS a box of tissues."

Char2: "We thought you might be crying after the last present."
