* rules
Comics ought to be funny whether the reader has read the book or not.

For the reader who //has// read the book, the comic ought to carry additional meaning that a nonreader would not perceive, by doing one or both of the following:

1) Recalling specific passage(s) from the book
2) Making an insightful comment about the book

* books
** The Hunger Games (series)
Gale and Peeta proclaim their love for Katniss, who is distracted with her new bow.

Various tributes in the 74th game talk about their districts and the name "The Hunger Games".
** The Lord of the Rings
Gandalf reacts to Wormtongue calling him "Ill-wind".

Gandalf shows Aragorn, Gimli and Legolas one of the Lovecraftian things from beneath Khazad-Dum.
** A Princess of Mars
John Carter fathers an egg...

John Carter advises a Barsoomian on how to woo a woman (mass murder).
** The Scarlet Pimpernel
A guard lets some people out of the gate of Paris. Second guard comes up, tells the first that those people included the Scarlet Pimpernel. Additional party arrives and accuses second guard of being Pimpernel. Etc etc.
** A Song of Ice and Fire
The smartphone of the average evil SoIaF character is split into "People I am rather fond of" (two to five) and "People who I would gladly feed to beetles" (everyone else). A Dothraki encyclopedia is mostly H. Tyrion Lannister's filing cabinet is divided into "Funny faces I have made" (big number) and "Funny faces I have not yet made" (small number).

Someone: "Winter is coming..." Someone (else?): "But not to Dorne! It's always hot/Summer in Dorne." Areo Hotah, as Oreo, with longaxe (in dress/veil/etc?): "This is my wife!" Everyone: "Visit Wacky Dorne!" Everyone can include Sand Snakes, Hotah, Darkstar (a literal dark star?), Martyn in his wooden wheelchair, the oversized skull of Gregor Clegane, and possibly Myrcella.
** The Trials of Lance Eliot
What's-His-Name (Regis?) throws his cards off the cliff. Lance (maybe) follows by throwing his bottle of drink. Then someone else follows by chucking down a grand piano or pipe organ or trombone or similar. Probably a piano of some description.
** World War Z
Max Brooks interviews someone who recalls an incident during the Zombie War when people just argued about what "kinds" of zombies the zombies were, which movies they were like, whether they were realistic, whether they were "infected", and whether "infected" counted as zombies. Probably they all get eaten at the end.
** A Wrinkle in Time
Something about the main character asking Charles, "Are you going to explain this to me?" Him: "Oh, yes. Later." Her: "When?" Him: "Probably never.
