* characters
** Narrator - Kenneth "Ken"
A CNA/orderly/care-giver at a boring assisted living facility. No outstanding qualities. He started making a tape journal a while ago, because...
- he's obsessive; he doesn't even listen to them
- he's very obsessive; he does listen to them
- he's worried about dementia, after taking care of old folks
- he'd worried about lawsuits

- He had a specific reason at first, a practical reason, but eventually he found it easy to talk into the recorder, in a way that it wasn't to talk to the air, or write things down. And he didn't have any friend close enough to babble at.

** the Leader
A previous leader of the Custodians, insofar as they had leaders. Left many years ago on a mysterious and apparently self-sacrifical mission. Not entirely certain what he was going after, but they're pretty sure it was important. They suspect (correctly) that he has information which he himself has forgotten the importance of.

The leader was lost as part of a battle (or hostile action) that wiped out most of the old guard. This is why it was so hard to track the leader down - the coming on of the new guard, younger and keener members, was also the transition to a less trusting, much less open form of doing business, with few real names and details. The survivors of the battle had the leader's name and address, but little else, and no known secret ways of contacting them; and this was pre-Google. They searched, but they simply did not find him.

* history

- the Old Guard have adventures
- the New Guard are brought on
- there's a big battle; most of the Old Guard are defeated, and the Leader is lost
- lots of time
- Ken starts work at the Facility
- the Leader is placed in the Facility by ?
- Ken notices something odd about the Leader

* plot
** draft 0

Mara wouldn't let me into work today. I got there at five - five after five, I mean, maybe ten minutes after, tops - and as soon as I got to the door I remembered they had changed the code, and I hadn't written it down, I couldn't remember it. I tried the old code, in case it would work, and of course it didn't work, so I buzzed the desk, which didn't do anything, of course, and then I went around back to the kitchen doors and hit the old doorbell for Marta. And she wouldn't let me in. I think I hit that doorbell four times, before I saw her face in the window, scowling at me. She tried to lecture me through the door, but I told her I couldn't hear, so she let me in and I tried to get past her but she just lectured me in the hallway. She had her line - she said the exact same thing she always says, that line about "I get here at four fifty-two and I have the oven warmed up by four fifty-four, once it hits five, my time's not my own" and just telling me I needed to come in earlier, really letting me have it. I think she enjoys telling me off, or at least, it's how she finds fulfillment. It's not enough for her that she's on time or does a good job, that's not enough for her, she has to fix everyone else. When she told me I was supposed to buzz the desk if I was late, like she always tells me, I told her, like I always tell her, that Stacey or whoever it is never sees the buzzer because she's busy watching soaps on that little TV by the desk. I don't know why Marta doesn't find this a very compelling argument.

It was hard waking up for work this morning. I didn't feel like I was really all there. Part of me was still in my apartment, watching my rentals until ten PM. Ten PM just shouldn't be late, you know? It feels awful to go to bed by ten. It feels awful this way, too, but it just feels unfair for ten to be late.

Everyone was right where I left them, anyway, this morning. Miss Daisy and Katherine and John and all the rest. Kyle was awake and yelling in his room but I got him calmed down, and Edward needed his morning brief change. I opened Alma's door and set out the newspaper for Mr. Nerre.

We got two new residents today. Not together - I mean, they came at the same time, but that's just because the ambulance got wind that they were going to the same place and packed them into one van. I don't think they're supposed to do that. Anyway, one's a real old man, Mr. Gartin, who was pushed in by his neice and didn't say a work or look at anyone throughout the whole sign-in, but the other was a young woman - the youngest one here, I think - I'm sure she wasn't more than fifty) - and, oh lord. I know we won't be keeping her, I just wish Doug wouldn't take two weeks to figure that out this time. This woman, Doris I think, this woman does not need assisted living. What this woman needs is restraints. She needs one of those nice facilities where they take all ages and all circumstances and just make sure they can fit leather straps around your rists. The lady is demented, she's psychotic, and I sweat she took a swing at Barb when Barb tried to help her out of her chair. The woman looks like she wants to bite someone. Actually, I wouldn't be surprised if she already had. Maybe that's why they sent her here.

We're at capacity, what with room 14 still getting fixed, so they put the woman in the show room, and the man gets to stay with Mr. Williamson until room 14 is ready. We all made sure to apologize to Mr. Williamson, but I think he actually kind of likes it; it was nice to see him with something to do, for a change. He spent a good ten minutes tidying things up his books and trying to move furniture around, which is the longest I've seen him go without asking for a cigarette.

...




* notes
**  nature of the Agency
not like Shield. Somewhat like SCP or X-Files.

Shield:
well-funded
secret
militaristic

Agency
strapped for cash
not secret, just not well known
non-violent, largely

Custodians
Orderlies
Hirelings
Farmhands

** general notes
Agency
The Red Room
poor funding and volunteer status
protocols re: mind control
the standard effects of mind control
religion amongst the members of Agency
approach to nonquantifiable and unpredictable threats
standard equipment
relationship with US government, other governments
