* FCP: overall
King: Maria Blackwell
Beast: The Tyrant
Merchant: someone who dies before the main action
Nomad: someone who had been beholden to the Merchant; has authority over the General
Wizard: The General
* FCP: Team Z
King: Mary/Maria Blackwell; Christian name unknown; doctor, assassin
Beast: male/female; previously under Tyrant's control; committed suicide
Trader: female; someone with connection to the other Trader; of Team Z, closest to Blackwell; dies of injuries outside Tyrant's sanctum
Nomad: female; teleported away to parts unknown
Mage: male; of Team Z, closest to the General; dies to overwhelming odds

* judging Blackwell and the Tyrant
Connected to !!NONFICTION stuff about privilege and the effect of actions, and being able to track each successive second tier effects (effects-of-effects) only 1/nth as much as the first tier, and so on. For this reason, we concern ourselves primarily with the first tier effects of an action, and much less so with each successive tier, not because those repercussions don't matter, but because they're effectively unknowable.

So likewise, although the accomplishments of any individual person, though we know they are really a product of the myriad elements that came before them and contributed to their opportunities, abilities, and personality, it is appropriate to judge strongly what we see that they do, to the same extent that we judge our own actions according to their first tier effects. This is the justification used to praise Mary, and vilify the Tyrant.

"The tragedy which had brought out the worst in so many did bring out the best in a few... the force which persisted and defeated Z did so via the same mechanism by which Z wrought so much destruction: trust. / Trust is perhaps one of the most powerful forces... it adheres people/individuals to one another."
* outline
The tyrant was finally killed in eventual single combat by Mary Blackwell, after the latter breached his fortress with her band of friends/warriors (most of them dying in the process). The final face-off was not witnessed by anyone else. Mary survived, but was severely wounded: she lost an arm, lost sight in both eyes, had severe enough general injuries that she never fully recovered, and had extreme mental trauma which rendered her dependent for the remainder of her life. She was very well-loved for her heroics, and was well taken care of.

The tyrant was given a funeral, of a kind. After debate, his body was finally encased in a coffin and launched into space, aimed towards the emptiest portion of the sky. His only eulogy was this: "He did what he thought to be right."

The tyrant ^^name undecided^^ was responsible for one of the apocalyptic periods of the post-modernity era... maybe?
* The General's afterward
I wanted her to be my daughter, and at the same time I wanted her to be my wife. Maybe that sounds wrong. I just wanted to care for her. What she made into such fierceness was this vitality that I have never seen before or since. There was no one like her ever before in the world, I am sure. But even so, even with such power, she was hurt, and she had so much life in her that it hurt to see her hurt, and I wanted to protect her.

Apart from keeping her alive, I wanted, most of all, to help her free from the life of a struggle. She was a genius, as people say, but she really succeeded because of house much she gave up; I cannot even tell you how much she gave up. She loved dancing, and music, and math; people, and giving gifts; the nuns at the orphanage tell me []... she gave up so many things, to make herself into a weapon, the sharpest arrow that was ever fired at the heart of evil. And even if her energy were spent, even if the best years of her life were spent, she deserved to come out of the battle into peace, into a time and a place where she could sleep without a weapon on her thigh [reference; or similar memory]. But she didn't. X's last and final evil act was to bind her, forever I suppose, in battle with him. He is dead, and as physically gone as a person can be, and we are rebuilding, and still she is fighting him.

I wanted her to be my wife, and my daughter... I wanted to protect her. But I have had to face the fact, again and again, that I am not strong enough. I was, perhaps, a good general, but Mary was on a level above me, a level above all of us; by the wisdom of her teachers and the strength of her arm she raised herself up to a high enough level that she could strike at X. I wanted to protect her. When she was younger, I wanted her to be my daughter, and she wouldn't be, and I wondered why; when she was older, I wanted her to be my wife, and she wouldn't be, and I wondered why; now I know. She was too strong for both. I wanted to protect her, but this whole time, she's been protecting me. She's been protecting all of us.

Only now does she have real need... only in the decrepitude of her injuries is she a dependant being. But I will be neither her father nor her husband, nor even her commander anymore. I don't even know that you could call me precisely a friend. I go to her, still, almost every day, and sometimes I talk with her, or listen, and sometimes I only sit there, and ninety-nine times out of a hundred she doesn't seem to know I'm there, and if she knows I'm there, she doesn't know who I am. I don't know if I'm her friend, because friendship means giving and taking, and she has nothing left to give me, and I'm not sure I have anything left to give her, except my time; the nuns take care of her. Perhaps I'm only what I've always been: her admirer.
* The Tyrant's philosophical writings

A: There was speculation that the Tyrant's philosophical papers were themselves somehow poisoned or boobytrapped. Which, to be fair, was true - we lost one researcher to [plausible poison] in the ink when he handled some pages without gloves.

B: He's dead?

A: No, we caught it before it got that far, but he did go blind.

B: But it's not as though anyone would be convinced by reading...

A: ...

B: Was someone?

A1: People found individual sections very compelling.
A2: WEll, at least one did. We *accidentally* gave access to all of the info to one researcher. [or] Accidentally left the locks off. Anyway, he joined up. Tried to break into the vault. Assaulted a guard with a [deadly weapon]...

B: Jesus.

-: Hedge a bit. *Imply* that some people read it without going crazy (but are forbidden to discuss it openly), and/or there's some selection bias with those who sought out/chose to read.

* notes

The Tyrant is 81 at his death/the beginning of the novel. Blackwell is 36. The General is 54.

Five-Character Paradigm:
Higher rank only means that that entity has power over them, like a secret weapon. Does not necessarily mean that they want to or succeed in using it.

The final battle as a game of Crux:
+ Elder Beast in the Tower.
+ Suited K/N/M/W, and adult B suited to EB, enter bottom.
+ Suited K/M reach Tier 1, where M dies.
+ K enters castle, defeats EB, wins (K is champion I guess?).

The entire war as a game of Crux:
+ M killed early.

* older stuff to incorporate?
** The Hammer Descending

I have known grace, in my time. I have been forgiven. I have made it my goal, in turn, to harm no living thing.

But the hammer, descending, has not.

It has been my experience that understanding begets compassion, and that which you most fully understand, you cannot bring yourself to wound. So, as I understand more of the world, there is less of it that I wish to come to harm. But of all the things I understand, I understand most clearly that the hammer understands nothing.

I can see it now Å\ even now. Iron head thrust rudely onto wooden haft, a stonemason's tool, heavy. I could hardly lift it. But then, I was, and remain, very much a child.

Shall I tell you how it happened?

Donato was my father in so many ways. He plucked me from the gutters of my native [POOR COUNTRY], the home that never loved me, and he fed me food from his own hand, and instructed me with words from his own mouth, and blessed me with thoughts from his own inimitable mind. Me, the child of dirt and worse. My earliest memory of Donato is of sitting by his side in the back seat of the open car he used to drive around the city. I am so short that I cannot see over the door, and Donato is a giant at my side, his gray suit immaculate, his great head turned away from me as he speaks over the sound of the car's engine to an unseen worker on the side of the road. I can still look down and see his strong hand.

He was my father in every way that mattered. But not by blood. And as it happened, that was the way that mattered most.

!!!

Maybe Gregory (or rather, Donato) was transferred from one school to another so that his father, the principal, would never be principal over his own son... one of those things that he was completely inflexible on...
** Heresiarch
Heresiarch

    Aldous Huxley
    Gabriel (Syme)
    (Chip) Zien
    Giant
    Father

. . .

Huxley rolled his window down.

Huxley rolled it back up again.

Down again, and up again.

At the end of the window-handle was a little plastic knob with ridges. Huxley counted the ridges.

Thirty-eight. The knob was blue, his favorite color.

How many ridges? Huxley counted again. He lost count. He counted again. Thirty-eight. Thirty-eight ridges.

They felt smooth if you ran your finger along them, but rough if you ran your finger against them. The knob could spin by itself, or you could turn the whole handle and the window would slide down.

Huxley did this.

Huxley rolled it back up again.

He sighed, very bored. He stared through the acrylic glass barrier between the front and back seats, and restrained himself from asking his driver how much longer they had to go.

He looked outside, but it was dark and there was nothing to see.

Huxley played with the window some more, then he found an old pen and took it apart, but he couldnÅft get it back together again. He fiddled absently with the top button of his polo, wondering if he was only imagining the car swerving oddly. He looked into the front seat again, about to ask his driver what was happening, but the driver was swearing, and wrenching the wheel left and right, and looking pretty preoccupied. The small car filled abruptly with blinding yellow-white light. Huxley held his arm up in front of his eyes and turned, slowly it seemed. He thought maybe he could see the front grille of a freight truck.

Huxley looked around. He was lying flat on his back on the concrete. His hands felt wet and warm. When he turned his head, he saw the face of the taxiÅfs driver, a lean, dark-skinned man, his mouth opening and closing like a fishÅfsÅ\though if he were actually speaking, Huxley could not hear him. Huxley sat up, feeling generally uncomfortable, as though some part of his body had shifted over to the left. As his hand brushed the ground it twinged with pain, and when he lifted it to the light of the street-lamp he saw a piece of twisted metal jutting from its back. Turning his hand over, he saw the other end sticking through his palm. He tried to pick it out with his other hand, but his fingers were too large to get a firm hold on it. He looked back at the driver with the intention of asking for help, but the dark-skinned man was clearly dead.

Huxley's hearing came back to him, and he heard the sirens. One of his eyes seemed to be swollen from the impact and his vision was blurry, but he could see the glint of the red-and-blue flashing lights off in the distance. He got to his feet, and took a look at where he was and what had happened. His taxi had been heading towards his home when it crashed, he thought. Yes, it must have been, he gave his address to the driver. And he had been thrown out of the front of the car, because the seatbelt hadn't been onÅ\it didn't fit over himÅ\and so, he must walk in the opposite direction, away from the lopsided wreck of a car, to get to his house. Huxley stood, his body turned towards the car and his head turned away, double-checking his logic with the fevered slowness of a child's intellect. Presently he turned and, limping slightly, lumbered off towards his home.

By the time the police cars reached the scene of the accident Huxley had gone, and for the rest of the night the only time he thought of it was when he remembered the piece of metal in his hand, and pulled it out with his teeth.

It was at a party the following night that Huxley saw someone whom he thought he would never meet again, or more accurately, hadnÅft thought that he would meet the first time.

Huxley had not been invited to the party, because that was simply not the sort of thing that happened to him. He was there for his job. He had never been invited to a party in his life, and for anyone who knew Huxley, it was obvious why. It was not because he had no friends, because there are many reasons other than friendship that someone may be invited to a party. It was not because he was a garbage-man, because although some scorned such a lowly job, some did not. It was not even because he was incredibly, immensely fat.

It was because, no matter how or when people spoke to him, they would get the feeling that this man was not simply large, but that specifically, he was larger than them. He was fat, yes, but underneath the rolls and layers of superfluous flesh there was the frame of a body that was enormous and unmistakably strong. The fat hung off of him and weighed him down, but it was only an impediment, and one had the horrible thought that he might tear it off of him and throw it aside in a transport of rage. Anyone who has seen an old blacksmith knows the build, the loose skin on muscles that could be stone; but if Huxley were a blacksmith, he must surely be one of the three giants who forged lightning bolts for Zeus. He might crush you by accident, turning around, or else command you to bow down to him, for if he let his voice rise, was there any doubt that its law would be as irresistible as the law of gravity?

In the end, though, it was not the fear that separated Huxley from other people, but the blatant impossibility of him. The senses could not reconcile his body with the rest of the world, and so they did not. He was ignored.

Huxley was well aware of the fact that people habitually ignored him, even while carefully giving him a wide berth. Actually, the full realization of this fact was one of his few genuine intellectual accomplishments, although he was at a loss to explain it. By his reasoning he expected that people ought to pay more rather than less attention to them, for the simple fact that he might hurt them if he were annoyed. Not that this was really something he would do, but, he reasoned, other people might not know that.

The man who caught Huxley's attention was sitting at the bar. He was a tiny, angular man, fiddling with a pen in one hand and a mostly-empty wine glass in the other, and looking around at the other guests as though making sure they weren't getting into any trouble. His feet reached neither the ground nor the lower bar of the stool nor anything else of interest. Huxley had stepped in just for a moment, to see if the trash bins in the back room needed to be taken out, when he saw the small man, perched on his stool like a miniature warden. Forgetting his job, Huxley turned and walked towards the man, his heavy footsteps audible over the din of conversation. People moved out of his way without looking at him.

It was a nice party, the sort of event where people arrived in fancy cars which were then parked by eager-looking valets. Huxley thought it had to do with the opening of a new hotel or something, maybe. He did trash-work for a lot of parties, and they generally looked the same to him.

The man turned as Huxley reached him, and for a moment they stared at each other without a word. Then Huxley said,

"You're bigger than all these people."

"No, I'm not," said the little man, quite surprised. "Smaller, actually, and by a great margin. You should talk, though, I'm surprised this building supports you, you look like a baby elephant, how much do you weigh, half a ton?" The words spilled out of him without pause, as though he did not need to breathe, or perhaps delegated that task to another time of the day.

"Tha's not what I meant," said Huxley, his words bumping into each other. "You're more than them. You see things they don't."

Huxley waited for the man to be affected by these words, but his companion grinned widely and said merely "Oh, do go on, tell me why I'm special, you do have a way with words, don't you?"

Huxley wrinkled his nose. His control over the English language and the muscles of his own jaw was more than sufficient for everyday conversation, but words were such small things to him that they always came out of him sounding as though they had been chewed a bit by accident. This man, he imagined, was a master of words, but he used them frivolously and abundantly. It annoyed him, and he had no desire to feel stupid by pitting his rhetoric against this man's.

"You're like me," he said meaningfully.

"Good lord, I should think not," said the man without hesitation. "The closest I could be to being like you would be to be one sixth of you, and I'm not sure I'm even that." He sat up a bit straighter suddenly, as though he had seen something across the room, and started scribbling rapidly on the side of his glass with the pen. This made a very high-pitched scratchy noise that made the hairs on the back of HuxleyÅfs neck stand up. Huxley was trying to decide which tact to take next to get him to speak properly, when the the glass was placed swiftly on the table and the little man's eyes fixed themselves on Huxley's.

"Why did you come here?" he said.

"My job," said Huxley. "IÅ\"

"No no no, I mean why did you come over here, to the bar, why did you come over here and talk to me?"

"I told you, you're like me."

"That much you've told me, yes, but you haven't told me why that made you want to wander through a crowd of lavishly-dressed businessmen in your stained garbage-man overalls and engage me in insightful and recursive conversation. Anyway, I'm surprised you're out at all, weren't you in some sort of accident yesterday?"

"Oh, yeah," said Huxley, remembering. "My taxi crashed. The driver died on the ground. I got a bit of metal stuck through my hand." He held up his hand, unbandaged and looking dreadful with a smear of dried blood, and fingered the little flaps of skin that might reveal the hole. "Right through it," he said.

"That is appalling," said the little man earnestly. His voice was neither high nor low, as though pitch were another thing he used only when convenient.

"It's okay," Huxley said, lowering his hand. "I don't really get hurt."

"No, obviously not," the man said, still looking at the mangled hand.

"You know, I think we may have started off on the wrong hand. Foot," he corrected himself, "wrong foot, sorry. I'm called Gabriel. What about you?"

"Aldous Huxley," said Huxley, and Gabriel roared with such laughter that other people at the bar jerked their heads around in surprise.

"Huxley!" he said. "Huxley! That's brilliant! Where'd you get that, then?"

"Saw it on a book," Huxley said thickly. "Liked it."

"Yeah? D'you know what that book's about?"

"Yeah. I asked the librarian. She said it's about how people are born in test tubes and machines and things, and not in their mothers."

"That sounds about right," Gabriel said, still grinning. "That idea appealed to you, did it?"

"Well, that's how we were born, isn' it? You and me?"

Gabriel waved this comment aside, then looked around at the other party-goers as though just noticing them.

ÅgHell, why are we here? I donÅft know any of these people, all here to get drunk and talk about their own clean cars and each otherÅfs dirty laundry.Åh He finished off the rest of his wine in one gulp and hopped off his stool, briefly vanishing from HuxleyÅfs field of vision.

. . .

Gabriel's grin vanished at once. He looked away briefly, licking his lips. His voice was low and harsh as he said, "Listen. You can't go around saying things like that, alright? Actually, that's why I'm here. I've been looking for you."

"Looking for me? Why'd you come to a party?"

"A party's a good place to find people. It worked, didn't it? Anyway, I came to warn youÅ\well, to tell you, in any case. There's rumor of a rift. Some ofÅ\" he hesitated for just a moment, "Å\_those concerned_ have been saying things against what they've been taught, being disrespectful, spreading some sort of propaganda about their elders or betters. Saying that what they've been led to know isn't what it's really like, that they've been lied to. It seems that, just from what I've heard mind you, seems that some have been leaving for what they think are more important things."

If any of this surprised or confused Huxley, he didn't show it. "It's not me," he said.

"I didn't think it was."

"If they come 'round to me I won't listen to them."

"I know that, that's not what I came to tell you about. It's him. The oldest. _Our brother_, you remember him, yes?"

A subtle tension seemed to set at this admission of a link between the two men. For the first time Huxley looked as though he might be worried, his huge forehead furrowing like folds of leather, and his fidgeting suggested that he had suppressed the urge to look around him. Gabriel, for his part, sat as still as a statue, his eyes fixed on Huxley's, the tips of his mouth pulled back very slightly.

"Yeah, I remember him," said Huxley, his voice lower and more clear than usual. "Is he still called Edward?"

"No," said Gabriel with distaste heavy on his breath. "He's chosen some new, disgusting name for himself. I haven't bothered to remember it. He seems to see himself as his family's personal angel of Death, judging and dealing judgment as he sees fit. He's been getting around to as many of us as he can, asking questions, looking for answers, always pressuring, assuming, torturing, and whenever he can, convicting. He's crazy, fanatical, he seems to think anyone questioning his authority is some sort of heretic who needs to be made example of. I know he's going to look for you."

"Did he get to you?"

"Of course he did, where do you think I go every week?"

"But you got away."

"Again, of course I did. I'm good with words, aren't I? And I'm young. He's not as worried about the younger ones."

"But I'm the youngest!" said Huxley incredulously. "He shouldn't want me at all!"

"Yes, but _you ran away!_"

"Father forgave meÅ\"

"_Think_, Huxley! Think, where our brother doesn't! He doesn't care, the point is, you disobeyed! It wouldn't matter if it happened a hundred years ago, everyone knows that _you have disobeyed!_ That's all he cares about! Anything you've ever done or said against Father, he'll remember and focus on. He's looking for someone to blame. He's looking for the heresiarch, the originator."

. . .

The realization of this was, in fact, one of Huxley's few genuine intellectual achievements. He had always been aware of the fabricated ignorance other people applied to him, of course, but for the longest time he had not know why they did it. Why didn't people look at him or speak to him? Why did they walk around him as if he were a wall, rather than a living thing? Why did he have to repeat himself or tap someone on the shoulder to get their attention at all? Huxley was logical enough to realize his own body, and to imagine that people ought to pay _more_ rather than _less_ attention to him, for the simple possibility that he might hurt them if they annoyed him. But, as Huxley had learned, it was only the small things that people worried about. He had heard once that thousands of people died every day in car accidents, and yet nobody seemed bothered by cars. They were only bothered by things that didn't matter, like what sort of food they ate or what their clothes looked like. Huxley felt sure that there was a grand reason for this, though he had no idea what it might be.
