* An Adoring Question
How many times across the years
Have I looked upon thine face?
Which number, O great multitude
Will answer this, my soul's reprise?

To seek out clue or gentle hint
So there can be no disgrace-
Not disrespect for nose and mouth,
Naught but joy when seen your eyes!

Help me, pray, assist one man
That, assured, he'll rest at night:
What amount of sight is mine
On such profile recondite?
* Crallo Brallo
Crallo Brallo in the sea,
Have you got a goat for me?
Crallo Brallo on the land,
Will you lend a helping hand?
Crallo Brallo in the sky,
How ever did you get so high?
Crallo Brallo in the moon,
Hope you learn to escape soon.
Crallo Brallo in the sun,
I'm afraid it's time to run!
* Jewel
Folded carefully into her brown hair, the green jewel was once the carapace of a flower beetle. It settled in the light from the back door, no longer obscured by the steam of boiling spaghetti-water. Consciously I reached for it, but she was not willing to stay, and I not to restrain. The accident did that to us, made her afraid, and I―who had been driving―wanted never to feel life struggle in my arms again. After an hour's conversation I looked away from her car pulling from the driveway to that jewel, sitting lifeless and dark on the counter table.
* Killer's Cry
See
The knowing look in your scoundrel eyes
When they alight upon mine.
Glance at the mirror if you don't believe me.
Do not be deceived,
If I have to I will kill,
And likewise you will die.

A knife?
You see in my hands a knife, a sword, a gun,
A wire 'round the neck
A heavy flashlight that caves in the skull.
My hands are bare (though I could yet kill with them)
The police will side with me.

Accusing orbs,
Wretched facsimiles of light,
Turn from me!
There is only one body at your feet,
But it can be joined.

Why do I wait?
How can eyes arrest movement?
I should see your blood across the ground,
Breathing,
Beautiful.
I should
See.

I would take you to my bed,
But you would not come.
I would talk with you at night,
But you would not stay.
I would slit your body from stomach to breast, 'till you screamed,
But for the glazing of your eyes.

My hand is stayed.
I am broken.
I am as those who cry.

There is only one body at your feet,
And it is mine.
* Staff and Stone

** 1. The Servant

There was a man of myriad might,
Who fought a fair and fabled fight.
Who buried buildings, and broke bones,
Who saw the city of Staff and Stone.

To whom was handed herald and heed―
For never was known another need
To gain the ground and guard the good
When war is woke, as it would.

Yet cruel was the city that carved his crown,
And it decided to drive him down,
Upon the death-bird's bloodied beak
Whom sinful souls in silence seek.


** 2. The Bird

Gentle breath being all she takes,
The deadly bird of prey awakes.

Resting, now, her head on hand―
Watching, now, her hand in light―
Seeing, now, the light on blade―
Holding, now, the blade for fight.

She will fight for those who stay
In shadows, names and reasons untold.
She will kill for those who pay
With handfuls of silver and blemished gold.

Holding, now, the blade for fight,
She flies quietly into the night. . .


** 3. The Knife

And yet,
She turned back,
          And looked upon the place
Where she held him,
And let him fall,
          And looked into his face.

And her hands
Were cold
          As she saw the blood
On her knife,
At his throat,
          On the ground mixed with mud.

The knife dropped
From her hand
          As she lay on her face,
And her tears
How they fell!
          For he who died in that place.


** 4. The Assassin and the King

There was no trial, no tangible test.
Only she, returned from rest;
By Stone strong and Staff slender,
A judge unjust, of fairer gender.

She was a woman who walked the ways
Of death and deception, during her days.
Known only in darkness, named only at night,
She murdered the man of myriad might.

And thus lives his legacy, thus his life;
A sorrowful soul in service of strife.
He rests now 'neath rust and rot,
By few unfavored, and by none forgot.
