* Carved World

There was an old man, on the steps of the palace. He was alone and seemed to be half-asleep where he stood. It was not until the cold, thin wind picked up that he opened his eyes. He breathed deeply, the air stinging in his lungs, and looked into the sky. There were gray clouds coming from the East, bringing rain and hail. Today was the day of a great celebration, and the storm would mean changing plans, cutting ceremonies short so that the people could return to their crops and preserve all that was there. The old man closed his eyes, the one of flesh and the other of glass, and when he opened them again, the clouds were gone. He walked up the stairs and into the palace.

There were no people in the entrance chamber, but the room was filled with music. The music emanated from the auditorium and flowed through the empty hallways, echoing against the walls; it was a sound of emotions, of joy and sadness; it was beauty enough to ease a thousand hearts' worries. So said all who heard the symphony. The old man opened the door to the auditorium half an arm's length and looked in. He was careful not to make any noise, although if he had no one would have noticed. Nobody even saw him, or noticed as the great man peered through the crack in the door and beheld his creation. The music passed over him like water over rock, and although he knew every note and every instant of it, he could still appreciate the work of art that he had created ¡V or rather, had helped to create. It was not truly his. It belonged to the young man sitting in the front row, and to another, who was now conducting. The former was their leader, everyone's leader. He had been elected the day before, and today had been the ceremonies, the new legislatures and the celebrations, culminating in this symphony. It was the symphony of the new order, of a new age of peace.

The old man closed the door softly, and made his way along the corridor that ran parallel to the auditorium. He ran his hand along the wall as he walked, feeling every brick, every stone, every grain of wood. He knew them all, seeing them in his mind, and again he breathed deeply. He felt the music, too, as it passed through the walls and through his wrinkled fingertips. His other hand hung limply at his side. That hand had died long ago, and he had it covered now by a heavy leather glove, to hide the dry black skin. He walked up a spiral staircase leading into one of the private boxes, his tired feet aching with every step. He wanted dearly to simply rest.

The old man finally reached the small balcony, which was empty. He walked slowly to the farthest corner of the the box, and lowered himself gently into a chair. It was the box he had reserved, at the very edge of the auditorium, and though it had a bad view of the stage he could see every other occupant, every single person in the room. He saw the faces of the leader and the council and of all those who were ushering in the new society. It had taken many years to achieve what they had; years of quelling wars and uprising, of ordering chaos and returning hope to the once-barren lands. But now it was done, and they had - peace. And it would not last forever, but it would certainly last a long time.

The old man closed his eyes and inhaled slowly, listening to the music. It was very beautiful.

!!!

Dagan had felt it when the symphony had started, and he was now running towards the palace. He could not explain how he knew, but he had felt it in the very core of his being, had run to the old man's house and known even before reaching it that it would be empty. He had known the night before where he would have to go to find the man, but he had not entirely believed it until that moment, and that realization spurred him on to the palace, up the stone stairs and into the entryway. The symphony was in its last movement, and for a moment Dagan stopped, his eyes closed, its beauty and grandeur sweeping over him. He forced himself to move again, and he ran quickly down the hallways, not knowing where to look, his steps echoing through empty rooms. He ran up and down staircases, praying he was not too late, not even positive of what he was afraid of missing. It was a feeling rather than a reason, a feeling that had gnawed and grown within him the whole day, and by the time he acted he could feel nothing else but this driving emotion.

Dagan wrenched open a door and ran up a spiral staircase, two steps at a time, and when he got to the top he saw ¡V the man. He was simply sitting there, listening to the symphony. For a moment Dagan thought he saw a wreath of light around the man, shining from him, but then it was gone. He was simply a very old man, peacefully enjoying the symphony.

Dagan spoke the man's name. The old man turned, and smiled.

¡§Friend,¡¨ he said, ¡§I wondered if I would see you today.¡¨

¡§Hello,¡¨ Dagan said, simply. He had thought he knew exactly what he was going to say, but now he couldn't seem to form the words. He sat down in the chair next to the old man, and watched the orchestra for a moment. The many violinists, the percussionists with their kettle drums. . .

¡§I thought I'd find you here.¡¨ Dagan said, keeping his eyes on the orchestra. ¡§But I thought you would come for the inauguration.¡¨

¡§I wanted to hear the symphony as it was meant to be played. That is all there is left for me.¡¨

¡§The government won't be perfect. We will still need your - guidance.¡¨

¡§I have done all that there was for me to do.¡¨

¡§Yes! Yes, you have! You have given us everything that you had, even when you had to destroy your own body! Why can't you spend your last years in rest? Why can't you allow yourself even that much?¡¨

Years ago Dagan had met a young, strong man who had an unrivaled desire to give, to help in every way that he could. He had spoken grandly and excitedly of the society that they could have, he had helped build houses, feed the poor, care for the sick, he had smiled and laughed, and now. . . Now there sat before Dagan a man who was old before his time. Dagan thought of the way the man's body had died and decayed so quickly; he looked at the man, seeing the frail skin, the glass eye, the leather glove. And he felt terrible. Never had the man put himself before any other person, never had he accepted even the barest of rewards for his work.

¡§You are sad,¡¨ said the old man, ¡§because you think of me as a man. You think that because of what I have done, because of my weariness, I am not at peace. Friend, I tell you, I am at peace. I have fulfilled my purpose.¡¨

Dagan was silent for a long time, trying to ease the constriction he felt in his throat. He listened to the symphony, and let it soothe him.

¡§You created this,¡¨ Dagan said.

¡§Created? No, I could never create anything. I could only ever destroy.¡¨

¡§You remember the first uprising, don't you? At the state council. They killed the guards and held a sword to the throat of every man in that room, but you spoke to them, and they surrendered.¡¨

¡§I told them nothing they could not hear from anyone else.¡¨

¡§You spoke to the boy, also, the one who fell down the well and broke his leg. He screamed and cried and would not listen to anybody when they told him to take hold of the rope, not even his parents. Yet when you spoke to him, and your eyes met, he was calm.¡¨

¡§He was young.¡¨ The old man smiled.

¡§And the candle?¡¨

¡§You are referring to incident on the ship that brought us our library?¡¨

¡§Yes. I remember that most clearly of all. While they repaired the mast's line I spoke to the guard who had left the room that held the books, and he told me he had set his candle down on the floor in his haste, but that he was not worried because it was in a puddle of water. How could there have been water in that room? I was the one who realized what had happened, that if the guard had stopped to check he would've seen that a lamp had broken and its oil had leaked onto the floor. I ran to the hold, expecting every book in the room to be destroyed, but the candle had burned itself out. I came into the room and saw nothing but a thin disk of wax in a pool of oil.¡¨

¡§I heard of that, yes. Do you hold me accountable for good fortune?¡¨

Dagan shook his head. ¡§There was no fortune. It would be easier to stand a sword on its point than balance a candle upright on a ship, when there is a high wind and one of the mast's lines is broken. You did that.¡¨

The old man was silent for a moment. He lifted his leather gauntlet with his good hand and considered it. ¡§It is not difficult to remove the fear from a child,¡¨ he said, ¡§or even the hatred from an insurgent. The fire I merely held in my mind, and it was gone.¡¨

¡§And that was the day your eye began to dim,¡¨ Dagan said.

¡§My medium is death, Dagan!¡¨ the old man said, meeting his gaze. ¡§I am no stranger to it! Everything I have done for you, for your people, I have done by destruction.¡¨

¡§Would you deny that the statue maker is an artist, because he can only remove from the stone, but never add?¡¨

¡§To carve the stone is to use the gifts that God has given you. To create the stone. . . Only God can do that.¡¨

¡§And you are not a god?¡¨

The old man laughed shortly. ¡§Do I look like a god? No, I do not think so; gods do not die.¡¨

Dagan took a deep breath. ¡§It was my purpose to protect you-¡¨

¡§It was your charge,¡¨ said the old man, ¡§and of that charge you are now released.¡¨

¡§But do you have to die? Now? Can't you stay a little longer, even if you are weak. . .¡¨

¡§Dagan,¡¨ said the old man, ¡§tell me what you hear.¡¨

Dagan listened. The symphony was very quiet now, but he could hear it. He could hear the beating of his heart. And, what else?

Dagan suddenly felt cold. He spoke the old man's name again, and then,

¡§Why aren't you breathing?¡¨

The old man did not look at him. ¡§I stopped breathing shortly after you arrived.¡¨

Dagan was shaking, his own breath coming in large gasps as though he could breath for both of them. He tried to speak, but the words caught in his throat.

¡§There is only one true sadness I have felt in my time.¡¨ said the old man. ¡§And that is to not be able to enjoy art. Anything I hold in my mind, anything I truly imagine is destroyed, and becomes lost. So I came here, I came to hear the symphony and know that my work was done. When I saw you, I knew that it was, so I did the one thing I have always longed but never dared to do, and I imagined myself.¡¨ He shuddered, as though the old body were giving up the last of its life. ¡§I held in my mind myself, my purpose, my life. I am dead now, my power is gone, and I am free to listen, and to feel.¡¨

The symphony was almost at its end now. Dagan was quiet for a long time before he was able to speak.

¡§What about them?¡¨ Dagan gestured to all the people in the auditorium. ¡§Will they remember you?¡¨

¡§They will be fine. They may remember me, but history will not, because it is not my purpose to be remembered.¡¨

¡§Your purpose. . .¡¨

¡§My purpose was to help. I was sent as a man, and I am a man, in all ways but one: there is no greed in me.¡¨

¡§That's why you could destroy,¡¨ Dagan said, and the old man nodded.

They fell into silence. The symphony ended to a great, tumultuous applause. The crowd stood, and the conductor bowed. The leader climbed onto the stage and shook the conductor's hand, and then embraced him, for they were friends. The musicians, too, were shaking each other's hands. The applause was almost deafening. Over it Dagan said loudly, ¡§What will happen to you now?¡¨

He turned, wondering if the old man had heard him, but all that he saw in the seat beside him was the leather glove.
* practice dialogue
Carved World

There is an old man standing on the stairs of a great palace. There is no one else around. He is weak and frail, and as the cold wind blows past him he's woken from a sort of half-sleep. He looks into the sky and sees storm clouds off in the distance. He closes his eyes, knowing them, and when he opens his eyes, the clouds are gone. One of his eyes is glass.

Where did he come from? He came from the city, from his house, and yet he came from nowhere. Perhaps when he goes to sleep every night he ascends or descends or transcends this world into another one, returning each day. It's not known, and it's not important. What's important is that he's here now.

He walks into the palace. There is no one in the entrance, but through the doors to the large chamber can be heard a beautiful symphony. The old man opens the door partially to look in, cautious not to distract anyone – but he needn't worry. They are too enthralled in the magnificent symphony to even notice him. He recognizes its beauty, even though he already knows it very well. He closes the door and walks along the hallway until he reaches a closed staircase against the wall, which he enters. At the top he walks through a door and is in a box seat in the performance hall, which is empty. It is the box furthest from the stage; the one he requested be left empty. He sits down slowly, with a sigh, resting his old arms on the arms of the chair. He puts down his cane, and listens peacefully to the symphony.

Meanwhile, the man named Dagan is rushing through the palace, looking for the old man. He came from the city just moments before. Why wasn't he at the palace in the first place?

Hello.
My name is Dagan.
Certainly.
I wanted to find the old man.
I don't remember his name.
As well as anybody knew him, which was not much.
Partially. Butuhe left, and when he did, hae did not stay in our memories well.
Yes. It is because it was not his purpose to be remembered. His purpose was to help.
Yes.
The government. Before he came it was barbaric, terrible. New rulers were chosen by assassination. Taxes were ehigh and many people lived in poverty. The entire nation was in a state of civil war.
I don't think I said that. He and I lived in the same city in which this took place, yes, but the effects were broader than that. Our city is the capital of the entire nation.
I don't think its important to name is.

OK, I'm going to start typing my questions, so that I'll have a log of them. Is that alright with you?
Certainly.
P[
So, you said you were rushing towards the palace to find the old man, correct?
That is correct, yes.
Why did you want find him?
I wS AFRAID HE WAS GOING TO DIE.
Because his job was done. He had united the nation and set up a new government. It was all very good.
 But why would that make him die?
Perhaps I shouldn't have used that word. I do not mean die, precisely. I'm not even sure he could've died. Wwhat I meant was, I was a fraid he was going to leave us.
Leave you?
Yes. You have to realize that this man was not an ordinary person.
Oh? He was extraordinary?
Yes.
How so?
This man united a nation that had been at war with itself  for two hundfred years. In less than a single generation he repaired the damage of thirty kings and leaders before him.
Was he a king?
No. He never had an official position. He was simply an advisor.
An advisor did that much?
I told you, he was no ordinary man. He was... different.
In what way?
He had – powers. Or rather, he had a power. I'm not sure I really understand it.
Can you tell me what this power did?

I can't tell you its extent, but I can tell you how he used it. When  he was advising, when he was playing a part in the city's history,  , he was able to... change thiings. Or more accurately, it seemed that things changed around him. The connection was rarely made between him and the strange events, and when it was, he denied it. He was a very humble man.
Tell me some of the things that happened aROUND HIM.
I remember a time when some of the new generals were being sworn in. During the proceedings we were attacked be a group of rebels, anarchists. There were many of them. They came through the doors and killed the guards, and they almost killed the generals and the old man himself. But they stopped.
Why?
Because... he talked to them. He convinced every one of them to stop pand give themselves up.
What did he say?
I don't remember.  I've tried to recall the words he used, burt they are like a dream to me. He spoke of the old government and the government he envisioned, and he spoke of the many horrors and bloodshed the people had seen already. He old them that their efforts would do nothing but promote chaos.
And that worked?
Yes.
Do you know of any other events that happened aroundhim?
Yes, I remember a few more. I remember when, at the of a new building, a young boy fell into a well.  He was a shy and quiet child, not very strong or bold. His leg broke when he fell, and though we lowered a rope, he wouldn'thold on to it. He simply held to the side of the wall and screamed and cried. It was horrible to watch.
Nobody could calm him down? Or persuade him to take hold of the rope?
No, nobody. Not until the man came.
He talked to the child?
Yes, but more than that. He looked into the child's eyes, and he seemed... he seemed to make it known to the boy that if he took the rope, he would be all right. He would be safe. The boy squieted, and took hold of the rope. When they pulled him, out, he was quiet and content. He thanked the old man before they took him to get his leg bandaged. The old man simply smiled.
That sounds incredible.
It was. One more example will suffice. There was a ship, I remember, one of the merchant ships that brought us supplies from the West. He – the old man – and I were both on it during one of its voyages.
What was it carrying?
Iron, I believe. But thator was the least important of its cargo. Most of the crew didn't know it, but the ship was transporting a library, as well. Over a thousand books, many of them very old, purchased for our city's library. They were books of history, and politics, laws and rules. With them we wrote the new laws and legislations, and put order into our nation. There were books of poetry, too, and songs of great beauty. It was a priceless collection, and it wa sinvaluable to our nation.
What happened on the ship?
The books were kept in one of the rooms near the middle of the ship. It was seldom used, and very well-protected.  It was kept locked, and as I sasid, most of the crew did not know its contents. They presumed it to be gold, or something of great monetary value, or nothing at all. There were no one guarding it, but every hour one of the leaders who knew its contents would enter the room and make sure the books were undisturbed.During one of these times, while the man was examining the manuscripts by the light of a candle, one of the mast's lines broke, and there was a great commotion on deck. The man quickly left the room to find out what had happened, and in his haste he placed his candle on the floor, reasoning that if it tipped over it would be extinguished by the water on the floor. If he had stopped to examine the room and smeell the subtance on the floor he would've realized what had actually occurred, that during one of the ship's more violent movements, a lamp had fallen off its holder on the wall and broken, and that the floor was covered with spilled oil. He had pllaced his candle directly on top of the oil, and the room was left unattended for the greater parrt of an hour before anybody checked it.
Were the books damaged?
No. Not one ofthem was burnt. The oil never caught fire.
So the candle was extinguished.
Yes, but not before it had burned through its entire length. When it was discovered, it was no more than a thin disc of wax.
It burned long enough to use all of its wax, and yet never ignited the oil?
Yes.
That sounds impossible.
Indeed it does.
What would have happened if the oil had been ignited?
I am certain that the entire collection would've been destroyed.
What would that have meant for the new government?
I'm not sure, but I shudder to think. It might've made all our efforts over the past years meaningless.
You have given me these three events, these three examples of the old man's powers. But they seem strange coincidences, the work of a great speaker,  and of good fortune. They do not seem the work of someone beyond the abilitiese of men.
So it may seem when I tell you, and so I have at times wondered myself. But you would not forget the sight of that young boy when he stopped crying, not for his mother or his father, but for the words of a stranger. You would not forget the way the rebels' eyes shone as they lay down their weapons and allowed themselves to be arrested.
And the candle?
It would be easier to stand a sword on its point than balance a candle upright in a ship, when there is a high wind and one of the mast's lines has broken.
(1724 words so far)
I'm sorry about the delay in the middle of our conversation, Dagan. I'm afraid it was somewhat unavoidable.
That's perfectly understandable. Think nothing of it.
Thank you. So, before we got onto the subject of the old man's powers – sorry, abilities, as you call them, where were we?
I believe I was describing his pllace within the government.
Ah, yes, thank you. You said he was an advisor, but held no official position.
That is correct, yes. 
The rulers never resented being – that is, taking the advice of a stranger?
He was a difficult man to dislike. And besides, the work he did for us was, as I've said, incalcuable.
You gave me the examples of, as you say, his powers. Could you give me some examples of how he shaped the new government?
Besides the other ones? His effect can not be very easily broken down. Where he spoke, people listeened; where he worked, they made progress. He was an inspiration to all who saw hoim.
He sounds almost angelic in nature.
He was not without flaw. I saw him angry, at times, and he was very prideful. But yes, he wwas a remarkable person, certainly more than a man.
I feel we've gotten very far off the main subject, and I think it is about time we get back to it. You were rushing towards the palace, where the oldl man was, because you were afraid he was going to die.
Yes.
Why did you have this fear?
It's not a simple answer, and ultimately I'm not sure I know myself.  This occurred at, essentailly, the end of the creation of the new government; that day was the appointing of the mayors and governors. The palace was playing host to a symhpony in honor of the new government. It was a day of celebration.
The old man...
He was there, too, at least, he was there when I got there. He didn't make a fuss, or make himself noticed, or talk to anyone at all; he went to the private box he had had reserved, and he sat alone and watched the symphony.
He didn't take part in the celebrations?
No. Not at all. He was very tired, and it seemed he wanted nothing else other than to listen to the symphony.
When you say tired, do you mean – well, how do you mean that, precisely? Emotionally, or physically?
Physically. I remember when I first met him – he was a few years younger than me, strong, and full of energy, full of life. At the symphony he was an old man, with an old, broken body.
How is that possible?
He aged very quickly,. His body decayed and was strained under the amount of work he did. He sacrificed himself to help us.
To help you?
Yes... I cannot say for certain, but I believe that his powers – his abilities, whatever extent they reached to, took much effort of him. If you had seen him then, that day, with his glass eye and his iron glove, you would understand what I meant.
An iron glove?
Yes. He used it to cover his hand.
Why?
That hand died long ago. He used the glove to hide the shriveled black flesh.
You believe his hand and his eye were caused by the help he did?
It is an astonishing tale, I admit, but it is all true.
I realize that this has been a very short visit – for which I am sorry; the fault is mine – but I must take my leave for the night. Tomorrow I shall try to make our meeting sooner and of greater length.
Thank you. Good night.
(2340 words so far)
Hello? Dagan?
It is pronounced “Dah-GAHN.”
Ah, thank you. Where were we?
I believe we were at a stopping point, so this time we are not restricted in where we start.
We were talking about the old man's powers.
Yes, and from now on I think we should refer to him as the Advisor. A title like “old man” is somewhat insulting.
As you wish.
As you said, we were talking about the Advisor's powers. But I think I've spoken of them long enough.
Very well. However, before we go on, would you mind elaborating on the incidents you mentioned earlier?
Certainly, although I think it would be better if we first finished with my story.
Alright. Where were we on your story, anyway?
I was going to see the Advisor at the palace.
Because you were afraid he was going to leave.
Yes.
OK. Why was he at the palace in the first pllace?
Everyone was. That is to say, everyone who was close to the origin of the new government was there.
The leaders?
Yes, and others. There were about four thousand people there.
Was it some kind of ceremony?
That was part of it. It was a long day of celebrations, inagurations,  signing of documents, that sort of thing, and it culminated in a grerat symphony.
When did you arrive?
I arrived after most of the ceremonies were completed; they held little interest to me, knowledgable as I was about the new government. I came in time to hear the symphony – the end of it, at least.
How was it?
It was... sublime.
Did you find the old man?
Ys. I found him in one of the otp balcnois – a privaet box. There wer man yof htem in the concert hal.
Was he alright when you found him?Yes. No... no, he wasn't. That is, he was very weak, but then, he had been weak for some time. I remember coming through the door, panicking, my heart racing, and seeing him just sitting there, so calmly and peacefully...
Was he alone in the box?
Yes. He had reserved that one for himself.
Are you aware of how long he  had been at the palace?
I believe he arrived only in time to listen to the symphony, but nothing else.
He didn't come to watch the final stage in the creation of the government?
It would seem not.
I-
He was very modest, as I said.
Of course.
I arrived at the palace... when I arrived, there was no one in the entrance hall., Nearly the entire place was deserted, except for the main hall. I ran through its many floors and staircases for about ten minutes before I found the man.
Let's back up a bit. Why were you worried about him leaving in the first pllace?
You asked me that earlier. It was because his job was done.
You said he was an old man, and weak. Even if his job was done, could he possibly had plans beyond his life in your nation?
You remember that before I said I was afraid he'd leave, I used the word “die.” Peerhaps that is the more appropriate word, after all.
Well, it must be one or the other.
That is simple to say. It was not so simple then.
You base this line of thought on the abilities you percieved in him? His extraordinary nature?
I base this lineof thought on his nature, yes, and I base his nature on his origin.
His origin?
Of course I could never tell you where he came from, and he never told me. If I asked him he would make vague allusions to a pllace “very far from here” or “of another time and another culture.” Of one thing I am perfectly convinced, however: his presence was not an accident. His sender was benevolent.
God?
I didn't say that, but perhaps. He denied it, or at least, he didn't accept it. But I think he did so more out of modesty than honesty. Unless...
A third possibility?
...unless he didn't know himself. That is something which he also suggested then.
Perhaps you ought to tell me about the discussion you two had in the private box.
That seems the thing at hand, doesn't it? I remember that, as I was running through the palace, I wa and to the palace, I was determining exactly what it was that I was going to say to him when I found him. I was going to confront him with all that I knew or thought I knew or would act like I knew, and I would explain to him precisely whe needed to stay.
+Were you worried that his absence would harm the government?
No, not at all. I simply didn't want him to leave. He was a dear friend to me. I knew him perhaps more than anyone else.
And yet his name eludes you.
Yes.
So, what did you two talkl aboout?

When I reached the box, and saw him, my words left me. I simply greeted him. He smiled, and becknoned me to sit with him. I did, and for some time we simply listened to the symphony. When at last I could speak, I told him what I have told you I had meant to tell him – that the government would still need his guidence. He assured me that they would not. I urged him to stay, but he simply smiled and said nothing. Eventually I pleaded with him, and he told me...
What?
He told me to listen.
What?
He told me to listen. And when I did, there was something I did not hear. The bearting of my heart.

...
It is not something I am fond of recalling; the chill down my back as I urged my ears to hear, to listen... but there was nothing to hear. He was dead.
Would it be all right if we stopped there for the night? We are almost done, I believe.
Yes, I think that would be best. I am saddened by these memories, anyway. Goodnight!
(3362 words so far)
