Some troublesome formatting. PDF preferable.

CAST
BY NATHANIEL RHEIN


CHARACTERS:

BAER - An old man
JOHN COGOROUGH - A young man
PENELOPE (PENNY) - Cogorough's wife
PADSFORTH - Friend to Cogorough and Penny
FIRST and SECOND - Travelers
* ACT ONE


(The stage has three sections:
	The higher section is a small modern building, like a temporary military base, with one room. It is sparsely furnished, but does include three single beds - two of which have been pushed together and are not made. It also includes a small table on which rests some sort of computer or screen. The only door goes off-stage. The lights here are dim.
	The lower section, and the largest, is the exterior of an old stone building. Outside the building is a stone staircase leading up and off-stage, and a large rock with a flat surface like a table. The ground outside the building is littered with stones and garbage, mostly old, broken machinery. There is also an old, tattered book among the garbage.
	The third section of the stage, which can be between the other sections, around the outside of the stage, or anywhere else that can be made to work, is an interim area, simply a small expanse of rough terrain which is obviously distinct from the other sections.
	It is night. There is no moon and no clouds, and stars are clearly visible. The There is an old man, BAER, outside the stone building, busy examining many of the rocks and pieces of trash. He is wearing an outfit appropriate for traveling. It is old and dirty, but still in decent condition. There is a ragged, filthy cast on one of his forearms, extending from just under his elbow to partly over his hand, immobilizing his wrist and thumb. He can move his arm without trouble but is able to use that hand in only a very limited capacity. He is protective of his wounded arm, especially when he feels threatened.)

BAER
(To self.)
There are a lot of pieces here. Too many, some say. They say if you have too many pieces, you'll never be able to decide which pieces to use. But I'm better than that. I know exactly what I'm looking for. I'm sure it's around here somewhere. In another moment I'll have found it.

(COGOROUGH enters from staircase. He is a young man and wears a simple, functional outfit; the casual form of some uniform. He is deep in thought and does not look at BAER.)

BAER
Do you have anything for me?

COGOROUGH
No.

BAER
What do you have?

COGOROUGH
I don't have anything for you, old man.

BAER
But you might have what I need! It's just around here somewhere, maybe you took it and thought it was something else.

COGOROUGH
(Looking at Baer.)
Will you be quiet? I don't have anything.

BAER
It's all I need. It's the last one.

COGOROUGH
It's the last what?

BAER
The last piece. The last part. I have all the other parts. I just need the last one. I know it's here somewhere.

COGOROUGH
How will you know when you've found it?

BAER
I'll know. Oh, I'll know. I know just what it looks like. It's all on the surface. I'll know the markings.

COGOROUGH
You're a damned idiot.

BAER
And you're a gentleman.

COGOROUGH
You've been here since you woke up haven't you? Looking through this garbage? I remember when I first came here, you were searching. The same garbage, the same worthless things, and you among it, always searching. I remember.

BAER
You were nicer then.

COGOROUGH
Things change. Except for you. You just grow old. One day you'll die, and then you'll never find what you were looking for.

BAER
(Stops searching. Looks at COGOROUGH.)

COGOROUGH
I'm sorry. I didn't mean that.

BAER
What else do you remember? Do you remember her?

COGOROUGH
Yes.

BAER
Do you remember what she looked like?

COGOROUGH
Yes.

BAER
Do you remember her hair?

COGOROUGH
Yes! It was yellow.

BAER
What?

COGOROUGH
It was yellow.

BAER
(More intense; coming closer to COGOROUGH.)
And what about her voice?

COGOROUGH
Yeah, I remember her voice.

BAER
What do you remember?

COGOROUGH
Her... her singing. I will always remember her singing.

BAER
What did she sing?

COGOROUGH
Yes...

BAER
Cogorough! What did she sing?

COGOROUGH
She sang about the sun.

BAER
What else?

COGOROUGH
The beetles.

BAER
What else?

COGOROUGH
The homestead.

BAER
What color was her hair?

COGOROUGH
It was yellow.

BAER
What happened the day you broke your arm?

COGOROUGH
I fell. We were looking for something in the dark, I tripped and fell.

(BAER moves closer to COGOROUGH. COGOROUGH backs away from him.)

BAER
What did she do?

COGOROUGH
She came running. She saw me and she ran to find something to put on my arm.
(He touches his arm unconsciously.)
She told me not to worry, she said it would heal if I let it alone. She took me back to the house - 

BAER
What house?

COGOROUGH
She took me to the house.

BAER
Where?

COGOROUGH
To the house!

BAER
To which house!

COGOROUGH
To her house!

(COGOROUGH sways, about to fall, and is caught by BAER.)

BAER
What color was her hair?

COGOROUGH
Golden!

BAER
What?

COGOROUGH
It was golden! It shone against the night sky and I felt it, it was warm against my fingers and the back of my hand. Her whole body was warm, it was soft, she lay in front of the fire each night and even then the sky and the sun were in her eyes.

(COGOROUGH is looking at everything, at nothing. BAER steps away from him.)

COGOROUGH (cont'd)
I saw her in the light. She was home there, with the warmth all about her. She was herself, she was really herself! I saw her - she spoke to it and guided it around her and it was her guardian and her lover. She was a creature of light. She looked into the sun and didn't flinch. She looked straight into the sun.

BAER
Did you look into the sun, as well?

COGOROUGH
(More lucid.)
I looked at her, and that was very close. But I never saw the sun. I asked her if I could see it, and she said I could, but when she opened the door I was too afraid and I made her close it again. I told her it was enough to look at her.

BAER
At a woman?

COGOROUGH
What? Yes. At a woman. It was enough. She was beautiful. I could not stand the sun's terror, but I could stand her beauty.

BAER
I'm sure you could.

COGOROUGH
(Having fully recovered his senses.)
...What did you do? Why did you make me say that?

BAER
Say what?

COGOROUGH
Everything.

BAER
You told me I was going to die.

COGOROUGH
(Pause.)
I'm sorry.

BAER
Yes. Well. Remember there's only one of us can die, and that's whichever one can't kill the other.

COGOROUGH
I'm sorry. You're very poetic.

BAER
Were you listening to yourself, earlier?

(COGOROUGH says nothing. He walks to the rock and picks up a jagged piece of glass from behind it.)

COGOROUGH
Is this what you were looking for?

BAER
No. But it's close. The markings aren't quite right.

COGOROUGH
What markings?

BAER
You can see them if you look closely enough. They're almost right. Almost exactly right. That's how I know what I'm really looking for must be very close.

COGOROUGH
Do you think you'll find it?

BAER
I know I'll find it.

COGOROUGH
When?

BAER
Soon.

COGOROUGH
When it's daytime, and you can see more clearly?

BAER
Yes. When it's daytime. Then I'll see it.

COGOROUGH
It's never daytime here.

BAER
It will be very soon.

COGOROUGH
No, it won't.

BAER
You will see.

COGOROUGH
I already see. I know it won't be daytime because I already see. You're the one who can't see. Do you understand anything?

BAER
You are too kind.

COGOROUGH
Yeah.

(He places the piece of glass on the rock and walks to the staircase. Pauses before going up.)

COGOROUGH
I hope you find what you're looking for very soon.

BAER
I will. It's just around here somewhere. It's very near.

(COGOROUGH exits via staircase.)

BAER (cont'd)
I'm sure it is. There are many pieces here.

(He continues searching. Picks up the tattered book and examines it closely.)

(To self.)
All these pages. Why would anyone need so many pages? They all say the same thing, different shades of the same unmeaning illogic. The inane ramblings of dead ramblers. It doesn't matter any more. I cannot fathom why these things are so often kept. All these pages, all these books, all the same. The same old tripe.

(Tosses the book onto the rock. Sees the piece of glass.)

What's that?

(Walks over to the rock, picks up piece of glass carefully, examines it.)

He left this. This isn't what was here before. He brought this and he left it... It's interesting. What is it? A fragment of a window, a piece of the sky, a segment of a glass snake or eel. What shall I do with it? I can't keep it here, it's too crowded already. If I don't keep track of the things I have it will take longer to find the last piece. This one is in the way... Why does it shine like that?

(Places the piece of glass back on the rock and walks over to the other side of the stage, talking while he walks.)

There are six people who come to visit me. No, three of them come to visit me, and two of them come to fight with me. I don't know why the sixth one comes, because that has never happened. Cogorough comes to fight with me. He says unkind things. I have to say unkind things back or make him say unkind things to himself so that he'll go away. If I didn't then he'd never leave me. He'd wait until I fell asleep and then he'd take me away to - 

(BAER turns abruptly towards the top of the staircase, from which we can hear PENNY speaking.

PENNY (Unseen.)
I don't think that's really necessary. No, no, I'll be fine. Just stay here, will you? Thank you. I won't be long.

BAER
She comes occasionally. It's been a while since her last visit. The last time she came I nearly found what I was looking for. Maybe this time I'll find it. Maybe she'll help me. She comes to visit. She doesn't come to argue with me.

(PENNY appears at the top of the staircase and walks down. She is a young woman. Her hair is very short or otherwise out of the way; her outfit is similar to COGOROUGH's in style and functionality.)

PENNY
Hello, Baer.

BAER
Hello, Penny. How have you been?

PENNY
Oh, I've been alright.

(She sits on the bottom step of the staircase.)

BAER
Has he been treating you badly?

PENNY
Who?

BAER
(Gestures towards the top of the staircase.)

PENNY
Oh, no. Just a little disagreement. Nothing serious.

BAER
That's good. You do get along so well most of the time.

PENNY
Yes... You're very kind. I know you don't like him.

BAER
I never said that.

PENNY
Not all things have to be said, Baer.

BAER
No, I suppose not. But it's not that I don't like him. I just get nervous sometimes. Do you understand?

PENNY.
Yes... have you considered the medication I told you about?

BAER
Medication! I don't want pills!

PENNY
Baer - 

BAER
No, I won't!

(He takes a pocket-watch from his pocket and walks swiftly to the rock.)

PENNY
Baer, listen - 

(She is interrupted by a loud crash as BAER slams the pocket-watch on top of the rock. He leaves it there.)

PENNY
(Pause.)
Have you found what you've been looking for yet?

BAER
No. But it's very near. Will you help me look for it?

PENNY
Sure. I'll help you find it. What does it look like?

BAER
(Holds up the piece of glass.)
Like this. Like this, but the markings are different. More symmetrical. This one's off. It's in the way.

PENNY
I don't see any markings on it.

BAER
They're off. They're all wrong. But the right one's just around here. I can feel it. It's very close. If you help me look for it, I know we'll find it.

(He places the piece of glass on the rock and returns to his searching.)

PENNY
I'm afraid I'm not very good at finding things.

BAER
(Chuckles.)
Of course you are, dear, of course you are.

PENNY
Why do you say that?

BAER
(Getting down on his hands and knees to continue searching.)
Because it's true. You know it's true.

PENNY
Why?

BAER
You can see more clearly than I. More clearly than he can, too. You're a finder. When a man needs something and he finds one of you, he knows that he doesn't have to worry about what he's looking for because she'll find it for him.

PENNY
Tell me about finders, Baer.

BAER
(Stands up before talking. Continues searching, but slower and more distracted.)
Ah, now you're having fun with me. Why should you ask me about yourself? I should let you speak, and then you will have your answer. Or maybe you're trying to have some fun at my expense?
(Chuckles.)
You're funny, Penny.
(Pause.)
There's nothing to say about a finder that's not in the name. A finder finds things; she can't not. Truth is, I don't think there's anything can be found without a finder somewhere along the way. It's your eyes. They see things that others... that I can't see. They're keener than mine. Now, my eyes are as good as any man's, but there's nothing... nothing like the eyes of a finder.

(He stops what he's doing and takes a long look at PENNY.)

BAER (cont'd)
You're a pretty girl, you know that?

PENNY
(Stiffly.)
When are you going to find what you're looking for, Baer?

BAER
Very soon... I think...

PENNY
What if I don't help you?

BAER
You already are.

PENNY
There's nothing I can do for you, Baer. I'm not good at finding things. I'm not special.

BAER
That's not true.

PENNY
Yes, it is. I couldn't even find my way back to my home if I needed to. John is the pilot.

BAER
I hardly think you need a pilot.

PENNY 
Baer, please listen to me. You have to understand all of me if you want to understand part of me. You have to know my whole self if you want to know me at all. You can't keep making things up.

BAER
I don't make things up.

PENNY
Yes, you do. You don't make people up but you take their experiences and you switch them around until they aren't true any more. You take words that are correct and you put them in wrong orders. What about this mess?

(She gestures to the garbage.)

What did this used to be? Did it used to be anything? This has to have come from somewhere, Baer.

BAER
This has always been here. Well, as long as I have.

PENNY
And how long is that?

BAER
How long -  Penny, what is this?

PENNY
How long have you been here? Please, Baer, I need to know!

BAER
What are you talking about? You're not making any sense.

PENNY
Why not? Why can't you answer my question?

BAER
Penny, it's not as simple as all that. You look at -  you look all these pieces, and you think of them as lifeless. You think they're not moving, but they are. They're moving constantly. There are vibrations in every one of these, in every piece of the universe there are vibrations. What you have to know is how to read them. There are markings you have to understand. They're symbols. You have to know where they lie, where the sun's light falls on them.

PENNY
What do you mean by that?

BAER
The sun, the sun is the answer. It will show which is the right one. As soon as it rises, I'll find it. I'll know by the markings. You will, too! Oh, it will be clear to anyone who looks at it. I'll even let that foul one, Padsforth, I'll even let him see it. I won't care, then.

PENNY
What if the sun doesn't show you? What if the sun comes up and everything looks the same, but brighter? Baer, what if there's no difference between these things in the dark and these things in the light.

BAER 
Of course there is! There has to be.

PENNY
Why?

BAER
I can find what I'm looking for in the light. It's too dark now. I would have found it already if there wasn't the darkness in the way.

PENNY
When was the last time it was bright?

BAER
Yesterday, of course.

PENNY
What happened yesterday?

BAER
I lost the last piece.

PENNY
Why couldn't you find it then?

BAER
She left.

PENNY
Who did?

BAER
(No answer.)

PENNY
Who left? Was she a finder?

BAER
I remember her.

PENNY
Who do you remember, Baer?

BAER
Why do you ask me so many questions? Why do you always want to know about my life? Why are you always asking, taking, never giving? Yes, yes, you're willing to give your pills, what you call medication, what you call help, but you never give anything of value. You never give up anything that's yours. If you were kinder, you'd help me find what I'm looking for. Just by being here you're helping, but you could do so much more. Don't you understand? It's the last piece! It's the last one I need, the very last one, and I've been searching for so long.

PENNY
How long is a day here, Baer?

BAER
A day is always the same length. It is the time it takes for the light to come and pass.

PENNY
How long is that?

BAER
Longer than I would prefer. But I'll know for certain when she comes back.

PENNY
And when will that be?

BAER
Tomorrow.

PENNY
...I see.

BAER
(More animated.)
You should move around more. Stretch your legs and breathe the fresh air. I remember when you first came here, I remember you wore a mask because you were afraid of the air! Well, at least I cured you of that fear. But you're still afraid of it, I can tell; you always run back to your home to breathe the air there, because that's the only air you really trust. It's the only light you trust to meet your eyes and the only smells you trust to touch your nose. It's the only place you feel comfortable. But you have to get past that, beyond that. You have to learn to feel... the wind, and the light of the sun.

PENNY
I've felt the light of the sun.

BAER
Of course you have, Penny.

PENNY
Have you?

BAER
What do you think?

PENNY
You know what I think.

BAER
You can't just say that. You can't just say that and expect it to mean anything.

PENNY
You want to know? I think if you saw the sun now it would kill you. You were afraid of it before, weren't you?

BAER
Who told you that?

PENNY
John did.

BAER
You mean Cogorough? You can't trust him.

PENNY
Of course I trust him. I love him.

BAER
Then you won't listen to anything I say about him, will you?

PENNY
That's not - 

PENNY
Forget I said anything.

PENNY
You were afraid of the sun before.

BAER
You can't know that.

PENNY
I don't have to have known you to know that! I don't have to have been there and asked you, and asked you that very question to know the answer now! It's more complicated than just the way things look, just what's on the surface. What's on the surface doesn't mean anything, it means less than nothing. What's on the surface lies - 

BAER
Like me? Like how I lie?

PENNY
I didn't say you lied.

BAER
You did.

PENNY
No. I said you made things up. I said you changed things, re-arranged them and that the result - 

BAER
(Taking the pocket-watch from the rock.)
I think our time's up, Penny. I'm sorry.

PENNY
Baer, don't - 

BAER
I'm sorry, Penny, but I can't put any more time in the day, no matter how adept I am at re-arranging things.

PENNY
Baer, please, don't be like this.

BAER
I'm sorry. But it's time for you to leave.

PENNY
Baer, listen, what do you want me - 

BAER
No more questions.

PENNY
What do you want me to say?

(BAER quickly takes the piece of glass from the table in his good hand and, holding it like a knife, advances on PENNY. PENNY backs away and runs up against the side of the staircase.)

BAER
No more questions, not now, not now. Don't speak. Don't look at me like that. Don't look at me like that!

PENNY
Baer you need to stop - 

BAER
I ask you to stop, and you do not. Now you tell me to stop - 

PENNY
I'm not going to hurt you! I was never going to hurt you!

BAER
Then you don't understand what pain is!

(COGOROUGH and PADSFORTH appear at the top of the stairs. PADSFORTH is of a different race than the others. His outfit is like COGOROUGH's, and over it he wears a heavy jacket, something tough, made for work. At his belt is a small device, like a computer or radio.)

COGOROUGH
What's going on? Penny!

BAER
(To PADSFORTH.)
You!

PENNY	
John, help!

BAER
How dare you come here!

(COGOROUGH and PADSFORTH hurry down the stairs.)

COGOROUGH
Get away from her!

PADSFORTH
Put the glass down, Baer!

(BAER steps away from PENNY to deal with this new threat. COGOROUGH takes PENNY aside. PADSFORTH stands in front of BAER.)

BAER
I don't want to see you here.

PADSFORTH 
Give it to me.

BAER
Do you understand me? I don't want to see your face!

PADSFORTH
Give me the glass!

BAER
I should hurt you now, show you how much I hate you.

PADSFORTH
You're not going to hurt anyone - 

BAER
Quiet! Do not presume to know what I will do!

PADSFORTH
I know - 

BAER
You know nothing of me!

PADSFORTH
I know you are a frail old fool and if you had tried to hurt Penny you would not be alive now.

BAER
Not Penny! Oh no, not Penny! But I will hurt you!

(BAER strikes out with the glass. PADSFORTH jumps out of reach.)

PADSFORTH
Why?

BAER
For your very life, which you do not deserve!

PENNY
Baer!

BAER
(Still advancing on PADSFORTH; not looking at PENNY.)
You don't understand, Penny, but it's for the best.

(BAER lunges at PADSFORTH, who ducks swiftly out of the way.)

COGOROUGH
Baer!

BAER
No!

(COGOROUGH now advances on BAER.)

COGOROUGH
Baer! Stop it!

BAER
I will not - 

(COGOROUGH comes at BAER's side, grabbing the hand with the glass. They struggle, but COGOROUGH wins easily, taking the glass and pushing BAER to the ground.)

BAER
(Panting, pointing at PADSFORTH.)
It's his fault! Him! He's to blame!

COGOROUGH
Talk sense!

BAER
Without him, this wouldn't have happened. If he wasn't here, if you hadn't brought one of them with you, this never would have happened.

COGOROUGH
Don't be stupid.

BAER
I'm not. I'm not.

(An alarm is heard. PENNY and COGOROUGH look at PADSFORTH, who takes the device from his belt and looks at it.)

PADSFORTH
I don't know. Something moving fast.

PENNY
John, we should stay - 

PADSFORTH
We can't.

COGOROUGH
He's right. We have to go back to the house.

PENNY
We can't leave him like this.

PADSFORTH
It's not up to us.

(PADSFORTH turns off the alarm on the device.)

BAER
(Still on the ground.)
Can't just leave him.  Ah, no. Ah, no. Just leave him. Alone and friendless and sightless and alone...

PENNY
John.

COGOROUGH
I know. I know. But we have to go.

BAER
Yes, go.

PADSFORTH
You be quiet.

BAER
Oh, it speaks! How I hate it for speaking.

COGOROUGH
(To PENNY.)
Come on.

(COGOROUGH and PENNY exit via the staircase. PADSFORTH follows, but stops halfway.)

PADSFORTH
Do you know what's coming, old man?

BAER
(Standing.)
Death for you, I can only hope. Stay, and perhaps they will kill you.

PADSFORTH
You don't need to keep up your old charade for my sake, Baer.

BAER
I would abandon a thousand charades for the chance to see you suffer.

PADSFORTH
Stay safe, then, or you may lose your chance.

BAER
How clever you must feel you are. Ah, but it is nothing of the sort. It is merely more of you, more of the six who visit me.

PADSFORTH
There are only three of us, Baer. John, Penny, and myself. Only three.

BAER
As you say. Now, leave this place.

PADSFORTH
As you say.

(PADSFORTH exits via the staircase.)

BAER
Two come to fight with me. Three come to visit. Penny comes to visit. I don't mind it when she comes.

(He looks around at the garbage and at the rocks.)

He took the glass. Good. I didn't need it. It did shine, though. Why did it do that, I wonder? Ah, some things are not known. It is a very odd object, though. Very odd.

(BAER scratches his cast, considers things for a moment, then resumes his searching.
	A few moments pass.
	FIRST and SECOND enter into the interim section, the expanse of rough terrain, and travel through it. They are ghostly figures in cloaks or other ascetic clothing. Their appearances are similar, but not identical. Their eyes are dark. They are referred to singularly as "he" for the sake of simplicity; they have no gender.)

(Lines arranged in parallel are delivered simultaneously. Lines begun by one and finished by the other may overlap slightly, whenever intelligibility is served by it.)

 FIRST      SECOND
The night is dark.       |                

                  |       Yes. I believe it is
                |       the lack of light.

How can you be sure?       |                  

                 |       My eyes. And yours?

They have gone cloudy again.       |                          
I fear I need new ones.       |                     
What do you see?       |              

       |       The dark.

To see darkness       |             
is to see nothing.       |                

                     |       Only absolute darkness.

It is not       |       
           |       absolute? Not
                 |       as I understand it.
               |       Do you understand
differently? No, not I.       |                     
Is there something       |                
            |       up ahead? Yes,
                 |       I think -  there is.

Why would there be anyone...       |                          
                     |       anyone past the city...
all the way out here...       |                     
                            |       where the others of his kin...
where the rocks are all dry...       |                            
                           |       gather to sing their songs...
And through them blows       |                    
the wind so long...       |                 
                       |       and blow the wind through
                      |       their instruments...    
whose sound echoes...       |                   
       |       echoes...
testifying the absence...       |                       
             |       the presence...
...of friends?      of friends?   

(Pause.)

Do you think -        |            
                         |       Not when it can be avoided.

(Both chuckle. FIRST chuckles longer.)
  
Is it one of them?       |                

              |       Of them? Of who?

Of they, of ¡°he"s,       |                
of ¡°her¡±s, of peoples.       |                    

                        |       Not peoples, only persons.

Well, yes. Do you know -        |                      
                |       No, of course not.

(FIRST stops and jumps back, staring at the ground, as though he felt something on his foot. SECOND looks over, then stamps firmly on the spot. They both look for a moment more, then continue on.)

 FIRST      SECOND
I do not like the       |               
                           |       small ones, no, there are few
                             |       who do. When they are too small
                            |       they cannot be said to possess
the spark, the gift,       |                  
sentience,      Sentience.
which is the barrier       |                  
between murder and -        |                  
  |       And?
Well. A simple solution       |                     
to a simple problem.       |                  

       |       Succinct.
Succin -  yes, I was       |                 
going to say that.       |                
It is a person up ahead, then?       |                            

                   |       So far as I can tell.

You've been wrong before.       |                       

                     |       But not often. There is
                        |       no reason to be wrong now.
      |       (Pause.)
                          |       I think it is a lost person.
                    |       Why would there be any
           |       persons here?

Perhaps he is exploring.       |                      

                       |       What is there to explore?

Nothing, to my eyes. But theirs       |                             
are different. Perhaps they see                                     
                      |      Information? A curiosity?
                   |      Something of interest?

Everything is of       |              
interest to them.       |               

                |       Almost everything.

Well, yes. They find       |                  
the living and the dead       |                     
equally informative.       |                  

           |       This is true.
                    |       Why do they constantly
constantly gather?       |                
Why do they never stand still?       |                            

                            |       They tire of movement quickly,
                             |       but they tire of standing still
                |       even more quickly.

Shall we happen upon him?       |                       
                     |       Shall we talk with him?
Speak his language?       |                 

                   |       We could stop just...
just outside the building       |                       
            |       where he is...
waiting.       |      
                    |       ...collecting garbage.

(They stop for a bit.)

 FIRST      SECOND
                         |       I must admit, I am curious.

Curious?       |      

  |       Yes.

You do not think       |              
he is exploring?       |              
That he is... an explorer?       |                        

                     |       You cannot see so well,
              |       but he lacks the
                        |       appearance of an explorer.

And what is the appearance       |                        
of an explorer?       |             

                |       An explorer is one
               |       who plans to move
                        |       from one place to another.

Like us?       |      

                          |       Similar to us. But I see now
                       |       that this one is planning
                    |       to stay in this place.
   For      For...
how long?       |       

                           |       Difficult to say. But as much
                         |       as I have said, I can tell.

How can you tell?       |               
What marks him as       |               
one who plans to       |              
                   |       stay? He is injured - 
Wounded?       |      
                       |       Wounded, he has sustained
               |       some hurt, but he
                        |       does not try to repair it.

An explorer does not worry       |                         
overmuch about pain.       |                   

                           |       No, but an explorer will worry
                   |       if his arm is injured,
                        |       and he will endeavor within
                   |       or without his travels
                 |       to have it repaired.

And he       |     
      |       does not.

When shall we come upon him?       |                           

                |       Very soon, I think.

Very well.       |         
And what shall we say to him?       |                            

                    |       Shall we say something?

Of course.       |         

 |       Hmm.

Well -        |     
                          |       We will ask him, will we not?

How he has come to be here,       |                          

                        |       And what he has come to do.

Can we remember the       |                  
last person we saw?       |                  

                         |       We have never seen a person.

Not true!       |        

(SECOND staggers as though struck. FIRST remains still, staring at SECOND.)

 FIRST      SECOND
What do you       |         
need?      say? 
Are you well?      Are you well?
                         |       Yes. I thought we had never
seen a person?       |            
How soon you forget!       |                  

                 |       Not soon! Not soon!
                   |       Of what do you speak?

Remember. The red planet?       |                       

  |       Yes.

The air was       |         
  |       dry.

The ground was       |            
   |       dead.

(PENNY enters the base during the next lines. She turns on the main light, then busies herself for a few moments with a trivial task, then sits on her bed, one of the unmade ones, rather glumly.)

The star was       |          
           |       bright in the
sky,      sky.
Yes. Do you remember the -        |                        

          |       (No answer.)

 - ship?       |     

       |       The ship?

(COGOROUGH enters the base during the next line. He withdraws the piece of glass from a pocket or such, and places it on the table. He briefly consults the computer, then sees PENNY looking glum. He goes to her and squeezes her shoulder briefly. He then begins pacing the base, slowly.)

The bird? The steel bird?       |                       

    |       (Gasp.)
                 |       That soulless thing!

As it were. I see you       |                    
                        |       remember. How did I forget?

You chose not to see.       |                    
You hated the bird, yes?       |                       

              |       Yes! It was dead!
                       |       It was dead, yet it moved!

Yes, it moved.       |             
It was given life.       |                 

                  |       Life cannot be given!
                      |       It can only be inherited.

Its life was false.       |                  

                |       That is what I say.

We have given       |            
false life to things.       |                    

                      |       To things, yes! To simple
                       |       things! Simple mechanisms,
                           |       and small contraptions, and...
Pliable appendages.       |                  
But nothing that       |               
                       |       flies. Nothing that flies.
               |       Nothing that flies
                    |       without wings. Nothing.

But we could see       |               
that they had.       |             

                          |       Yes. I see in your mind, now.
                      |       You were not as bothered.

I am not as bothered.       |                    
It is my disposition.       |                    

     |       Or mine.

Either. But you       |              
remember them? The       |                 
                     |       persons, yes, I remember
            |       a small amount.

We saw them only a       |                 
small amount. They were       |                      
          |       afraid of us,
                        |       they fled from us, and they
fired at us. That is when       |                        
my eyes were damaged.       |                    

   |       Is it?

I don't know. How can my tell?       |                             
Can I reason my own wounds?       |                          
Can my eyes see themselves?       |                          

                   |       My eyes can see yours.

But can they understand them?       |                            

(PADSFORTH enters the base. COGOROUGH stops pacing; he and PENNY watch PADSFORTH while he takes off his jacket and hangs it up.)

                  |       No. That is one thing
                   |       we cannot do. Not now.

Not quite, no.       |             
Shall we continue?       |                 

 |       Yes.

(FIRST and SECOND continue in their traveling.)

PENNY
Do you know what it is?

PADSFORTH
Thunderstorm, I think.

COGOROUGH
It'd be about the first.

PADSFORTH
Yeah, but that's what it looks like. We'll have to stay in the camp for now.

PENNY
It's coming that quickly?

PADSFORTH
No, it'll be a few hours, but we'll have to stay in, to be safe.

PENNY
Will Baer be alright?

PADSFORTH
Has he ever been "alright"?

COGOROUGH
I suppose at one point he must have been.

PADSFORTH
A while ago, maybe. It doesn't make any difference now. We'll check on him after the storm's passed - after we're sure it's passed, you understand. The base should be able to stand a thunderstorm alright, but the air's going to be bad for a while and we can't risk any injuries.

PENNY
I know, I know.

COGOROUGH
And the greenhouse?

PADSFORTH
It'll be fine. But yeah, I'll check on it. I was just going there.

(The dialogue between FIRST and SECOND resumes. Meanwhile, PADSFORTH, not taking his jacket, exits the base. PENNY and COGOROUGH look at each other; he squeezes her shoulder again, and resumes his pacing. She lies down on her bed.)

 FIRST      SECOND
How much of the red planet       |                        
persons do you remember?       |                      

                          |       Only what we have spoken of.
                     |       Their eyes were bright,
                |       but they saw well.

Well enough. Who was it       |                     
that we saw on the gray planet?       |                             

                         |       The gray planet? Oh, it was
                   |       the small ones who...
                         |       grouped together, attaching
                         |       and becoming larger things.

Ah, yes. They saw nothing       |                       
at all. Yet they had a strong       |                           
      |       insight.

There were things       |               
they -  noticed,       |             
 seemed to see,      Seemed to see.
 yet had only deduced       |                   
from what they felt.       |                  

                  |       They felt very much.
                      |       It is a shame they could
                     |       not see; they were very
                        |       beautiful. Do you remember
their patterns? Of course!       |                        
Such things I have never seen       |                           
before or since.       |              
I imagine few have.       |                 

                  |       And they said it was
                           |       merely their nature to do so!
                |       If only they would
             |       put their hands
                           |       to the abstraction of virtue,
                     |       it is hardly imaginable
                         |       what they could accomplish.

To art? But they are blind;       |                         
what reason could they       |                    
have for art?       |           

                      |       For the benefit of those
                |       who were not them.

They had no cognizance       |                    
of such a concept.       |                

Unfortunately.      Unfortunately.

And now, I think,       |               
we shall meet this person.       |                        

(FIRST and SECOND transition from the interim area to the old building. They do not, at first, stand next to each other.
	Upstage, COGOROUGH sits on the bed next to PENNY's. He is deep in thought.)

BAER
(Not noticing them.)
Two more come to visit me... They may make the difference, cause me to find what I'm looking for.

 FIRST      SECOND
You are right!       |            
This is no explorer.       |                  

                         |       No... But I am not so sure.
                 |       I may be wrong yet!
          |       Do you see - 
the inconsistencies -        |                   
         |       Yes, those.

Is this a person?      Is this a person?

(BAER looks around for the sound, but does not see the two.)

BAER
Who's there? Have you come to visit me? Do you know what I'm looking for?

 FIRST      SECOND
He does not see us.       |                 

                             |       His eyes are bright, as I said.

Yes, I see now. But what of the       |                             
                      |       others? It is not wholly
                     |       consistent. This one is
           |       old, however.

You are right.       |            

BAER
(To self.)
Three come to visit me. Penny comes to visit me. I don't know about the other two... I don't see them very often. They don't help me find what I'm looking for, though. They have keen eyes, but they look in the wrong directions. I thought I heard them coming, now, but I must have been mistaken. I should not let myself get distracted from my searches. How ironic it would be to miss the thing now! I am so close, of course.

 FIRST      SECOND
                     |       What is he looking for?

I cannot tell. All       |                
that is here is worthless.       |                        

                    |       But, worthless to him?

I would think so. It is only       |                          
rocks and parts from his ship.       |                            
         |       (Shudders.)
If he were searching for rocks       |                            
he would have been satisfied       |                          
long ago. Unless he's gone mad.       |                             
What's wrong?       |           

                      |       He came in a steel bird?

You must learn to stand       |                     
the thought of some things.       |                         

                   |       Some things, yes, and
                     |       we'll leave it at that.
                    |       Did he come in a bird?

I assume so. Perhaps it was       |                         
not his bird; these pieces       |                        
have been here for a long       |                       
time, but somehow they       |                    
seem foreign to him.       |                  

                        |       I defer to your reasoning.
                        |       But how would he come here
              |       without a steed?

Perhaps he was carried       |                    
by a real bird.       |             

                        |       Real birds cannot navigate
           |       the darkness.

I assume there are those       |                      
that can. Unless there is       |                       
a city of men on this place.       |                          

                          |       No, no. This place would not
                             |       support a city. Even such as we
                        |       must make our visit brief.
                   |       It will be gone soon.

Soon? You have not       |                
mentioned this.       |             

                       |       I thought it unimportant.
                       |       Don't worry; we can leave
            |       as we arrived.

Quite true.       |         

BAER
Three come to visit. Two come to fight. I do not know about the last. I can't remember. When does the last come? Perhaps I have written it down somewhere?

(He takes up the tattered book and looks through it.)

Always the same.

(He drops the book and walks away from it. FIRST picks it up.)

 FIRST      SECOND
A book.      A book.

BAER
(Turning and staring at the book.)
What? What? What's wrong with it? Why does it hang in the air?

(FIRST and SECOND look at each other. FIRST drops the book.)

BAER
Better. That's better. That's the... proper place for a book. The proper place.

 FIRST      SECOND
             |       Can we make him
see us? Probably.       |               
But do we want to?       |                

Perhaps.      Yes.    

What will he do if he       |                   
               |       does? It seems he
                    |       will not be surprised.
                   |       Evidently he has been
Expecting us? Then why       |                    
is he shocked by the       |                  
                |       book? Who can say?
                             |       But he knows that we are here - 
                          |       that we are coming, that is.

He does not act normally.       |                       

                        |       Who can say what is normal
                             |       for his kind? Certainly not we.

Well, he does not act as the       |                          
ones of the red planet did.       |                         

                  |       You mean he neglects
                  |       to attack us? Yes, I
                       |       had noticed that as well.

Don't be sarcastic.       |                 

 |       Me?

Never!      Never!

(BAER looks around again.)

BAER
Who's there?

 FIRST      SECOND
       |       Shall we?

Is it proper?       |           

          |       Is anything?

Who can say?       |          

(FIRST and SECOND move so that they are standing just next to each other.)

 FIRST      SECOND
Old man!      Old man!

(BAER looks around and sees them.)

BAER
Yes? Yes? Who are you?

 FIRST      SECOND
We are two.      We are two.

BAER
Two? I was waiting for two. They come to visit me.

 FIRST      SECOND
He does seem to have       |                  
prognosticated our arrival.       |                         

  |       Yes.

BAER
Will you help me search for the last piece?

 FIRST      SECOND
The       | 
last piece?      last piece?

BAER
Yes. It is just around here, just near where I have been searching. I would not have overlooked it; I can tell it by its markings. But I know that it is just here, very close, very close. I can feel it. It is very close, and it is the last thing that I need.

 FIRST      SECOND
You search through      You search through
this garbage?      this garbage?

BAER
You may call it what you wish. But I search because I know I will find what I am searching for.

 FIRST      SECOND
He will not.       |          

        |       Pessimism.

What does it look like?      What does it look like?

BAER
I cannot say. But I will know it by its markings.

 FIRST      SECOND
                |       By its markings...

(SECOND moves away from FIRST and begins looking around at the pieces of garbage.)

BAER
Where are you?

 FIRST      SECOND
Still here.       |         

BAER
Where - 

 FIRST      SECOND
Still here.      Still here.

BAER
My eyes are old, but not so old yet. Don't hide.

 FIRST      SECOND
        |       We don't - 
Hide? I think we do.       |                  

                           |       But how? We've done nothing - 
And nothing is too little,       |                        
for his senses. Come.       |                   

(SECOND resumes his place next to FIRST.)

BAER
Yes... So, will you help me search?

 FIRST      SECOND
                |       How do you see us?

(BAER takes the pocket-watch from his pocket and twists it around in the air, trying to find a place where the light is good enough to read its face.)

BAER
I wonder if it's time for Penny to come back. I think she might help me.

 FIRST      SECOND
How do you see us?      How do you see us?

BAER
As two gentlemen who meet at a crossroads, yes? That is what any meeting-place is, a crossroads between one path and another.

 FIRST      SECOND
                  |       Yours is not a path.
                  |       Only a static point.

BAER
We are just men, as is anyone. I do not know what your purpose is, but mine is to find this last piece. This one last piece.

 FIRST      SECOND
                        |       You are not men as we are.

BAER
Perhaps we can be friends, yes? There are three who visit me. Penny, you, and there must be another. Will you wait with me? I'm sure he will be here presently.

 FIRST      SECOND
Old man -       Old man - 

BAER
(Makes a dismissive gesture.)
Oh, I am not as old as all that. Come, then; will you wait with me? He must be here soon.

 FIRST      SECOND
 I will wait a bit.      We will wait a bit.

(FIRST and SECOND exchange looks.)

BAER
Thank you. You are very kind.

(He returns to his searching.)

 FIRST      SECOND
              |       His eyes are not
                   |       as good as I thought.

Are you sure?       |           
I think it is his mind.       |                     

       |       His mind?
                    |       You think it is not as
keen? No, I think he discerns,       |                            
but does not discriminate.       |                        

         |       A different
method of classification.      method of classification.

BAER
What's that?

 FIRST      SECOND
Nothing.      Nothing.

What is it, do you think,       |                       
that separates us       |               
from such as them?       |                

  |       Now?

Always.       |     

                     |       They may be egocentric.

A sensory manifestation?       |                      

                   |       It is not unheard of.

Apparently not.       |             

(BAER picks up a random piece of garbage and examines it intently.)

 FIRST      SECOND
He knew that we were coming.       |                          

          |       So it seems.

But he knew that we -        |                   
                       |       That we were coming, yes,
                         |       and yet he knows us as one?
                 |       His knowledge is...
...clearly distinct       |                 
from his sight.       |             

                      |       Perhaps he does not see?
                          |       Perhaps it is merely insight
                     |       and outside perception,
                      |       fragile nested processes
                         |       and redundant extraneouses?

Indeed?       |     

             |       ...No. No, I am
              |       merely speaking.

Ah. Now -  for what, do you       |                        
suppose, does he search?       |                      

                     |       It is difficult to say.

What you are looking for -       What you are looking for - 
have you seen it before?      have you seen it before?

BAER
Oh, you do ask strange questions. Tell me, does it matter if I've seen it before? Does one need to have seen the last piece of a puzzle to be able to recognize it?

 FIRST      SECOND
                 |       Pieces of a puzzle?

What are the markings?      What are the markings?

BAER
It would be useless for me to try to describe them. But I'll know them when I see them. I'll recognize them.

 FIRST      SECOND
As you say.      As you say.

                      |       Perhaps he has gone mad,
        |       after all.

Perhaps.       |      

                     |       Shall we wait with him?

For how long?       |           

                            |       What meaning is there in time?

None; only in events,       |                   
and I think we shall       |                  
share his for a little while.       |                           

                      |       Only for a little while.

You do not want to stay?       |                      

(Upstage, COGOROUGH lies down next to PENNY - to rest, not to sleep or be tender with her.)

                 |       I did not say that.

Not all things need to be said.       |                             

       |       I feel...
                 |       uncomfortable here.

Oh! How so?       |         

                            |       This... man does not mesh with
                            |       the land properly. Nor does he
                            |       reflect the nature of his kind
                       |       as we know it; nor is his
                         |       purpose concretely defined,
                          |       even to himself. I think you
                 |       were right: I think
              |       he has gone mad.

Does madness in persons bother       |                            
you, then? It seems to me that       |                            
madness in one of them is in       |                          
the same vein as sanity in us.       |                            

                      |       Only superficially. Only
                          |       superficially. The life of a
                         |       root may be the death of an
                       |       insect, but life is still
                       |       coherent for each to whom
                      |       it has been passed down.

Semantics. High semantics,       |                        
but the same nonetheless. If       |                          
we say the life of a root and       |                           
the life of an insect are the       |                           
same, it is our folly. They       |                         
are the same only in that we       |                          
name them the same. And what       |                          
power did a name ever have?       |                         

                        |       We can hardly answer that;
                       |       we have never been named.
                           |       Regardless, things are not so
                           |       separate as you say. The life
                             |       of a root differs from the life
                      |       of an insect in all ways
                     |       imaginable, but life is
                       |       preserved in objectivity.
                       |       It is its own essence and
                        |       quintessence. Its referent
                            |       is itself. This much you know.

Yes. But not only that much.       |                          

                    |       You speak dangerously.

To you?       |     
And of what consequence?       |                      
Speech is only the expression,       |                            
words only the product;       |                     
the symptom.       |          

                           |       It is the symptom that kills.

Only when the disease       |                   
is unchecked.       |           

(SECOND is taken aback; he steps away from FIRST slightly.)

 FIRST      SECOND
                      |       What do you say? Not all
                      |       diseases can be checked.

Yes? You speak of mortality?       |                          

                   |       Be serious. I talk in
                        |       abstracts, and you talk in
                           |       divines. This is not helpful.

No?       | 

BAER
Who's that?

(He looks over at SECOND as they are arguing.)

I wondered when your companion would arrive.

 FIRST      SECOND
What?      What?

BAER
Your friend. Though I admit I cannot tell you apart; surely you are twins?

FIRST
(Stepping nearer to BAER.)
My friend?

BAER
Yes. Or was it you, who arrived just now? You are too similar.

SECOND
His eyes - 

FIRST
Are bright? His eyes are bright? They see far more than brightened eyes. They see far more than eyes ought to see. They see as we see -  as you see, and as I saw.

BAER
Now, what are you talking about?

FIRST
How do you see us, old man?

BAER
Don't I keep telling you? You look the same to me.

SECOND
Both of us.

BAER
Well, I don't see anyone else here. Now, then; will you help me find what I'm looking for?

FIRST
What are you looking for?

BAER
The last piece! The last part, the very last moment.

FIRST
(Again stepping nearer to BAER.)
Of what?

SECOND
He is mad.

BAER
Of the puzzle, of course! Of that riddlesome problem that has plagued me this past day - 

FIRST
Day?

SECOND
He is mad. He is mad! There is no day here.

BAER
(To SECOND, sharply.)
Always the same, with you, isn't it? Do you refuse to believe in the light only because it does not now strike your eyes?

SECOND
I believe in the light. But it has not touched this place in a long time.

BAER
Hah! Even I don't see it as a long time.

SECOND
(Sharply.)
What?

BAER
It is only night. It is only the night between two days. What's wrong with you?

FIRST
This is not madness.

SECOND
Not of the mind, but of the heart! Of the spirit!

FIRST
Of what?

SECOND
Of what! Of what, indeed! What are you? (Points at BAER.) What are you? How long have you been here? How long have you been in this place?

BAER
Why, I'm only here until I find the last piece, until the sixth comes to visit me -  six do come to visit me, though I cannot remember why the sixth comes. But I'm sure I will.

FIRST
I say, this is not madness.

SECOND
It is an abomination! It is not possible.

FIRST
For them, or for us?

SECOND
For any! We must leave this place. We must leave. We cannot stay.

BAER
Oh, but stay a little while - I have almost found what I am looking for.

SECOND
What you are looking -  what -  no, you will not find it. You will not find it here.

BAER
Oh?

SECOND
You will not find it here. If you find it here it is death for us, and I cannot -  I do not want to die yet.

FIRST
(Quietly.)
Perhaps it is not. Perhaps he will find it.
(Addressing BAER.)
What is your name?

BAER
My name is old. But I am called Baer.

FIRST
Baer. May I help you find what you are looking for?

BAER
Why, yes! I think with your help, I may find it. I've almost found it already, and with just a touch more searching and it will be found.

(FIRST begins to search with BAER.)

SECOND
(Distraught.)
Friend! What is this? What is this that you see that you should not? What is this that has entered your mind?

FIRST
Will you search with us?

SECOND
You never learned to avert your eyes. You never learned to look away -  or you did, and you chose not to. Your eyes were damaged once, and I have always felt your pain, but what was done then cannot be repaired. You must learn to look away!

BAER
All things can be repaired.

SECOND
(Addressing BAER.)
How old are you? How long have you been here that you no longer understand yourself? How long have you been searching here, looking through the same piles of stone and filth? How long have you sat and stooped and crouched and cringed beneath the collected pieces of the dead bird that brought you here? How long have you kept that cast on your arm? Has it not healed, or is there something other than a wound beneath it? Will it betray your nature if it is removed? Will it reveal a skeleton of bone or of iron?

BAER
I am not old. But you are welcome here.

SECOND
No. To you I may be, but to myself I am not. I cannot. I cannot bear to see it. I cannot bear to be so near... decay, artifice -  whatever facet of death it is that you hold so close to you for comfort and sustenance. I can let the light reflected from it strike me only so long, and then I will be undone.

(To FIRST.)
You as well, friend. You do not see. You look too closely, and you do not see. You cannot see, anymore. You must trust me. You must trust me. For the life we share, you must trust me.

FIRST
I have always trusted you. And I will again.

SECOND
When?

FIRST
When you speak sense.

(SECOND is still for some time.)

SECOND
(Quietly.)
Will you not come with me?

FIRST
As soon as I have found the piece. I have almost found it.

SECOND
Will you not come?

FIRST
I will not.

(SECOND is still for another moment. Then he lunges at BAER and tries to tear the cast off of his arm. BAER, using his free arm, hits SECOND in the face with the back of his hand, and SECOND falls to the ground.)

BAER
Three come to fight. If three come to visit, and three come to fight, then what of the sixth? No, no; I must have miscounted. You are always welcome here.

(SECOND, shaking in fear and pain, gets to his feet and runs away, exiting the stage.)

FIRST      BAER
                         |       Hmm... Now... where is that
last piece?      last piece?
* ACT TWO


(An hour or so later. It is still night, though fewer stars are visible. PENNY, COGOROUGH and PADSFORTH are in the base, in the middle of a discussion. The discussion is of a type they've had many times before, and they are weary of it. The piece of glass is still on the table.
	BAER and FIRST are still searching through the garbage.)

PADSFORTH
How much longer do you want to take? At this point, if we tell them there's nothing more we can do, they'll probably let us leave. They'll probably let us leave even if we just say we're sick of it.

COGOROUGH
You've got more clout with them than either of us. They'll probably listen even if just you say it. If you think we're done, tell them.

PADSFORTH
It's not going to be just me. HQ would take it, but -  we agreed, when we got here, we'd run this fairly. We each get a vote. I wouldn't go over your heads, unless... well, I don't know. But I'll be clear about what I think: he's not sane. I realize this is your field, Penny, but I don't think it's anything more subtle than his mind simply being broken.

COGOROUGH
His mind and his arm.

PADSFORTH
Right, right, and neither shows any signs of mending. How long've we been here? That arm should've been healed three times by now, but he still whines if we even try to take a look at it.

PENNY
I've never been keen on our chances of really helping him, certainly not curing him. I only do what I can, and I hope it helps. But he doesn't act normally. Not normally for sane or insane. We're still very far from actually understanding him...

PADSFORTH
My concern is that that's not how HQ will look at it. My feeling is that they're just trying to think of a name long enough to describe whatever's wrong with him - I mean, what a thing like him MEANS - and then they'll be done. They'll pull us out, put us on Etcher or the Laznerung, and it'll be business as usual for the old man on the rock.

COGOROUGH
I don't think it's our place to speculate.

PADSFORTH
Of course not. Our place is here. I only want to know how LONG our place will be here.

PENNY
It may be until he leaves.

PADSFORTH
He's not going to leave. If he needed a caretaker, we wouldn't be the ones sent. I wouldn't be. He is a specimen, remember? His death would give HQ just as much to talk about as his life currently does.

PENNY
That's fine for you, that's fine, but I'm not a cosmologist. Baer's not a specimen to me, he's a person. That's why I'm here.

PADSFORTH
I don't mean to say that I only want to... that my interests only extend as far as the directives. I'd like to treat Baer as a person. I want to be able to actually talk with him. I'd like to feel I was doing something of value, here. But there's something about being near him... that gets to me. It's not his insults -  as though I cared about... But there's something deeper. He puts me on edge. As soon as he's in my sight I can feel my heart racing and my palms sweating. I could never be around him very long. You know what I mean, don't you, John?

COGOROUGH
Yes. I don't think I can explain it any better. But it doesn't seem to affect Penny.

PENNY
He just seems like an old man to me. I mean, he's different, he's not normal, but I don't feel any of the effects you two talk about. But, (sigh)... I think it's because he likes me. Or at least, he doesn't like you two.

PADSFORTH
He likes John well enough.

COGOROUGH
Not really. He doesn't have the same prejudice against me, but he certainly doesn't like me. Did I tell you what he did to me, before Penny talked to him?

PADSFORTH
Yeah.

PENNY
You didn't tell me. Was it like the other times? Did he make you see things?

COGOROUGH
Not see things, remember things. He made his memories belong to me, when he wanted to. It was... not pleasant. It was painful. I think he does it because he doesn't have the strength to remember them himself. They hurt me, but they're not really mine; they must be absolute torture to him.

PENNY
Was it about the girl again?

COGOROUGH
Yes. I think it was the same girl. It's hard to tell. But the part with his arm changed. I think his memory is going. He really is old.

PADSFORTH
We always knew that.

COGOROUGH
That he had lived a long time, yes, but we didn't know at first that he was old. 

PENNY
Even so, it's hard to say what it means to him.

PADSFORTH
It's hard to say what anything means to him.

(He pauses, pensive, his eyes on the table.)

He doesn't eat. He almost never sleeps. All he does is look through that garbage for days on end, and babble to anyone who will listen about his lost piece. And insult me, whenever he sees me.

PENNY
But we must have some connection to him. If only because of what he looks like.

PADSFORTH
Our eyes are not as trustworthy as we generally like to think. We can't know that what we see is what he really is.

PENNY
We can't with other people, either. But it's all the more important here, with him, because we see him as one of us. That means there's a connection. Even if it's only mental, or illusory, even if it's just chance, we need to understand it, so we can understand him.

COGOROUGH
And help him. If we can.

PENNY
Yeah.

PADSFORTH
(Consulting the radio-object from his belt.)
It's about time. Should I put the call through?

COGOROUGH
If you would.

PADSFORTH
All right.

(PADSFORTH exits.)

COGOROUGH
(After a pause.)
Are you all right?

PENNY
I guess. I don't like this, though. I feel like we're doing something wrong.

(COGOROUGH faces PENNY, and she him, while they talk. They look away occasionally as they speak, but watch each other's reactions closely and obviously. They are comfortable together - as comfortable as two people can be.)

COGOROUGH
What do you mean?

PENNY
It's -  you know how sometimes someone will say something, or do something, some little thing that just makes you think that they have to be a certain person? Or that they have to be thinking in a certain way? It's like that with Baer. He has to be human. He does all these things that don't make sense, but then he gets angry and sad and there's something about the way his moods work, the way they change... and I think, I know what that is. That's human. He has to be. (Sigh.) And then other times I don't know. There's so much of this we don't understand. How did he get here? Does he understand where he is? None of it seems possible. It's like some sort of dream.

COGOROUGH
Well, I think it is a dream, for him. He's been here for how long, we don't know, and apparently he's always done the same thing and lived the same way. And just a month ago we come here, and we must be this enormous change to the way his life works, the way he interacts with the world - 

PENNY
But he doesn't interact with the world, he just watches it and pokes at it.

COGOROUGH
I know. But let me finish. He's like this, he's always been like this, and then we come along and change it all, and you'd think that it would completely change how he lives, that it would make him sane or insane or whatever else. But it doesn't. He doesn't change.

PENNY
But he does change. Sometimes.

COGOROUGH
Yes, but only for a moment. He always comes back to who he was before we got here.

PENNY
Do you really expect him to change who he is? That's hard enough for a young person.

COGOROUGH
Yes, I know. I'm not talking about who he is. I guess that's... not what I meant. But he must have some sense of time and causality. He knows that first we weren't here, and now we are. He has these problems - the thing he's looking for, and he hates Padsforth, he'd probably kill him if he could - anyway, he has these problems, but he always goes after them with the same words or the same solutions, even though they always fail and he seems to know that they always fail. It's like senility, but it's more like he's dreaming. Like we're this dream that he's having, and he can't get out of it, and most of the time he's not even aware that he's dreaming.

PENNY
But we're the people in the dream, and it's all different for us.

(SECOND enters the interim area. He walks slowly, dazed and weak, and after a while he slumps against the wall.)

COGOROUGH
Mhmm. Penny... was he actually going to hurt you?

PENNY
When?

COGOROUGH
Earlier. With the glass. Would he have cut you, if Padsforth and I hadn't gotten there?

PENNY
Well... I don't know. He might've.

COGOROUGH
I don't really think we can let you talk to him alone, then.

PENNY
It's alright. I'll be fine.

COGOROUGH
You just said he might've hurt you. You can't expect me to be okay with that. I don't know why you're okay with it.

PENNY
I'm not. No, don't be silly, I'm not. But it's not really that simple. There's a difference between what he would've done and what would've actually happened.

COGOROUGH
(Dryly, after a pause.)
Really?

PENNY
(Smiling.)
Yes, really. Don't you trust me?

COGOROUGH
Of course I trust you. You ask silly questions.

(COGOROUGH moves to PENNY and puts an arm around her. They continue to look into each other's eyes as they talk.)

PENNY
It's why I'm here.

COGOROUGH
Yeah.

PENNY
That's the same thing he said, you know.

COGOROUGH
Who? Baer?

PENNY
Yeah. He said, "you ask silly questions," or something like that.

COGOROUGH
I think he has some issues with women.

PENNY
I never would have guessed. Maybe you should be the psychologist.

(Pause.)

Do you... do you think it's really good for us to be here? I know we talk a lot, but, I'm never sure if...

COGOROUGH
What do you mean?

PENNY
Well, do you?

COGOROUGH
Yeah, I do. I think it's good for us to be here. But I don't know for how long. I think it could change any time, and we should be ready for when it does.

(PADSFORTH re-enters. It's obvious he has something important to say. COGOROUGH drops his arm from around PENNY, but not quickly or abashedly.)

COGOROUGH
What is it?

PADSFORTH
We can't stay long.

COGOROUGH
What do you mean?

PADSFORTH
We have to leave. Within the hour.

PENNY
What?

PADSFORTH
It's not a storm. It's something bigger. They don't know. They said -  well, they don't know. But something's going to be here and it's too dangerous for us to stay.

PENNY
What about the base?

PADSFORTH
We'll have to leave it. We were going to leave most of it, anyway. But we need to take whatever we want, now. We probably can't come back. It might not be here if do.

PENNY
Why not?

PADSFORTH
(Somewhat agitated.)
I don't know. No, I don't! They said they couldn't explain it. They just know that it won't be safe for us to stay here when it happens.

COGOROUGH
That doesn't make sense.

PADSFORTH
It doesn't? Have you been in a black hole? Do you know what happens? Can you guess whether it's safe? Never mind, it doesn't matter. We have to go.

PENNY
What about Baer?

PADSFORTH
We can stop by him, but not for very long.

PENNY
We can't just leave him!

PADSFORTH
We can hardly take him with us!

PENNY
No, I mean, if we leave now and it all goes away, then everything we've done was wasted.

PADSFORTH
We always knew that was a possibility. And anyway, what have we done?

PENNY
We've talked to him - 

PADFORTH
And he says always the same things in reply.

(COGOROUGH sees something on the screen and walks over to look at it.)

COGOROUGH
What's that?

(PENNY and PADSFORTH come close enough to look at the screen, too.)

PADSFORTH
I don't know. I saw something like that earlier, after we got back.

PENNY
Like it?

PADSFORTH
Something moving independent of the wind. 

COGOROUGH
Look, it stopped at the pit. It's not Al, is it?

PADSFORTH
The signals don't make sense for a bot.

PENNY
It's not far from Baer. We could see what it is. Padsforth - 

PADSFORTH
I can set the ship down near enough to it. Short range, I can do that much. You two can go.

COGOROUGH
Do you think it's safe?

PADSFORTH
Who would know? Do you want to look at it?

PENNY
Yes. I think we should. It could be anything.

PADFORTH
It could be anything.

COGOROUGH
I don't think we have to worry about that too much. We can defend ourselves if we need to. I don't think we will.

PADSFORTH
Why?

COGOROUGH
Just a feeling.

(The lights flicker abruptly.)

PADSFORTH
Right.

(The three of them start gathering things into three small packs.)

COGOROUGH
How much time do we have?

PADSFORTH
Not much, if we're stopping for Baer. Call it ten minutes. No, call it five.

(The three of them continue packing.
	Elsewhere, SECOND rouses somewhat.)

SECOND
How long have we traveled? How long, to be torn like this? I do not want to die.

(He jumps up suddenly, speaking loudly and earnestly.)

Cousins! Where are you now? Parent, speak to me! Friends, friends, show me your faces. Show me your eyes! Where are you when I call for you? Where are you? Where are you?

(He cries out.)

I cannot! I cannot navigate the silence alone. I cannot see with my one pair of eyes. I cannot triangulate with one set of coordinates. It will be my undoing! I do not want to die.

(Meanwhile, the other three finish packing, each slinging a pack behind his or her shoulder. PADSFORTH then busies himself with the computer, with his radio, maybe with some controls on the wall or door. COGOROUGH and PENNY leave; passing the table, COGOROUGH picks up the piece of glass. He exchanges looks with PENNY. She takes his hand and they walk out together.)

SECOND (cont'd)
How long have we traveled? Too long, to perish so! Alone and dead in our ended tracks. Friend, you looked too close! Look away! Look away! Do you not hear me? Will you ignore me? I will forget all, only trust me! Only look away from the man! Do not see what he sees! The life of a root is death to an insect. Friend! Will you die for so hard a thing as he? Will you be the tool of those who will see terror killed before it is overcome, and overcome before it is obviated? Better to die for a city, a friend, even a word, better than for this old being who has already let death into his heart. Sibling! My sibling...

(PADSFORTH returns to the computer, and speaks to it.)

PADSFORTH
H. W. O. Padsforth. Protocol twenty-one, protocol two, emergency activation. Skip pre-flight set.

(The sound of rocket engines, distant, is heard. PADSFORTH takes his coat and exits the base, turning out the lights as he does so.
	Downstage, the sound catches SECOND's attention; he rises, slowly, his eyes turned upward.)

SECOND
What... what happens? I cannot see. My eyes are bright. I have seen the light, and I did not look away quickly enough. My eyes can no longer be trusted. Is the earth torn apart? Is it consumed? Is it atomized? I see only death. My eyes cannot be trusted. I am afraid. I am afraid.

(He looks in front of him, seeing something that is not there. He points at it.)

You! What have you done to this place? I thought that this world had killed you, but even now you may kill this world. And me! You would not even see me die. You would look at the place where I was and the place where I was not, and the memory would pass from you. I am nothing to you, and I hate you for it. But I would forgive all. Yet -you do not desire forgiveness, because to accept forgiveness is to admit sin.

(He looks at the other side of the pit, at another thing that is not there.)

Yes! High semantics indeed, my sibling. They may be all we have, now. We have lost so much. Only together are we ourselves, and apart we are only so many beings. Nothing more. Friend, will you not come with me?

PENNY (Unseen; a little winded.)
Down here, he's down here!

(The sound of engines dies down. SECOND loses sight of the two things that are not there, and returns to the wall of the pit to lean against it.)

SECOND
Sibling, your death is my death. I do not want to die.

(COGOROUGH and PENNY enter the pit, wearing their packs. COGOROUGH is not holding the piece of glass.)

COGOROUGH
Who are you?

SECOND
I am the second of two.

COGOROUGH
Two? Where's the other one?

SECOND
He is gone.

PENNY
Gone where?

SECOND
He's been trapped by the old man.

PENNY
Baer?

SECOND
Yes, damn him, by Baer.

PENNY
How did he trap him?

SECOND
I do not know! If I knew, then I too would be severed and lost!

COGOROUGH
What -  what are you?

SECOND
I am the second of two.

COGOROUGH
But what are you?

SECOND
What do you mean? I say what I am. I have no patience for the minds of you, not now.

PENNY
What do you do?

SECOND
Now?

PENNY
Ever.

SECOND
We travel. But now, I suffer. I suffer and I wait. But I will not have to wait long.

COGOROUGH
Do you know what's going to happen?

SECOND
Do I? Do any! No. This place will be gone soon.

COGOROUGH
How?

SECOND
By its absence, you fool! Do you see anything? Do you see anything but the cold stone you rest on, and the cold metal that bears you?

PENNY
Our ship?

SECOND
Ahhh! Do not speak of your damned bird. Not now.

(COGOROUGH steps towards SECOND.)

SECOND
Don't move away from each other. I want to see you.

COGOROUGH
And how do you see us?

(Downstage, during the searching, FIRST picks up the book, sits on the rock, and begins examining it.)

SECOND
You are two. You are not entirely different from my sibling and I. You have bound your lives together. Have you not? Have my eyes been damaged, as well?

PENNY
No. You're right.

SECOND
A small comfort in times of ill.

COGOROUGH
Something's going to happen to this place soon. Something's coming. What are you going to do?

(SECOND shudders violently.)

SECOND
I do not want to die...

COGOROUGH
Can you survive what's going to happen? Or can you escape?

SECOND
Can a predator's eyes see different? Can a prey's see the same? If I live, it is the death of my sibling, and if he stays, it is the death of me. I am under a great stone. I cannot escape.

COGOROUGH
Your sibling. He's with the old man?

SECOND
With and beneath. Yes.

PENNY
Can he be saved?

(The sound of rocket engines is heard again, closer and louder. SECOND cowers, and PENNY takes COGOROUGH's hand.)

PENNY
John...

COGOROUGH
It's okay, he's just setting down near here.

PENNY
(Indicating SECOND.)
Look at him. What's wrong with him?

COGOROUGH
I don't know.

PENNY
I this he's - 

SECOND
(Anguished.)
Friend! Even this insane reflection of you is dark in my eyes, but I cannot bear it! Friend! I cannot bear it! How could you? Bird! Fall from the sky, if you know grace and life! Fall and be done with! Fall! Damn you, my sibling, that it should come to this! I would have left, we would have seen this place no longer, but for your incaution! Sibling, how many lives will you destroy?

(The sound dies down.)

SECOND
Another one will undo me. I do not want to die. But I do not know if I want to be already dead.

(PADSFORTH enters, wearing no pack.)

PADSFORTH
There you are. What is - 
(He sees SECOND.)
Oh. Who are you?

SECOND
I am the second of two.

PADSFORTH
There's another?

SECOND
Yes.

COGOROUGH
With Baer.

PADSFORTH
What?

PENNY
His sibling. He says his sibling was trapped by Baer, and that he's going to die.

PADSFORTH
Who is your sibling?

SECOND
The first. The elder. The wiser. So we thought.
(To PADSFORTH.)
Will you kill the old man?

PENNY
What are you talking about?

SECOND
Hear me, one. Will you kill the old man? I do not ask. I should not ask. But I feel that you may. He must hate you so.

PADSFORTH
Why? Why does he hate me?

SECOND
Because you are like him, and he cannot bear to see himself.
(To COGOROUGH.)
You. Does he like you?

COGOROUGH
Baer? The old man? No, he doesn't.

SECOND
No, he would not. He is spiteful when he is not insightful.

COGOROUGH
Why would Padsforth kill him?

SECOND
Because there is hatred there. Surely the old man cannot bear the touch of this one's light for very long. (Gestures to Padsforth.)

PADSFORTH
Do you know what's about to happen, alien?

SECOND
This place will be ended. The day is returning here.

COGOROUGH
It can't be day here.

SECOND
Yes.

(Pause.)

PADSFORTH
(To COGOROUGH and PENNY.)
We should go.

COGOROUGH
Alright.

PENNY
(To SECOND.)
Second... second of two?

SECOND
Yes?

PENNY
Would you like to come with us?

SECOND
I'll not be borne by your metal bird. I don't want to get near it.

PENNY
We're going to Baer, first.

SECOND
The old man?

PENNY
Yes. Once more, before we leave here.

SECOND
Why? Do you, too, seek death?

PENNY
We want to help him, if we can.

SECOND
Help him!... You draw the map for a journey that cannot be taken. Do you not understand him?

PENNY
We want to. If we can understand him, then we can help him.

SECOND
Why? Why travel so near that fire? He will not see it if you die. It will pass from his vision. This one, especially. (Gestures again to PADSFORTH.)

PENNY
I can't really explain it right now. It probably doesn't matter. But we're going there. Your sibling, is he still alive?

SECOND
Yes.

PENNY
We can try to get him back.

SECOND
You will help me?

PENNY
We'll try.

SECOND
(Earnestly.)
Sibling! Here are some with cognizance! Here are some! We did not know. Yes, I will come with you, and though my life is surely undone, for what you offer I offer you the same. Speak and I may act. Only by trust can this thing be accomplished. But come! We have little time.

(They exit. PADSFORTH lingers for a moment after the others have left.)

PADSFORTH
That power which grants the alien hope... may it grant me temperance.

(He exits.
	Though it is as dark as ever, the stars have been fading from sight, and at this time they are completely gone.
	FIRST is still examining the book.)

BAER
Oh, where is it... I think I passed my hand over it just now - if I can only remember which one. You should put that down, my friend, and help me look; I've told you already that's not it, and I think with your help I will quickly find what I am looking for.

FIRST
Perhaps. But I think this may prove useful. There seems to be much in it. It has seen a lot.

BAER
But can it tell you any of what it's seen? No. It's the same, the same as it always is and as books always are. Oh, it's a fine distraction, but distractions are not often commendable.

FIRST
As you say. Still, if you don't mind, I will examine it a bit longer. I think that, just a bit longer, and it will tell me what it knows.

BAER
Must you? Oh, but of course, you may. I'll wait for you to grow tired of it; it won't take long. Then we can find the last piece.

FIRST
The last piece.

BAER
Yes. The very last one that I need. I have all the others; everything else is in place. When I find it, I will be done.

FIRST
Done, yes. Can you tell me again what it looks like?

BAER
Tell you? I shouldn't think I'd have to. You remember, don't you?

FIRST
I -  I think I do.

BAER
Of course you do. Come now; check your memory.

FIRST
I recall another. A sibling; very dark, he was. Quite pleasant. He spoke quietly and was a good companion for traveling.

BAER
Dark, you say?

FIRST
Yes. Dark like the sky. Dark as the respite between the stars.

BAER
And?

FIRST
And... we were able to travel great distances, together. To the blue planet, to the red planet and to the planet of shadows. To the gray planet of the small ones, and the planet on the edge of a great fire; to the ones who dwelt in the fire and the ones who dwelt in the bubbles in the lakes of cooled lava. We traveled and saw the notched statues, and one who lived between this and every other place that is. We met those who are at once great and small, and whose footsteps are an unmaking of the earth. We met one who spread as diffusion spreads heat, but did not diffuse, who only grew in number and momentum. We saw the place that does not move. We saw others of our race. Our cousins, our parent...

BAER
But you were injured.

FIRST
On the red planet. I do not know if it was the fire or the steel, but I knew by the pain I felt that I had been injured. Only for a moment, and then those nerves were dead. But my sibling looked on me in sadness, and in it I also grieved for my damaged body. But all things pass.

BAER
And all things return.

FIRST
Do they?

BAER
Of course. You should know as well as any that night is always followed by day. In all your travels, you could not forget that.

FIRST
Of course not. No. But sometimes I do. It's hard to keep things in mind. Where is my sibling?

BAER
When we find the last piece, you will have him.

FIRST
Ah! Yes. Where is it?

BAER
It's here. It's right here somewhere. It's just in front of us. Help me a little while and we shall find it.

FIRST
Yes.

(FIRST drops the book on the rock and begins searching through the garbage again. COGOROUGH appears at the top of the stairs.)

BAER
(To no one in particular.)
Six come to visit me...

COGOROUGH
Baer.

BAER
Cogorough! I didn't expect to see you here. Do you have anything for me?

COGOROUGH
Nothing.

BAER
Ah, are you sure about that? You may have brought something without knowing it.

COGOROUGH
I didn't, but I think you have something that doesn't belong to you.

BAER
What? Must you find reasons to accuse those who are alone?

FIRST
You're not alone.

COGOROUGH
Are you the first of two?

FIRST
Yes.

COGOROUGH
Your sibling is looking for you.

FIRST
My sibling does not see. I've not moved. Where is the difficulty in finding something which does not move? It is I who search for him. And I will, in a moment, find him.

COGOROUGH
Baer! The other says you've held this one. Is it true?

BAER
I do not lay hands on those who come only to visit! Three come to visit, and here is one. And you come to fight. Why must you be so stubborn? If only you would help me search then I'm sure I would find what I'm looking for.

COGOROUGH
You need to let him go.

BAER
I don't know what you're talking about.

COGOROUGH
Baer, you will be here until you die, but you don't have to keep him.

(BAER stops searching and stares at COGOROUGH.)

BAER
Speak to my face if you speak lies.

(COGOROUGH hesitates, then descends the staircase and walks until he is only a few feet from BAER. FIRST stops what he is doing to watch.)

BAER
How long have you been here?

COGOROUGH
Long enough.

BAER
How long?

COGOROUGH
(Backing away.)
You can't do it, Baer. It won't work - 

BAER
(Loudly.)
How long have you been here?

COGOROUGH
Too long!

(COGOROUGH has stopped moving backwards. He stands still, trembling, trying to keep his eyes from unfocusing.)

BAER
What did you see when you came here?

COGOROUGH
I saw -  blank rock. I saw -  a home.

BAER
What did you see?

COGOROUGH
I saw a place for her and I to lay our heads.

BAER
Yes. What happened the day you came down?

COGOROUGH
I fell. There was a fire. I burned my arm.

BAER
What did she do?

COGOROUGH
She helped me...

BAER
(Intensely, bearing down on COGOROUGH.)
And?

COGOROUGH
She rested my arm and wrapped it -  she wrapped it - 

BAER
And?

COGOROUGH
(In pain.)
Stop, stop!

BAER
I will not tolerate lies. Not now.

FIRST
I don't understand.

BAER
Don't worry. Three come to visit me, but Cogorough comes to fight. I have to hurt him to make him stop. Just a bit. Just enough to make him learn his lesson.

(PENNY appears at the top of the stairs.)

BAER
Ah, Penny!

PENNY
This needs to stop.

BAER
Oh, it will, don't worry about that, Penny. I'm going to find the last piece. I'm going to find it. Give me a minute, one minute! I'll find it. With you here, I'll find it.

(PENNY descends the stairs, looking at COGOROUGH, who is still trembling but has regained his senses. When she reaches the bottom she goes to him.)

BAER
Will you help me search, Penny? Penny?

PENNY
What did you do to him?

BAER
Nothing at all! He merely talks. It's not my fault if he talks about the wrong things.

(SECOND and PADSFORTH appear at the top of the stairs. SECOND keeps his head down, but PADSFORTH watches what is happening. BAER doesn't notice them.)

PENNY
This can't go on, Baer. Something's going to happen.

BAER
Quite a premonition!

PENNY
Something's going to happen to this place. We think it might be destroyed.

BAER
What are you talking about?

PADSFORTH
It's the end, Baer.

BAER
You!

PADSFORTH
Me! Ha!

(PADSFORTH steps off of the staircase, landing on the ground below, his feet hitting the floor loudly.)

BAER
Why are you here? Will you even now give me your dark counsel?

PADSFORTH
Oh, don't worry. I'm not staying long. None us are.

BAER
Why do you even speak if you insist on speaking slander? Leave!

(SECOND descends the stairs, head still down.
	PENNY and COGOROUGH continue to hold each other, and watch things unfold.)

PADSFORTH
In due time. There's someone you've kidnapped, and you need to let him go.

BAER
Bah! Madness! Penny, do you hear this? Do you hear the insane things he accuses me of - 

PADSFORTH
You wager to tell ME of insanity? Look around you, old man! Your mind has gone long ago!

BAER
Quiet! Shut your mouth!

PADSFORTH
No.

BAER
(Taking a step towards PADSFORTH.)
What do you see, then? What do you see around here? What do you remember?

PADSFORTH
(Rigid.)
I don't know. I don't know.

BAER
What do you see?

PADSFORTH
I see -  I see the ocean.

SECOND
(Finally finding his nerve, and addressing FIRST.)
Friend!

BAER
The water?

FIRST
What?

PADSFORTH
Yes, the water.

SECOND
Friend, are you alright?

FIRST
I am alright.

BAER
What else do you see?

SECOND
What do you see, friend?

PADSFORTH
I see my wing. I flew too low, and it shattered against the surface of the water.

FIRST
Very little. I will see more when I find it, when I find the last piece.

BAER
Why did you fly so low?

PADSFORTH
I don't know.

SECOND
There is no piece. Don't you see?

PADSFORTH
I couldn't see. I was blinded by the light.

FIRST
How can I see? The light returns, here.

SECOND
Not yet! There is still time! Break free of the old man!

FIRST
What?

BAER
By her? You saw her?

PADSFORTH
What? I don't know what you're talking about. I saw the sun. I was blinded by the light of the near star.

SECOND
The light is still young. There is time. Don't you see? Look away from the old man! Look away! You have already been hurt by his light, but there is still time. Look away!

BAER
That's her! You're remembering her!

PADSFORTH
There is no girl! I see only the sun!

FIRST
Can I not look anywhere where there is light?

BAER
Can any look at the sun?

SECOND
No! Remember the red planet! Remember the persons! Remember their bird!

PADSFORTH
There is nothing. Nothing but the sun.

BAER
Stop lying!

FIRST
The metal bird?

PADSFORTH
I don't - 

SECOND
Yes! Yes, the bird!
(To COGOROUGH, PENNY and PADSFORTH.)
You have one, don't you? The soulless one?
(To BAER.)
You, as well! How else did you get here?

PENNY
Second - 

SECOND
No! No more! Lone one, strike him down, and my sibling may yet live. But no other way! No other!

(PADSFORTH shudders, as though very cold, then relaxes. He speaks again to BAER.)

PADSFORTH
She's gone, Baer.

BAER
What do you mean.

COGOROUGH
The girl.

BAER
What - 

COGOROUGH
It's not us. It's not ours. It's in your past - 

BAER
You're speaking madness. Two come to fight! Two! But not for long.

PADSFORTH
No! Not for long! We will leave, and I think you will, as well.

BAER
(Angry, but really trying to make him understand.)
Just one more piece! That's all I need! Don't you understand? I've almost found it! Why are you so blind? One more piece, and I will be done!

PADSFORTH
Done! You are already done, old man! You are already dead!

BAER
Liar! I would remember death!

COGOROUGH
You don't remember anything! Why do you keep that cast on your arm, Baer?

BAER
It was hurt - 

COGOROUGH
How was it hurt? Did you break your arm?

BAER
Yes.

COGOROUGH
Did you burn it?

BAER
Yes, yes!

COGOROUGH
Which is it?

BAER
Neither! Both!

COGOROUGH
Do you remember what you first told me? You told me you cut your arm.

BAER
No, not cut it.

COGOROUGH
Cut it on a piece of glass.

(COGOROUGH holds out the piece of glass.)

BAER
No! The mirror of the sea is unbroken, it stretches out beneath me, it is whole - 

COGOROUGH
What sea?

BAER
The sea -  the mirror in the room - 

PADSFORTH
What room?

BAER
Stop it -  stop it - 

PENNY
Don't!

PADSFORTH
It doesn't matter! He deserves to die, anyway!

PENNY
No! Look!

(PENNY, COGOROUGH and PADSFORTH look to a point above the audience. A moment later, the alarm is heard.)

COGOROUGH
We have to go. It's too late! We have to go!

(He and PENNY begin to run up the stairs, but stop when PADSFORTH fails to follow them.)

COGOROUGH
Padsforth!

PADSFORTH
I'll be right with you.

PENNY
Come on!

PADSFORTH
I'll be there! I'll be there in a moment. Don't worry.

(COGOROUGH and PENNY hesitate for just a moment, then run up the stairs, exiting the stage.
	Slowly, the stage begins to brighten with the light of dawn.)

PADSFORTH
Do you know what's happening?

BAER
To you? I can only hope.

 FIRST      SECOND
I don't       |     
understand.      Understand,
     |       friend!

What happens?       |           

         |       This place!
                  |       This place is dying!

Why I am here?       |            
Where is the man -        |                
                    |       No, don't look at him!
                  |       Look away! Trust me!

I will trust you.       |               
But I see so little.       |                  
I fear I have killed my eyes.       |                           

                  |       I will be your eyes.
                    |       Will you come with me?

Yes, yes! Always.       |               

PADSFORTH
Do you know what's going to happen, Baer? You're going to die. And you're going to die alone. We tried to help you. But it doesn't matter. Nothing matters now. It's too late. There's no last piece, no solution to your puzzle. You will die unsatisfied.

BAER
Only to see you die as well, and in misery, and I'll have my satisfaction!

PADSFORTH
Misguided to the last!

FIRST      SECOND
What happens to this place?       |                          

                          |       I don't know. I think perhaps
                        |       the great fire consumes it.

Perhaps. What happens to us?       |                           

                       |       We leave. This part of our
                           |       journey must be ended as well.
                  |       Where will we travel?

Where! To the darkness,       |                      
I only hope. I have       |                  
lost all taste for planets.       |                          

        |       As you say!

PADSFORTH
It can't possibly be because of where I was born, can it? Why you hate me? You realize we're from different planets. I don't even know what these other two are.

BAER
Your accent makes no difference to me, idiot. Why should I care where you were born or where you grew? Only your insolence could make you so blind, Padsforth. Only the self-hatred and deceit that mark your kind. If you had made one redeeming decision in your life, if you ever spoke the truth, I would not hate you. If you ever listened to me, I would not hate you. Always breathing your air, afraid the air of my home will sicken you. Oh, but we shall see!

PADSFORTH
What?

BAER
Your friends, you fool!

(The sound of rocket engines begins again, louder and closer than before. PADSFORTH whirls around to look at something in the distance.)

PADSFORTH
The ship!

SECOND
No!

(PADSFORTH dashes up the stairs and exits the stage. The sound of the alarm dies away as he leaves. SECOND, as though physically assaulted by the sound of the engines, falls to the ground against the side of the stairs. FIRST is still near the rock, and he looks calmly into the sky behind the stairs before speaking.)

FIRST
Again with the bird. Sibling! Some things you must learn to look at.

SECOND
I cannot.

FIRST
Well enough. It will pass. I will wait. I will always wait for you.

BAER
It doesn't matter. Will you help me find what I'm looking for?

FIRST
(After a long look at BAER.)
What are you?

BAER
I am just a man.

FIRST
No, no you are not. I have seen men. I have seen peoples and persons. I have seen great ones and small ones. But I have not seen you before.

BAER
And why should you? Is any matter duplicated in this universe?

FIRST
No, but it is all matter. It all follows patterns. I don't understand you. Why should you wait in this place?

BAER
I am looking for the last piece. In another moment I shall find it.

(The light continues, slowly, to grow.)

FIRST
In this garbage?

BAER
Everything is garbage when it is not in its correct place. What I seek will not be garbage once I have found it.

FIRST
As you say. Still I don't understand. But I see that the day is returning.

BAER
The day always returns.

(The sound of engines dies away.)

FIRST
Perhaps by the light of the day you will find what you are looking for. But only by looking. Some things must be seen.

(SECOND stands, shakily.)

FIRST (cont'd)
If one cannot see, how can one understand? And even where the light is strongest or the dark deepest, and where the eyes are damaged, I may understand by what I no longer see. All things must be seen, if only for a moment, if only for the smallest instant.

(SECOND takes a slow step towards FIRST.)

SECOND
Not all things...

FIRST
Yes, sibling, all things, however small.
(To BAER.)
You! You look different in the light.

BAER
(Facing FIRST and looking at him.)
Perhaps the light looks different upon me.

FIRST
Yes, but...

(He takes a step back, apprehensive. When he speaks again, it is in a quiet voice.)

FIRST (cont'd)
What are you?

BAER
What do you see?

FIRST
Displaced greater power - 

(FIRST collapses, and his body falls from sight.)

SECOND
(Rushing forward.)
Friend! Friend! Sibling! Kin!

(BAER turns to look at SECOND. The light is almost as bright as day. SECOND hesitates, then runs, exiting.
	Alone now, BAER makes a cursory search through all the garbage around him. He picks up the book and throws it aside.)

BAER
So much trash. But the last piece remains. And I shall find it.

Six come to visit me. Six! Two come to fight, but they have left now, and three come to visit. I may not see them again. When the sun is high, I will leave. I never intended to stay here - but I will, only to find the last piece. It will not take long. Not long at all.

Some say that if you have too many pieces, you'll never be able to decide which piece to use. But I'm better than that. I know exactly what I'm looking for. I know it's around here somewhere. In another moment I'll have found it. Just a moment.

(The light is as bright as midday. BAER seems to notice it for the first time. He stops searching and looks into the distance above the audience.)

BAER (cont'd)
Ah, what's this?

(The light begins to grow very quickly, passing the limits of day and becoming blinding. BAER rubs his hands together abstractedly.)

BAER (cont'd)
Too many pieces, they say. But I'm better than that. Smarter.

(The light is very bright. The stage begins to come apart. The pieces of trash begin to disappear.)

BAER (cont'd)
Never too many. It is possible to have too few, but never too many. But not here. Here is all that I need. Here is... all...

(The book is gone now, and the rock.)

BAER (cont'd)
Here... Here! Here I have it! Here will it come upon my body! By its markings I shall know it!

(BAER raises his arms slowly to the sky. The stairs are gone now.)

BAER (cont'd)
The last piece! The final part! Here is all that I need! Here is my life and my love!

(BAER tears the cast from his arm and drops it to the ground. The skin underneath is whole, but as black as ink.)

BAER (cont'd)
My life! My life!

(The cast is gone. Everything is gone, except for BAER and the light.)

BAER (cont'd)
Here it is! Here I have found it! Here I have proved them wrong! Here have the heavens descended to the earth! Here! Naught but here! Come upon me! I can bear the light! I can bear your gaze! Look upon me! Look upon me! My life, my love!
