* The shallow sand
The shallow sand does not abide the foundations of a house, nor do the fields of dry rock. The living earth will suffer its body to be shaped and replaced by pillars of concrete and tooled wood, but only under protest. Harvey was deaf to these protests. As a young boy, he had climbed over the fence into a power station to look at a sparking transformer and was thrown to ground when it exploded, so he was deaf to most things, actually. He didn't hear the sounds the little bugs and worms made as he hammered wooden stakes into the ghround to mark the extent of his planned basement; he barely heard the hammer. He only heard his wife come down and tell him it was time for dinner if he turned his hearing aid on, which he only did after she came down and tapped him on the shoulder, so it didn't make a great deal of difference. He turned it off when he worked so it wouldn't interfere with his concentration, he turned it off when he slept so the faint buzzing wouldn't interfere with his sleep, and he turned it off in the house sometimes so that his wife would have to come right up to him to get his attention, and then he'd quick kiss her before she got away, which made her roll her eyes.

¡°Fifty-seven years old,¡± she would say, ¡°Fifty-seven years old, and still you act like we were nineteen.¡±

¡°I can't help it if you're as pretty now as you were when you were nineteen.¡±

¡°Well if that's true, then when I was nineteen I looked like an old woman, and I don't want to think about that.¡± And then she would walk off to finish cleaning the kitchen.
    
* I have not been gentle
I have not been gentle. I have not been wise. I have not been any of those things that I promised to be in that stone hut, so long ago. Patience I lost long ago, and temper, and the council of those I once held dear. I would have it now, but they would not have me, even were it possible; even if they were here. I have not been pure. I have not trusted God. I have not put aside myself. No, in only one way have I fulfilled the promises that I made, twenty-five months ago: I have not been idle.

I do not look to atonement. That is now beyond my reach. I live in the knowledge that, whatever I may do from now until the day that I die, it will not be enough. It may be that I will be hunted, and scourged, and chained, or even given pity; but none of these things will bring me peace. That I will have only when I have fallen asleep forever. But while I am a awake, I will suffer, and I will not complain.

When I was young, I acted rashly and blindly. When I took my oaths, I knew not what to do with my new responsibility (though I ought to have). In my indescritions that followed, even then, I followed my heart, drunkenly, without goal or purpose but the whims of the trice. But [it is] I am no longer so. All the clouds and veils have been pulled from before my face, and my path is laid bare, and there is no other. Though I have squandered nearly all of the gifts [?] that were given to be my charge, I have one left, the smallest morsel; yet this I will bear before me, and do with it what needs to be done [], and I will throw myself in thorns to keep it from touching the ground. []

...and when the time came to do what must be done, as it had so often before, I was not conflicted/afraid...
...but when the time came to do what must be done, as it had so often before, I hesitated. My hand would not move. I was unable to strike.
I was not afraid... I was not even ashamed.... but my hand would not move. It would not obey me...

* I knew a man
I knew a man, at the academy. He was very poor, but he was an artist. A poet. He was very good with words. He used to tell me that I was...

We spoke of many things, as we sat nightly by the banks of the Hedron. He told me he wanted to take me away...

But I, being young and foolish, did not agree...
* NaNo freewrite
There were perhaps fourteen different reasons Gerald would choose this particular campsite for the site of his bomb-making committee, but the only one which he would readily tell to anyone was that it was surrounded by large chunks of radioactive metal.
It was radium, actually, or The Original Radioactive Metal as it was called in the tabloids. It was embedded into the earth in jagged spikes that rose some thirty feet into the air, glowing faintly and bestowing cancer onto anyone brave enough to near them. The cancer, obviously, was not a problem, as that had been cured years ago. What was sometimes awkward was the mutations.
Oh, it had been alright at first, and extra arm there or an eye a foot across, but then there was a man who grew a cannon in his chest, and a woman who was part grass, and finally the birth of a transparent child, at which the mayor drew the line. He acted so vehemently against the idea of non-opaque infants that he was suspected of having had a bad experience with an airy younger brother some time in his youth. These suspicions were unsubstantiated, however, and did nothing in the way of assuaging his vicious legislature against mutants in general. The end result was that the clearing was made an official embassy of Norway (while Norway's laws were actually more strict in this case, no one from Norway ever seemed to get around to arresting them for it). This also allowed them to fly the Norwegian flag legitimately, and that was Gerald's favorite flag.
So there was the campsite, and there were the jagged bits of radium, and there was the crowd in front of the sound stage, and Gerald on top of it. Gerald was not a mutant but in the interest of inter-special relations acted as though he was. The political philosophy he professed during his speeches was referred to generally as Nondiscriminatory Noncollectivism. In theory, this established Gerald's identity as a mutant by assuring anyone listening that each citizen ought to have not only the right, but the duty to disobey, disregard and especially to be ignorant of the laws of the land and of everyone else. In practice, however, Gerald was just a bad speaker.
¡°However insignificant your plight,¡± he was saying, having just looked up plight in his dictionary (Great Auntie Gretel's Little Big Book of Big Little Words), ¡°However minuscule your turmoil, however vague your concerns, you, as a citizen of Norway, Canada or, indeed, the outer layer of the Earth's crust itself, you as a citizen have a right to avoid your duties. The smallest matter, can be to you the cause of a lifetime of stress! When you lose a button off your shirt, you ought to curl into a ball, weeping softly and considering the values of existentialism!¡± He paused to wipe his forehead with his handkerchief. His handkerchief, for its part, dissolved into a number of fluorescent butterflies with a sound like an asthmatic violin jogging up a flight of stairs. He ignored the butterflies and went on with his speech.
¡°Citizens,¡± he said, an entirely inaccurate term (in fact no country currently had any legal way of granting citizenship to a mutant, who was technically not a human, and furthermore it was not likely that any country would, in the near future. As inhabitants of Norway, the mutants were generally referred to in legal documents as the vice president's pets. Of course, not all of the members of Nondiscriminatory Noncollectivism were mutants, but for the sake of convenience they were generally all thought of as the same), ¡°I stand before you today as a man poised on the brink of the cliff of the last battle of the beginning of the end of dignified human existence! I stand, poised here, so close that the barest touch may send me toppling over the bluff, to be lost forever! I stand before you as your leader, your dictator, and your humble tyrant! Citizens, the time has come at last-¡±
At this point he was drowned out by several noisier members of the audience as they began to tear apart some of their neighbors with enormous talons just behind their knuckles. In an instant the entire crowd was in chaos, people and mutants running in every direction, body parts making the ground slippery. Gerald made a sound like ¡°Aik!¡± as a human torso was lobbed in his direction, and he ducked, slipped, and tumbled out of view.
It's not as though there was any reason to distrust the vice admiral, or indeed to doubt his word or statement. Eugene was simply prone to being distrustful, that was all, and this much was obvious to the others in the room, and they considered it placidly as the old man went on and on, and Eugene continued to, quite obviously, not pay attention. There was a certain amount of tension in the air, the sort about which various trite sayings concerning knives and cutting came into play and the whole thing was almost a mixed metaphor by itself. It does not, in fact, make sense to say that any type or sort of tension can be literally cut by a literal knife, as in the business of cutting it is consistency, size, resistence, and so forth with which one is, or ought to be, preoccupied; tension, as it is, is an entirely different (although equally important to physisists) concept in both effect and units of measurement, not to mention cutability, as it were, which, as it is, it rather lacks. Eugene was a small man in most ways: he had small hands, small feet, small features, a small body structure, small eyes, and a small brain. This last aspect of his surprisingly near-universal miniscularity is not to be immediately confused with scope either of intellect, intelligence, consciousness or ability to proactively function in the modern world without shoving a fork through your nose. There is not a terribly direct or one-to-one corrolation between brain size and intelligence, at least intelligence in the conventional sense. The small size of Eugene's brain hade a profound effect on his mental abilities, but only on those which were (or were supposed to be) concerned with the continued functioning of his body, and all the sundry tasks therein included in that description, including the beating of his heart, the contraction and expansion of his lungs, the sweating of his palms, and so on and so forth which, being not wholly supported by his unconscious mind, required a certain measure of assistance from his conscious mind, as will presently become clear to the reader.
"Beat, beat, beat..." Eugene muttered under his breath as he continued in his pointed failure of acknowledgement of the vice admiral's mind-numbing speech or, in fact, his very mind-numbing existence. "Beat, beat, beat... digest, damn you," he added, in reference to parties obvious.
The vice admiral, for his own part, was speaking of manners far more repetitive and far less interesting, and of which most seemed most concerned with or driven by the price of rice per acre, his own brilliance, paper (which he referred to exclusively as foolscap), or some odd and unexplained (at least, in a way that made the matter more, and not less, confusing) ways. He waas, at that moment, just seagueing into his thoughts on beige-colored paper.
'I would now," said the vice admiral, puffing out his stomach, mustache, ego and hilt-of-sword all at the same time and in the same motion and breath, "like to turn my thoughts and therefore words (for I am, and have generally said it is the case that I am, more adept at thinking by talking than by merely the traditional fashion, as it were and for what it's worth) to the subject of beige-colored foolscap, by means of the seague which I have just now used."
The audience, mostly upper-class men who read such fine materals as the New Yorker, Mad Magazine, and the Half-Life 2 online message boards, let this unclever cleverism pass with the same lack of acknowledgement which generally greeted all of the vice admiral's various -isms, especially the clever-isms. It was not so much that they wanted to (or did not carer of they) showed and greaat disrespect for the vice admiral (which was done elsewhere and other times merely as an old and important (though ultimately superfuous) matter of course, just as the vice admiral seemed to himself exist merely in terms of quantities of age, import, or superfluouty; they simply were exercising their long practiced art of, as they so readily (readily, that is, after the consumption or inhalation of several good strong beers) called it, 'staying the heck out of someone else's business, especially when that someone's business includes or seems by accurate judgement from a sane and more or less stable mind to be likely to in the near and immediate future include incurring the very potent wrath of the vice admiral.'
That was what they called it, at least. Others speculated, however, as they are wont to do, that the profoundly basic concept of instinct was the primary force at work in such sociallities.
Stepping into the bright snow was like stepping into life for the first time. Nikolai blinked; even in the dim light of the full moon it seemed to reflect more than what touched it. Bathed in the light, feeling it wash over him, Nikolai let the heavy door close behind him with a barely-registered _thud_.
The highest part of the sky was black, and all that lay between it and the ground foamed with infinite falling particles of snow. Nikolai moved through the cold wetness like a man dead, or rather, like a man never before alive. He entertained the thought that he had been born this hour, this minute, and that this was the first time he walked, his grand entrance into the world.
Maimed, he thought. That is how I come into this world. Stricken. Infected. Blighted. He lifted his left hand in front of his eyes; it was ungloved and the layer of snow cut it with the inarticulate pain of too intense a termperature. He flexed it. The muscles contracted, the fist clenched; the hand worked well.
I remember, quite clearly, when the first Digitized Man met himself.
I was a friend of his. Not a good friend, you understand, but I had known him for some time. If I had to describe the man briefly I would simply say that he was blunt. I could do him better by saying that he was very to the point, or perhaps a no-nonsense sort of person, but to be entirely honest I doubt that he deserves it. He wielded words the way a blind man wields a club, bludgeoning both friend and enemy in his brutal attempts to make a point.
Piano tuner

Eyes set - weary, but set - he rolls his cigar around his teeth. It¡¯s uncertain where the cigar came from, but it seems a minor concern at the time. It¡¯s a large, bulbous thing, bringing a rare, rugged beauty to the color brown. Friendlier than a cigarette, it brings to mind not unkempt truck drivers or the ash-blackened lungs you see in TV commercials, but people. You look at him now, his eyes concerned, his shoulders set, his posture confident, and you see Dick Tracy, his yellow trench coat concealing the telltale tommy gun. When he talks, his drawling voice rolling around his words dryly, instead appears to you the face of Groucho Marx, mustache and all. In fact Jon doesn¡¯t have a mustache, but if you were to describe him it would be difficult to omit the feature, his face being so accommodating to one.
He sets his brass equipment case on the ground, and the crowd clears a space between him and the piano as if he told them to. He is a man who can speak without speaking, Jon. He pulls out the Tuning Rod, a five foot-long steel rod tipped with a small handcrafted hook. He extends the Rod, checks the tip, and pulls out a large black wallet. Except it¡¯s not a wallet - he presses a button and it unfolds into a pitch-black shield, the whine of its fission motor filling the air as the kinetic dampening shield kicks in. The shield is nearly impervious to all sorts of electric, electromagnetic and sonic attacks and blasts. It can deflect a concentrated weight of roughly two hundred and eighty pounds before sustaining structural damage. It is light, it is thin, but it is protection.
Turning back to the piano, shifting his weight carefully into his legs, Jon watches the instrument carefully. It has begun playing Beethoven¡¯s Fifth on itself, the keys moving more and more rapidly. As the melody crescendos, the chords cascading into to more than a song, more than a tune, into pure emotion, Jon tightens his grip on his weapon. He had been a piano tuner for over sixteen years now, and when people asked him how he could do what he did without getting scared, he still had the same answer.
Throw up in the morning and clean it up in the afternoon.

* Chapter 1: Falling

Lance had remembered what happened when he woke up. That is to say that, minutes ago he could've described exactly what had happened to him, and now all he could tell you was that minutes ago he could've described exactly what had happened to him. It was like trying to remember a dream, and in fact, as he thought about it, that was probably exactly what he was doing. When he prodded the dead memory now, all he got was the aftertaste of a feeling that was like pain, and although it wasn't really pain it still made him uneasy.
Lance tried to forget the memory-of-a-memory, which proved more difficult than did remembering where he was, because where he was, was falling.
He had fallen for an age already, and wouldn't land for another age. He fell through air and he fell through clouds. A translucent shield encased and protected his body, and prevented his skin from feeling the cold air rushing past him, but he could still hear it, and that sound filled his body. It was the sound of a thousand angry beasts trying to tear him apart, clawing at him, biting, roaring. The wind was a great monster that wanted to but could not kill him, and the sound was its cry.
The ground was approaching fast, too fast. Lance saw it and thought the same thing he had thought every time he had ever fallen. He saw entire planet rising up eagerly to meet him, and with absolute conviction, he thought, I am going to die. He had always had strange thoughts when he fell, as far back as he could remember. He would step out of the plane, the sound of whose engine would be muffled when his shield winked on, and he would remember how safe he was. He would remember how many times he had done this before. And every single time he would stay calm, his heart rate would stay down, and something inside of him would scream. Then his thoughts would wander, and he would not be able to stop them.

* New Animal
A new animal was in the jungle one day. A huge, sea-stained beast, it had lumbered from the sea in a paroxysm of madness, casting aside bush and tree alike before dashing itself against a rock and lying still in the wet sand of the beach. It was long, sleek, shining; it was a battle-ship! No, it wasn't, there were no guns. A battle-ship is a porcupine, an angry collection of deadly tubes and spikes ready to loose all the chaos of gunpowder on the world. This this was a porpoise, or maybe a dolphin's third cousin, the one with some dinosaur blood in it. A submarine! No, no, not even that; a submarine is like the bulb of a flower that grows on the bottom of the ocean and which no one has ever seen; it has a head, and a tail, and a fist, and the fist can be deadly if it is required. The new animal in the forest had rammed to shreds bush and tree, but had hurt itself quite badly in the process, and even if it had never met the rock it would never again know buoyancy, unless there were a resurrection. It had no head, but was shapeless; or, if its shape must be named, let it be called a badly-made arrowhead. It had no arms or hands, either, no tail aside from brand-new gas-powered motor, stuck onto the back of the boat like an afterthought. It had been stuck on; in the beast's death throes, the motor had become dislodged and passed from human knowledge. It is either the home of insects now, or it is nothing.
¡°This,¡± said a woman with sand in her hair. And then, so much later that it might have been an unrelated comment, ¡°. . . is wonderful. This,¡± and here she stopped talking for truly an astounding amount of time, the amount of time that it took for her to walk all around the wrecked and upside-down motorboat, and to look inside at the mud-splattered seats, and to walk round to the other side and look specially at the enormous gash across its midsection. As she looked at it she spied a large gray beetle making its way jovially down the side of the twisted metal. She continued on to ¡°is¡± as she flicked the beetle onto the ground, and spat out the final ¡°wonderful¡± as she stomped on it. The first time, that sentence had been merely sarcastic, but this second time, it was positively toxic.
