* quotes

"Corsalle I died in his sleep, an old man. Corsalle III likewise. Corsalle II was killed by a wild boar he injured in a hunt. And Corsalle IV was killed in his bedchamber, naked, begging for his life."
"Lies! He died in the arena! He died wearing his father's armor, and not until more than a dozen arrows had found him! A friend of mine saw it."
"And will you spread the tale?... The Rangora have won the right to the truth ... The Rangora fill the mountain range..."

"Tell me, X?"
"Y."
"And Z?"
"A."
"Then why do you call me General."

Gulrath
Milrath
etc.
Grorm Bloodied

"The King's orders―"
"The King is dead, and all your piety won't bring him back."

"You were six days in your fall from Heaven."

Gen: "Is it your dream to X?"
"My dream is to see Tercrest a mighty empire, strong against her enemies."
"Then tear your clothes. Your dream is dead."

"You've had one too many."
"So has your mother."

Books from the Library of Creo.
"And what are these books here?"
"Those are books which I disagree with."
"You keep them because they are significant?"
"Some of them."
"And the rest?"
"They help me to attune my thoughts."

Yes, truth and pains are friends enough...
Yes, truth and pain consummated their union long ago, though I did protest.

What a marvelous place you have come from!
You were six days in your fall from Heaven.

* notes

Morrin Hadre. Carl. Drake. PAJFORA. Paj.

Kingdom: Rutgar
King: Corsalle IV
Enemy: Athotra, Athotran

Kismor

The Prince fled, on someone's orders, to Zon-Drissith, the City of Staff and Stone... Zon-Rithick?
Erzon-Drissith

687

AFTER THE SIEGE
BY N. R. B. Rhein

* CHARACTERS:

MORRIN HADRE Captain of the guard.
DRAKE Advisor to the King.
PAJFORA ("PAJ") A physician.
CARL A cavalry soldier.
CORSALLE IV The king, dead.
CORSALLE V The prince, fled.
DERSKIN Another advisor, fled.


* ACT ONE

(The stage is dark.)

DRAKE
Have you any more of these biscuits?

PAJFORA
No. The stores are nearly empty. It'll be potato and cabbage for the forseeable future.

DRAKE
I saw a cat in the North tower, yesterday.

PAJFORA
Catch me a cat. Can you use a bow? We'll have stew.

DRAKE
Get Carl back here.

PAJFORA
Carl can't use a bow. I'd like to see him skewer a cat with a cavalry spear. No, better, I'd like to see you bruise your knuckles on one. Do that and we'll have stew, I promise you.

(The lights slowly come on. They reveal one of the exterior rooms of a partially-destroyed castle. [Find castle terminology.] Part of the wall is missing, following attacks by siege-engines. There are candles or torches in brackets, currently unlit, due to the sunlight coming in through the hole.
DRAKE is sitting on one side of the stage. He is a fat man, in clothing which was once fine but is now very dirty. He is eating a dry, hard biscuit. Standing next to DRAKE is PAJFORA. PAJFORA is a middle-aged or older man wearing a white tunic, also very dirty. On the other side of the table, on a thin cot, lies HADRE, just beginning to wake up. HADRE is wearing only trousers; his chest is wrapped around by a great white bandage, which has been changed recently, and there are smaller bandages on his arms and neck. As he wakes up, he starts to look around, then lift his head. The pain from his injuries causes him to move slowly.)

DRAKE
How long will the vegetables keep us?

PAJFORA
A month, if they need to.

DRAKE
I don't relish that thought. What of your babe?

PAJFORA
He'll keep. I couldn't give him biscuit so he's been on thin broth this whole time. That and a little sugar.

DRAKE
Sugar?

PAJFORA
Just a little. I put it in water and he takes little sips without choking. For sweet dreams.

DRAKE
Sweet dreams? You've never had a fever.

PAJFORA
I have, when I was a boy. I got wretching fever from a girl in our market. Night sweats and choking with every bite of soup. Almost died.

DRAKE
And when you sweat at night, were you dreams sweet?

PAJFORA
They were abysmal. But my babe doesn't have the fever. He's not even sick.

DRAKE
He's not well.

PAJFORA
Nor would you be. But there's more ways of being unwell than just being sick.

DRAKE
I wager he is both unwell and sick together.

PAJFORA
No, you'll have to wait until Carl gets back. He may be fool enough to gamble with you.

(At this point, HADRE has gotten off his bed and made his way, slowly, to where the others are. They do not notice him. Leaning against the wall or doorway, HADRE speaks.)

HADRE
(Weakly.)
You've an edge in your words, physician.

(DRAKE and PAJFORA turn to him, surprised.)

PAJFORA
Hello!

(PAJFORA goes to him to see if he is alright.)

Yes, truth and pain go often together...

(PAJFORA touches HADRE. HADRE winces in pain from his various bruises and injuries.)

PAJFORA
...It is the same with healing. Why are you standing?

HADRE
I awoke over there...

PAJFORA
I laid you over there, the better part of a week ago.

HADRE
A week? A week? No, I can stand. Where are the other drawn? How goes the battle?

DRAKE
Oh, the siege has gone splendidly; but not for us.

HADRE
Is that the king's advisor?

DRAKE
Him that was.

HADRE
And is it lost? The castle is untaken. It is damaged, to be sure, but I see no Athotran marching the square―

DRAKE
The Athotrans have left.

HADRE
Left? They have taken the castle and left?

DRAKE
The castle was not their goal.

HADRE
But they laid seige to us. They attacked us for days―

PAJFORA
Two days.

HADRE
―Two days, they brought beast and engine to bear on us, they sent their soldiers into our arrows. They have taken our land. The drums of Athotra have played the war-march these past four months, and they have left?

DRAKE
The castle was not their goal.

HADRE
What, then?

DRAKE:
Do bears seek bees, or d0 bears seek honey?

HADRE
I miss your meaning.

PAJFORA
They marched East.

HADRE
To... the mines? ... The temple?

PAJFORE
They passed the temple. We've heard no other news. But you can see, from the tower ― the northern watchtower, it's still standing. There is no camp at the mines.

HADRE
They cannot mean to climb the mountains.

DRAKE
Bears can climb.

HADRE
They will lose half their men if they do. More. The mountains are not gentle [kind].

DRAKE
Their motivation is sufficient for that, I think.

HADRE
What do you know of this, Advisor?

DRAKE
Call me Drake.

HADRE
Why?

DRAKE
My father called me Drake.

HADRE
You are the King's advisor.

DRAKE
There is no king here. Who do you wish me to advise?

HADRE
Advise his subjects! Pajfora is a physician, I am Captain of the Guard―

DRAKE
Captain that was! There is no Guard! There are no subjects!

HADRE
The King has drawn you into your station. Your oath binds you to him. It binds you to his orders.

* misc.

Yes, the battle was glorious. It went on, gloriously, for two days. But you were six days in your fall from Heaven, and you have landed in a different place. I am sorry to say it.

He and the other adviser went South, to Zon-Drissith. I would have gone, as well, but... I am weary.
