Sandwich of the Sea — A Deep, Dark, Dank Comedy

* Cast
+ Sandwich — Junior Organizer
+ Mishwiks Oglvrthy — Technician (various)
+ Acefire Joe — Security
+ Edbe Rozel — Senior Biologist
+ Jobble Wrillis — Secretary to Captain Tumor
+ Captain Jerffy Byron Tumor — Captain, Sub-Captain, Captain of the Rig
+ Jimmy McCreamy — Fisherman
+ Mae Kerch — Important public offical
+ Ávalon & Éralon — Oglvrthy's Genetically-Engineered Semi-Cybernetic Lab-Rodents (gerbils)
+ Jenkxin Spamwell — Head Organizer, Sandwich's immediate boss

* Chapter One: Under the Dark and Depressing Sea

Well. . .

Sandwich worked aboard an extensive deep-sea scientific rig. He had worked and lived there for over four years, enjoying vastly one out of every fourteen minutes or so. He had been nicknamed Sandwich because the first thing he had eaten after being brought aboard the rig was a sandwich, and every year on his birthday all of his colleagues and friends gave him fresh sandwiches. Sandwich in fact was not particularly fond of sandwiches, and would have much preferred some nice pasta or perhaps a chicken casserole, but no matter how many times he told this to the others, they either forgot or thought that he was joking, and he continued to receive sandwiches.

He did have a real name, but it is not clear what it was.

So Sandwich passed the days easily enough, including this one, which began far too soon, with the sound of a heavy, padded weight hitting the floor. The sound made Sandwich jerk awake, although he really should've been used to it now; it happened once a day, at least. The heavy weight had been perched on top of the bunk above Sandwich's, the way bowling balls often perch themselves upon inverted pencils, and after it hit the ground it rolled up against the door, knocking aside stacks of books and computer-paper, before finally yawning and scratching its head and standing up in a fat sort of way.

"Oi," said Sandwich to his roommate.

"Uff!" said his roommate.

Sandwich's roommate (and bunkmate) was a very round man named Oglvrthy, which I will tell you right now is pronounced "AH-gil-ver-thee". Oglvrthy was Sandwich's superior, technically, and though they bunked together they rarely worked together. Oglvrthy had been on the rig longer than anyone else, having joined its crew shortly before it was built, which is complex situation that may be elaborated later on. Every morning Oglvrthy rolled off of the top bunk and crashed to the ground, and every time, Sandwich woke with a start. Occasionally Oglvrthy fell off during the night, as well, as though simply eager for a good bit of falling. Sandwich had once or twice suggested switching bunks, but Oglvrthy insisted that sleeping on the lower bunk made him scared. This was unfortunate for Sandwich, who, though not being scared of sleeping on the lower bunk, had to endure sleeping with Oglvrthy in the top bunk, who was so large and heavy that the bottom of the bunk sagged down almost enough to touch Sandwich's nose as he slept.

"Grmpf," said Oglvrthy from the floor. "Well! I'm up. I think I'll go work on those pressurizers sommore."

"Ugh," said Sandwich, because it was early and he had not yet had his morning sandwich. I mean, tea. He found that he needed some sort of stimulant to wake up in the mornings, but coffee felt overly plebeian. And sandwiches didn't enter into it. They were right out, as it were.

Oglvrthy waddled out of the little room, humming as he went, and Sandwich decided that he wouldn't be able to get back to sleep and might as well get up now. He hopped out of the bunk, got dressed, then changed his mind and got back into the bunk again. This did not last long, however, as Oglvrthy returned a moment later to fall on the floor again. Some part of Sandwich's brain tried desperately to form the question: "Why did you fall on the floor again?" but it took too long to decide between that and: "Was falling on the floor again the _reason_ you came back into the room?" and before he could make up his mind Oglvrthy was gone again. So, annoyed now, Sandwich got out of bed again, collected his affects, accouterments, accessories, paraphernalia, and oddments, and followed Oglvrthy out of the room. He walked over to the kitchen and was just starting his morning cup of tea when one of his colleagues, Acefire Joe, walked in.

"Morning, Sandwich," said Acefire Joe.

"Morning, Joe," said Sandwich.

"Sleep alright?"

"Eh."

"Eh?"

"Eh."

"Ah."

Sandwich sipped his tea, pleased with himself for having started his day with such an invigorating conversation. Acefire Joe got himself a packet of hot cocoa, made it, and then tried to sip it, but started too early and burnt his lip, then spent the rest of the day feeling displeased with Sandwich for putting the idea of sipping things, especially hot things, into his head in the first place. This may sound like a childish thing to do, but if so it is not very surprising, because Acefire Joe was in fact a young boy. If you are wondering what he was doing working full-time on a deep-sea rig, the answer is that he got the job on account of having a very, very deep voice. This is not to say that his job involved the use of his voice at all; actually, Acefire Joe worked security. But his deep voice cause people to pay attention and respect him when they might otherwise not, and his surly attitude made it impossible for people to think of him as really young, at least so long as they did not think very hard.

Now, normally deep-sea rigs do not have full-time security guards, because normally deep-sea rigs are not frequented by thugs, drunks or shady characters. This one was, however, which was a very confusing situation seeing as the entire rig was quite a great quantity of leagues beneath the surface of the water, but there you go. Acefire Joe was a master at his job, and he loved it. He wasn't old enough to carry a firearm, so instead he carried a crowbar. It was a very nice, red crowbar, with notches on it for all the people it had taken down, and a holster for easy carrying and quick access. Acefire Joe was not tall enough to really get a good hit with the thing above the shins, unless he managed to combine a strike with a particularly good jump.

Acefire Joe was a particularly good jumper.

As Acefire Joe left the room to begin a day of hitting things and of being generally displeased, Sandwich finished his tea, decided to have a second mug, changed his mind, started to leave, changed his mind twice more, then really did leave. He walked out of the kitchen into the common room, turned into the hallway, and then into the computer room. There was only one other person in the room when he entered.

"Hey, Sandwich," she said.

Sandwich jumped, and hurriedly composed himself. "Good morning, Edbe."

Edbe Rozel was one of the few female crewmembers of the rig on which with whom Sandwich was on somewhat friendly terms. She was a biologist by trade, one of several with permanent living quarters on the rig, and was a rather vague person; tall, thin, and a bit underweight from constantly forgetting to eat. Oh, she was nice enough, thought Sandwich as he sat down at one of the computer workstations, but it was hard to carry on a conversation with her without getting the impression that she was looking at something behind you or maybe talking to herself instead of you. Edbe did not say anything else, and Sandwich carried on with his daily tasks, checking E-mail and so forth, then turned and saw Edbe suddenly in the seat next to him and staring at him. Sandwich jumped, lost his seat, tumbled to the ground, scrambled to his feet again, and righted the chair. He saw that Edbe, who had not flinched during this whole ordeal, had not actually been looking at him, precisely, but had been looking in the exact direction in which his head had been. He sat back down, clutching the armrests of the chair for support, and waited for her to speak.

After waiting a long time she was still silent, so Sandwich opened his mouth and was about to say something when Edbe abruptly said, "You might want to check your files, they did a sweep of the system last night. . ." and then returned to her workstation.

Sandwich was still for some time, staring at her. It was not that this was abnormal behavior for her; it was rather that Sandwich had yet to become fully used to Edbe's normal behavior. When he had convinced himself that their brief confrontation was over he turned back to his computer and checked his daily service log to see what his assignment for the day was. When he saw it, he groaned and decided it was probably time for a quick break. He left the computer room about five minutes after he had entered it.

Standing in the hallway between the computer room and the ESC (Emergency Supplies Closet), Sandwich contemplated his existence. He considered that perhaps man was never made to live miles underwater, or in rooms made of steel with two-inch-thick windows looking out into shadowy lawns of deep sea weed and dusty-looking shells, and every now and then a nightmarish blind fish. It was not that Sandwich minded worked on the rig, you see, or even that he disliked working at all, but he was not much of a morning person. He was still standing in the hallway when Oglvrthy came upon him.

"Whum," said Oglvrthy conversationally. "What do you think?"

"Of what?"

"Of this day. What do you think?"

Oglvrthy's voice was low and somewhat squishy-sounding.

"Well," said Sandwich, "it seems like a fine enough specimen of the breed. Or what passes as the breed, down here. It's not like we get any daylight."

"Oh?" said Oglvrthy. He looked around at the solid steel walls as though looking out of windows. After some time he said, "Needs more flavor."

"What?"

"This day," said Oglvrthy, tapping the wall, which he apparently had mistaken for the day. "This day is in want of flavor."

"What kind of flavor?"

This seemed a very serious question to Oglvrthy, who thought about with a frowning expression for some time before he replied.

"I don't know, but you'll be the first to find out when I do. Well, so long!" And he wandered off again.

After that, Sandwich decided the hallway was a dangerous place to stand, and he decided to head over to the machine deck to see if anything interesting was going on.

The machine deck, usually just called the deck, was the single largest room in the rig. To the North was the control room and to the South was the sanitation complex, both low-ceilinged little buildings residing on the deck like enormous turtle-shells, if turtle-shells were flat and box-shaped. The entire East side was filled by the pool, in which floated various subs and other water-craft, and which had gates at its ends for the subs to get in and out of the base. A wide bridge crossing the pool from the main deck led to the sub control room and the captain's room.

The main floor of the deck itself was littered with machines and mechanical equipment, ranging from piles of subsuits to small cranes, and submarines up for repair. The high ceiling of the machine deck was bright with artificial sunlight panels, which along with the size of the room and the pool, made the room the closest thing by far that the rig had to an outdoors. This made it a favorite haunt of wanderers and slackers, in both of which groups did Sandwich count himself a member. It was also the room in which most of the rudimentary sports were played, mostly by men who played them in direct contradiction to the fact that it was not particularly _possible_ to play any real sport in the room. There was one basketball hoop, but it had been fitted some twenty feet high by a malicious handyman, and there was no basketball anyway. There was a soccerball—dozens, in fact, due to a mistaken delivery—but no soccer goal. And the closest things to court lines drawn on the deck was an old but extravagent hopscotch grid, placed on the steel deck-plating before it had been transported underwater to be put into the shape of the room, drawn there by the children of some foreman of some steel mill, who drew it using indelible acid because they could find no chalk. Eventually there evolved a sort of brutal, primordal hybrid game, combining usage of the insane basketball hoop, the plentiful soccer balls, the hopscotch grid and—as often as not—the pool itself, which was kept at an enjoyable fifty degrees or so (enjoyable, that is, to certain organisms other than humans).

As Sandwich stepped onto the scarred and dirty plating of the machine deck, he knew at once that something was up. A sub, damaged by the looks of it, was just being lifted out of the water by one of the cranes. As it was set down as gently as a crane is able to set something down it shed enormous sheets of water, little waves that fell to the ground and made littler waves that traveled about and went over the tops of peoples' shoes and in to their socks. As the sub came to a rest Sandwich could see what looked like an enormous stab wound on its starboard side; where the hull had been punctured the entire body had crumpled inwards, the metal stretching so that the paint was cracked and faded and had the look of an ancient thing.

Sandwich walked over to one of the doors of the control room and knocked, hoping to ask about the sub, but it seemed like everyone was busy. He tried to get close enough to see if they had gotten something out of it, but there were too many people around, working the crane, trying to get at the dead sub with their tools, or simply running about with computers and papers like an ant-hill with bureaucrats instead of ants. Like a _bureaucrant_-hill.

Sandwich was about to give up when he heard the voice of his good friend, Jobble, from behind him.

"Civ sub, eh? That's what you're thinking, yeah?"

Sandwich whirled around so far that he had to unwhirl about thirty degrees before he was facing Jobble.

"What? Oh, I guess. Wasn't it?"

"Doesn't look so. Yeah? Doesn't look. Someone big in there, I see. Big metaphorically, I mean. Like, important. Something like a queen."

"Are there queens, anymore?"

"What?"

"It's the 21st century. Are there any queens?"

"Well there's the Queen of the Denmark, isn't there?"

"You're saying the Queen of Denmark was in that sub."

"No, no! Christ^, listen, I said metaphorically."

"You said that the word 'big' was meant metaphorically."

"And who are you to say it isn't?"

"No one! But you didn't say you meant 'queen' metaphorically."

"And what makes you think I need to say that? Are you presuming to know what I do and do not mean?"

"No, listen. Is the person in that sub over there a queen?"

"What, previously, or regnant?"

"What?"

"Regnant. Means 'reigning.'"

"Oh. Either."

"There's no one in that sub."

"Fine, but who _was_ in it?"

"Someone like a queen."

"You mean like a literal queen, or a metaphorical queen?"

"I mean like an similetical queen. Hell^, can't even have a conversation normal-like without you questioning everything I say."

"Yeah, I guess that would be pretty hard."

This was actually a fairly successful communication with Jobble, given the standard. He had been a teaching assistant, years ago, before an accident with an elephant under unusual circumstances lead to his retirement from the position. Sandwich was not quite clear on whether this was due to his inability to continue in that capacity, or to his snubbing by academia vis-à-vis the involution concerning the elephant, and Sandwich had never brought himself to ever put forth his uncertainty as an actual question.

Jobble stepped forward and watched the millings about at the damaged sub with dramatic interest, not unlike the way he watched most things. In fact he had a permanent look of drama about him, like the look of a young action movie star: he was of average height, with a lean but muscular build, and short black hair which he kept gelled and combed forward so as to give the impression of something pertaining to dangerous and impressive velocities.

"Anyway," said Jobble, "I just came from Captain's room. Eh? He wants to see you. In there."

"What? What about?"

"Dunno. Something about this old thing, I think." Jobble indicated the damaged sub.

"OK. . . why? How would this have anything to do with me?"

"Eh," said Jobble.

So Sandwich made his way past the damaged sub, still unable to make out whether anyone or anything in particular had come out of it. As he crossed the bridge he passed yet more bureaucrants rushing to the sub, as well as old Jimmy McCreamy, the pleasant old man who sat on the bridge or on the edge of the pool all day with a fishing pole.

"There's no fish in there, Jimmy," said Sandwich.

"Go fuck^ yourself," said Jimmy.

_He's in a good mood_, thought Sandwich, pushing open the door to the sub control room. He said hi to the people working in there, who ignored him, and then he knocked on the door to the Captain's room.

"In!" barked a voice from inside the room.

"What?" said Sandwich.

"In!"

"What?"

"In!"

Sandwich hesitated, then, hating himself, said,

". . . What?"

There was a pause, then the door was flung open. Captain Tumor was a small man with a medium voice.

"I said 'in!' As in 'come in!'"

"Oh," said Sandwich. "I just heard 'in,' and it seemed more like a sentence fragment than a command."

"It was both!" said Captain Tumor.

"No, I meant, it sounded like a fragment of a sentence that was merely a statement, not an imperative."

Captain Tumor went back to his desk to get his revolver and shoot Sandwich, but he stopped before he had completed the action.

"Hell^," he said. "What do you want, then?"

"Sir," said Sandwich, "Jobble Wrillis told me you wanted to see me. Is there a reason you're loading a revolver?"

"What? Oh, no, no, just making sure the. . . bullets weren't. . . too gray. Yeah. I mean, stolen. Making sure they weren't too stolen."

"Yes, sir."

"_Who_ told you I wanted to see you?"

"Jobble Wrillis, sir. He's your secretary."

"Oh, oh, Wrillis, right, right. Right. Wrillis. Where is he, anyway?"

"I just saw him down on deck, sir."

"Eh. He's taking forever to get to his work again. I wish I could straighten him out."

"Sir, is there something wrong with your gun again?"

"What?"

"You've started loading your revolver again, sir. Just when you said you wished you could straighten Jobble out."

"Eh? Oh, oh, I see what you mean, what with the revolver in my hand and all that. We'll just put that back in the desk."

"You keep that gun in your desk for protection, sir?"

"Yeah. Yeah, why else?"

"Oh, nothing, sir, I just was curious why you didn't keep it loaded."

"Hell, you don't know anything about gun safety, do you, boy?"

"I'm thirty-one, sir."

"What's that?"

"I said, I'm thirty-one, sir. I don't think I'm really a 'boy.'"

"What do you want me to call you, then? 'Girl?'"

"I see what you mean, sir. So what about gun safety?"

"What about it?"

"You said I don't know anything about—"

"Yes! Exactly. You want to know why I don't keep this revolver loaded? What if a kid got in here, started playing with it? If I kept this thing loaded, he'd probably blow his own fingers off. Can you imagine that? Terrible. Terrible! Now. You see?"

"I suppose so. . ." Sandwich frowned. "Are there any kids down here?"

"Eh?"

"I said, are there any kids down here? We're a few miles underwater."

"Hell! How am I supposed to know how kids find their ways into the places they do? Sneaky little buggers, if you ask me, they are."

"Yes, sir."

"God knows they get into every _other_ place you think they can't. And make a mess there, as well!"

"Yes, sir."

"I have a few kids, you know? Up top? And they're all the same. Oh, I don't mean that. But they are. But I love them. But they really are."

"Yes, sir."

There was a drawn-out silence during which the captain gazed dully at the locked case in which he kept various types of ammunition to guns that he did not own. Sandwich shifted his weight from foot to foot, trying now and then to shift it to both at once.

"Alright then, Sandwich," said Captain Tumor finally. "You're dismissed."

"Yes, sir." Sandwich turned to leave when the captain jumped and said,

"Oh, oh! Wait? Now. Did you want something?"

Sandwich thought very hard. "I don't believe I did, sir."

"Then why were you in here?"

"Because you wanted me, sir."

"Oh. Why did I want you?"

"I don't know, sir. Job— Wrillis said you wanted me."

"Oh, oh, right, yes, right, as it were. Ah. Hm, but I didn't. No, not really."

"Ah, yes, sir."

There was another long silence. Sandwich tried desperately to think of which one of them was obliged to speak at this point. Perhaps he ought to just. . . go?

"I'll just. . . go, then, shall I, sir?"

"Ah!" said Captain Tumor, so loudly and suddenly that Sandwich jumped and knocked his head up against the top of the door-frame. "No, no, I have something for you after all. Yes. Ah, yes! Of course. You can show Miss Kerch around!"

"Ah— Miss— what?"

"Kerch, Miss Kerch. She just arrived. Not by design, mind. Rather a nasty accident. But she's here now. Eh? Make the best of it? She's a rather important public official, don't you know?"

"Uh— no, I didn't. Was that her sub, out there?"

"Yes, yes, rather a nasty accident, I'm told. Something about a stygian shark."

"Oh. Ah."

"Quite. Anyway, it would be quite helpful if you would show her around."

"Show her a— what?"

"A _round_," insisted Captain Tumor. He was sitting very still and staring at Sandwich in a way that suggested that the latter's head might ignite. Sandwich was growing increasingly uncomfortable as he realized that he might very well be getting into a good deal more than he had initially expected. He considered diving out of the open door and onto the deck and then into the pool to hide underwater for a few weeks until the captain simply forgot about him.

The captain continued, seriously: "Listen, Miss Kerch was on her way to the Vernderbitz rig some leagues from here. The sub was wrecked but she's OK, and for the time being she's stuck here because of that shark. So in the meantime, we need to, you know, show her a decent time. This is a _very important person_ we're talking about. Someone with a lot of say. If she likes what she sees here, well, it could mean good things for us. Eh? Increased funding? Maybe enough money to buy some of the things we've been doing without, like plates, and keys to some of the doors we've accidentally locked and have never been able to get open again."

This seemed reasonable enough to Sandwich. "But," he protested, "what am I supposed to show her? The guest habitat? The communal kitchen? This isn't really much of a luxury rig."

"Eh!" said the captain. "I don't know. Show her to the guest habitat, obviously. Beyond that, I don't know, show her the library and the tower. Really ham it up."

"The tower's locked, sir."

"What's that?"

"I said, the tower's locked, sir. Remember? It's one of the keys we've lost."

"Ah, ah. Well, get Joe to open it up for you. Or Jimmy. Old conker's good at getting to weird places, seriously."

"Ahm."

"Yes. Maybe you can have Oglvrthy show her the power room, as well. You know how much he loves his worthless little gizmos and stuff."

"You mean the heat collectors. And the generators."

"Yeah, those."

"The ones that keep us alive, sir."

"What? Yes— yes, _those_ gizmos. Whatever."

"Sir, I really don't think I'm the best—"

"Hell! I'm _sure_ you're not the best. But we haven't _got_ the best so you'll have to do."

"Ah— as you say, sir. I mean, yes, sir. I suppose. Sir."

"Yes."

"Ah."

Confused, Sandwich wandered out of the room and down onto the bridge of the machine deck. Jimmy was where he had been, still sitting with his fishing pole in his hands, a kindly air about him. As Sandwich walked past him, he hesitated in such a way that he lost his footing and nearly lurched into the water. He steadied, barely, both hands on the suface of the bridge for support.

"Hey, Jimmy," said Sandwich. Jimmy didn't answer, which Sandwich took as a _Yes? What is it?,_ and he continued, "Hey, do you know how to get into the tower?"

Jimmy turned with the slowness of an ancient skeleton turning to the man who had killed him by driving a sharpened flagpole through his head.

"Why?" he rasped.

"Oh, no reason, it's just, well, it's hard to explain, but it'd be helpful if I could, well, get in there, in the near future, you know."

Jimmy turned back to his fishing, even more slowly, if possible, and didn't say another word, a reaction which altogether Sandwich took to mean _Oh, no, I'm sorry, I don't know how, but I do hope that you find the solution in a timely manner, young man. Pip chop!_.

Sandwich had wandered all the way out into the middle of the machine deck before he realized, with a start, that he hadn't been told anything along the lines of where this Miss Kerch was, what she looked like, or even in fact if she spoke English. He felt a sudden rush of fear as he saw in his mind himself, clumsy and bungling, leading around an imperious, almost queenly foreigner, who asked him questions in a bizarre and unknowable tongue, and which he answered in a three year-old's English, until she became weary of him and impaled his fragile pale body upon an enormous spike. He wondered vaguely whether Captain Tumor might really forget about him if he hid underwater for several weeks. He wondered also if it was true, what Jimmy had once told him, that you could survive underwater for several weeks with nothing but a towel and a bag of chips and he really ought to try it sometime.

Somewhat dejected, Sandwich went over to the squat control room and leaned against its Westernmost door, until it opened and he fell backwards into the room with a yelp.

"Aho!" said Oglvrthy, who had opened the door. "Sorry about that, Sandwich there. Are you alright?"

"I think so, yeah," said Sandwich, who accepted Oglvrthy's hand in getting back to his feet. He noticed that Oglvrthy was wearing an enormous toolbelt. Among the many and sundry tools attached to it Sandwich could see a hammer, two screwdrivers, an electric drill, a package of nuts and bolts, a level, a pair of gloves, a pair of safety goggles, a pair of overalls, and a pair of specially-trained, Genetically-Engineered Semi-Cybernetic Lab-Rodents (or GESCLRs, which is pronounced "Gesslers"), which were hanging by their tails and squeaking in annoyed fashion.

"So, what are you doing?" asked Sandwich.

"Ah-ah, just a bit of repairwork. You know how things get in there." He jerked his thumb backwards at the control room. "Goons hardly know a screw from a nut, they're so into their computers and things. Half the time they call me over for something a child could fix. A lame child! A lame child with a learning disability and one eye. Half an eye, even!"

"They broke something?"

"One of them decided that if you could heat up macaroni & cheese in the microwave for sixty seconds at one hundred percent power, you ought to be able to heat it up in one second at six thousand percent power. Took out half the back panelling, and nearly his arm, as well. Whole place smells like cheese and starch."

"Ah," said Sandwich, feeling weird.

"Indeed," said Oglvrthy. "But it's no problem, really. A very simple procedure."

This method of stating things made Sandwich feel even more weird, and he said so, but Oglvrthy had already wandered off to some other odd job. Still feeling uncertain about what he ought to do, Sandwich went into the control room.

The control room was long and cramped, and every inch of it seemed to be filled with computers, desks or people, in irregular patterns. In the middle of the room and almost matching its length was a high wall, so that the room was in the shape of a flattened zero. The only place where there were not people or objects was the bright, narrow walkway that ran down the middle of the room, and around the wall, and which heated up very quickly if anything remained in contact with it for very long—to discourage loiterers.

Sandwich walked along the pathway, looking around at the cramped people typing furiously on cramped computers, with wires hanging everywhere and the occasional specially-trained semi-cybernetic rodent scurrying forth bearing a message or on an errand to repair the innards of a computer. He passed by several computer-technicians who were in something like hysterics, watching a progress-bar fill up on one of the monitors. He passed a young man who seemed to be spending his time drawing an incredibly-detailed and artistic sword in a digital drawing program. He also passed a number of people doing boring number-work, and two people who were asleep at their joint desk, their elbows resting against each other.

When Sandwich got to the East side of the room, he saw that there was some sort of confrontation, or possibly a conglomoration, taking place. A tall woman in a dazzling orange-and-red dress was arguing heatedly with a man whom Sandwich, upon fully rounding the corner, recognized as Jenkxin Spamwell, the Head Organizer, and his own immediate boss.

"Mr. Spamwell," said the woman; her voice was deep and rich, like blood and chocolate mixed together. "Mr. Spamwell, if you cannot perform even the simple tasks which I set before you, I do not see why it should surprise you that I grow angry. In the course of one short conversation, you have shown yourself to be not only a pig, but a cow, an ass, and by all means a dead fish. I shouldn't be surprised if you turn out to be a rat, as well, but quite honestly I feel no desire to continue our acquaintance long enough to find out."

"Miss Kerch," said Spamwell, looking quite awkward and out of his element, "I didn't mean to offend you. All I mean to say is that, under the circumstances, I don't see how you can blame us for not being ready with—as you call it—a— 'royal tour—'"

"A _Tour Royale!_" squaked Miss Kerch, indignantly.

"Yes, yes, a _Tour Royale._ The simple fact is that we aren't— er, we aren't exactly _set up_ for such a. . . ah. . ."

"Yes? A _what_."

"An— extravagence."

The woman named Kerch drew herself up to her full height, and her orange-and-red dress was like a deadly flame wrapped around her and singing the eyeballs of all her saw her.

"Am I to understand," she said, like death, "that it is considered an _extravagence_ to play a proper host in this facility? Am I to understand that it is the widely accepted opinion here that to show kindness to an _honored guest_ is somehow going above and beyond the reasonable line of duty?" She pronounced the two syllables of _du-ty_ as though they were gunshots.

"Miss Kerch!" said Spamwell, entirely flustered now. "I'm sorry, but this is a _research facility!_ We've never even had a visitor before—certainly not someone of your stature."

"In_deed_," said Miss Kerch.

"I mean— we can give you the guest habitat, of course, we will, and you have free reign of most of the facility, like anyone else, but, I don't really know what else to do."

"You can do your job," said Miss Kerch. "You are the Head Organizer. _Organize_."

Spamwell was still spluttering when Sandwich realized that he had been standing in the same spot on the walkway for the past thirty seconds, and the bottoms of his feet were growing warm with the heat of the melting rubber of his shoes. He jumped, and Spamwell noticed him, and Miss Kerch turned around to look at him. And Sandwich's world was positively inverted.

She was beautiful. She was like like a goddess, radiant in her orange-and-red dress, her scowl like the scowl of the huntress on the prowl. She was tall; he had noticed before, yet he had not! How could he not have seen? She was a titan, an empress, surely. He felt he might strain his neck looking at her face. And what a face it was! Her cheeks: pale red, like the steady flame that dances on an old campfire. Her eyes: bright blue, like the ring of fire made by a cigarette lighter. He lips: red like the fire that burnt heretics alive. Her teeth: white in a way which Sandwich was sure was related to fire though he could not at the moment come up with a suitable connection. And her hair was like fire flowing from her head, if flowing was something that fire did.

She also carried a crimson-handled whip, which was interesting.

Sandwich tried to find his footing, but it was difficult. His entire life up until that moment seemed a blur, a worthless blur, the worthlessest of blurs. He knew at once that he was in love, and that he was hers forever, and that if she did not love him already, it was his only purpose in life to make her love him. All there was was for him to discover how.

"Yes? And who are _you_?" said Miss Kerch. Even her voice was beautiful, and soft, and fiery, in a mildly conflicting way.

"This is S—" began Spamwell, but in that moment Sandwich felt as though a ray of clearest sunlight had burst forth from the pipe-covered and wire-spidered ceiling of the control room to shine on him. He knew exactly what to do.

"I am your guide and your personal assistant for your stay," said Sandwich, stately, "and you may call me Sandwich."

Miss Kerch blinked for a full few seconds, probably because a man had just informed her that his name was the word which meant _Two (or more) slices of bread with a filling between them_. Spamwell was staring at Sandwich as though he had turned into a sandwich, and was still staring when Miss Kerch said, "Well, I'm glad _someone_ here is on top of things. Mr. Spamwell, you have been most unhelpful, but if you refrain from speaking any further, I may overlook this particular incident."

"Uhm," said Spamwell.

"It's perfectly alright, Jenkxin chap," said Sandwich, mad with excitement, "I cleared the whole thing up with Captain Tumor. He wanted to give the job to Oglvrthy, but I told him I'm the man for it."

Spamwell was still looking as though he had just been told that purple was green and that houses turned corners, but he recovered by and by and shrugged and said, "As you say, Sandwich."

"Yes, yes," said Sandwich, his eyes crossing slightly, "as I say."

"Mr. Sandy," said Miss Kerch, "if you would show me to my rooms. I have endured undue hardships today and I think I will retire early."

"Yes, of course," said Sandwich. "After you."

"I do not, in fact, know the way," said Miss Kerch severely.

"Yes, of course," said Sandwich in exactly the same tone of voice as before, though his cheeks had flushed hotly at her words. "After me." And he led her out of the control room, and onward toward the guest habitat. He considered taking her through some of the generator rooms to try and impress her, but she had said she wished to retire, as it were, and anyway, the door between generator rooms B and C was locked and had no key, so it wouldn't be a very efficient detour.

As they passed the computer room they ran across Acefire Joe, who was just leaving it. He looked apprehensive at the imposing figure of Miss Kerch, and his hand drifted near his crowbar, but Sandwich gave him a warning look and then said, "Ah, no, Joe, this is, ah, Miss Kerch. I'm just showing her to the guest— er, rooms."

"Kerch," said Acefire Joe, as though testing the word's strength.

"_Joe_?" said Miss Kerch. "This child is. . . _Joe_?"

"Hmm?" said Sandiwch. "Oh. Yeah. Well he's not— I mean, well, yeah. Acefire Joe. He does security detail."

"In_deed_," said Miss Kerch. "Mr., ah, Joe, how long have you worked here?"

"Why do want to know?" said Acefire Joe, annoyed.

"Call it a professional interest," said Miss Kerch. She was acting oddly, looking at Acefire Joe as though he were an actual person. "I am also mildly curious how a person as young as yourself is able to perform the duties of—"

"Here!" said Acefire Joe, angrily. "I do my job and that's enough. Isn't it? I don't have time for random interrogations by whatever Zroya or Sekhmet happens to be in the area at the time." And he stalked off.

"Don't know what's wrong with him," said Sandwich.

"Perhaps he missed his nap?" suggested miss Kerch.

They made their way the remaining distance to the guest habitat without interruption, and as they reached the door Sandwich was trying to figure some way of asking for her hand, so that he might kiss it, when she slammed the door shut in his face. Realizing with a certain amount of anxiety that his wooing of her might take as long as two or three days, or even longer, Sandwich walked slowly back to his own room and got into bed. He wondered how he would ever get to sleep, the thought of her being so bright in his mind.

Then he remembered that it was not yet noon, and technically he was expected to do some work today, whether or not he was showing around guests. So, feeling annoyed and not tired and feeling annoyed that he was not tired, Sandwich got out of bed again and headed back to the computer room. As he walked towards it he passed Oglvrthy in the hallway, who, seeing him, shrugged, then turned around and went back the way he had come from.

. . .

* Chapter Two: Oglvrthy's Ploy, And Other Things


Walking back from his encounter with Sandwich on the machine deck, Jobble thought he saw Acefire Joe walking towards him down the main hallway. Jobble was a bit paranoid about Acefire Joe, on account of the fact that all of their encounters ended with Acefire Joe hitting him about the shins with his crowbar. Whether it was because Acefire Joe consistently (and mistakenly) took Jobble to be a vandal, as Acefire Joe insisted was the case, or whether he simply disliked him for some odd reason, Jobble was not entirely clear on, but he was willing to let the mystery lie for the time being in favor of self-preservation. Quickly he ducked out of the main hallway and into the short hallway that led to generator room B, which in turn led to generator room C, and the power room. Technically it led to generator room A, as well, but that door had been locked for months.

Generator room B, more or less identical to its siblings, was a perfectly cubical room that housed something like a mad inventor's entire life's work hammered into a single semi- or pseudo-coherent piece of engineered insanity. At least, that's how Jobble considered it. He had no engineering background and considered the whole mess to be a dark form of witchcraft or voodoo. _Stable?_ he thought. _Yeah, it's stable. So are giants, while they're standing_.

The generator hummed and clicked. Thick coils of fiber-optic conduit carried its life-preserving energy to all parts of the rig, through tubing shielded with thick layers of rubber. The whole mess had the look of something on the verge of an explosion. It was a bomb, surely; a deadly bomb, the deadliest of bombs, here inside its precious shielding. The shielding of an atomic bomb, the shielding that reflects the bomb's power in upon itself again, over and over in the few milliseconds it takes for the bomb to discharge, so that its yield is so many times greater than it would be if its energy merely extended once and was gone.

Though, as he looked at it from another angle, Jobble saw that the generator looked more loke a furnace, like the great cylindrical iron furnaces used to heat ships in older times. Or, no, he thought, that's probably not how ships were heated. But the image was in his mind for some reason, and he spent some time enjoying its anachronistic majesty.

From another angle, the generator looked like an enormous head, and Jobble wondered if it might say anything, and, if it did say something, if it would command him to worship it. He decided immediately that he would not, that he would much prefer worshipping a god made of stone or glass (assuming that flesh and blood were unavailable), and not this mindless monstrosity.

Jobble reached up and touched a side-panel of the generator. It hissed angrily, and he brought his hand back quickly, thinking he had been burned, although he hadn't been.

At once Jobble realized that he had spent an inordinate amount of time in the room, and that probably Acefire Joe had long quitted the main hallway. Yet, simultaneously he realized that he had almost never visited the power room, as the captain insisted that he would certainly destroy the entire station and bring death to all if he did, and in that moment the spirit of wisdomless adventure stirred within him.

Generator room A was much as generator room B, except that this, the main generator, was somewhat more tired-looking that its companion in room B. The panels, the nuts and bolts, the wires and tubings and cannisters and guages and rivets all seemed to be in the same places, the conduits exitted the room at only slightly abridged angles, but somehow the thing had the feel of an older being, an older machine.

It also had the feel of something which is at about a hundred and five degrees, at least at the spot where Jobble touched it, and he jumped backwards, cursing, this time having actually burned his hand. He continued into the power room.

The power room was quite small, compared to the generator rooms; more of a hallway, really, than a room. There was no furniture or objects of any kind in the hallway-room, but the walls were completely covered with wires, switches, control panels, and the like. Five even smaller rooms broke off from the main power room, each no bigger than two telephone booths put together: four of them were receivers which gathered the energy sent to them by four volcanic heat converters, one receiver to one converter, and the fifth room was a conglomorate energy input/output station, from which the rig could pull extra energy, if needed, from a nearby undersea battery, or push energy, as needed, into off-rig ships or equipment.

Jobble explored each of the first four rooms, mildly interested, then the fifth, and was annoyed to find it locked. He thought about why he hadn't known this to be the case in the first place, and he realized it was because the power room, itself, was usually locked. This also accounted for the fact that he had gone to the trouble of exploring the control room at all that day, having lived on the rig for over a year and a half already.

After a while, unable to think of anything else he might accomplish, Jobble headed out of the control room. Before he had left, though, he noticed a red light blinking in one of the tiny receiver-rooms. He looked at it. There was a label underneath the light:

— EXPLOSION WARNING D —

Jobble frowned. He couldn't quite grasp the meaning of that last bit. He read it again, to make sure that was all it said. All it said was:

— EXPLOSION WARNING D —

Jobble frowned even further. He looked around for some sort of instruction manual, and found it hanging from a hook above his head. He flipped to the table of contents, then the index, not expecting to find anything, but finding something anyway. He flipped to the page referenced for "explosion warnings":

In the event that an EXPLOSION WARNING light is active, please consult this list to determine what category of explosion-likelihood you are 			experiencing:

A. Explosion PROBABLY WON'T, but MIGHT, OCCUR.

B. Explosion will happen ONLY if you DO SOMETHING STUPID.

C. Explosion will occur if a dice rolled thrice SHOWS THE SAME NUMBER ALL THREE TIMES.

D. Explosion is ABOUT TO HAPPEN IF YOU DON'T DO SOMETHING QUICK.

E. Explosion has ALREADY HAPPENED and you are LIKELY DEAD.

Jobble's frown increased yet further, so that it became uncomfortable. He looked back at the flashing warning light.

— EXPLOSION WARNING D —

He saw the other four explosion warning lights as well, all dark. Altogether, the situation was somehow troubling. He tried to remember if he knew what an _explosion_ was, then with a jolt he remembered, and he also remembered that he didn't want one to happen. He searched frantically about the various guages and read-outs covering the walls of the tiny room, finally seeing one labelled:

— PRIMARY MASS INDEX —

. . . And whose needle was deep into the red zone of the little circle. Quickly he found the button marked:

— PRIMARY MASS RESET —

. . . Slammed his fist down on it, then lamented the fact that the button did not need very much pressure and he had slammed his fist against a hard metal surface without any particular need. However, he noticed that the little needle was slowly receding to the safe little hemicircle, and that the warning light was fading, fading, dark. Jobble sighed in relief, not so much because he had actually been worried but because it seemed like an appropriate thing to do, and hung the manual back on its hook above his head. After this he considered sticking around, but felt subconsciously that the existence of the first problem was probably caused by his presence in the room, and that if he stayed there would only be more disasters for him to take care of. So he left the tiny room, and the power room, and generator rooms A and B, until he found himself back on the machine deck.

The damaged sub was near where it had been, but it had by now been hoisted onto the backs of two small flatbed trucks that had been linked together side-by-side, to be carried off to the side of the massive room. It was rather badly damaged, and it was obvious it was not repairable—probably it was so beyond help that very few of its componants were salvagable. While he watched, someone shouted something, and then something hard smashed into the side of his head.

Spinning, Jobble leapt away from the object, but the ground jumped around behind him and hit him against his elbow and shoulder. Then Jobble realized that it was the _room_ that was spinning, which lead to the realization that the room could not be spinning, and that therefore _he_ must be spinning.

"Oi! You! Stop!" the tiny figure of Acefire Joe was sprinting towards him like a mad baby gargoyle. "Thief! Thief!"

"Aaughk," said Jobble plaintively, trying to get up. The ground flipped over to his other side and punched him about the head and neck area.

"Ah! Ha! Ha!" said Acefire Joe. He retreived his crowbar from where it lay on the ground, and held it in a threatening manner over Jobble. "I have you now, thief!" he cried. "It's up! It's up! The game is up!"

Jobble held his head in his hands and tested the tact that if he stayed still long enough, so would the world. Meanwhile, he remembered his earlier insistance on avoiding Acefire Joe.

"Joe!" he said at length.

"What!"

"Joe!"

"What!

". . . _Joe!_"

"What! Oh, morning, Jobble. You look like hell, you know."

"May I ask—erk—why you threw a crowbar at my head?"

"Well, I thought you were a thief!"

"You always think I'm a thief! You always bloody run around thinking I'm a thief! Why do you think I'm a thief? When have I stolen anything? When have I taken something here? You're always running about, lobbing that thing at heads and things, and I never take anything!"

"Look, I'm sorry, Jobble, but I didn't recognize you."

"Why the hell wouldn't you recognize me?"

"Well, you've got a huge discolored bit on the side of your head."

"Ah. Of course."

Jobble staggered upright and held himself motionless until his eyes were basically able to focus on one particular object at a time. This object was Acefire Joe, whom Jobble then kicked.

"Real mature," said Acefire Joe, from the ground.

"We're even now," said Jobble."

"Like hell we are."

"Yeah, I probably owe you bit more than that."

"Whatever. Hey, what's with the sub over there?"

"What? The busted one?"

"Yeah. I thought it was one of ours that got caught in a bay door."

"A bay door? That's not right. Where'd you hear that, then?"

"Oglvrthy told me."

"Huh."

"So what happened, then?"

"A styg shark. Eh? You can see by the scoring on the side of the body, there, in the paint, Edbe."

"What?"

"I said, you can see by the scoring in the paint on the side of the body, there."

"Edbe?"

"What about her?"

"Why did you say her name?"

"When?

"Just now. You said the thing about the paint, then you said, Edbe."

"It only seems polite to address people by their own name, don't you think?"

"But I'm not Edbe. I'm Joe. We've been over this— "

"Well, who says I'm talking to you?"

"You're talking to me right now."

"But earlier!"

"Earlier you said, 'Edbe,' like you were talking to her."

"I _was_ talking to her."

"But she's not here!"

"She's right behind us."

"Is she?"

In fact, she was.

"Oh," said Edbe in the general direction of Acefire Joe, "hello, Joe."

"Oh. Hello, Edbe. How go the old blood and guts?"

"Bloody and gutsy," said Edbe. "Did you throw your crowbar at Jobble again?"

"A little bit," said Acefire Joe.

"I object to this madness," said Jobble, crossly. "It's as though everyone here believes major head injuries to be a mere passing matter."

"Has Joe ever given you a major head injury?" said Edbe.

"Well, he knocked me out, once."

"You woke up later," said Joe.

"_Two weeks_ later," said Jobble.

"Was that when he injured your major head?" said Edbe.

"What?" said Jobble.

"You were complaining about major head injuries. Was that when he injured your major head?"

"Yes," said Jobble. "Definitely."	

Acefire Joe snickered, and Jobble kicked him, and received a thwack from the crowbar upon his shin for his trouble.

"Oh, listen," said Edbe, apparently having just thought of something, "have either of you seen Sandwich? I need to talk with him."

"Sandwich?" said Jobble. "Last I saw him, he was heading off to talk with Captain Tumor. Something about showing that queen around."

"The captain wanted Sandwich to show a queen around?"

"Yeah."

"Hmm." Edbe lapsed into silence for an awkward period of time. Finally Acefire Joe started to say,

"Well, I'd better— "

—And then Edbe said, "There are at least two things wrong with that statement."

"What do you mean?" said Jobble.

"Well, well, first of all, the captain is hardly aware of Sandwich's existence," said Edbe. "He only ever gives him assignments or jobs if he just happens to see him."

"He happens to see him often enough around the base, though, eh? It's not a very big rig we live on. And they live in opposite rooms. I should think they see enough of each other for the captain to give Sandwich an assignment now and then."

"I suppose. Except that the captain has been in his office all day, just like his is every day. And most nights. Actually he's been sleeping in there. You didn't know that? I thought you were his secretary."

"Oh? Oh, I suppose I knew that." Jobble was somewhat annoyed at being corrected. "Alright, so he didn't ask for Sandwich specifically. But he needed someone to show that Kerch woman around, and he didn't trust me for some reason, and so I sent Sandwich in because I knew that'd get the problem out of his hair and he'd stop complaining about it to me."

"Kerch?" said Acefire Joe, which surprised both Edbe and Jobble, as they had quite forgotten that he was there. "Mae Kerch?"

"What?" said Jobble. "Oh, I suppose so, yes. Her."

"Ahh. Hmm."

"'Hmm?'" Edbe wondered aloud.

"I mean what I intone," said Acefire Joe.

"Ah."

"You know," said Jobble, with a sudden and hungry look in his into-the-distance-staring eyes, "you know, you know, I heard a story once, that might explain this whole thing."

Edbe and Acefire Joe stared at him.

"I think," he said, then hesitated, then gained further resolve, then continued, "I think— yes! So— so, there was this man. Right? So there was this man. His name was Johnny, and he was a very dark fellow. Very dark."

"Dark skin?" asked Vivian, who has no other line or appearance in this narrative.

"No, no, disposition!" said Jobble. "His disposition was dark. He was sarcastic and wry, pessimistic; in a word, dark. He lived alone, but even the people who lived next to him—he lived in government-sponsored projects—but even the people who lived next to him, as I say, and who never invited him over for tea because they knew he wouldn't accept, and because even if he did accept they wouldn't want him over, and because even if he did accept and they did want him over, they didn't have any tea—even these people knew that he was a dark, a very dark person."

Edbe and Acefire Joe stared at him with an intensity not often encountered.

"So— there was this man, Johnny, and he was a very dark fellow. Quite dark, indeed. And he was known to take long swims in the dark. You know how your not supposed to swim at night, aye? Especially not out in open waters, because that's when the sharks are, as is widely known, very most likely to get you. But this man, Johnny, he was so dark, he was so pessimistic a person, that he went anyway, knowing the dangers— knowing them better than most, even. And he was a very good swimmer, after a life lived with a long habit of night swims, but he wasn't good enough for what was about to happen to him."

"What?" said Edbe, while Acefire Joe backed away slowly.

"The shark!" said Jobble, and his eyes were alive with some deep and hitherto-hidden fire. "The shark! Now, despite Johnny's disposition, he had no particular desire to die. You know? He wasn't depressed. Merely pessimistic. Merely dark. Well, very dark. Merely very dark."

"Right," said Edbe. "So, he was eaten by a shark?"

"That's just the thing," said Jobble. "He never went out swimming when there were sharks out. It was strange; no one told him, he never checked, whether sharks were out or not, it was as if he just _knew_— but even that was inaccurate, because his behavior surprised _him_ as much as anybody else. He simply went out swimming when he felt like it, and didn't when he did not. By fate or chance or intuition, he only went out when there were no sharks out. Until Lonely Tuesday."

"Lonely Tuesday?"

"The loneliest day of the entire year."

"When is it?"

"On a Tuesday."

"I mean, which Tuesday?"

Jobble wavied his hand. "It varies. Anyway. So this man, Johnny, goes out swimming on Lonely Tusday, the same way he has every Lonely Tuesday for years and years— "

"Wait a minute, wait," said Edbe. "What's this about a queen?"

"What?"

"You said that Captain Tumor was going to have Sandwich show 'that queen' around. What queen?"

"Kerch."

"I don't think she's a queen."

"What, are you denying the existence of contemporary queens?"

"Well, there aren't many."

"Ah, but there's the Queen of Denmark, isn't there?"

"Whoever we have aboard this rig, I doubt she's the Queen of Denmark."

"She might as well be the Queen of Denmark," said Sandwich dreamily, who was standing exactly where Acefire Joe had just been standing. His sudden appearance caused both Edbe and Jobble to jump, which in turned caused Sandwich to jump. After he had recovered his composure, he went about recovering his deamy air.

"Where'd you come from?" said Jobble. "And where'd Joe go?"

"He said something about hitting vagabonds," said Sandwich. "With his crowbar, I think. Anyway, I just came from the computer lab. I was trying to work, but I just couldn't concentrate, you know?"

"Why not?" said Edbe.

"Because of her. . ." said Sandwich, his voice trailing off into silence, and his gaze trailing off into the vague and generally ill-defined distance.

"Who? The queen?" said Jobble.

"She's not a queen," said Edbe.

"And yet she could be!" said Sandwich.

"We are talking about Mae Kerch, right?" said Edbe.

"Mae!" said Sandwich, hearing her given name for the first time. He said it several times more, for some reason enjoying the sound of the particular name far more now than he ever had in the past. It was probably a coincidence. "Mae. Mae."

"Sandwich? Sandwich?" said Edbe, trying to get his attention.

"Huh? Edbe? Oh, Edbe." said Sandwich.

"Jobble Jobble," said Jobble, feeling left out. Sandwich and Edbe both stared at him as though he had grown a third horn, or in fact as though he had grown two horns to begin with.

"Anyway," said Sandwich, "it's brilliant, it's all brilliant. I'm showing her around the rig. I'm her personal assistant for the duration of her stay. It's brilliant!"

"I don't understand why having a public official stay on a scientific rig is really precisely 'brilliant,'" said Edbe.

"What? Oh, no! No, it is, it really is," said Sandwich. "You haven't met her yet. Just wait until you meet her. She's— _magnificent_."

"_Magnificent?_" said Jobble, slightly staring at him.

"_Magnificent_," said Sandwich again, trying to indicate his intended usage of the power of the word by emphasizing it in a peculiar way, that is, by holding the 's'-sound of the 'c' for a very long time, so that the word became something more like "magnifisss_scent_."

"In what way?" said Edbe.

"In the ways that matter. In precisely those exact and specific ways which exactly _matter_."

"Such as?"

"Each and every one of them for which therge is a name. And those that don't."

"Ah."

"Sandwich," said Jobble, "I believe you are in need of a strong drink."

"To congradute me? Or in celebration? Of the fact that Mae Kerch is in our midst?"

"Yes, yes, that exact reason, you guessed it exactly," said Jobble, pushing Sandwich along while giving Edbe the he's-craaazy signal while Sandwich couldn't see.

"But, but, I have to wait. For her. I have to wait until she needs me!" Sandwich babbled, trying to stay where he was.

"Why, what's she doing now?" said Jobble.

"She's, ah, sleeping, I guess."

"Whum? It's like ten-thirty in the morning, mate."

"She's probably running on a different sleep cycle," said Edbe. "She's not from around here."

"You mean from this rig?" said Jobble. "Well that should be obvious, shouldn't? No one's 'from' here except for the crew, like us."

"I mean from this country," said Edbe.

"We're not in a country," said Sandwich, blankly. "We're underwater."

"Fine, the country we're affiliated with," said Edbe.

"With which we are affiliated," corrected Jobble. Edbe threw a pen at his face, but it missed his eye.

Sandwich, who was abruptly deep in thought, said, "What country _are_ we affiliated— I mean, with what country _are_ we affiliated, again? I can't seem to remember for some reason."

"Uh," said Jobble.

"Hmm," said Edbe. "You know, that's odd, but I can't either."

"Huh."

"Anyway," said Edbe, "I think Mae Kerch is from a different country from. . . whatever country most closely matches our sleep-cycles."

"But our sleep cycles are largely artificial," protested Jobble.

"So that means she could be from anywhere," said Edbe.

"Except for here!" exclaimed Sandwich.

Jobble said, "I thought we had already established that she wasn't from here, seeing as the only people who can really be said to be in some reasonable capacity 'from' here are people such as us, the crew of this rig. And old Jimmy McCreamy."

"Oh, I like Jimmy," said Edbe. "He's so nice."

"He really is, isn't he?" said Sandwich. "I think he comes from a gentler generation."

"Oh, definitely," said Jobble, and then, "What was I talking about just now?"

"The fact that the only people who can really be said to be in some reasonable capacity _from_ here are people such as us, the crew of this rig," said Edbe.

"Oh, yeah," said Jobble. "Except that I emphasized 'from' differently."

"What?"

"I said, I emphasized the word 'from' differently."

"What do you mean?"

"What do you mean, what do I mean?"

"I mean, what do you Goddamn^ mean?"

"Oh. I mean that you gave it a sort of italics-type emphasis, while I merely gave it an emphasis like that rendered by, you know, bracketing apostrophes."

"Those are typographical phenomena. You can't assume direct phonetic analogues for all typographical phenomena."

"I can, if phonetic phenomena derive from typographical phenomena."

"But, they don't."

"Not _always_. They sometimes do, though. And you used a different emphasis."

"How can you even tell something like that?"

"Good ears." Jobble tapped his ear to emphasize this.

"Huh."

"So where _is_ she from?" said Sandwich.

"Hmm? Oh, Kerch?" said Edbe.

"Yes!"

"Oh, I don't know. Someplace."

"Most likely," said Jobble.

"Probably Denmark," mused Sandwich, his eyes beginning to unfocus rapidly.

"Sandwich!" said Jobble, seized with one of his unpredictable fits of energy, "How about that drink?"

"But we don't keep alcohol on the rig," said Sandwich. "Leastways not where people can get at it."

"No, but I have a brewery."

"Where'd you learn to make a brewery?"

"Old TV show."

"Huh. Should we really be drinking this early? Actually, shouldn't we all be working?"

"If I go in there," said Jobble, indicating the captain's room, "he'll just get after me about all the things I could be doing somewhere else. Or maybe he'll try to kill me. He does that, you know."

"Kill you?" asked Sandwich, startled. "What, on purpose?"

"Eh," said Jobble.

"Hmm," said Edbe. "Actually, maybe I should get back to work. I think I needed to operate on someone today."

"Really?" asked Sandwich, shocked to find that he was again startled, in so little a space of time.

"No, not really," said Edbe, and she walked through the door to the main hallway and left.

"Odd girl, that," remarked Jobble, looking after her.

"No, no, she's not," said Sandwich, dreamily. "She's _magnificent."

"Edbe?" said Jobble, bewildered.

"What? No! Mae. Mae _Kerch_."

Jobble decided that he was tired of Sandwich at that point, and decided to do some work, after all.

.
.
.

Chapter Three: Where Work Gets You

Jobble did return to work but, as usual, taking up residence in what was technically his chair just outside the captain's office had only the effect of causing the captain to restlessly pace for a few minutes before telling Jobble to get up and do something useful, for Heaven's sake. Here is a dream:

There once was a mollusk without a shell. This mollusk lived in perpetual fear of things that might hurt or even kill him, because he lacked the protection of a shell. Not only that, but in addition, all his mollusk friends, or rather, his mollusk contemporaries, who were not really his friends but whom he would like, all things considered, to be able to consider his friends, and for them to consider him _their_ friend, tended to make fun of him whenever he was around them, and sometimes even if he wasn't. He wouldn't have known this latter fact if he hadn't been told by a passing yearling, but as he _was_ told by a passing yearling, he did in fact know this fact, and it did not serve in the general scale of things to either cheer him up or release him from the drear of a day-to-day shellless existence. At least, that's what you might think—that this mollusk was sad and lonely and emotionally unstable and prone to shyness and awkward outbursts. The reality, however, was somewhat unexpected: he was a very personable mollusk, having a penchant for coming up with excellent anecdotes, and generally being able to carry on conversations with good skill, and to make all laugh with his jokes—if, that is, they would listen to him tell them, which in most cases, they did not. But this didn't bother him, as he was content to tell them to other living things, such as seaweed and coral, which of course do not talk. More often than not, he took their silence as stern but helpful criticism, and since he was a very personable mollusk, and desired only the best for his audiences, he was alwas striving to improve his ability to regail things with ears or other sensory organs with his stories and witicisms.
