The End of All Things

* Chapter 1: The Beginning of the End (of All Things)

The end of all things came as a surprise to most of those involved. It was a huge and sordid affair, involving the burning of galaxies and the spilling of coffee. Rud was around to witness most of it, and as it began, he gripped the sides of the vidscreen with white knuckles. The vidscreen was, of course, simply a white board which served as a backdrop to the screen itself, which was projected into the air by means of a little knob linked to the computer, so RudÅfs gripping the vidscreen had the effect of making the display flicker and shift, trying to stay oriented on it.

ÅgRud!Åh cried someone from behind him. The next sound was of a strangled gasp, and then a choked cry, which was followed by a gagging sob. Rud turned, the vidscreen still in his hands and the display now quite warped trying to keep up with it, and saw that it was Billiam, who was not very good at dealing with stress in the best of times and since this was in fact by standard standards the very worst of times, was dealing with the his stress quite badly indeed, that is to say, by slumping against the deck and muttered inchoately.

ÅgItÅfsÅ\Åh he managed.

ÅgI knowÅ\Åh Rud told him.

ÅgI sawÅ\Åh began Bill.

ÅgOn the screenÅ\Åh supplied Rud.

ÅgEverywhereÅ\Åh elaborated Bill.

A third party entered the room, with the intent, the casual observer might hope, to improve the present quality of conversation.

ÅgWhat is it?Åh asked Sharie. Her hair had come out of its band and was in her face, and one of her shoes had escaped her somehow, but she was determined not to act shaken.

ÅgItÅfsÅ\Åh began Rud.

ÅgThe universeÅ\Åh added Bill

ÅgAll overÅ\Åh continued Rud.

ÅgTerrible conflagrationÅ\Åh asserted Bill.

ÅgItÅfs conflagging everythingÅ\Åh hazarded Rud.

Seeing where this was going and not wishing to join them there, Sharie seized the vidscreen out of RudÅfs hand, pushed him out of the chair, and sat down to examine it for herself. ÅgOh,Åh she said, and then, ÅgUm.Åh She called for the captain.

ÅgWoo,Åh said the caption, sort of swaying into the room. ÅgIs it just me or is the universe ending around us?Åh

ÅgNo, just in front of us.Åh said Sharie.

ÅgHa! Well itÅfs lucky weÅfre at the edge of it, then, innit? Full speed backwards, and so forth.Åh he swayed back out of the room again.

A few seconds his head popped back into the doorway. ÅgSeriously, though whatÅfs going on out there?Åh

Rud and Bill gibbered. Sharie said, ÅgI told you. The universe is ending in front of us.Åh

ÅgRight, but I mean.Åh He waited for her to respond. She didnÅft. ÅgUm,Åh he said. He came back into the room soberly and leaned forward to look at the vidscreen. It showed a number of planets and stellar objects more or less engulfed in boiling wafts of plasma. It also informed him that the rate of destruction was beyond that of essentially every known cosmic force.

ÅgHey, there,Åh he said, ÅgyouÅfre being serious.Åh

Sharie sighed and scooted out of the way to let him peer at the vidscreen more closely.

ÅgWe, ah, we should probably do something,Åh said Rud. He was really a very stable guy most of the time, but he was sensitive to the grand and the dramatic, and he realized with a pang of disappointment that he never determined what the proper reaction was to facing the apocalypse.

Bill, for his part, had become distracted when he hit his elbow against the doorframe, and was rubbing it dejectedly.

ÅgWhat exactly did you have in mind?Åh said Sharie.

ÅgWell, I donÅft know, but _some_thing.Åh Rud looked at her, but she was looking at him so he looked away again.

ÅgLook, thereÅfs only one thing we can do right now, and thatÅfs get away from here. I donÅft know whatÅfs destroying everything here, but itÅfs moving pretty slowly.Åh She looked at the captain, who was still gazing at the vidscreen and offered no argument, so she said aloud, ÅgShip, move us away from the wave of destruction at three-quarters speed, please.Åh

ÅgON MY HONOR,Åh the ship intoned, its voice heavy like lead. On the vidscreen, the images of burning planets started shrinking.

ÅgSo what gives with the fire and brimstone and what have you, then?Åh said the captain.

ÅgWhat?Åh said Sharie.

ÅgWhy was everything on fire?Åh

ÅgI donÅft know! How am I supposed to know?Åh She flung herself into the back of the chair to glare at him.

ÅgWe can get away from it though, right?Åh said Rud.

ÅgYeah, we can,Åh said Sharie, Ågbut it doesnÅft look like itÅfs stopping.

ÅgOh. Well how long until it, uh, you know. . . Åh

ÅgDestroys the entire universe?Åh

ÅgI was going to say _hits heavily-populated worlds_ as a warm-up, but yeah, thatÅfs a good question, too.Åh

ÅgEr, maybe fifteen hundred years or so. So at least we can be safe.Åh

Rud looked horrified. ÅgFifteen hundredÅ\that means itÅfs moving faster than light!Åh

ÅgYes, but this ship moves _much much_ faster than light.Åh

ÅgThatÅfs not what I mean! I mean, what is it? What could do that?Åh

ÅgYes, IÅfve known the answer this whole time but just havenÅft had the courage to say it. Please, continue asking me. Maybe you can ask me some other questions that I definitely know the answer to, like the meaning of life and how many rings the Grand King Morbor of Hallawoop wears on his third hand.Åh

She glared at him, and he scowled back. ÅgYou donÅft have to be nasty about it,Åh he said.

ÅgHoo,Åh said the captain. ÅgThereÅfs a dude down there.Åh

ÅgWhat?Åh said Sharie and Rud together.

ÅgOn the planet-thing. Whatchacallit. Planetoid. The little-planet-jigger. Over there.Åh He jabbed his finger inaccurately at the vidscreen. ÅgCompy says thereÅfs some dude on a hill on it.Åh

ÅgShip, what is he talking about?Åh said Sharie.

ÅgIT SEEMS THAT THERE IS A SURVIVOR ON VEXORK, THE FIRST PLANET OF THE XORK SYSTEM IN SECTOR 99Z4^K.Åh

Åg_A_ survivor? Just one?Åh

ÅgYES, STANDING ATOP THE CREST OF THE HIGHEST MOUNTAIN OF THE PLANET. BEHOLD!Åh

The vidscreen changed to show a blurry image of a man who seemed to trying to fly off the mountain by using his arms as wings.

ÅgWhat happened to everyone else on the planet?Åh said Sharie.

ÅgTHE REST OF THE PLANET IS CURRENTLY COVERED IN A SEA OF PLASMA YEA, A THOUSAND FEET DEEP. IT IS PROBABLE THAT THE LONE SURVIVOR, TOO, WILL BE COVERED IN PLASMA WITHIN THE NEXT MINUTE.Åh

ÅgShip,Åh said Rud urgently, Ågcan we save the man? Is there time to get him?Åh

ÅgWHY, YES, I SUPPOSE SO, AT THAT, YES.Åh

ÅgWell thenÅ\Åh

ÅgOH, WAIT.Åh

ÅgWhat?Åh

ÅgAH, NEVER MIND.Åh

Rud took a private second to despise the ship.

ÅgDo it, ship. Go save him.Åh

ÅgALRIGHTY THEN.Åh There was a sound of changing acceleration, as of distant thunder. ÅgYOU SHOULD KNOW THIS IS NOT WITHOUT SOME RISK OF DAMAGE TO MY STRUCTURE AND YOURSELVES.Åh

ÅgHow much risk?Åh asked Sharie.

ÅgPIZZA,Åh said the ship, which was what it always said when it was asked a question it was unable to answer. Rud shrugged, and Sharie seemed to lack a response, and so went on with her glaring.

ÅgLucky dude,Åh muttered the captain after a few seconds.

ÅgEh,Åh said Bill, from the floor.

ÅgYeah,Åh said Rud, in reply to both of them.

ÅgI BELIEVE A RECALCULATION IS IN ORDER,Åh the ship informed them.

ÅgWhat? Why? On what?Åh said Rud.

ÅgON TWO COUNTS, ACTUALLY. FIRST, IT SEEMS THAT THE MAN WILL BE DEAD SOONER THAN I ORIGINALLY THOUGHT, AS HE HAS JUMPED OFF THE MOUNTAIN. SECONDÅ\Åh

ÅgWhat!Åh said Rud, jumping.

ÅgÅ\I CAN IN FACT ANSWER THE QUESTION ABOUT THE RISK INVOLVED INÅ\Åh

ÅgShip! Can you teleport him from here?Åh

ÅgYES. BUT YOU MIGHT WANT TO KNOW MORE ABOUT THE RISKÅ\Åh

ÅgNo! Not right now! Teleport him right now!Åh

ÅgERÅ\Åh

ÅgNOW!Åh

ÅgUH, YOU KNOWÅ\OH, WHATEVER. ENGAGING TELEPORTERS EXACTLY TWO SECONDS AGO.Åh

There was another sound, also like distant thunder, except distant thunder which has been left out in the rain for a few nights and is a bit dirtier and less stiff than it was before.

ÅgCool,Åh said the captain, after he had made sure that the ship had turned around and was again safely flying away from unspeakable destruction, ÅgI love intros.Åh

.

.


The young man named Izzy Oz stood (that is to say, had stood) atop the towering peak of VeXork MonsÅ\the once-home to the fleeing armies of Emperor Ferdinand during the Fourth Civil War, shelter to the fearsome Blue Beast of VeXork, source of the one of the universeÅfs purest dolomite veinsÅ\and spread his arms in the manner of those dramatic individuals who do things like spread their arms at the sight of the end of the world. He looked into the roiling, angry sky and the rushing, deadly plasma, and something of the romantic came up within him, and he had to admire the beauty that was here with all the death. He knew that he deserved to die a hundred thousand times over, and thought that perhaps justice would be served now, as his body was destroyed by flames a hundred thousand times hotter than his body could withstand. There was a sadness in his eyes, because he was not entirely in favor of dying, and also his favorite hat shop had just been burned into ash and the ash burned into its component subatomic particles. But he approached the edge of the cliff of VeXork Mons with his arms still spread, as though he might fly, or command the plasma, or conduct it, or absorb it, or be killed all the more quickly by it as stray wisps of the stuff disintegrated his outstretched limbs.

With a pang of regret that no one would ever be able to buy a hat from DrimpleÅfs Hat Emporium ever again, and also that the entire universe was being destroyed, he leapt from the edge of the cliff, and the sea of plasma rushed up to meet him.

Then, between eight and eleven-and-a-half seconds later, there was a sound like a balloon being popped inside your skull, and Izzy Oz found himself aboard a blueish-gray spaceship traveling at three-quarters speed away from his home planet of VeXork.

.

.


The captain headed the welcoming party, which in fact consisted of all those people mentioned before, and also a security bot, which was basically a gun on wheels with a brain the size of a soup cracker glued to the side.

ÅgHo,Åh said the captain as he swerved sideways into the teleporter room, where Izzy was just getting up after having been teleported mid-bellyflop onto the floor.

ÅgHi,Åh said Rud, just behind him.

ÅgEr,Åh said Bill, behind him.

ÅgListen, just whatÅ\Åh said Sharie, who was cut off by the security bot, which entered the room, said ÅgINTRUDER!Åh and opened fire.

The captain dove sideways out of the path of death, Rud dove forwards to knock Izzy off his feet, Sharie dove backwards to push the security bot back into the hallway, and Bill dove nowhere in particular because it seemed to be the thing to do all of a sudden.

ÅgShip!Åh shouted Sharie, holding the clumsily struggling security bot, ÅgShut off the security bot! Now!Åh

ÅgHIS SOMNOLENCE SHALL BE SWIFT IN ITS DESCENT.Åh

ÅgJust do it!Åh Sharie said, but the security bot had already quieted and was now Ågsnoring,Åh which is the sound machines make when in standby.

ÅgWelcome aboard!Åh the captain said, cheerfully, as the smoke cleared. This was not only proverbial, as the volley the security bot had let loose had burned a three-foot hole in the wall behind Izzy and Rud, and the melted metal was still smoking.

ÅgUm, what. . . Åh said Izzy. Rud got off of him and he got to his feet awkwardly: the artificial gravity on the ship was somewhat weaker than the gravity had been on VeXork. Izzy looked around, and swallowed. He saw the man who had jumped on top of him, heavy-set and out of shape, breathing heavily from exertion or excitement. He saw the captain, easily identified by the pointed gray hat with the Octuple-U insignia of the acting Gray Space military fleet, and easily identified as a member of the Yumika race by his two noses, a race well-known for not ever having names. He saw the small manÅ\very small; part Vrillian, perhaps?Å\who was now rubbing his foot where he had hit it during all of the confusion. Finally he saw the woman, which was significant because he had never seen a woman before. He was also aware that an attempt had been made on his life, apparently from the direction of the doorway, though all he saw there was the woman, rubbing her arm where she mustÅfve hit it.

ÅgThis isnÅft hell, is it?Åh said Izzy, frowning.

ÅgNot quite,Åh said Rud and Bill together, while Sharie muttered something else. The captain raised one eyebrow.

Åg. . . But itÅfs not heaven,Åh Izzy continued, shaking his head. This time Rud and Bill stared at each other, bemused, while Sharie and the captain snorted for different reasons.

ÅgThis is a ship,Åh said Izzy. ÅgWhere am I? Was I teleported here?Åh

Rud said, ÅgYeah, this is a ship, and yeah, we teleported you here. It looked like you werenÅft going to be around much longer on that planet.Åh

ÅgWhat ship is this? I see youÅfre an Octuple-U captain.Åh He gestured to the captain.

The captain drew himself up a bit. ÅgHey, good eye, there. IÅfm the captain here, donÅft ask the name Åecause I donÅft have one. This is the, uh. Ship, what are you called?Åh

ÅgIÅfM NOT SURE.Åh

ÅgShip, what are you called?Åh asked Sharie.

ÅgMIQUE-TYPE, VRILLIAN DESIGN, HEAVY RECON CLASS, SPECIAL EQUIPMENT, SERIAL NUMBER HAJS-HASJ, COMMISSIONED BEFORE THE THIRD AGE OF THE WORLD, BUILT THEREON BY THE VRILLIAN KING GREDERICK ATOP A MOUNTAIN OF HIS ENEMIESÅf BONESÅ\Åh

ÅgThank you, thatÅfs enough,Åh said Sharie, while the captain grumbled about his own ship not responding to him.

ÅgA Mique...Åh Izzy frowned, thinking. Then he shook his head. It was probably nothing. He said, ÅgWell, I certainly didnÅft expect anyone to be out here to catch me, as it were. IÅ\Åh he coughed, ÅgI probably deserve to die, and I was ready to, but IÅfm grateful to you for saving me.Åh

ÅgHey, no problem,Åh said the captain. ÅgI think itÅfs in the rulebook somewhere, saving people when you can. Here, IÅfll get you a drink, you look terrible.Åh

ÅgIÅfm Xorkian,Åh said Izzy, coldly. ÅgI always look like this.Åh

There was a rather scaly silence, and then the Xorkian laughed.

ÅgYeah, no, I really just havenÅft had a shower in days. My nameÅfs Izzy, by the way.Åh

The captain laughed too, and he lead Izzy and the others to the shipÅfs dining room, Sharie making Rud and Bill drag the disabled security bot with them so she could take a look at it and try to figure out why it had malfunctioned and shot at Izzy.

ÅgSo what were you doing on VeXork?Åh said Rud, as the captain put out a number of simple plastic glasses and filled them with simple colorless liquids.

ÅgI told you, IÅfm Xorkian,Åh said Izzy, taking a swig from his glass without looking at what was in it. He gasped, choked, tried to breathe, couldnÅft, staggered backwards, and fell against the floor, coughing and hacking, his face red. He struggled back to the table and slumped into the chair offered to him by Rud. ÅgI lived there,Åh he finished.

ÅgWhoop, I think I gave you mine,Åh said the captain, leaning over to look in the XorkianÅfs cup. He moved to switch the two glasses, but Izzy put his hand up, saying ÅgNo, I think I can handle it, now that I know whatÅfs coming.Åh

He couldnÅft, and this time Bill had to leap behind him and keep him from cracking his head against the counter. With Rud and the CaptainÅfs help they hauled him back to his chair and took the glass away from him before he could take another sip.

ÅgGood stuff,Åh he muttered, after he had more or less recovered.

ÅgDid you know you were the last survivor on your planet? In your whole system?Åh said Sharie, one hand still fiddling with the security botÅfs machinery.

ÅgYes, well, I mean, I sort of assumed I was. I wasnÅft sure about the other planets, but VeXork Mons is the highest mountain on VeXork, so I donÅft see how anyone else could have been alive.Åh

He sipped his new drink tentatively, but it seemed okay.

ÅgSo you knew about what was happening? That everything was getting burned up?Åh said Sharie.

ÅgYeah.Åh

ÅgI mean, everywhere.Åh

ÅgYeah.Åh

ÅgI mean, this entire edge of the universe.Åh

Izzy nodded. ÅgItÅfs a form of light, I think. Light can be either wave or particle, but thereÅfs some light now thatÅfs sort of something else. ItÅfs like plasma. And it moves through floopspace, so it gets places faster than it normally would. As far as I know itÅfs not going to stop.Åh

ÅgThereÅfs nothing we can do to stop it?Åh said Rud.

ÅgWe? I donÅft think thereÅfs anything a team of Jurna scientists with a moonful of supplies could do. We canÅft do anything. Not unless youÅfve solved the nullspace equations.Åh He laughed at this last unserious remark.

Silence descended ominously on the group. Izzy continued sipping his drink, and the captain said ÅgHooormÅh thoughtfully.

ÅgItÅfs just going to keep spreading?Åh said Rud.

ÅgYeah, until it gets everywhere.Åh A dark look came over Izzy suddenly, and he shuddered.

ÅgDo you know where it came from?Åh said Bill, quietly.

ÅgYeah. It came from the quasar, Xork. But itÅfll sort of reflect off the planets and stray matter in the system until itÅfs coming from everywhere in the system.Åh

ÅgDo you know what started it?Åh said Bill.

ÅgUm, yeah.Åh Izzy coughed. ÅgErm, I did.Åh

The silence returned and started filling up the room like millions of burning hot golf balls: very uncomfortable, but still novel enough that you sort of hang around to see whatÅfs going on.

ÅgOh,Åh said Bill.

ÅgHooorm,Åh said the captain again.

ÅgWell,Åh said Rud.
