* ZERO ― UNINTELLIGIBLE BITS
 Without a business suit, it is difficult to sneak into a meeting of the top executives of an oil company. This was a fact rapidly becoming clear to Jennifer, though she was also holding onto the opinion that it was because she was a woman, and they just wouldn’t assume a woman would ever be an executive, the sexist pig peanut-butter-eating bastards.
 Pam was with her,

* ONE ― THE THING IN THE OLD MANSION
 "The juice is loose!" cried Sgt. Femberly, running in a rather staggering way across a field of grass that was littered with broken bones and old magazines. His comrades, all that was left of his platoon, seven brave men, wondered at his words. Staring, they almost missed the quickly increasing shadow of a great bulk hurtling towards the ground.
 It was a big thing, that bulk, yes; big and wet, and carrying a smell like wet, furry socks twice burnt. It was a bear, though Pvt. Hip, quite incorrectly, before the thing fell on him. Yes, yes; that was always the way.
 Femberly looked but only once, seeing the thing making a second leap to crush Pvt. Edwards, and Pvt. Bender's hands coming off. It turned its head quickly, fixing a single eye on him, but probably it didn't see him at all, on account of quite an astonishing number of cataracts.
 Femberly ran out of the courtyard into the old mansion, and out of the old mansion onto the old street, and from the old street he ran towards the old city until his feet were completely numb, and he collapsed in a heap. He lay there for a second, considering sleep, then rolled over madly, pointing his empty and damaged and completely useless rifle around, but there really was no point. There was a long stretch of time, and then he groaned and waiting neither patiently nor impatiently but dreadingly as the monster, well okay not monster but thing, large thing, very oh very large thing, came around the side of the old mansion, ran as though in slow motion (for its stride was ten feet or more) down the old street until it came to where he, Femberly, lay.
 The thing, with skin like wax, body like giant grasshopper, lowered itself to the ground beside him and stared. Then it nudged him over, and again, lifted his limbs in succession, and disposed of his weapons (the rifle, a pistol with three shots left, and a newly sharpened antique Civil War bayonet). Femberly had no strength to protest, and only put his hand on one of its long legs. He pulled at it, plaintively, and the thing nudged him again. Then it shook, stood, and went down the old mansion into the old street, away from the old city, and most certainly away from the strange little harmless Femberly.

* TWO ― PANTHERS AND CITY COUNCILS
 City councils are not very well known for their complimentary snacks, and the reason for this is a thing only occasionally guessed at (very rarely correctly) by those who never attend them, but even as well by those who do, who, being themselves blinded by the various goings-on at such meetings, the plans planned and the votes voted and the vicious tirades viciously tiraded, either about the grass or the cows or carved trolls or the vagrants or the feral troubadours, these people, being blinded―blinded metaphorically, though in at least one documented case literally―by these things, found (or would have found, had they been given reason to search) that it was not really theirs to understand the actions of such people at such events; no, that was for others, those who had the time and the energy to decode such things, to spend long hours in the middle of the night when their favorite shows were on not watching the shows but listening at a tap-wire or chasing message-cats or decoding cryptically cryptic cryptograms (like math; like numbers; like the luminescent and frightening lattice-work of mathematics; so they said) to discover the meanings at the base of such events.
 "This is reason enough to avoid city councils: wild panthers. But there is another: tamed panthers. The wild panther is like a lightning strike, like a lightning strike whose electricity is teeth and whose crackle is a growl and who is in fact a large cat, and the wild panther comes when unexpected; the wild panther that cannot be predicted, either when it comes or what it will do when it arrives there. It may kill, oh, of course it may. But then, it may not."
 "I know that much. I did work at a zoo."
 "That's true. I remember that. Yes. But you were mauled, I remember that, too; you were mauled on your second day."
 "That was a mistake by the papers. I was actually malled. I was literally hit by a mall."
 "How exactly is one hit by a mall?"
 "Very, very extremely hard."
 "That would make sense. But. But! But tamed panthers, tamed panthers are something else entirely. A tamed panther comes when expected―not when you expect it, but when someone expects it, you can count on that. You can set your watch by that."
 "That seems unlikely."
 "A wild panther is, like Chesterton said, a bomb in the neighbor's pocket."
 "Bradbury."
 "Exactly. He knew. I assume you read The Panther Chronicles?"
 "No. No, I didn't."
 "Yes you did, I gave you my copy."
 "You gave me your original copy. The copy you wrote by hand. And spilled things on. It reeked."
 "You never gave it back! It's been a month. I assumed you were reading it."
 "I took it to a cheap motel to read it, but the manager was obliged to destroy it when its scent started damaging some of the other tenants."
 "I wish, oh how I wish, that I were surprised by that."
 "You're not?"
 "I am indeed and in fact not."
 "What did you write that in, anyway?"
 "It's amazing the many ways you can make ink when you enlarge your definition of the word ink."
 "I imagine it is."

* THREE ― HATS
 "There is no time when it is not appropriate to wear a hat." That was Higgins. He was always saying things like that.
 "That can't be right. I am quite sure that that is not right. What about church?" That was Blint. He was occasionally saying things like that.
 "You have a problem. Do you know what that problem is? Perhaps you do not, and accounting for this possibility, I am going to inform you of it: Blint, you have not yet an appropriately large and flexible definition of the concept of a hat in your mind."
 "I prefer my mind to be in a hat." (This being clever, as the mind resides in the brain, the brain in the skull, the skull in the head, and the head, rather loosely speaking, in the hat, not to imply that the hat is loose-, and thus ill-, fitting, but rather that it would not be very difficult to come up with a rational argument why the statement is not precisely true.)
 "A hat is what goes on your head. Sometimes that's just what it sounds like, a hat; sometimes it's your hair. Now, we all have hair, I mean most people have hair on their heads, they have some, you and I have some, that guy does, most of us do; but it's not always our hat. Likewise you can wear a hat and it not be your hat. You can walk into a store― at hat store― and buy a hat and pay for it and put it on your head and it fits, but it's not your hat. A hat is that which you use to complete the whole of your being, the top of your being; it is the lid for your soul."
 "You said that other things can be hats? Such as hair?"
 "Yes, yes; the hair can be a hat. For some, naturally, though others may require a better haircut, a knowledge of how to prepare their hair, that sort of thing. . ."
 "What of bald men? Do they have no recourse other than a hat for a hat? I mean, a hat-hat? A hat that most people would describe as, 'Well, that's a hat!'?"
 "They do, but it's more difficult; difficult to understand. It's really an issue of how they hold their head, what that does to the air above them. You can hold your head in such a way as to shape the air above it. Not in the shape of a hat, mind, but in the shape of, as I said before, if you were paying attention, a lid."
 "A lid for the soul," he added, and Blint joined in, being often able to anticipate and match Higgins' comments.

* FOUR ― THINGS FOUND IN A HAMPER LYING ON THE BOTTOM OF A DRAINED RIVER BY A YOUNG MAN
 First, a toothbrush; a yellow thing, and disgusting.
 Second, cardboard box of toothpaste, as though to validate the First; but the tube was gone.
 Third, a hand; or maybe it wasn't a hand, maybe it only _looked_ like a hand, maybe in was a rubber glove knotted and filled with jam.
 Fourth, a bowler hat, mauve. Not many people know they make mauve bowler hats. If you think about it, you will realize they must, as enough people have been alive for enough time that probably every type of hat has been made at least once in every color; but few people take the time to think of this.
 Fifth, a chair, but a small chair, like something a doll would sit in. Not even a doll; a figurine, a figuring of glass. The chair was not glass, though, but wood.
 Sixth, nine pennies. No more, no less.
 Seventh, a box of snake food, plastic, sealed, water-proof, well within the limits of its expiration date. But this is a fraud; snakes don't eat snake food, they eat mice, or birds, or other snakes, or eggs; not snake-food. Sooner would you find a fish license than that.
 Eighth, the plastic top to a tube of salty chips.
 Nine, the chips themselves.
 Tenth, a tenth penny, no different from the rest, except the difference we give it.
 ―That is what there is; the thing we give; the difference we give; the difference born of the difference atween you and I; the relationship between the storyteller, and the storytellee. But where was I?―
 Eleventh, a switchblade, stained with mud. Probably it was the weapon used in the murder of a mudman.
 Twelveth, a jigsaw puzzle, entirely complete, but very soggy.
 Thirteenth, and old man; he was completing the jigsaw puzzle.
 Fourteenth, a novel, stream-of-consciousness, pedantic, lurid, boring; stream-of-consciousness in the style of Joyce, or at least attempted so, pedantic in its technical language, lurid in its adjectives, boring in its remarkable lack of motivation in the the main characters. It just wasn't a good novel.
 Fifteenth, some cereal, actually quite tasty. And,
 Sixteenth, a walking stick, a shapeless thing, made even more shapeless by its shattered head. Wood does not shatter under water. Or, it does, but not properly, not quickly; it bends too much. This walking stick had splintered as in an explosion, but probably it had not been an explosion; probably it had been someone's head.
 Everything was wet.

* FIVE ― A DISAPPOINTING REVELATION
 Having passed through the sandstorm, finally, and having passed through the rest of the desert on the back of a particularly vile camel, and having seen the sun set like a glob of butter, and having blisters on her ass and little water, Jennifer was not entirely surprised when the bar she entered immediately caught fire. Things like that had been happening constantly, regularly, for the past month at least, and always when she was tired. Sam was convinced that it was a combination of psychic abilities and a negative outlook on life, and told her this very often. Jennifer appreciated the honesty, but not very much.
 So she sat outside the burning bar, uninterested by the different colors found in the flames of different alcoholic drinks. Her camel, Ed, walked slowly from the burning building until he was beyond the reach of the heat, and lay down again. She pulled a deck of cards from her hand. Oh, how she hated cards. Cards were not a thing to help. Cards were not a thing to provide catharsis. Cards were not a thing that you pulled out after exiting a burning building―yet she did. This was what bugged her, exactly what bugged her; she saw these things in herself, these irrational decisions, these things that she did, unable to control herself. It wasn't even that, though. That makes it sound as though they were caused by irrepressible urges. What it really was was that she had no urges at all, not even the motivation to do something logical. So she fell back on a default, any old standby, any one of the many (very many) skills she had mastered over her lifetime. One was cards. Card-counting, mostly, but she new some fancy folds and juggles and passes and palms and shuffles, as well. It had proved useful on more than one occasion. Actually, it turns out you can make a lot of money from the yokels in the desert if you know a good Three-Card Monte― or if you know the Monty Hall problem, and are prosaic enough to make into a question that you can place bets on. Granted, that's a harder one, as most people are hard enough to convince of the actual facts of the Monty Hall problem, let alone those who stand to lose money if they're wrong.
 It was true, though, what Sam said; these things, these sorts of things, odd things, bad things, happened around Jennifer, always when she was tired, always when she was upset. Once in college, after staying up all night studying for a test, and arriving to the classroom to late to actually take it, all her classmates' eyes turned to wood; twice cars had exploded when she failed to get her morning cup of coffee, and (if she could recall correctly) a late night with a mediocre date had led to the death of almost three small house cats in an accident which to that day was difficult to classify as either electrical or fire. The official report said "Acts of God," but her insurance company was a budget one, and that's what it called most things. It actually did cover almost everything, but covered it in the sense what, if you had an accident, a fat man named Lars would drive over to your house in an old jalopy, carrying a briefcase containing duct tape, aerosol oil, a ball peen hammer, an electric torch and a book on hypnosis, and he would trying to fix whatever problem you had. This was questionable. Once, faced with a dead dog, he had hooked her up to a live current and actually succeeded in bringing him back to life for a full forty-eight seconds, although it was completely black and made a noise like a bark fed through a blender.
 After a time, Sam rode in from the blurry distance on an electric skateboard and stopped next to her.
 "Hey," she said, as usual. "Rough day?"
 "Not bad. Not bad." She took the water Sam offered, grateful. "Well. I've had better. There was― have you ever tried to argue with a camel? It's―"
 "Yes, once."
 "―It's― yeah, it's not easy. It's, I mean, okay, they're not going to _win_ the argument, no. No, they're not going to do that. But you know what? _Neither are you._ It doesn't work that way. Winning an argument means two things: first it means being right, or at least, arguing better; and you can't argue better than something that's not arguing. The mad hatter was just fucking wrong. You can not have more tea if you have not had any to begin with. The other requirement for an argument is for the other person to cry. That is very, very important. Camels, however, do not have tear ducts. Did you know that?"
 "I'm pretty sure that camels have tear ducts."
 "No, no they don't―"
 "I'm actually fairly certain―"
 "No, no, shut up, shut up."
 "You shut up, listen, they're mammals, aren't they?"
 "That's open―"
 "That is not fucking open to debate. They're mammals, and mammals have tear ducts."
 "Fine."
 "Did you know that cats' tear ducts, they cry clear tears, but they dry black?"
 "Really? I have never noticed that."
 "Yeah."
 "Okay. Anyway, even if they have tear ducts, it's very difficult to make a camel cry. You have to tell it a sad story, but not just any sad story, a sad camel story. And I mean, you can. . . you can tell a sad story involving camels, even a story in which a camel, under sad circumstances, dies, but that's not necessarily good enough. Camel's appreciate honesty, they appreciate irony, they appreciate the unbeauty of things going wrong and bad on a cosmic scale. They're like that. It's the humps, I think. They're affected by the bigger things."
 Just then, the desert exploded.

* SIX ― DURDLEHOPPER
 Without warning, the larger of the fifty-seven balls of wrought iron came unloose from its chain-bindings and came skittering across the top of the battleship like a rock skipped on water, water filled with easily-crushed man-shaped water-bugs in its way. The great and horrid monstrosity finally went over the edge of the battleship and, before it could reach the shoreline, where it would probably have crushed many more people, it fell short into the water and sank with a quickness that nearly belied its great bulk―nearly, because it was difficult to be bellied anything of the like when faced with such an enormous circular tidal wave as was caused by its impact in the water.
 The iron ball sank quickly into the depths, rolling along the steeply-sloping sea floor some few hundred feet from the shoreline. It traveled for really a very significant amount of time before going off of an enormous underwater cliff and over an enormous underwater canyon, in which an enormous underwater undiscovered inhabited city, like an aquatic Atlantis (but aquatic in the sense that its inhabitants lived underwater, not that they had lived above-water but whose city had sank and who had all perished as a result). The denizens of that fair place looked up to see the cause of the enormous shadow that had appeared in their city. Now, the shadow and the looking were not precisely what we call them, as there is not nearly enough light to see, that far down, and the non-Atlantis underwater people didn't have eyes anyway, or again, not as we understand them. What they (and they were called Durdlehoppers) had in place of eyes were eye-shaped and eye-colored little spheres which resided in what in a human being would be their eye sockets. These organs, which they simply called eyes, "saw" "light" in the sense that they felt the vibrations of a strange substance that was either wave or jelly, and reacted to and could be obscured by physical objects in much the way that visible light can. Actually, it's probably somewhat easier all around if one just assumes that their eye-analogues were just pretty much eyes. But they weren't. But just so long as you understand, semantically, rationally, technically, that they're not eyes, not actually, then you can go along your pretty business acting as though they were eyes, and acting likewise as though your thoughts corresponded to a viewpoint which asserted (in correctness) that these above-mentioned non-eyes were, in fact, in opposition to the facts of the matter, eyes.
 The great stone bounced off the opposite cliff, rolled back on the city, and crushed every single Durdlehopper except one, who died of shock upon seeing his city destroyed.
 I say that it was all but one Durdlehopper who died in the crash, but really, there were two survivors, counting the one who immediately afterward suffered a severe survival-failure: the other, a Durdlehopper by a name the closest human phonetic approximation of which is Bil, wa sat that point getting very angry at a slot machine in the Lucky Seven Floating Casino in the water just off California. He was getting very particularly mad at it as it had just eaten all of his money. Not metaphorically or symbolically, either; rather, it was really a vicious money-and/or-flesh-eating monster disguised as a slot machine, and it had, as mentioned, just eaten all of Bil's money, but not only that; his left hand and his right thigh had both been lost to the thing. Now, Durdlehopper limbs grow back remarkably quickly, sometimes in just seconds, so this really wasn't such a setback to Bil; however, the loss of twenty-seven whole dollars is rather a great blow to the average Durdlehopper, who is lucky to find a job that pays a half-cent every other day. Bil didn't have a good job, or in fact any job at all, but rather had stolen the money from an old lady, after spending the past two years getting up the nerve for, and planning, the perfect heist, and then enacting it.
 It turns out that the perfect heist was taking the money out of the old woman's purse when she was looking another way, after calculating just how much money to take and when to take it so that, upon next checking her available cash, she would assume nothing out of the ordinary―she being a bit slow in the head and used to losing things and being wrong about things, especially numbers, and especially money, and especially especially numbers (that is to say, quantities) of money. Even multiple moneys.

* SEVEN ― FREDERICK THE WISE
 Holding the shield high above him, Frederick the Wise launched his body across the battlefield, feeling the dragon's flames which, even through the elf-forged barrier, singed the hem of his cloak. Actually, it probably wouldn't be long before the edges, and then the sub-edges, and then the sub-sub-edges, and so forth, of the shield began to melt. This was really what you would call a pretty serious problem for Frederick, as that constituted just one or two "subs" away from his wrinkly, vulnerable fingerflesh, which he was more or less fond of and appreciated possessing in a non-melted-and/or-scorched-to-ash state. Actually, he was a perfectionist, and even had the gall to prefer them not to be burnt at all. Jeez, what a jerk.
 There is a definite chance that, had he gotten the dragon, Frederick would have made a hopeless gesture and then died (he had not even a weapon with him), but that is not to be known, as he very soon accidentally stepped into a portal from another world, and thus fell into it, that is, into the portal, and thus also the other world.

* EIGHT ― WORDS AND PHRASES ENJOYED BY THE LATE EDGAR GARVIS
 "Cervix".
 That was just because of the sound of it―the sound of it, and the fact that it included both a 'V' and an 'X'. Perhaps he was juvenile, perhaps he was bland, but Garvis really believed in the existence of dramatic or melodramatic or grandiose of such "exotic" letters.
 "Catch-all.
 Not just because he was obsessed with Pokemon. That is to say, obsessed to rather a ridiculous and even dangerous level. Actually he had had to have two intercessions for that alone, three if you count the one for collecting regular cards. But it wasn't just because of this that he liked "catch-all"; partially, perhaps principally, it was because of an erroneous supposition in his mind that any word with catch-all's meaning would, itself, be a catch-all, and able to be used as answer to all manner of questions.
 "Flamage".
 Garvis didn't know what this meant, but liked the image it put in his mind; like, a cross between a French loaf of bread, and a deadly-looking sword. Though relaly, in all fairness, any sword that was partly a French loaf of bread would probably not be very usable as a sword, and any French loaf of bread that was partially a sword would probably not be very useful as a French loaf of bread, but that is such a nitpicky issue of unnecessary minutiae that the author refuses even to mention it.
 "Bestiary".
 If you began thinking bad thoughts upon reading that, you sohuld know that you are a reasonably terrible person. In any case, he liked the word both for the way that it sounded and for its meaning, for the image or the idea or the concept of a room, maybe a large room, but a large complex of large rooms, or even a small (probably cramped) room, simply filled with beasts; that is, animals, monsters, and so forth. Garvis considered all animals beasts and all beasts monsters and all monsters mustard, so that made his life pretty interesting.
 "Wretchedness".
 Dunno about that one. Just the combination of the meaning with the repetition of the 'S's at the end. Brilliant, is what Garvis tended to think about that. Brilliant.
 "Awa'".
 That's Scottish in origin, at least, that's what Garvis thought and was pretty sure of. He had heard it in a song once, a song played by two middle-aged men in large beards with thick accents that made jokes inbetween songs and were eventually chased out of the pub by the manager when it became apparent that they had already consumed more alcohol than they could pay for even if a third of the population of the city showed up at the bar, payed the cover charge, and also ordered bottles of wines made of diamond bricks. But in spite of all this (or perhaps due to it), they really were very talented singers and songplayers, good bards, and just interesting and entertaining people. Anyway, Garvis had heard the word in one of their songs. Probably one that mentioned Bonnie Prince Charlie, whoever the old codger was. Probably a lunatic.
 "Mary".
 Not the name, but the verb, regarding matrimony. Actually, Garvis liked it because it was also a name; he liked it particularly at the beginning of sentences, where it was capitalized, or in titles, where it was in all-caps, and thus intistinguishable from the feminine name. Garvis loved, absolutely loved, indistinguishability.
 "Primordial".
 Mostly, though, he just wanted what mordial was.
 "Screechingly".
 This is how Garvis' wife said most things, and yelled and cried and whispered most things, for that matter. At least, that was the fact of the matter if you got Garvis drunk, or sober, and asked him to comment on how his wife said things, and also took his word for it, all of which were fairly unwise courses of actions to take, and difficult to boot, considering the fact that he was quite dead.
 "Infuriating".
 This was how Garvis felt whenever another horse-drawn carriage pulled in front of his sedan. Actually this happened with surprising regularity; probably it didn't help that he lived in Amish country, or that his sedan had ran out of gas ages ago and―gas being up to thirty-nine dollars a gallon, now―his sedan was itself being pulled by horses, that is to say, ponies, that is to say, miniature ponies, that is to say, over a hundred miniature ponies. But hey, a sedan is pretty heavy when it's made of iron with iron seats and an iron steering wheel and gold windows and a fat driver and passenger.
 "Enliven".
 As opposed to zombies, which, Garvis supposed, were "endeadenned", or something like that. Actually, now that he thought of that, that didn't make sense. Didn't sound quite right. Probably it didn't matter too much, though, Garvis being dead and all.
 "Chthonic".
 This is just a great word. Try it out sometime.
 Just then, all of those words exploded.

* NINE ― A SENTENCE
 Hold it―that's it―just there, just beyond the window out of which you can see the black and red smoke rising from the burning once-grand village of the king's son's countess' second cousin, but not so far off to the side that you lose sight of the long, long stripe―they chose a stripe because they couldn't get a chevron that was big enough (supply and demand)―which runs the length and breadth entirely of the airship, hold it there, there, there so that the light of the setting sun (as it brushes against the oddly-purple hue of the poisoned sea), when it juts through this window and that one and that one (see, you can see how they're set up, so that it goes so, just so), when it shines off the large circular mirror in the Captain's Hold and the small rectangular one in Sick Bay and the triangular sharp-edged one hanging from the ceiling in the Galley, hold it right there so that that sunlight shines against the prism in the middle of the room, that is to say, the prism gotten from Fletcher, Fletcher the thief, Fletcher the scoundrel, Fletcher the courtier, Fletcher-Won't-You-Come-Back-Home, yes that Fletcher, the prism he got in a heist from a giant factory while being pursued by the shattered ghost of his long-dead nemesis and head of the special police force Jock Brich, the prism that was once the jewel in the great monster's headdress and once the jewel in King James' priceless electrum fedora and once even the end of the staff of the faux-wizard (the pseudomage, the mock-warlock, etcetera) Glimmerglen, hold it, that is to say, the pedistal, hold the pedistol so that the light from that sun peeks through those windows and over and against those mirrors and against that prism― but, carefuly, not to hold it so high that you cut off the air supply from the East side of the ship () to the West ()
