* Chapter 1: The Suit of Armor

Joseph Benedict Kennedy slumped against the dirt wall of the tunnel. The firelight from the torches he had placed along the walls made the shadow of his tired body jitter on the ground to his sides. There had been torches in the sconces when he came down, if you could call them torches - and if you could call them sconces. Desiccated and charred bits of wood stuck into rudely struck piercings in the wall; they looked like they had been put there with nothing more than a hammer and a spike, which they probably were. The newly-placed torches, good wooden rods covered in rags torn from the clothes of the many ancient bodies upstairs and soaked in pitch from the big barrel that Joseph had dragged in his wheelbarrow from the nearby town. It felt wrong, even obscene, to strip the dried skeletons, but necessity made light of objections, and the torches made even more light. The cloth was good, and though much had been eaten by rodents and moths, what remained was in better condition than Joseph had expected.
	Joseph Benedict Kennedy raised his head just enough to look back down the distance of the tunnel he had just covered, with torches placed every now and then; he put as much space between them as he could, to make them last, placing them just close enough that he could rely on them to get back out again. His eyes had been lulled by the repetitive motion of walking through the tunnel, squinting into the darkness, and wrestling torches into and out of the holes in the walls, and when he had sat down, his eyes thought they still saw the movement of his walking. Now, looking back down the tunnel, the length of it struck him softly, making his fingertips tingle. He saw, also, the thing that Cedric had seen, and Treverst as well: the tunnel was rounded, not like a tunnel made by human hands, but like the tunnel of a worm.
	It wasn't evident from walking along it. The tunnel had seen so many feet that the floor had been packed almost flat. But, looking back now, there was no denying the rolling, meandering path the tunnel took, and especially that rounded roof. Time had eroded what must have been, once, an almost perfect circular cross-section.
	Having sat down, the headache and monotony that had settled in Joseph's head seemed to drop, by gravity's pull, through his chest and into his legs, where it showed its true form as a strange mixture of numbness and ache. The soles of his feet, protected only by the thin soles of his shoes (growing thinner by the hour, it seemed), hurt so much that he almost wanted to cry. He told himself that he had to get up again and keep walking, and soon, but his body seemed unconvinced. He rubbed the heels of his hands against his closed eyes, then against his temples. He looked again down the length of tunnel he had traversed, then along the length that he had not, then he shook his head, then he let it loll back and rest against the wall, but only very a few seconds. Discipline prevented him from falling asleep, or even holding too long a position that was likely to allow him to sleep.
	Discipline, or fear. Not that there was anyone else down in the tunnels, no animals, no monsters. But the place itself, the geometry of it, the matter, was dangerous, and like so many places (though not all), it had no mind. It had not even the chaos of some of the other places Joseph had had to go; it had only the deadness of time, and the force of pressure, and many millions of pounds of dirt to obscure the sun. These things were enough to kill, and Joseph Benedict Kennedy valued his life.
	Joseph pulled an old and worn little notebook from his the right breast pocket of his vest and held it in the light of the torch that he was currently carrying with him, and which he had leaned temporarily against the dirt wall. He flipped through the thin, dog-eared, scrawled-upon pages; //careful//, he thought to himself, as he always did when he handled the little notebook, but weariness made it more difficult, and in the back of his mind he knew that in his current state he was more likely to damage it.
	With as much care as he could, Joseph paged past passages of long transcribed thought and diatribes, and found a crude but carefully-drawn and annotated map that stretched across six pages. It wasn't actually possible to tell, logically, with the information he currently have, exactly where he was; there were three distint possibilities, in fact. There were many tunnels, twisting to and fro over the page and through the ground, most ending too soon or too late to be of any use, and the lines drawn on the dirty page almost certainly lacked the sufficient level of detail in the rendering of their curves for Joseph to be more sure. If he had had a compass, he would have known which of the three possibilities he was in, but he did not have a compass.
	Joseph looked tiredly at the map, as he had so many times, and confirmed for perhaps the eightieth time what he had to do if he hit a dead end, and what he had to do if he hit a fork, and what he had to do if he found anything suspicious, and what he had to do now.
	What he had to do now was walk.
	Joseph Benedict Kennedy tried once more to convince his aching feet that he had to get up and start walking again. He failed. Then he got up and started walking anyway.
	
Joseph Benedict Kennedy stood beside a large iron casket.
	//Is it really a casket if it contains no body?// thought Joseph, loosening the heavy belt of tools and easing it off of himself. //Especially if it has //never//contained a body? If it was never even //meant// to contain a body?// He laid the belt on the ground and removed the hammer, the spikes, and the pry-bar. He stuck his main torch into the ground next to the casket ― or the box, or whatever it was rightly called ― then lit another torch and stuck it into the ground on the opposite side. He wanted good light while he worked, but he was unwilling to sacrifice any more torches. He would need just as much light on the way out. More; the return trip would likely take much longer.
	The chamber that held the casket was a dead-end, a room that was little more than a place where the tunnel widened slightly before stopping. It was entirely possible that it had originally continued and joined up with one of the other passages further on, and had only later been changed and collapsed to create this room.
	Joseph stopped what he was doing, frowned, and looked at the wall opposite from the entrance. The light from his torches was anything but plentiful, but it was enough to make him change his mind on that last thought. //No, there's no sign of any collapse. This tunnel never went any further. Anyway, this room is probably almost the oldest part of the tunnel system.// He didn't even let his mind wander over to the thought that, if it had been a tunnel once, then he might be able to dig through and find a shorter way back up than what he had taken down. He had learned long ago, as a very young child, that in an endeavour which required great persistence and patience, even brief glances thrown at the hope or possibility of a shortcut is poison to one's resolve. And anyway, it didn't matter, because he had brought no digging tools.
	It may not have been a casket, semantically speaking, but it was built like one. Joseph scrutinized the seam between the lid and the base all around the width of it, looking for any part that had been weakened or opened slightly by the assaults of time and corosion, or else any place where the vagaries and imprecisions of the box's construction had rendered it less secure. Joseph found neither. The box was expertly made, despite its mundane ornamentation, and the local spiders and such had no interest in it. It was also free from rust, which Joseph supposed meant that those agencies that had created the tunnel and placed the box had been careful to find a place that did not lie under any body of water, or lay so far below that none would seep through. Either that, or they had found a way to treat the dirt ceiling to hold it together, or perhaps some manner of spell to seal the iron against water. The thought of this made Joseph wonder what other things one could ward away from iron, if water could be guarded against so. The though disquieted him. He pressed his lips together and started contemplating what parts of the box would afford him the greatest room for leverage.
	Finally he chose a place to start. He took one of the spikes ― long and heavy and inexpertly finished ― and set the point against the seam between the box and its lid. Then he took up the hammer and started to pound the spike inward.

The shadows cast by torchlight move and change and sometimes seem even more alive than those things which cast them. Enough torches can create enough shadows to fill a room with people, to the tired eye. Enough people that it is not so hard to slip in between some of them without being noticed. Especially if someone is attentive to something else, such as working a long steel pry-bar into the tiny crack that is the result of driving five spikes nearly an inch into the lid of an iron casket.
	"You shouldn't do that," Joseph Benedict Kennedy said to himself, while he grunted and put his weight behind the pry-bar. Then he straightened up, pulled a handkerchief from his pocket, and wiped the sweat from his face. As he did so, he idly noted the three shadows cast by his body. Three shadows. And yet, there were still only two torches. And one of the shadows moved independant of the others.
	All the feeling went out of Joseph's hands, and he jerked his head up to see a middle-aged woman standing beside one of his torches. In his shock, he exclaimed, "What?"
	"I said, you shouldn't do that," said the woman.
	"I thought I said that," said Joseph.
	The woman frowned. She was regarding Joseph's progress, the spikes, and the pry-bar, with decided apprehension. "How long have you been down here, Craid?"
	"I'm not him. I'm not Cedric. I haven't seen him in weeks. I'm here alone."
	She turned her frown to him. "You're Kennedy?"
	"Yeah, Kennedy."
	"And you're trying to open this coffin."
	"I think it's, I think it's a box, really." Joseph had not really cought his breath, either from the work or from the surprise of seeing the woman there.
	"And you're trying to open this box."
	"There's a suit of armor in here." Joseph felt like he was speaking like a child; but he had spoken with no one but himself for almost three days, and it seemed to be the only way he could find to speak at all. The woman said nothing, only continued to frown at him and the progress he was making, so Joseph felt compelled to continue, "It's been here for a while, it's... it's important that I... I'm going to get it out," he finished, a bit lamely.
	The woman frowned a bit harder and said, "You're going to get it out."
	This annoyed Joseph for some reason, but he was still surprised at finding the woman there at all, and between the annoyance, the surprise, and his general exhaustion, Joseph felt like he barely had a handle on the conversation. He decided it wasn't worth it. He put his hands on the pry-bar again and resumed the work of trying to force it under the box's lid.
	After about another minute, the woman said yet again, "You //really// shouldn't do that."
	"Fine," said Joseph, struggling with the pry-bar.
	"No, I mean, you //really// shouldn't. Honestly."
	"Great," said Joseph.
	The woman found a way to frown with her whole body. She said, "Do you know who I am?"
	"No, and I don't really care," Joseph grunted. He was getting no further with his hands, so he picked up his hammer again and started trying to hammer the pry-bar further into the box.
	"I think you should," said the woman.
	"Well, maybe, but I don't. Okay? I really don't. And I don't care why you're here."
	"I'm here to tell you not to―"
	"Oh, yes, yes, I've figured that much out, thanks. Thank you so―very―much." Joseph spoke between heavy swings of the hammer. "You've probably got some great reason, right? Maybe you've rehearsed it? Something I don't know about? Some danger, some angle I hadn't considered? Well, that's great. I hope you enjoyed rehearsing it, because I don't want to hear it. You can just... you can just go home and say it to yourself. I don't need any speeches."
	The woman listened to this without moving. She watched as Joseph put down the hammer and grabbed the pry-bar with both hands and put his weight on it. For a moment, it looked as though he might be successful, but then there was a sort of popping sound and the pry-bar slipped out of the tiny crack beneath the led and made Joseph stumble. Joseph didn't curse, didn't throw the pry-bar or get angry. He simply went back to the box, breathing heavily and wiping his forehead again, and started to check whether he had made any progress, and whether any of his spikes had slipped. After he looked them all over, he decided he needed just a little more room, so he retrieved the sixth and final spike from his little pile of tools on the floor, picked up the hammer again, and started to hammer it into the box along with all the others.
	"Kennedy," the woman said after a while, "my name is Kendra Lovelace, "and I can see you've already made up your mind as to how to react to me, and to what I have to say. But I'm afraid I can't let that be all it takes to get me to leave. Getting down here wasn't easy, you know - as I'm sure you know - and I haaven't come down here for nothing. And I haven't come down here to be told off and then give up, either. I got told what you were doing by Edgar at the bar, and you're not the only one who's been spending a lot of sweat and curses to get here. Buut listen, it doesn't matter. It's not the point is. The point is, this isn't what you want. It's not worth it. This armor can't make you immortal."
	Joseph took a particularly heavy swing at the stake. Then he looked up at Kendra and said, "I'm perfectly aware of that."
	"Nor will it let you kill anyone you want."
	Joseph took another swing. "I know."
	"It won't let you fly, either."
	Joseph took another swing and said nothing.
	Kendra waited a moment, then continued, "it doesn't grant you the strength of giants, and it won't make you unstoppable in a dual. Or a joust. It's not imperveous to fire, it won't let you bend others to your will. You cannot convene with the dead, or with spirits, while wearing it. It is of no assistance in breathing underwater. It possesses no special connection to dragons or animals of any kind, nor to trees, nor riverstreams, nor the wind. Objects touched by the wearer do not spontaneously turn to gold." Kendra waited while Joseph continued to swing the hammer and say nothing. She bit her lip. She said, "You are perfectly visible while wearing this armor. And heavy. Not weightless. And you can't see long distances."
	Joseph persisted in his silence. He let the hammer hang at his side while he examined the stake he had just pounded into the box, then the other stakes. The first one he had put in had slipped almost completely out, so he positioned himself to hammer it back in. He was careful not to look at the woman during any of this, or even acknowledge that he was still aware of her presence. He wasn't tired of her, precisely, but he had little to say by way of defending his position against her, and he wished she would go away. Despite the absolute certainty that this Lovelace woman would not be driven to leave by his ignoring her, he rather hoped that she would.
	She seemed to be thinking. Joseph had hit the stake five times before she said, "You can't sell it, either."
	"Well, I could," said Joseph, against his better judgment. "Technically, I could. I mean, I won't, I'm not going to, but there's no real reason that I couldn't. Nothing would stop me. But I'm not going to sell it."
	"But there's no point in digging it up, it doesn't //do// anything," said Kendra, earnestly. "It can't do any of the―"
	"I know. I know it can't do any of those things. And you left out jumping over mountains, and catching lies in the palm of my hand. I know it can't do anything like that."
	Joseph kept his eyes away from Kendra's, because he knew that she was frowning again, and it irritated him. It was no use; he could //hear// the frown in her next words.
	"Then, why are you trying to open the box?"
	"Because I have a pig to catch," said Joseph	

* misc.
well, you could sell it. but i wont.
but it can't
i know it cant



JOSEPH POV

anthing else?
kendra tried to remember

nor will it kill...
i know
then why
because i need a pig...

then why didnt you want me to...
its social. its economic. everything i said, you can find a hundred people who believe.

...with all you've been saying, I half expected an explosion.
I think that part comes later, she said

hammer the pry-bar




* ?: The Unbroken Little Boy
Thomas Erwan sped along the hallway towards the classroom where his History class had almost certainly already begun. His string of goslings and baby goats followed him intently, weaving clumsily out of the way of passing teachers and walls.
