The Quirks Inherent

* Prologue: The Day the Sky Caught Fire

.

.

Budd Bower looked around at his room of disappointments.

None of them looked back at him.

He sighed, and decided to start at the beginning again, despite the insurmountable evidence that this would yield little.

¡°John!¡± he said, and John jumped. ¡°Where was the disc, the last time you saw it?¡±

¡°It was, ah, it was, on the cabinet in the break room, sir.¡±

¡°The upstairs break-room?¡±

¡°Yes, sir.¡±

¡°And why was the disc on the cabinet in the upstairs break-room? Smith!¡±

Smith, who had made a strained sort of gulping sound when his name had been called, stammered for a moment and then said, ¡°I, er, put it there, er, sir. Er.¡± He realized Budd was going to ask him why he had put it there, and quickly added, ¡°Because, er, because I thought it might get lost if I left it where it was.¡±

¡°You mean, if you left it on the conference table. Where it belonged.¡±

¡°Er.¡±

¡°I might add, at this point,¡± said Budd loudly, addressing the room again, ¡°that we would not have had to relocate the disc to the conference table in the first place had we a functional bulletin board. Jacobs! Remind us why we do not have a functional bulletin board.

Both Jacobs' body and his voice remained very stiff. ¡°I knocked it down, sir.¡±

¡°With a frisbee.¡±

¡°Yes, sir. With a frisbee.¡±

Budd recounted his first days as an employee of United Planetary Holistic Offensive/Defensive Entities, or UPHODE. That was around twenty years ago, right after the organization had been created. Technically speaking it wasn't created, but rather it came about as a result of merging together all of the world's major Planetary Offense/Defense operations. At the beginning it had been a very strict, militaristic organization, which was very appropriate, considering its purpose as sole defender of the planet. Then, about five years ago, after some very important and convincing studies were done concerning left-brained individuals with high IQs and the effect of social atmospheres in high-stress jobs, and suddenly all the shouting officers and tense soldiers had been replaced by guys with wandering expressions and T-shirts with quotes on them. Budd had remained, due to his faith that if there was ever an actual emergency, he would be there to sort things out.

His faith was being tested.

¡°I can only imagine,¡± said Budd after his long reverie, ¡°that it would be foolish to ask if anyone knows where the disc is right now. Not foolish for any reason of importance, mind you.¡± He shot a glance at his audience to make sure they were still cowering. ¡°After all, this is the safety of the entire planet we are talking about here. Oh no, not foolish for that reason. Foolish because, if I do ask this question, I have a feeling that nobody will answer. Since we have determined that the person responsible for this occurrence is in this room, however, I am forced to ask again. Does anybody know where the disc with the backup codes is?¡±

Silence.

Budd waited.

More silence.

¡°Apparently, one or more of you are very forgetful. Allow me to assist your memory.¡±

The other men braced themselves the way a twelve year-old prepares to get yelled at. Budd had already explained the situation several times, and each time it felt worse to hear it.

¡°The vast, vast majority of all of this planet's defensive capabilities are in the hands of this organization. Because of their immense complexity, it would be far too difficult for a small group of humans to control the defenses by themselves. Hence, it is all automated. You tell it to go, it will go. You tell it to fight, it will fight. You tell it nothing, that's exactly what it does. Failsafe control. The machines will never exceed their commands. These commands can only be given by one of two methods. The first method is to go through a maze of security systems, passwords and identity checkers  which require the authority of a majority vote of the planets highest rulers and leaders. The second method is an all-out, last-resort emergency protocol by which one may arm the entire system using a single, totally unique disc.

¡°Something that many people do not know about this system is that it has a downtime. Once a year, for four days, the system will put itself into a much less aware state in order to run self-diagnostics. Due to the massive amounts of security and failsafes built in to the system, there is absolutely no way to activate any part of it during this downtime using the standard method. All the security clearance in the world won't let you do squat. For those four days the only way to activate the system, should the need arise, is the disc.¡±

Here comes the important bit, thought the men.

¡°The fact that we are aware of sentient races in this galaxy other than our own is the original and continuing reason that this organization exists. We are here because we have always known that there is some chance, however small, that such races may threaten us. During the past few decades, we have only received the barest of messages from extra-terrestrials. But last night, we got something I  don't think we can ignore.¡±

Budd gestured to the array of computers that lined the wall of the conference room. Some of them had been forced back into working order, but many of them still said the same thing they had for the past few hours, the same thing that appeared on computer and television screens around the entire world.

The message went like this:

MAY YOUR CITIES BURN WITH FIRE AND PLASMA. MAY THE DIRT RISE UP AND SMOTHER YOU. MAY WATER DESCEND UPON YOU AND FILL YOUR LUNGS. MAY THE AIR TEAR AT YOU AND DESTROY YOU. MAY THE MOUNTAINS COLLAPSE UPON YOU AND BURY YOU. MAY YOUR SHELTERS COLLAPSE AND LEAVE YOU TO DIE. MAY YOUR VEHICLES FAIL AND FALL TO PIECES BENEATH YOU. MAY THE GROUND SPLIT AND SWALLOW YOU. MAY THE SKY REIGN STONES UPON YOU...

It went on for a while.

Innumerable attempts had been made during the first hours to reply. Questions, pleas for mercy, and threats were thrown at the unknown beings, but their message never changed. When astronomers scanned the source of the transmission, they saw an enormous fleet of interstellar space craft, bizarre alien things, apparently armed for war.

The men in the conference room then remembered that that was not the important bit. The really important bit was just coming up.

¡°By all our calculations, we have around six hours before the aliens are close enough to attack earth,¡± Budd said. ¡°The fact that this is happening right in the middle of the system's downtime is a regrettable coincidence. Regrettable, but unforeseeable.¡± He paused for effect, and the effect was astronomical. ¡°The fact that during this time we have also lost the only other means by which the system may be activated, because of a Frisbee, well, I'm not sure there's even a name for that. Irony doesn't go that deep.¡±

The men remained as silent as ever. Yes, that was it. That was the important bit.

His speech over, Budd though about what to do next.

¡°Marcus, you still say you saw the disc on John's bag?¡±

Marcus coughed, hoping that that would be enough of an answer. Budd glared at him, and he decided it probably wasn't.

¡°Ah... I think so, sir.¡±

¡°Did you see it or did you think you see it?¡±

¡°I, um, saw it. Yes, I definitely saw it. There.¡±

¡°On the bag.¡±

¡°On the bag. Uh, sir.¡±

¡°John, you definitely didn't see the disc when you picked up your bag, correct?¡±

John nodded.

¡°Can anyone think,¡± said Budd, ¡°of any reason someone would remove a disc labeled system transcripts from John's bag?¡±

There was a soft sound, like a frightened mouse, which came from Smith. Budd immediately disliked the sound intensely, because instinct told him that it had something to do with the rules concerning the backup disc, which he also disliked intensely. The rules included that the disc be given an inconspicuous label and kept in an inconspicuous place. The only rule Budd was really in favor of was of keeping the disc in a place where it could be monitored by the security cameras, and that just happened to be the only one that had been broken.

¡°Smith,¡± Budd said quietly, ¡°you are aware that the backup disc's label reads 'system transcripts,' right?¡±

Smith gibbered.

¡°Smith!¡± said Budd.

¡°Er,¡± said Smith, ¡°I do, er, recall, er, being told that, yes sir.¡±

¡°You recall being told that.¡±

¡°Er.¡±

¡°Some time ago, I imagine.¡±

¡°Well...¡±

¡°Long enough ago that it might've, by chance, slipped your mind at some point or another?¡±

Smith swallowed. ¡°That is... a definite possibility, sir.¡±

Budd silently counted to ten so fast that he might as well have counted to two.

¡°Do you know where the disc is, Smith?¡±

¡°I, er, moved it, sir.¡±

¡°Where did you move it?¡±

¡°To, er... well, I thought it was just a useless copy. And you're always getting after us when we have a messy office...¡±

Budd's voice was very quiet. ¡°Where did you put the disc, Smith?¡±

¡°In... in the trash...¡±

Budd put his face in his hand.

¡°...sir,¡± finished Smith.

Just then the alarms started going off.

¡°Well,¡± said Budd, without bothering to look up, ¡°it seems that they've arrived.¡±

.
.
.


Budd and the others stood outside in the fading sunlight. There were large, angular ships hanging lazily in the sky, with bright rays of energy streaming from them. They could hear the sounds of distant explosions.

¡°Smith, you're an idiot.¡± said Budd. Smith mumbled his agreement.

They watched as a nearby office building wobbled and fell over. The ground shook.

It was the same story everywhere, according to the radio. The alien armada had spread itself over the world's most populated areas and began to systematically destroy them. What little defense could be thrown at them suggested that they were not indestructible, but without the UPHODE's support, it really didn't make much of a difference.

¡°You see that apartment building over there?¡± said Budd, pointing it out. ¡°I happen to know that the top three floors of that building go completely unused, for reasons the staff never find out. The reason is there are missiles in there. Anti-air missiles. And missile launchers. Deadly stuff. Accurate to within half a foot. They're part of our system. Completely automated. Won't do a thing.¡±

The fleet wandered around the sky some more. They heard people screaming.

¡°Over there,¡± continued Budd, ¡°see that park? There are high-powered lasers there, in a cavity underground. They can cut through steel like a hot knife through butter. They're programmed to come up when they get the signal. From us.¡±

A plane ventured near the crafts and became an indistinct splotch of light.

¡°Heck, the security guards, at that school over there? They're not even real people. They're robots. They're set to act like normal people unless our system goes off. If it does, they transform into walking turrets. Death on two feet for anything not human.¡±

¡°Is that true?¡± said Jacobs.

¡°I don't know, I just heard that somewhere.

¡°Is today trash day?¡± said Marcus.

¡°No, that was Wednesday.¡± said John. ¡°Why does it matter?¡±

¡°Well, somebody else probably already thought of this, but couldn't we all get in that dumpster?¡±

Everyone stared at him. Budd said, ¡°I don't think the dumpster's going to protect us.¡±

¡°No, I mean to look for the disc.¡±

There was a moment of silence while everyone tried to remember what their organization's protocol was for the transportation of waste. Then they were all shouting and running and trying frantically to climb up into the dumpster.

A high-pitched sort of whine began to fill the air. Budd looked up, one leg over the side of the dumpster, and saw that one of the alien ships had gotten much closer, and had begun to release smaller ships and ground vehicles.

¡°Move!¡± he shouted at the others. They scrambled about the dumpster, picking up armfuls of garbage and flinging them about, making a huge mess. Suddenly John lept up, clutching a disc in his hand. They all grabbed for it, dropped it, grabbed for it again, and then there was a second scrambling to get back out of the dumpster. As they ran back to the door of their building, bolts of energy began hurtling towards them and exploding against its side. They turned, and saw a large spidery vehicle walking towards them, its legs a flurry of movement. Beside it were figures that were in some ways human, and in others, well, not.

The men tumbled into the building and ran up the stairs to the control room. John, who had the disc again, ran to the main computer and frantically told it to let him put the disc in. It obliged, eventually, and he shoved the disc into its slot. Everyone held their breath. The computer worked for a few moments, then the screen read:

EMERGENCY DISC ACCEPTED. SYSTEM WILL INITIALIZE IN TWENTY SECONDS.

There was an audible sigh from everyone.

¡°How much do you think it'll activate?¡± asked Jacobs.

Budd thought about it for a moment, his breathing still heavy.

¡°They've got ships in orbit, in the air, and troops on the ground. I think. . . all of it.¡±

They all looked out the window at the alien ships.

Then the countdown ended, and the sky caught fire.
