* The Pieces of Carrow, Demswick, and Greaves

In the silence that had followed the first sounding of the trumpet, Trevor D'Armic had walked slowly out of the leaning tower that stood beside his house, along the narrow street paved with bricks, and into the great breadth of the common road, which was cluttered with debris now, and he had picked up a single stone and returned home with it. He had walked slowly because he had wanted to give anyone watching him time to aim at his head. He had wanted to show them that he was not afraid to die. This resolve came from the part of his mind he had conquered, while the part that was wild ran feverishly through the logic of the situation, trying to deduce whether or not someone was watching him, and if so, whether they would decide to kill him. It was a long walk - or had seemed long, during the walking - and for stretches of a second or more he became convinced that there was no one, that he was safe. In these moments, the urge to break and run had become strongest, and in these moments he had told himself it was most important to keep his head up and to walk slowly.

Cornua, his wife, had watched him do this, a blank piece of paper trembling in her hands, and when he returned and locked the door behind him she said, without moving, "What were you doing? What were you thinking?"

Trevor opened his mouth and shut it again. He walked to the wooden table in the middle of the room and placed the stone on it. As he walked away again, Cornua rushed in front of the door and seized both his wrists in her hands.

"No. You can't," she said. "Not until you tell me why you walked out there."

"What's in your hand? Why are you..."

Cornua opened one of her hands, showing the crumpled piece of paper. She said, "I don't know. It must've been in my hand when I looked out the window. I was going to write a letter when I looked and saw you." She dropped the paper.

Trevor sighed and said, "I'm not going back out. You can let go of me. I just want to sit down."

She let go and watched him walk to the sofa and sit down slowly. The sofa had been a wooden park bench, stained and damp, when they found it. Its two iron legs had been sunk in slabs of concrete to prevent its removal. Trevor had labored with a sledgehammer and small chisel for two and half hours to break up the concrete, then the two of them had lifted one end of the heavy bench into a plastic wheelbarrow, which Cornua pulled while Trevor walked behind, holding the other end off the ground. All during the trip home he had complained, saying that if he had a metal saw or bolt pliers or any real proper tools the job would've been done in half the time. When they got it home, she scrubbed at it with soap and water and a steel brush, then they placed it in front of the fire for a week to dry it out. The wood was heavy and strong, but also old and weatherworn, so she covered it with a can of blue paint she had found in the attic of a condemned shop. Since the bench would not stand on its two uneven legs, and Trevor had no way of removing them, he piled up bricks in two stacks, with a hole in the middle of each for the legs, and rested the bench on top of them. Finally they cushioned the bench with old pillows and a blanket tucked around them to keep them in place.

Cornua looked at him until he had to look back, but even so, he remained silent, only giving her a pained expression. He wanted to speak, to give her some justification for his actions, but was unable to. The concept was simple in his mind, but in some way it was beyond his willpower to put it into words and speak it aloud. After a while he dropped his gaze from hers and spoke regarding the evening's meal in a voice without emotion. She replied in a voice similar.

Hours passed with no greater words than these. In the evening, when the sun was nearly gone and Trevor was putting out bowls for supper, there came a frantic knocking at the door. Trevor opened it quickly, and a very young man came in, almost a boy, breathing heavily, his hair unkempt.

"Trevor!" he said, looking amazed, "Trevor, you're here! I thought you must've gone already. I saw the light on and thought you'd left Mrs. D'Armic." He looked around. "Hello, Mrs. D'Armic."

"Hello, Patrick. Would you like some supper?"

"No, thank you." To Trevor, "I'm glad you haven't gone yet!"

"I'm not going anywhere."

"You're not going to Ollisle?"

"I am especially not going there."

"Why not?"

Trevor smiled a little wearily. He got a third bowl from the cupboard and said, "Have some supper with us. Your Nana won't mind."

"I know. But I'm meeting some of the guys at Francis's place. Edward and Bull. We were going to follow you to Ollisle, but if you're not going, we're still going to try for it."

"You made this plan previously?" said Trevor. "They're waiting for you now?"

"Yes. Well, not this plan, not tonight, not specifically. But they know something's up. They're on edge, you know? Well, we've all been on edge. Anyway, they know something's up and they'll come if I ask them to. They're ready."

"Ready for what?" muttered Trevor, but Patrick didn't hear him. Cornua said, "What's in Ollisle?"

"It's the Breakwater. The big brick building, you know? You can see it from Demswick's corner."

"It's an office building," said Trevor.

"They turned it into a military hospital, didn't they?" said Cornua.

"That's right," said Patrick. "They set up the whole building that way. But more happened than that. When things got worse, they blocked up most of the entrances and turned it into their headquarters. Holed up. Brought in everything they had."

"Do you mean information?" said Cornua, frowning.

"He means weapons," said Trevor, before Patrick could speak.

Patrick looked from one to the other and said, "Yeah, weapons. Well, they never used them, right? I mean, things never... they didn't come to that, here. People just ran out."

"So what are you looking to do?" said Trevor.

Patrick opened his mouth but hesitated. Then he looked at the floor, apparently choosing his words. It occured to Trevor that Patrick was not used to speaking plainly with someone who didn't already agree with him.

Finally Patrick said, "The others - Edward and Bull, and Mr. Ruthrey - the others and I think we should be ready to defend ourselves."

"Only to defend yourselves? That's the only use you'd find for weapons?" said Trevor.

"We don't want to attack them!" said Patrick.

"I know, I know," said Trevor. "But are you familiar with the feeling of holding a weapon? Of owning one? Of knowing, when someone wrongs you, or when you feel you've been wronged - of knowing what you could go home and get, what you could do?"

"We don't want to hurt people. It - wouldn't be our purpose to hurt people. Only defending ourselves. Anyway, are you an expert? Have you ever even held a gun?"

"No," said Trevor, "no, I've never held one. I know very little about them. I'm just asking questions. I want to know what you know."

"Would you be able to use the weapons you find?" said Cornua. While she was talking, she took the bowl from her husband and put on the table with the other two. "Would Edward or Bull, or even Mr. Ruthrey, be familiar with anything you found in a military base?"

"We- we can use them while we're still in the city," said Patrick. "We can practice with them before we come back. There's no one in Ollisle anymore, no one'll bother us. And we have a friend in Demsick, she knows how to use them. She was an engineer."

Trevor said nothing while he thought about this. Patrick watched him closely, then glanced at Cornua, who was pouring steaming soup into each of the bowls. Then he looked back at Trevor and said, "Do you think I'm being foolish?"

"A little."

"Why?"

BAD DRAFT FOLLOWS

"It seems to me that you are... tempting fate. Or rather, tempting Greaves.  It seems very dangerous."

Patrick looked at him very intently then. "So why did you pick up the stone? Edward saw you. He saw you walking all the way."

"I don't want to kill anyone."

"I don't want to kill anyone. I don't want that, either."

"...I don't know exactly why I picked up the stone. I didn't plan to, before I heard the trumpet. Perhaps I simply... it may be that I simply wanted a way to show them that I am not afraid of them."

"And are you afraid of them? While you were walking, were you afraid?"

"Oh yes, yes, I was." Trevor looked at his wife.

Patrick said, "And you call me foolish?"

"...It is possible that we're both foolish," said Trevor.

Patrick looked from Trevor to Cornua and back again. ".We were on the other side of Carrow when we heard that trumpet, me and Bull and my Nana. We went in the house right away, but after a while Bull and I went and found Mr. Ruthrey, and we talked about it, and we decided, we thought the trumpet was a challenge. I mean, we've all been kind of on edge, you know? For a while now, and... well, we know that Greaves has weapons, we know they're not like us, we know things went worse there. Everyone knows that."

"Everyone assumes that."

"Well, we pretty much know. We know they keep guns on the wall. We don't do that, and Demswick doesn't... anyway, Mr. Ruthrey said he was waiting for something like this. He said it'd be better if they never did anything, I mean, he hoped that Greaves would never bother us, if they just kept ignoring us, but now they've made this challenge, and... well, he said we either respond to it, or we give up. Then we saw Edward, and he told us about you walking out there, and he saw you pick something up - he thought it was a gun at first, but then he saw it was just a rock, and Mr. Ruthrey said, you answered the challenge. That's basically what you said by picking up that rock."

"That is not what I was... that was not what I intended to say," said Trevor, though he was unsure.

"I don't want you to be sorry," Patrick said earnestly. "We talked, and we're glad you did it. We think it was the right thing to say. I'm sorry if you won't come with us, but... we're still going to go. Ollisle. We've got everything ready. We have food and tents and... we can probably do the whole thing in a day. It's not a very long walk to the Breakwater, only about four hours."

"It's a longer walk than mine was, to be sure."

"Yeah. Safer, though. You know you were walking within range of their rifles, right? I mean the ones we've actually seen, we've seen them use. Like when they shot that dog."

Trevor nodded. "I remember."

"You knew you were within that range, right?"

"Yes, I knew." Trevor smiled weakly. "I told you I was afraid."

"I've been afraid, too. But I don't want to be. I want something that will stop me from being afraid. I see you still have the rock."

"Yes, I still have the rock."

"Well, pretty soon, I'm going to have one, too. But I think I'm taking a smaller risk for a bigger rock."

Patrick walked out, then. Trevor put the unused third bowl away and said to Cornua, "Do you think he'll do it?"

"Yes," she said.
* notes
They think they'll find a rocket launcher, a javelin with an enchanted head...
you friends have told you there's a rocket launcher, a javelin there... an enchanted bow...


Trevor is not entirely confident that they're wrong to retrieve the weapons...

Must point out that there were people milling about when the trumpet was sounded. Most went inside. Trevor's the only one who went out.

Pieces... maybe Trevor has a piece of an old courage or knowledge...
NATCOSMOLOGY: the sounding of the trumpet was an announcement that the attackers now owned the land before them, every stone.

It doesn't really strictly make sense that Trevor would take a stone from the ground. That's part of the point.


Demswick: it has been our understanding that... something would happen... ever since Greaves sounded their trumpet.
Also: of course, most Carrowers and Demswickers don't get along so well... or rather, say that some Carrowers don't trust Demswickers...
Demswick guy is combative, and either he or an associate is the one that Patrick's group knows can use weapons.
Some of the weapons are not... straightforward. Not things you hold and point. They're things you... program. Or order. Or rebuild. Whatever.


Welcome to war.
Welcome to justice.






I have to make reference to the fact that... this is a temporary living affair. Maybe they've been there a year. Expecting another year... but they have few animals. Maybe they're mostly living on food rations, or crops or... maybe they've got some sort of synthetic super crop that will last for a while...
They're all dislocated people... pushed out of where they were... even Greaves... The pieces are of many little cities, but they're primarily the pieces of three old cities: Carrow, Demswick, and Greaves. Those three cities were perhaps hit hardest during the war, but they were the biggest, so the most pieces of those remain... although, none of the remaining pieces were the centers of their cities; the centers were destroyed, were burnt out. Only the periphery survived.
So what does Trevor do? I don't think he does much; I think their food is provided by the supercrop or whatever. They don't actually have to farm that much. But they have to deal with an oppressive and a hostile landscape. Maybe radiation... but more likely, things are just broken. Thieves exist. There's little entertainment. People are tired, and scared. Many don't know where their families are.
They (the people) are waiting. Maybe they're waiting for the radiation to go away, or for their families to find them, or for the fighting to die down, or just until their food runs out, and they have no choice but to move.



Perhaps: Greaves was hit hardest, not by the war itself, but by anarchy after the dust settled. Thieves, raiders, gangs, etc. It became very warlike and dangerous. It became basically condemned, and then they realized that there were people rebuilding, making into a habitable place again, not unlike Carrow and Demswick, but with the hint of something worse. Carrow and Demswick basically chucked their weapons; they accepted that everything of value was already gone, and that they were only there because they were the few who were content to wait and get by with very little in the way of luxury or promise of better circumstances, etc. But Greaves still has weapons.



"Pieces" takes place after a halfway-apocalypse ware. It's not merely a nuclear war that destroys a country or two; but it was not apocalyptic; it did not wipe out 99% of humanity. It destroyed... I dunno, perhaps between a fifth and a half of the population of the planet, and there's enough to rebuild... they have some way of fighting radiation, or maybe the bombs are a bit cleaner... or maybe just medicine to reverse the effects of radiation... fight a race against those affected by radiation poisoning... But anyway, everyone is putting themselves back together now. International trade, international everything... the international web has shattered. The internet is largely down, many satellites are down. I can imply that many things relied on the satellites, and that the satellites were therefore targeted, something like that. Say that the two or the three or the four superpowers of the world obliterated each other, but failed to obliterate everyone else.
